# (PART\*) Unit A: Historical Context {.unnumbered}

# Overview {.unnumbered}

## 1.2 - Overview {.unnumbered}

### Overview {.unnumbered}

**SUGGESTED TIME TO COMPLETION: 6 to 9 Weeks to Complete**

For Unit A: Author: Geraldine Matus 2003. Copy Editor: Deborah Witwicki 2003. Editorial Revisions: Laura Salamanca 2015.

We are not just learning the mechanics of human sexuality, birth control, and reproduction. We are seeking to understand the historical, cultural, religious, popular, and symbolic contexts of these aspects of humanity so that we can better:

-   Reach othes with empathy for the psycho- social context within which they live
-   Help others gain awareness and an ability to work relationally with their reproductive health and menstrual cycle to enhance or prevent reproduction

The practice of birth control has existed since ancient times. The earliest of human history records various practices of contraception, abortion, infanticide, and forms of both temporary and permanent sterilization. This history's progression of knowledge and applications unfolds in ways logical, curious, and mysterious. While a woman's relationship to her sexuality and reproductive life is essentially an intimate one, her control over this relationship has always been subject to many other influences in her community. Cultural, political, and religious mores have always held sway over standard sexual practices and partners, ideal relationships between husband and wife, and concepts of ideal population growth. Spiritual leaders have sought to govern sexuality and reproduction in accordance with the ideals of a higher spiritual power. Physicians have claimed authority over the scientific “realities” of sexual and reproductive health.

The whole topic of birth control is something of a Tower of Babel, impossible to discuss in any depth without speaking in the languages of politics, religion, and science. Moreover, the exercise of birth control is a power play in terms not only of who holds the decision-making responsibility and authority, but even in terms of who holds the information. Central to this struggle, of course, is the question of female equality.

In short, the study of birth control can be as chaotic and laborious as birth itself. Yet, if we keep in mind our goal - to help contemporary persons understand and work relationally with their reproductive health and menstrual cycle to enhance or prevent reproduction - the journey promises to be an exciting and rewarding one. As well, there is a personal bonus. As you explore the history and politics of this field, you will have the opportunity to deepen your knowledge of your own sexuality and reproductive potential as you see them, and as they are mirrored in the society around you.

This unit sketches out a broad history touching on chronological landmarks, and introduces important cultural and social influences that have affected birth control practices. For the sake of brevity, and immediate relevancy, the information provided in this unit is representational of largely North American and Western thought and research. I encourage each student to explore beyond these limitations and find out about how the topics discussed here may present elsewhere.

Believe me, it is an interesting journey.

### Contained in Unit A, you will find the following Sections: {.unnumbered}

-   Unit A Section 1 Syllabus
-   Unit A Section 2 The Practice of Birth Control
-   Unit A Section 3 Birth Control in Social and Historical Context
-   Unit A Section 4 Ethical Considerations in Sexuality and Birth Control
-   Unit A Section 5 Socio-Religious Perspectives on Menstruation
-   Unit A Essay Topics
-   Unit A Journals
-   Unit A Evaluation (Essay, Multiple Choice, Short Answer)
