# 1: Syllabus {.unnumbered}

### 1.2 - Learning Objectives {.unnumbered}

In completing the readings and exercises in this unit of study, aim to be able to:

1.  Identify the various forms of birth control and pinpoint the historical periods in which they were introduced.
2.  Explain how historical and prevailing attitudes towards individuals and fertility influence birth control availability and design.
3.  Understand how the politics of healthcare and human sexuality influence birth control availability and design.
4.  Appreciate how the strength of these influences is pervasive in our time.
5.  Identify time lines for the development of birth control and important historical developments which have affected their practice.

### HRHP Program Journals {.unnumbered}

The purpose of the journal submissions is for you to reflect on some of the issues addressed in each unit of the program. It is suggested that you use a journaling format for your reflection on each topic. If you are more comfortable expressing your responses in other forms, such as in prose, poetry, movement, or visual arts, please do so.

What is important about the journals is that you engage in a process of informed inquiry and reflection. As a Holistic Reproductive Health Practitioner (HRHP), you will encounter many clients who think differently from you, and who would likely have different responses to the journal questions and course work. Reflecting on your personal reactions to the material through completing the journal questions helps prepare you for receiving them in all their diversity. As well, such inquiry strengthens your grasp of each unit's material. You will encounter journal questions throughout the material.

----

## 1.3 - Required Readings {.unnumbered}

###  Required Readings {.unnumbered}

#### How to Approach the Readings {.unnumbered}

All of the selected readings are designed to be coherent with the written text and commentary provided in the courseware itself. You are expected to read all the required readings, full texts, articles, online text, and such. It is recommended that you read the material in the order it is presented, however if you get stuck or find yourself too entangled in your thoughts to be able to make sense of things. Then STOP and go ahead and plan to come back to the stuck place later. See the Student Handbook Section 1.3 [Critical Reading and Transference](https://justisse.ca/index.php/college/ad_courseware/page/1830). Use the method described therein to approach where you find yourself stuck, over agitated, over critical, and such. It will help you to digest the text and make purposeful meaning of the readings. Have fun.

When approaching a large text/text book, we suggest that you scan through it so you know all that it contains in a peripheral sort of way and then dive more deeply into the required reading. Keep a separate electronic/paper journal for each of the books and write notes, talk back via transference dialogs to the material. You will be pleasantly surprised to find that it all seems easier.

___

 **Unit A on-line material in its entirety and additional texts listed below.**

**Please note that any readings from the Human Sexuality Text by Hyde and Delamater are not necessarily consistent with the Justisse College International pedagogical or philosophical approach. They are intended to give students exposure to what is common mainstream thinking as regards human sexuality. Please read it with a critical mind.**

1.  Unit A Section 1.1 Syllabus
    
2.  Unit A Section 1.2 Required Readings
    
    ___
    
3.  Unit A Section 2 The Practice of Birth Control
    
4.  Unit A Section 2.2 Contraception
    
    1.  **[The Moral Property of Women: A History of Birth Control in America](http://www.amazon.com/Moral-Property-Women-History-Politics/dp/0252074599/ref=sr_1_1?s=books&ie=UTF8&qid=1427331247&sr=1-1&keywords=The+Moral+Property+of+Women%3A+A+History+of+Birth+Control+in+America).** 2007. Linda Gordon. Chicago:  University of Illinois Press 1974/1990 New York: Penguin Books. This book addresses the history of birth control and the intense controversies regarding reproduction rights that have raged in the United States over the past 150 years, _The Moral Property of Women_ is a thoroughly updated and revised version of the award-winning historian Linda Gordon's classic **_Woman's Body, Woman's Right_**, originally published in 1976, 2nd edition 1990. Gordon argues that reproductive control has always been central to women's status, and opposition to it has long been part of the conservative opposition to gender equality. From its roots in folk medicine and in a campaign so broad it constituted a grassroots social movement at some points in history, to its legitimization through public policy, the widespread acceptance of birth control has involved a major reorientation of sexual values.Gordon puts today's reproduction control controversies--foreign aid for family planning, the abortion debates, teenage pregnancy and childbearing, stem-cell research--into historical perspective and shows how the campaign to legalize abortion is part of a 150-year-old struggle over reproductive rights, a struggle that has followed a circuitous path. Beginning with the "folk medicine" of birth control, Gordon discusses how the backlash against the first women's rights movement of the 1800s prohibited both abortion and contraception about 130 years ago. She traces the campaign for legal reproduction control from the 1870s to the present and argues that attitudes toward birth control have been inseparable from family values, especially standards about sexuality and gender equality. Highlighting both leaders and followers in the struggle, _The Moral Property of Women_ chronicles the contributions of well-known reproduction control pioneers such as Elizabeth Cady Stanton, Margaret Sanger, and Emma Goldman, as well as lesser- known campaigners including the utopian socialist Robert Dale Owen, the three doctors Foote--Edward Bliss Foote, Edward Bond Foote, and Mary Bond Foote--the civil libertarian Mary Ware Dennett, and the daring Jane project of the 1970s, in which Chicago women's liberation activists performed illegal abortions. ([http://www.amazon.ca/The-Moral-Property-Women-Politics/dp/0252074599](http://www.amazon.ca/The-Moral-Property-Women-Politics/dp/0252074599)) 
        
5.  Unit A Section 2.3 Post Conception Birth Control
    
6.  Unit A Section 2.4 Natural Birth Control
    
7.  Unit A Section 2.5 Conclusion 
    
8.  ___
    
    Unit A Section 3 Birth Control in Social And Historical Context
    
9.  Unit A Section 3.1 Introduction
    
10.  Unit A Section 3.2 Witches, Midwives, and Nurses
    
    1.  **[Witches, Midwives, and Nurses: A History of Women Healers](http://www.amazon.com/Witches-Midwives-Nurses-Mountain-Pamphlets/dp/0912670134/ref=sr_1_2?s=books&ie=UTF8&qid=1427331196&sr=1-2&keywords=witches+midwives+and+nurses+a+history+of+women+healers).** Barbara Ehrenreich & Deirdre English. New York: Feminist Press at the City University of New York. 1993/2010. Women have always been healers, and medicine has always been an arena of struggle between female practitioners and male professionals. This pamphlet explores two important phases in the male takeover of health care: the suppression of witches in medieval Europe and the rise of the male medical profession in the United States. The authors conclude that despite efforts to exclude them, the resurgence of women as healers should be a long-range goal of the women's movement.
        
11.  Unit A Section 3.3 Ancient Times
    
12.  Unit A Section 3.4 The Christian Church and Sexual Morality
    
    1.  Pope Paul VI. (1968). _Humanae Vitae._ [www.vatican.va/holy\_father/paul\_vi/encyclicals/documents/hf\_p-vi\_enc\_25071968\_humanae-vitae\_en.html](http://www.vatican.va/holy_father/paul_vi/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae_en.html).
        
13.  Unit A Section 3.6 The 18th & 19th Centuries
    
    1.  Gordon, L. (2007). _The moral property of women: A history of birth control in America._ Chicago, IL: University of Illinois Press. **(Parts 2 and 3)**
14.  Unit A Section 3.7 The 20th and 21st Centuries.
    
    1.  Gordon, L. (2007). _The moral property of women: A history of birth control in America._ Chicago, IL: University of Illinois Press. **(Part 4).**
        
    2.  **[The Woman in the Body: A Cultural Analysis of Reproduction](http://www.amazon.ca/Woman-Body-Emily-Martin/dp/0807046051/ref=sr_1_3?s=books&ie=UTF8&qid=1437345105&sr=1-3&keywords=the+woman+in+the+body).** Emily Martin (1987). Boston, MA: Beacon Press. A bold reappraisal of science and society, _The Woman in the Body_ explores the different ways that women's reproduction is seen in American culture. Contrasting the views of medical science with those of ordinary women from diverse social and economic backgrounds, anthropologist Emily Martin presents unique fieldwork on American culture and uncovers the metaphors of economy and alienation that pervade women's imaging of themselves and their bodies. A new preface examines some of the latest medical ideas about women's reproductive cycles. ([http://www.amazon.ca/Woman-Body-Emily-Martin/dp/0807046051/ref=sr\_1\_3?s=books&ie=UTF8&qid=1437345105&sr=1-3&keywords=the+woman+in+the+body](http://www.amazon.ca/Woman-Body-Emily-Martin/dp/0807046051/ref=sr_1_3?s=books&ie=UTF8&qid=1437345105&sr=1-3&keywords=the+woman+in+the+body))
        
    3.  Thomas, J. E. & Zimmerman, M. K. (2007). Feminism and profit in American hospitals: The corporate construction of Women's Health Centres. _Gender and Society, 21_, 359 -383. doi:10.1177/0891243207299947. [Link to "Feminism and Profit"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Feminism%20and%20Profit%20in%20American%20Hospitals.pdf)
        
15.  Uni A Section 3.8 International Discourse on Birth Control
    
16.  Unit A Section 3.9 Contraception & Abortion Timeline
    
    1.  Pro-choice Action Network. (2009). _A legal history of abortion in Canada._ Vancouver, BC. [http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml](http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml)
        
    2.  Merhi, D. (2012). For their own good: Ontario's legal legacy of the “moral” woman. _Dominion: News from the grassroots 84_. [http://www.dominionpaper.ca/articles/4526](http://www.dominionpaper.ca/articles/4526)
        
    3.  Gibbs, N. (2007). Abortion in America: 1 Woman at a time (pp. 15 - 23). _Time._ _[Link to "Abortion in America"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Wars.pdf)_
        
    4.  Saletan, W. (2006). Where the rubber meets Roe: The pro-life case for contraception. _Slate._ [Link to "Where the Rubber Meets the Roe"](http://www.slate.com/articles/health_and_science/human_nature/2006/09/where_the_rubber_meets_roe.single.html)
        
17.  Unit A Section 3.10 PILL-Timeline
    
    1.  Timeline: The pill. _PBS._ [Pill Timeline.pdf](http://www.justisse.ca/MediaGallery/Documents/HRHP/UnitA/Pill%20Timeline.pdf) link or go to site [http://www.pbs.org/wnet/need-to-know/health/a-brief-history-of-the-birth-control-pill/480/](http://www.pbs.org/wnet/need-to-know/health/a-brief-history-of-the-birth-control-pill/480/)
18.  Unit A Section 3.11 Conclusion
    
19.  ___
    
    Unit A Section 4 Ethical Considerations in Sexuality and Birth Control
    
20.  Unit A Section 4.1. Introduction
    
21.  Unit A Section 4.2  History of Contraception: Things to Ponder
    
22.  Unit A Section 4.3 The Greatest Experiment Ever Performed on Women
    
23.  Unit A Section 4.4 [Bill C-6 Assisted Human Reproduction Act](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#:~:text=Bill%20C-6%2C%20An%20Act,stages%20on%2011%20February%202004.&text=The%20bill%20later%20died%20on,of%20the%201997%20federal%20election): read only the: 
    
    1.  [BACKGROUND](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#backgroundtxt)
    2.  [COMMENTARY](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#commentarytxt)
        
    3.  **[BRIEF CHRONOLOGY OF RELATED FEDERAL GOVERNMENT ACTIONS](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#brieftxt)**
        
24.  Unit A Section 4.5 Beyond Sexual Fundamentalism
    1.  Ellison, M. M. (2001). Beyond sexual fundamentalism: The call for an ethical eroticism. Sexual Addiction & Compulsivity, 8, 3 - 11. [Link to "Beyond Sexual Fundamentalism"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Sexual%20Ethics%20Paper.pdf)
        
    2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 1: Sexuality in perspective. In _Understanding Human Sexuality_ (3rd ed.) (pp. 1-19). Toronto: McGraw-Hill Ryerson. **[Understanding Human Sexuality](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g?usp=sharing)**
        
    3.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 21: Sexuality education. In _Understanding Human Sexuality_ (3rd ed.) (pp. 596 - 622). Toronto: McGraw-Hill Ryerson. **[Understanding Human Sexuality](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g?usp=sharing)**
        
25.  Unit A Section 4.6 Why Not FAM?
    
    1.  World Health Organization (WHO). (2004). _Selected practice recommendations for contraceptive use_ (2nd ed.). Geneva: World Health Organization.  **[Link to "Selected Practices"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/WHO%20Selected%20Practice%20Recommendations%20for%20Contraceptive%20User.pdf)** This guide provides guidance on how to provide contraceptives, with the goals of maximizing effectiveness and managing side effects and other problems. The second edition contains 33 recommendations ranging from when to start a method, how to manage problems women experience using certain methods, how to provide emergency contraception, and what clinical exams to perform before a method can be initiated.
        
    2.  World Health Organization (WHO). (2008). _Selected practice recommendations for contraceptive use - 2008 update._ Geneva: World Health Organization. **[Link to "Updated Selected Practices"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/WHO%202008%20Update%20Selected%20Practice%20Recommendations%20for%20Contraceptive%20User.pdf)** On 1-4 April 2008, WHO convened an expert Working Group in Geneva, Switzerland, to revise the second edition in response to newly published evidence and requests for clarification of specific recommendations from users of the guideline. This document summarizes the changes made to recommendations related to questions 6, 9, 11, 18 and 22 in the second edition of the _Selected Practice Recommendations for Contraceptive Use_. The revised recommendations will appear in the 3rd edition of the guideline when it is published. In addition, this document includes a clarification of the recommendation related to question 17.
        
    3.  World Health Organization (WHO). (2009). _Medical eligibility criteria for contraceptive use_ (4th ed.). Geneva: World Health Organization. **[Link to "Medical Eligibility"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Medical%20Eligibility%20Criteria%20for%20Contraceptive%20User.pdf)** This document reviews the medical eligibility criteria for use of contraception, offering guidance on the safety of use of different methods for women and men with specific characteristics or known medical conditions. The recommendations are based on systematic reviews of available clinical and epidemiological research. It is a companion guideline to _Selected Practice Recommendations for Contraceptive Use_. Together, these documents are intended to be used by policy-makers, programme managers, and the scientific community, to support national programmes in the preparation of service delivery guidelines.
        
    4.  Berger, A., Manlove, J., Wildsmith, E., Peterson, K., & Guzman, L. (2012). What young adults know—and don't know—about women's fertility patterns: Implications for reducing unintended pregnancies. _Child Trends 26_, 1 - 6. **[Link to "What Young Adults Don't Know"](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/What%20Young%20Adults%20do%20not%20Know%20About%20FABM.pdf)**
        
26.  Unit A Section 4.7 Conclusion 
    
27.  ___
    
    Unit A Section 5 Socio-Religious Perspectives on Menstruation
    
28.  Unit A Section 5.1 Introduction
    
    1.  **The Woman's Encyclopedia of Myths and Secrets**. Barbara G. Walker. San Francisco: Harper Row. 1983. “menstrual blood” & “menstrual calendar” pages 635-648. 
        
        Do You Know: Where the legend of a cat's nine lives comes from? Why "mama" is a word understood in nearly all languages? How the custom of kissing began? Whether there really was a female pope? Why Cinderella's glass slipper was so important to the Prince? The connection between Tantra and the Sacred Heart of Jesus?  The answers to these and countless other intriguing questions are given in this compulsively readable feminist encyclopedia. Twenty-five years in preparation, this unique and comprehensive source book focuses on mythology anthropology, religion, and sexuality to uncover precisely what other encyclopaedias leave out or misrepresent. _The Woman's Encyclopedia_ presents the fascinating stories behind word origins, legends, superstitions, and customs. A browser's delight and an indispensable resource, it offers 1,350 entries on magic, witchcraft, fairies, elves, giants, goddesses, gods, and psychological anomalies such as demonic possession; the mystical meanings of sun, moon, earth, sea, time, and space; ideas of the soul, reincarnation, creation and doomsday; ancient and modern attitudes toward sex, prostitution, romance, rape, warfare, death and sin, and more. _The Woman's Encyclopedia_ is a revolutionary book that offers a rare opportunity to see our cultural heritage in a fresh light, and draw upon the past for a more humane future.
        
29.  Unit A Section 5.2 Jewish Family Purity Laws
    
    1.  Nishmat: Women's Online Information Centre. The Jerusalem Centre for Advanced Study for Women. Read the section on “Becoming Niddah” [https://www.yoatzot.org/becoming-niddah/the-niddah-status/](https://www.yoatzot.org/becoming-niddah/the-niddah-status/) 
        
    2.  Jewish Women's Archive: Jewish Women: A Comprehensive Historical Encyclopedia: [http://jwa.org/encyclopedia/article/female-purity-niddah](http://jwa.org/encyclopedia/article/female-purity-niddah)
        
30.  Unit A Section 5.3 Christianity and Catholicism
    1.  Women were considered ritually unclean **[http://www.womenpriests.org/traditio/unclean.asp](http://www.womenpriests.org/traditio/unclean.asp)**
        
    2.  Macbeth, A. (2013).. **[Buddhism and Menstrual Taboos](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Buddhism%20and%20Menstruation.pdf)** (This paper was compiled by Macbeth as a journal response. We are sharing it here for the benefit of others.)
        
31.  Unit A Section 5.4 A Sampling of Menstrual Myths, Taboos, and History
    
    1.  **[The Power of Menses](http://wolf.mind.net/womens/menses.htm)** by Ofelas Pathfinder
    2.  Museum of Menstruation and Women's Health **[mum.org](http://www.mum.org/)**
    3.  **[The menstruation taboo](https://www.youtube.com/watch?v=jH1sh7aU-mk)** Diana Fabianova at TEDxBratislava 2013: (click on the CC button at the bottom right to see the English subtitles)
    4.  Video of **[A Taboo-Free Way to Talk about Periods](https://www.ted.com/talks/aditi_gupta_a_taboo_free_way_to_talk_about_periods?language=en)** Aditi Gupta at TedxGateway Women May 2015.
    5.  **[Menstrual Hygiene Management: A taboo that must be broken!](https://blogs.adb.org/blog/menstrual-hygiene-management-taboo-must-be-broken)** blog by Anupma Jain, Senior Social Sector Specialist. June 06, 2013. 
    6.  **[Decolonising your body: Maori attitudes towards menstruation](https://thespinoff.co.nz/atea/17-04-2019/decolonising-your-body-maori-attitudes-to-periods/?fbclid=IwAR1Pf37WoHpantiH30diCO5s5s4C_3e0KfOLEgSkeOm6_6y0krRfmO_KvzA)** Leonie Hayden April 17, 2019
    7.  Fahs, Breanne. (2011) **[Sex during menstruation: Race, sexual identity, and women's accounts of pleasure and disgust.](https://www.academia.edu/2844213/Sex_during_menstruation_Race_sexual_identity_and_women_s_accounts_of_pleasure_and_disgust?email_work_card=view-paper)**

----

## 1.4 - Comparative Readings {.unnumbered}

### Annotated List of Comparative Readings {.unnumbered}

1. [Reproducing The Womb: Images of Childbirth in Science, Feminist Theory, and Literature](http://www.amazon.ca/Reproducing-Womb-Childbirth-Feminist-Literature/dp/0801481619/ref=sr_1_1?s=books&ie=UTF8&qid=1437345338&sr=1-1&keywords=reproducing+the+womb).Alice E. Adams. New York: Cornell University Press. 1994.**** Alice E. Adams crafts a subtle new response to the controversies surrounding reproductive freedom and the implications of medical technology. She explores a spectrum of competing visions of childbearing, from misogynistic nightmares of matriarchal control to feminist utopias. Firmly rooted in political reality, Adams offers innovative answers to the questions posed by the intimate interconnections, and the perceived conflicts, between fetus and mother, individual and collective. (Ass reviewed in Amazon)
    
2. [The Fear of the Feminine: And Other Essays on Feminine Psychology](http://www.amazon.com/Fear-Feminine-Erich-Neumann/dp/0691034737/ref=sr_1_1?ie=UTF8&qid=1427331038&sr=8-1&keywords=The+Fear+of+the+Feminine%3A+And+Other+Essays+on+Feminine+Psychology). Erich Neumann. Bolligen Series LXI, Essays of Erich Neuman Volume 4. Princeton: Princeton University Press. 1994. These essays by the famous analytical psychologist and student of creativity Erich Neumann belong in the context of the depth psychology of culture and reveal a prescient concern about the one-sidedness of patriarchal Western civilization. Neumann recommended a "cultural therapy" that he thought would redress a "fundamental ignorance" about feminine and masculine psychology, and he looked for societal healing to a "matriarchal consciousness" that forms the bridge between the feminine and the creative. Brought together here for the first time, the essays in the book discuss the psychological stages of woman's development, the moon and matriarchal consciousness, Mozart's _Magic Flute,_the meaning of the earth archetype for modern times, and the fear of the feminine. In Mozart's fantastic world, Neumann saw a true _Auseinandersetzung_\--the conflict and coming-to-terms with each other of the matriarchal and the patriarchal worlds. Developing such a synthesis of the feminine and the masculine in the psychic reality of the individual and of the collective was, he argued, one of the fundamental, future-oriented tasks of both the society and the individual.
    
3. [Women's Mysteries Ancient and Modern](http://www.amazon.com/Womens-Mysteries-Ancient-Modern-Foundation/dp/1570626294/ref=sr_1_2?ie=UTF8&qid=1427330981&sr=8-2&keywords=Women%E2%80%99s+Mysteries+Ancient+and+Modern).** M. Esther Harding. New York: Harper Row.1976/2001. Here is a classic study of the feminine principle in myths, dreams, and religious symbolism. In presenting the archetypal foundations of feminine psychology, the author shows how the ancient religious initiations of the moon goddess symbolized the development of the emotions. Understanding the psychological meaning of these initiations, she believes, can help to heal the troubled relations between men and women today.
    
4. [Songs of Bleeding](http://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=songs+of+bleeding). Spider. New York: Black Thistle Press. 1992. Women's Initiation rites and rituals based on native spirituality, from Taino teachings.
    
5. [Daughters of Copperwoman](http://www.amazon.com/Daughters-Copper-Woman-Anne-Cameron/dp/155017245X) 1981/2002. Harbour Publishing. Madeira Park, BC. In this, her best-loved work, Anne Cameron has created a timeless retelling of northwest coast Native myths that together create a sublime image of the social and spiritual power of woman. Cameron weaves together the lives of legendary and imaginary characters, creating a work of fiction with an intensity of style matched by the power of its subject. Since its first publication in 1981, _Daughters of Copper Woman_ has become an underground classic, selling over 200,000 copies. Now comes a new edition that includes many pieces cut from the original as well as fresh material added by the author. Here finally, after twenty-two years of gathering dust, is the complete version of the groundbreaking bestseller.
    
6. [How to Lie With Statistics](http://www.horace.org/blog/wp-content/uploads/2012/05/How-to-Lie-With-Statistics-1954-Huff.pdf) Darryl Huff. 1954. Darrell Huff runs the gamut of every popularly used type of statistic, probes such things as the sample study, the tabulation method, the interview technique, or the way the results are derived from the figures, and points up the countless number of dodges which are used to full rather than to inform.
    
7. On the Birth Control Pill -- Marks, L. (2001). [Sexual Chemistry: a history of the contraceptive pill](http://www.amazon.ca/Sexual-Chemistry-History-Contraceptive-Pill/dp/0300089430/ref=sr_1_1?s=books&ie=UTF8&qid=1437356744&sr=1-1&keywords=Sexual+Chemistry%3A+a+history+of+the+contraceptive+pill)_. New Haven: Yale University Press.** This volume chronicles the development an impact of the birth control pill. From the social context of the emergence of medical research that lead to this development, to the handling of health concerns, the author discusses several heated debates about the importance of the pill to society and its risks and benefits to women's health.
    
8. On Abortion -- [No Choice: Canadian Women Tell their Stories of Illegal Abortion.](http://www.amazon.ca/No-choice-Canadian-stories-abortion/dp/0968379605/ref=sr_1_1?s=books&ie=UTF8&qid=1437356780&sr=1-1&keywords=No+Choice%3A+Canadian+Women+Tell+their+Stories+of+Illegal+Abortion.) (1998). The Childbirth by Choice Trust, Eds. This collection of stories details the experience of abortions obtained by women in Canada, starting in the early 20th century and onto the 1960s. The volume is divided into four chapters (“From the turn of the century to the second world war”, “The Forties”, “The Fifties” and “The Sixties”) that each provide a short introduction to the birth control and social context of the time, as well as its impacts on particular women in Canada.
    
9. [New Blood: Third Wave Feminism and the Politics of Menstruation](http://bookzz.org/book/1267264/4ab505) Chris Bobel.(2010) Rutgers University Press. London, UK. _New Blood_ offers a fresh interdisciplinary look at feminism-in-flux. For over three decades, menstrual activists have questioned the safety and necessity of feminine care products while contesting menstruation as a deeply entrenched taboo. Chris Bobel shows how a little-known yet enduring force in the feminist health, environmental, and consumer rights movements lays bare tensions between second- and third-wave feminisms and reveals a complicated story of continuity and change within the women's movement. Through her critical ethnographic lens, Bobel focuses on debates central to feminist thought (including the utility of the categoy "gender") and challenges to building an inclusive feminist movement. Filled with personal narratives, playful visuals, and original humor, _New Blood_ reveals middle-aged progressives communing in Red Tents, urban punks and artists "culture jamming" commercial menstrual products in their zines and sketch comedy, queer anarchists practicing DIY health care, African American health educators espousing "holistic womb health," and hopeful mothers refusing to pass on the shame to their pubescent daughters. With verve and conviction, Bobel illuminates today's feminism-on-the-ground--indisputably vibrant, contentious, and ever-dynamic.
10. Medical eligibility criteria for contraceptive use. Fifth edition. World Health Organization (WHO): [http://www.who.int/reproductivehealth/publications/family\_planning/MEC-5/en/](http://www.who.int/reproductivehealth/publications/family_planning/MEC-5/en/)
    
11. [Misogyny: The World's Oldest Prejudice](http://www.jackholland.net/) Jack Holland
    
12. [The Alphabet and the Goddess](http://www.alphabetvsgoddess.com/) Leonard Schlain
    
13. [Woman an Intimate Geography](https://www.amazon.com/Woman-Intimate-Geography-Natalie-Angier/dp/0544228103) Natalie Angier
    
14. Related to the Unit A Section 3.4 The Christian Church and Sexual Morality reading Pope Paul VI. (1968). _Humanae Vitae,_ is [Turning Point: The Inside Story Of The Papal Birth Control Commission: and How Humanae Vitae Changed The Life Of Patty Crowley And The Future Of The Church by Robert McClory](https://www.goodreads.com/book/show/1820539.Turning_Point)
    
15. Ross, Loretta & Solinger, Rickie. (2017). _Reproductive Justice: An Introduction_. Oakland: University of California Press
    
16. Munson, Ziad. (2018). _Abortion Politics_. Medford: Polity.
    
17. The Colbert Report on [Rockefeller Medicine](https://www.corbettreport.com/rockefeller-medicine-video/?fbclid=IwAR1ofi1Fyg1sf3nrz9eijdZwQZpU86HpXZAMsipCCGkt-PNeVr3oGWodfGc) - this is a current investigation into the capitalistic practices of medicine in the United States. This theme you first visit in Witches, Midwives, and Nurses.

----

## 1.5 - Unit A Final Evaluation {.unnumbered}

### The final evaluation for Unit A includes {.unnumbered}

You are responsible to conduct yourself with academic honesty.

#### Unit A Journals {.unnumbered}

**NOTE:** Each journal is embedded in the section of courseware literature that is relevant to that journal. Do the journals as they appear in the literature you are reading. 

 [#1 A.2.2: My Experience with Contraception](https://justisse.ca/index.php/college/ad_courseware/page/1002) 

 [#2 A.2.3: My Thoughts about Abortion](https://justisse.ca/index.php/college/ad_courseware/page/1003) 

 [#3 A.2.4: My Thoughts On Natural Birth Control](https://justisse.ca/index.php/college/ad_courseware/page/1004) 

 [#4 A.3.3: Obtaining Permission to Abort](https://justisse.ca/index.php/college/ad_courseware/page/1025) 

 [#5 A.3.5 Collective Influences](https://justisse.ca/index.php/college/ad_courseware/page/1594) 

 [#6 A.3.6 Three Articles On Abortion](https://justisse.ca/index.php/college/ad_courseware/page/1027) 

 [#7 A.3.6 Pro Choice or Pro Life](https://justisse.ca/index.php/college/ad_courseware/page/1027)

 [#8 A.3.7 Are women better informed?](https://justisse.ca/index.php/college/ad_courseware/page/1028) 

 [#9 A.3.7 Feminism and Profit in American Hospitals](https://justisse.ca/index.php/college/ad_courseware/page/1028)

 [#10 A.3.9 Contraception and Abortion Timeline](https://justisse.ca/index.php/college/ad_courseware/page/1029)

 [#11 A.4.4 Policies on Reproductive Technologies](https://justisse.ca/index.php/college/ad_courseware/page/1038) 

 [#12 A.4.5 Sexual Fundamentalism](https://justisse.ca/index.php/college/ad_courseware/page/1037) 

 [#13 A.4.6 What Young Adults Know](https://justisse.ca/index.php/college/ad_courseware/page/1035)

 [#14 A.5.4 Menstrual Taboo Literature Review](https://justisse.ca/index.php/college/ad_courseware/page/1604) 

 [#15 A.5.4 Menstrual Taboos -- Three Articles](https://justisse.ca/index.php/college/ad_courseware/page/1604) 

 [#16 A.5.5 Unit A Reflections](https://justisse.ca/index.php/college/ad_courseware/page/1605) 

#### Multiple Choice and Short Answer Exams {.unnumbered}

**Do not open up the multiple choice or short answer exam until you are ready to take it.**

-   multiple choice exam: 75 questions with 130 minutes to complete
-   short answer exam: 25 questions with 75 minutes to complete

----

## 1.6 - Unit A Essay Topics {.unnumbered}

Choose **one** essay topic from the nine topics listed below. Write an essay of between 1500 and 2500  words.  Be concise. Provide rationale for your ideas and enrich your work with examples, metaphors, or allegories to illustrate your main points. Please include citations where you directly or indirectly represent the ideas others. Choose themes that can be treated in this size of an essay. If your proposed topic seems like it could be a book, then narrow it down to one elements of the topic, or part of an element. Lengthiness only matters if it has substance.

**If none of the topics suit you, you may request, in a formal letter/email to your HRHP Trainer, consideration of an essay topic of your choosing. Any topic of your choosing must be relevant to this unit.**

**Format**

-   Use APA publication manual 7th ed. to cite references, format quotes, create a bibliography, etc.
-   Document needs to be either a PC compatible Word document or a plain text file
-   Use a 12 pt font, preferably with serifs, like Courier or Times New Roman
-   Double space text
-   Page margins - 1” (2.54 cm) top and bottom, 1” (2.54 cm) left and right

Please see [Formatting your Essay for Justisse College](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/Admin/Formatting%20your%20Essay%20for%20Justisse%20College.pdf) for guidance.

**An excellent source for helping you follow APA format and basic research and essay writing guidelines is**  **[http://owl.english.purdue.edu/owl/resource/560/01/](http://owl.english.purdue.edu/owl/resource/560/01/) Bookmark this site for future reference.**

**Breakdown of essay evaluation for 100 points**

-   format                                  20                          
-   support & rationale for ideas   30
-   organization & development    25
-   originality & imagination         25          

### Essay Topics {.unnumbered}

1.  In Canada, [Bill C-150](https://en.wikipedia.org/wiki/Criminal_Law_Amendment_Act,_1968-69#Abortion) legalized therapeutic abortion under certain conditions. Abortion was previously a criminal offence in Canada, which was still largely influenced by the Catholic Church's moral positions on this issue. Bill C-150 made it legal for women to get an abortion if a therapeutic abortion committee of three doctors felt the pregnancy endangered the mental, emotional or physical well-being of the mother.[\[5\]](https://en.wikipedia.org/wiki/Criminal_Law_Amendment_Act,_1968-69#cite_note-CBC-5) In a 1999 speech celebrating the 30th anniversary of the bill's passage, Senator Lucie Pépin argued that the new freedom provided by Bill C-150 "proved to be a stepping stone for many other freedoms and options that have altered women's place in \[Canadian\] society — self-esteem, education, jobs, a voice and empowerment".[\[6\]](https://en.wikipedia.org/wiki/Criminal_Law_Amendment_Act,_1968-69#cite_note-6) Abortion legislation in Canada was further liberalized in 1988 with the R. v. Morgentaler ruling, which left Canada without any laws regulating abortion through all nine months of pregnancy.[\[7\]](https://en.wikipedia.org/wiki/Criminal_Law_Amendment_Act,_1968-69#cite_note-CBCtime-7) Include in your essay, your thoughts about whether Bill C-150 has any relation to holistic reproductive healthcare and provide rationale for your comments. If you would rather write about a similar law in your own country please do so, just provide information about the law.
2.  Review Canada's Bill C-13 and a sampling of commentary about it. Write about your reaction to Bill C-13. Include in your essay your thoughts about whether Bill C-13 has any relation to holistic reproductive health care and provide rationale for your comments.
3.  Review the **Humane Vitae encyclical** [http://www.vatican.va/holy\_father/paul\_vi/encyclicals/documents/hf\_p-vi\_enc\_25071968\_humanae-vitae\_en.html](http://www.vatican.va/holy_father/paul_vi/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae_en.html) in light of how it has value or is problematic with respect to sexual and reproductive health freedoms and self-knowledge. Provide an outline of the specific regulations regarding the use of fertility awareness to avoid pregnancy, and acceptable sexual practice for Catholics. Provide commentary on the pros and cons of the regulations laid out by the encyclical.
4.  Create your own proposed set of laws and regulations regarding menstruation.  That is, your own menstrual taboo.  Provide rationale for each proposed law or regulation.  The rationale may either be psycho-socially or physiologically based.
5.  Write about your response to the required text reading: **Witches, Midwives, and Nurses: A History of Women Healers** by Barbara Ehrenreich and Deirdre English with respect to the value of knowing this particular history for those who are working in the area of reproductive health.
6.  From the required text reading: **The Woman in the Body** by Emily Martin pick one chapter that you were particularly affected by and write your response, commentary, or rebuttal on it.
7.  Refer to Chapter 5 “**Social Purity and Eugenics**” in from the required text reading **The Moral Property of Women** by Linda Gordon (Chapter 6 in Woman's Body, Woman's Right), and 3 other sources of your own on the topic of eugenics. Develop a commentary on how eugenics continues to be carried out in current North America and/or Western European society.
8.  Read this article [Abortion Solution Where the rubber meets the Roe](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Solution%20Where%20the%20rubber%20meets%20the%20Roe.pdf) What is your perception of the dynamics of the abortion wars? How are you affected by propaganda either for or against abortion?
9.  Read this Washington Post article: [Abortion solution: where the rubber meets Roe](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Solution%20Where%20the%20rubber%20meets%20the%20Roe.pdf) that addresses the changing ideas about abortion and contraception. Compare and contrast the current thinking about the reduction of abortion rates with increased access to contraception to what that thinking was in the 1960s to 1970s.
10.  The pro-voice and Reproductive Justice movements arose from the unique conditions of history and politics in the U.S. Apply a reproductive justice or pro-voice lens to the fight for women's reproductive rights in another country or context.
