# 2: The Practice of Birth Control {.unnumbered}

## 2.1 - Introduction {.unnumbered}

This Section will introduce you to the range of birth control methods as practiced throughout history, including the basis of our Justisse practice: fertility awareness and natural birth control. We use the term “birth control” here in its broadest sense to encompass contraception, natural birth control, and even measures taken after conception or after birth. 

Section 2 outlines some basic historical and cultural context for each birth control practice discussed. These practices are broken down into three categories.

-   2.2 Contraception
-   2.3 Post Conception Birth Control
-   2.4 Natural Birth Control

Some of the required readings add significant content to the topic and provide you with an introduction to the religious and cultural tenets that infuse interpretations of the essence of human sexuality and reproduction, and in particular cultural and personal relationship to menstrual blood. Other readings provide foundation for the issues surrounding our Justisse practice. Section 3 follows up with a broader historical overview and a look at some of the prevailing attitudes toward women, women's bodies, their sexuality, and birth that have affected the evolution of birth control.

Throughout recorded history, the need for birth control has been compelling for a variety of reasons, ranging from the health and well being of individuals and and those they are responsible for to economic and political conditions. As you review the various birth control practices, consider your own birth control needs in the span of your fertile life. According to your reproductive age, you may wish to concentrate your considerations on past situations you have experienced; current issues you face, or anticipation of the future role of your reproductive potential and/or the development of your family. Whatever the nature of your consideration, you will realize that for most individuals issues about conception, reproductive health, and birth control are forefront for the 30 to 40 years of the female reproductive continuum.

Our first examination of birth control practices divides them into three categories:

1.  **Contraception** -- the intentional prevention of impregnation using a (generally artificial) device, agent, sexual practice, or surgical procedure.
2.  **Post-Conception Birth Control** - abortion and infanticide
3.  **Natural Birth Control** - any method of avoiding pregnancy that utilizes fertility awareness and periodic abstinence to avoid pregnancy. 

### Required Readings {.unnumbered}

1.  [Understanding Human Sexuality](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g) 3rd Canadian Edition. Janet Shibley, Hyde, John D. DeLamater, & E. Sandra Byers. Toronto: McGraw-Hill Ryerson. 2006 (Please click on the link to access Google Drive where the text is located.)
	1.  Chapter 07, pages 176 to 215 “Contraception and Abortion” Focus on the historical and political aspects of contraception and abortion. This chapter will be re-read in Unit D where you will focus on the contraception and abortion methods specifically.

### Learning Objectives {.unnumbered}

After completing the readings and activities in this section, you should be able to:

1.  Identify the various methods of birth control and the periods in which they were introduced.
2.  Distinguish between categories of birth control:  contraception, abortion and infanticide, natural birth control.
3.  Discuss the important role of birth control in your life as well in the lives of people across cultures and throughout time.
4.  Begin to realize the power and pervasiveness of spiritual myths related to the essence of the feminine.
5.  Identify some of the issues that have affected use of fertility awareness methods (FAM).

----

## 2.2 - Contraception {.unnumbered}

The earliest of human history records include practices of contraception. Historical records, medical texts, and sacred scriptures of the ancient Jewish, Islamic, Egyptian, Persian, and Hindu peoples refer to the use of a variety of contraceptives and forms of permanent or temporary sterilization. Recorded methods include: withdrawal or seminal retention, douching after intercourse, herbs or spermicidal preparations or suppositories inserted into the vagina, diaphragms, pessaries (caps), intrauterine devices (internal and external), condoms, hormonal contraceptives, sterilization, and periodic abstinence with or without the use of a variety of fertility awareness and calendar calculation methods. All of these methods or techniques have been practiced in some form throughout history, with the exception of hormonal contraceptives, which began to be introduced in North America and Europe in the 1960s.

In browsing through literature about ancient birth control methods there is evidence of remarkable resourcefulness and variety. However, there is little detail regarding the preparation, acquisition, and use of ancient methods. Perhaps this is due to the general paucity of historical literature and records about or by those who would likely have been the primary users and inventors of such methods. This lack of information may be because such information was considered sacred and/or dangerous to the uneducated and or uninitiated and was thus protected from mass dissemination by being passed down through oral tradition and apprenticeship, or encoded into magical or sacred texts. It would seem that since antiquity the primary method of educating others about birth control has been through apprenticeship with those knowledgeable in 'wise-woman ways' or folk medicine. Regardless of how the knowledge was obtained, since antiquity individuals have procured abortions, practiced infanticide, and used contraceptives despite religious, moral, or legal prohibitions against them.

 Historical records tell of the practice of **coitus interruptus** or **withdrawal**. This sexual technique requires that the man withdraw his penis from the woman's vagina before ejaculation, and release his ejaculate outside the woman's body. It is and always has been condemned by Judaism and Roman Catholicism as a sin against God's command to procreate. There is historical evidence that doctors also argued vehemently that this practice was dangerous, causing nervousness, impotence in males and “hardening of the uterus” in females. It is not surprising that coitus interruptus was commonly practiced in Medieval Europe, where the only other form of birth control available to Christians was late marriage and an early death. Studies done in the United States during the 1920s and 1930s established that coitus interruptus was then the most common non-medicinal form of birth control. _Coitus interruptus (withdrawal) is still the most widely practiced form of birth control._

**Seminal retention** (coitus obstructus or **c**oitus reservatus) is recommended in several Sanskrit texts. It is a sexual technique intended to prevent the man from ejaculating by applying pressure on the forepart of the testicle to block the urethra and force the man's semen backward into his bladder. Hindus have used it for hundreds of years as both a method of contraception and as spiritual practice. Some North American and European utopian and eugenic groups used it in the late 18th and early 19th Centuries. Currently, many people who follow certain Eastern spiritual practices use this method simultaneously as a method of birth control and spiritual development.

**Contraceptive douche** is a spermicidal liquid mixture that is washed into the vagina using a gravity feed syringe apparatus following sexual intercourse. Various forms of douche and techniques for douching have been used (although records show not very effectively) since ancient times. Greek physicians recommended the use of vinegar both as a douche and an application to the penis to kill sperm. There are recipes for douching in 19th Century books that were available to European and North Americans. In the 1960s, douching with Coca Cola as a popular form of emergency contraception.  With the advent of hormonal birth control, douching became a less popular method. Currently, it is unknown how many actually use this form of birth control, though evidence suggests it is not a popular method.

**Spermicidal agents** (spermicide or spermatocide) work by killing sperm directly or by making the woman's vagina hostile to their survival. Ingredients of choice for spermicidal agents include: the dung of crocodiles (Egypt), sheep, snakes, certain beetles, and other creatures, or a mixture of honey and natural sodium carbonate (Egypt), olive oil (Mediterranean), chopped grass or cloth (Africa), bamboo tissue-paper balls (Japan), wool (Greece and Persia), linen rags (Prussia, Slavic groups), and a sea sponge wrapped in silk (Jewish). Currently, as with douching, the modern versions of these methods are not popular. Contraceptive **vaginal suppositories** that are inserted into the vagina, much as a tampon is inserted are designed to melt at body temperature and cover the woman's vagina and cervix with a spermicidal agent. 

**Pessaries** are caps designed to fit over the cervix and hold a spermicidal agent. Some pessaries themselves acted as a spermicide. **Diaphragms** similar to pessaries serve the same purpose. They are fitted into the vagina by lodging them behind the pubic bone and the posterior side of the cervix so that they cover the cervix. They are meant to hold spermicide against the cervix. Contraceptive **vaginal suppositories** that are inserted into the vagina, much as a tampon is inserted are designed to melt at body temperature and cover the woman's vagina and cervix with a spermidical agent. Pessaries and diaphragms also provide some minimal barrier protection against sperm entering the cervical canal. Numerous recipes from ancient times are known for vaginal suppositories, pessaries, diaphragms, and accompanying spermicides.

**The male or external condom**, a barrier method of contraception consisting of a sheath made of latex, lambskin, or other material that fits over the man's erect penis and collects his ejaculate, was first used to prevent sexually transmitted infections (STI). Historical documents do show that many users were aware of its contraceptive potential. Western nations started actively manufacturing the condom in the 18th century, with consistent and prolific production starting in the middle of the 19th century. After World War I, the widespread use of condoms among North Americans and Europeans to prevent STIs was instrumental in the acceptance of condoms for contraceptive purposes; even religious fundamentalists were forced to encourage its use. _The condom is the second most popular method of male contraception after withdrawal._

The **female or internal condom** consists of a polyurethane pouch inserted into the vagina to cover the vaginal walls and cervix, catching any ejaculate deposited in the vagina. The female condom has flexible rings at each end. Just before vaginal intercourse, it is inserted deep into the vagina (like a tampon). The ring at the closed end holds the pouch in the vagina, and the ring at the open end stays outside the vulva during intercourse. Female condoms are more expensive than male or external condoms. They are not very popular.

**Birth control medication** later referred to as “the pill” or “the birth control pill” was first introduced in the 1960s. The **birth control pill**, which incorporates artificial analogues of estrogen and progesterone to affect the menstrual cycle and ovulation process, was heralded as the ultimate contraception solution. Initially, the artificial estrogen in the pill worked to prevent the ovaries from releasing an egg. Later formulations, containing less estrogen to reduce adverse physiological side effects, allowed for the occasional ovulation. Regardless, the pill was still effective because its ability to cause the uterine lining to become a “hostile” environment to an implanting embryo allow it to still prevent pregnancy. The high performance rate of the pill, when taken properly, made it the method of choice for those who lived in countries that permitted its use and sale. For the first time, the birth control pill made it an attainable reality to plan for pregnancy, the number and timing. Like many other pharmaceutical “solutions,” oral contraceptives were found to have serious health risks, especially among smokers. Among them were abnormal blood clotting and increased risk of heart attack, cancer, and gallbladder disease. The health risks of taking the birth control pill, and related birth control medication has caused heated debate among health professionals who advocate its wholesale use and those who desire it being taken off the market. Where available, hormonal birth control is still a majority choice, at least for some of the reproductive years. Aside from the oral birth control pill, hormonal methods today include: injection (Depo-provera), patch (Evra), hormonal implant (Norplant), intra-uterine systems (IUS) (i.e. Mirena, Jaydess), vaginal ring (Nuvaring), or pessaries.

**Intra-uterine Devices (non-hormonal)** **and Intrauterine Systems (hormonal)  are** contraceptive devices that are fitted inside the uterine cavity by way of the  vaginal canal. They create biochemical changes that interfere with the implantation of fertilized ova. The IUD may be made of plastic and/or copper. Hormonal IUDs release synthetic hormones. Copper IUDs are non-hormonal. Hormonal IUDs are thought to prevent pregnancy in various ways: thickening cervical mucus thus affecting sperm transport, thinning the secretory lining of the uterus thus interfering with implantation. Copper released into the uterine cavity by the Copper IUDs is thought to weaken and kill sperm, as well as interfere with sex steroid metabolism. All IUDs create a mild inflammatory condition in the uterine cavity that also interferes with implantation. 

Evidence suggests that forms of **sterilization** - surgical intervention to disable the reproductive system - may have been practiced since ancient times. The current practice of male sterilization **(vasectomy)** involves surgical sealing, tying, or cutting of the tube through which sperm travel from the testicles to the penis. Female sterilization **(tubal ligation)** involves surgical tying, cutting, or blocking of the fallopian tubes to prevent sperm and eggs from meeting. These procedures are regarded as permanent, though a small percentage can be successfully surgically reversed. In Victorian times, during the inception of westernized medicine and development of modern psychology (the era of Sigmund Freud), practitioners sometimes removed the reproductive organs as a remedy for hysteria and other illnesses--(clitorectomies were also performed as a similar “cure”). Sterilization was used in the late 19th Century - and continues to be practiced by some governments today - on those with mental or physical challenges in the interests of eugenics (the science of “improving” populations)..

#### **Required Reading** {.unnumbered}

1.  Gordon, L. (2007). _The moral property of women: A history of birth control in America._ Chicago, IL: University of Illinois Press. **(Part 1)** An earlier version of this text was Gordon, L. (1990). _Woman's body, woman's right: Birth control in America_ (2nd ed.)_._ New York, NY: Grossman/Viking.

  

___

  

### Journal Activity - A.2.2: My Experience with Contraception {.unnumbered}

#### My Experience With Contraception {.unnumbered}

Choose **one** of the 2 options below for your journal response here:

1.  Reflect on your own experience with contraceptives. Write some notes in your journal in response to items A to F listed below, and/or other thoughts that occur to you as they relate to your experience with contraception. 
    
    1.  How did you first learn about birth control?
        
    2.  What are some experiences you've had in discussing birth control with others (peers, teachers, healthcare providers, etc.)?
        
    3.  Have you tried various methods described in this section? If so, what have been the benefits and drawbacks?
        
    4.  What are some experiences you've had in negotiating birth control with partners?
        
    5.  If you have not yet tried any of the methods described in this section, which ones do you think you might be likely to try and why?
        
    6.  Which methods do you think you would never try and why? 
        
    
    2\. Go to your local sexual health clinic, and request information about birth control options. Be sure to ask lots of questions, including explanations of how popular methods work. Which of these methods were you offered? Did the health provider discuss any method's benefits, side-effects, or drawbacks? Did they ask about your relationship with your partner? Were you steered in any one direction? Document and reflect on your experience.

----

## 2.3 - Post Conception Birth Control {.unnumbered}

Historically and globally, **infanticide**, the practice of killing newborn infants, was periodically used to control population. Aristotle (384 -322 B.C.E.) and Plato (427-349 B.C.E.) recommended infanticide for eugenic reasons. Although infanticide, like abortion, is today not thought of as a form of birth control, historically many would include it as another option. Infanticide has been especially common in communities where it is desirable to alter the sex ratio between males and females in order to maintain a viable sexual division of labor. It has also been used in conditions unfavourable to population growth, such as famine, drought, and personal hardship and community disaster. Infanticide has also been used where abortion was not safely or easily obtained, and among nomadic peoples to maintain mobility. Please see the discussion of infanticide in Gordon's _Moral Property of Women, pages 13 - 15._

 In most societies, the decision to commit infanticide was a male's decision. Many 18th and 19th-Century documents and transcripts of trials for infanticide and abortion in the United States suggest that both practices were widespread. Historically most infants killed were female, and female infants remain the primary victim of modern infanticide practices,still used in some parts of the world (e.g. Tahiti, Formosa, India, and North Africa). Infanticide is rarely practiced where it is an actively punishable crime and where contraceptives and abortion are available.

Depending on whether you equate a developing fetus with an infant, **abortion** could be viewed as a sort of preemptive infanticide, thus the close association of these two practices among those who seek to control what females do with their uteri. Historical documents of diaries, correspondence, rituals, and medical  pharmacopoeia indicate that abortion has been commonplace throughout history. This suggests that many did not consider abortion immoral, even when it was explicitly regarded as immoral and illegal. The most dangerous abortions were those done by unskilled abortionists or self-induced abortions by those who were not knowledgeable about how to proceed thus. Abortion was always a viable option because before the 19th century more females died from childbirth and its complications than from abortions.

Although the overall death rate from pregnancy complications has lowered, more females still do die from complications associated with childbirth, than from complications associated with abortion. See the [WHO Maternal mortality Fact sheet N°348 Updated November 2015](http://www.who.int/mediacentre/factsheets/fs348/en/):

Also see [WHO Medical Eligibility Criteria for Contraceptive Use 5th Ed](http://www.who.int/reproductivehealth/publications/family_planning/MEC-5/en/) as noted in the Comparative Readings list in the Unit A Syllabus.

Currently, the particular availability and the acceptability of abortion varies widely by country and region, culture, and religious group.

See [Abortion in the Premodern World](https://mw.historynuances.com/2218-abortion-in-the-ancient-and-premodern-world.html) for a worldwide history of abortion, along with this article, [When Did Abortion Begin?](https://www.thoughtco.com/when-did-abortion-begin-721090)

  

___

  

### Journal Activity - A.2.3: My Thoughts about Abortion {.unnumbered}

My Thoughts About Abortion

From the 14th to 17th Centuries, many wise-women (and some wise-men), who provided safe and effective means of contraception and abortion, were killed for practicing witchcraft. With the loss of these women came the loss of an enormous oral tradition of medicine and healing, including contraception and abortion. As the Christian church and male medical profession gained power in Europe and North America, abortion was increasingly relegated as a crime. With very few wise women practicing their craft, and increasingly medical doctors performing surgical abortion without proper antiseptic technique, abortion had become dangerous for women. Some rulings against abortion were meant to protect women from the dangers of the procedures. Other rulings against abortion were meant to control freedom, and reinforce misogynistic and patriarchal attitudes towards female-flesh and female-blood. New understandings of the biology of conception and pregnancy, which demonstrated that the fetus was “alive” or “ensouled” sooner than previously thought, also fueled the movement against abortion. (For example, the Christian church had previously considered 40 days after conception for a boy and 80 days for a girl as the moment of “quickening” or the beginning of life. A consideration that had no validity before the use of fetal ultrasounding.)

1.  Do you consider abortion to be a viable, moral means of birth control?
2.  What authorities, in your view  (i.e. governments, churches, medical practitioners) should have input as to whether and under what conditions abortions are performed?

----

## 2.4 - Natural Birth Control {.unnumbered}

This is a brief touch on the topic of natural birth control, which is dealt with in more depth in Unit D Section 7.

Natural birth control contrasts markedly from other forms of contraception. It utilizes knowledge to identify the optimum times for procreation and time sexual intercourse accordingly to achieve or avoid pregnancy. Such identification involves a woman learning about the natural workings of the female and male reproductive systems and the physiological signs and events that reflect those workings, particularly the female reproductive cycle. Unlike the contraceptive methods described in Section 2.2, natural birth control does not depend upon either organic or synthetic biochemical intervention or manufactured or computerized devices. Natural birth control is based on a conscious awareness of one's immediate state of fertility or infertility, unlike other contraceptive methods where such awareness is not required and are generally used with blind hope that they will interfere with nature's intention to procreate. Natural birth control methods are discussed in detail in Unit D as well as the difference between Natural Family Planning (NFP) and Fertility Awareness Methods (FAM) 

**Natural birth control** is any method of avoiding pregnancy that utilizes **fertility awareness and/or periodic abstinence.** Fertility awareness is the determination of episodes of fertility and infertility within a single menstrual cycle. This determination is made based on an understanding of symptoms and events that are reflective of the female reproductive system's unfolding fertility and infertility. The practice of fertility awareness requires the user to develop the understanding to make the above determination by personally and directly observing and charting those symptoms and events that indicate fertility and infertility. Fertility awareness methods (FAM) apply this knowledge to avoid or achieve pregnancy. 

**Periodic Abstinence** is the intermittent avoidance of vaginal intercourse either to avoid pregnancy or as part of a spiritual or cultural practice. The first recorded use of periodic abstinence was for spiritual and cultural purposes and later for birth control. Periodic abstinence during identified fertile days of a woman's menstrual cycle is the contraceptive basis of natural birth control. The term periodic abstinence is used synonymously to refer to natural birth control, rhythm method, safe period, natural family planning (NFP), fertility awareness (FA), and various fertility awareness methods (FAM).

----

## 2.5 - Conclusion {.unnumbered}

From studying this introduction to the practice of birth control you will have begin to understand the complexity of the field of birth control. On the one hand, we seem to benefit from a wealth of alternatives, some of seem effective and convenient. 

In the 60s' sexual revolution it might have made sense for a heterosexual couple to share a Coke, have sex, and then for the woman to douche with a little of the leftover refreshment. Or, for her to apply a little pinch to the testicle (see seminal retention) that could not only act as a birth control life “preserver” (pardon the pun) but also an impish retaliation for any real or perceived sins of her partner. Seriously though, trying to introduce birth control into living is no easy,task nor no laughing matter.  It may indeed be a matter of life and death.  Foremost is the question of reliability and responsibility.

Individuals are learning more and more how to 'do it themselves' when it comes to birth control, and demanding greater access to resources to do so. One of those resources is fertility awareness education. However there are many questions yet to ponder.

What if birth control fails?  Who is to blame and who _bears_ the responsibility?  What are the side effects of birth control methods or the outcomes of unplanned pregnancies and how do they affect our sex lives, our position in community and our health?  Finally, how on earth do we get reliable, non-politicized, and non-partisan information and counsel to help us make our own choices?

For those of us who are committed to religious orders and institutions, the questions can become even tougher.  How do we reconcile the laws of our religion with the needs of ourselves, our family and the larger community?  Who is the ultimate authority - ourselves, our partners, governments, churches, a particular image of the divine, and / or the community? These questions are explored as we move through the rest of Units A, B, and D.