# 3: Birth Control: Social and Historical Context {.unnumbered}

## 3.1 - Introduction {.unnumbered}

### Introduction {.unnumbered}

Since ancient times, people have sought ways to control conception and limit the number of births for physical, psychological, social, and economic reasons. Often the compelling necessity to control conception has driven people to use various methods of birth control under circumstances that were frankly dangerous or prohibited. Periodically throughout history, various political, medical, spiritual, and religious leaders have sought to control contraception, abortion, infanticide, and human sexual practice.

Historical discourse on contraception often assumes that before the 18th Century, people had little or no access to contraceptive knowledge or means to limit birth except through natural attrition (high infant mortality due to disease and malnutrition of the infant and/or the mother and prolonged breastfeeding).  However, it is important to take into account the loss of contraceptive knowledge due to religious fundamentalism grounded in patriarchal and misogynistic epistemologies (e.g. Judeo-Christian, Islam, Hinduism, Buddhism); typically suspicious of wise-women or indigenous practices that relate to birth control and abortion. The continual colonization of patriarchal and misogynistic attitudes into all world cultures and the resulting vehement valuing of capitalism and materialism do not favor women having authority regarding their woman-flesh, woman-blood, sexuality, or reproductive processes. Equally, though perhaps differently, they do not favor men -- or persons who are gender or sexually diverse.

The baby boomers (1946 - 1964) may claim that they invented or initiated sexual liberation. Similarly, each generation seems to believe that they in some way have liberated sexuality more than their predecessors. Unit A Section 3 explores access to birth control information and freedom of sexual practice and demonstrates how these issues have fluctuated markedly over time as influenced by the prevailing cultural mores.  Importantly, the practice of birth control today continues to be governed by a wide diversity of political sanctions, religious strictures, medical proscriptions and pharmaceutical persuasions, among a variety of other factors.

There is a confluence between the history of attitudes toward birth control and the history of attitudes towards females, the feminine, and sexuality. This section offers an overview of landmark eras in birth control and looks at the profound effects of Christianity and other sociological influences in the development of knowledge and practice of birth control.

Our historical overview of the practice and politics of birth control methods is divided into the following sub-sections:

-   Section 3.2 Witches, Midwives, and Nurses
-   Section 3.3 Ancient Times
-   Section 3.4 The Christian Church and Sexual Morality
-   Section 3.5 Spiritual Influences of Some Major World Religions
-   Section 3.6 The 18th & 19th Centuries
-   Section 3.7 The 20th Century
-   Section 3.8 International Discourse on Birth Control
-   Section 3.9 Contraception & Abortion Timeline
-   Section 3.10 Pill Timeline

### Learning Objectives {.unnumbered}

After completing the readings and activities in this section, you will have more fully developed your ability to:

1. Identify key historical periods and trends in the development of birth control
2. Discuss the influence of the Christian church on the practice of birth control
3. Identify and discuss the various influences that have encouraged or discouraged the practice of birth control
4. Understand more fully the profound implications for any woman in any time period of the influences of spiritual, governmental and cultural forces with respect to who controls the female reproductive body.

### Required Readings {.unnumbered}

1. Ehrenreich, B., & English, D. (2010). _Witches, midwives and nurses: A history of women healers_ (2nd ed.). New York, NY: The Feminist Press.
    
2. Pope Paul VI. (1968). Humanae Vitae.[http://w2.vatican.va/content/paul-vi/en/encyclicals/documents/hf\_p-vi\_enc\_25071968\_humanae-vitae.html](http://w2.vatican.va/content/paul-vi/en/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae.html)
    
3. Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 20: Ethics, religion, and sexuality. In Understanding human sexuality (3rd ed.) (pp. 567 - 595). Toronto, ON: McGraw-Hill Ryerson.
    
4. Gordon, L. (2007). The moral property of women: A history of birth control in America. Chicago, IL: University of Illinois Press. **(Parts 2, 3, and 4).** An earlier version of this text was Gordon, L. (1990). Woman's body, woman's right: Birth control in America (2nd ed.). New York, NY: Grossman/Viking.
    
5. Martin, E. (1987). _The woman in the body: A cultural analysis of reproduction_. Boston, MA: Beacon Press.
    
6. Thomas, J. E. & Zimmerman, M. K. (2007). Feminism and profit in American hospitals: The corporate construction of Women's Health Centres. Gender and Society, 21, 359 -383. doi:10.1177/0891243207299947. [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Feminism%20and%20Profit%20in%20American%20Hospitals.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Feminism%20and%20Profit%20in%20American%20Hospitals.pdf) 
    
7. Pro-choice Action Network. (2009). A legal history of abortion in Canada. Vancouver, BC. [http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml](http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml) 
    
8. Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 7: Contraception and abortion. In Understanding human sexuality (3rd ed.) (pp. 183 - 224). Toronto, ON: McGraw-Hill Ryerson. See “Abortion” (pp. 206 - 213).
    
9. Merhi, D. (2012). For their own good: Ontario's legal legacy of the “moral” woman. Dominion: News from the grassroots 84. [http://www.dominionpaper.ca/articles/4526](http://www.dominionpaper.ca/articles/4526) 
    
10. Gibbs, N. (2007). Abortion in America: 1 Woman at a time (pp. 15 - 23). Time. [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Wars.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Wars.pdf) 
    
11. Saletan, W. (2006). Where the rubber meets Roe: The pro-life case for contraception. Slate. [http://www.slate.com/articles/health\_and\_science/human\_nature/2006/09/where\_the\_rubber\_meets\_roe.single.html](http://www.slate.com/articles/health_and_science/human_nature/2006/09/where_the_rubber_meets_roe.single.html)   
    
12. Timeline: The pill. PBS. Pill Timeline.pdf, [http://www.pbs.org/wgbh/amex/pill/timeline/index.html](http://www.pbs.org/wgbh/amex/pill/timeline/index.html)

----

## 3.2 - Witches, Midwifes, Nurses {.unnumbered}

Matriarchal and Goddess-centered cultures are attributed responsibility for inventing calendars. These cultures kept careful account of earth, sun, and moon cycles and organized seasonal rituals around them. They recognized the significance of Earth's infertile and fertile regions and seasons. While there are no pre-patriarchal historical accounts of women charting their menstrual cycles or the use of periodic abstinence to specifically avoid pregnancy, it is more than reasonable to conjecture that the peoples of Goddess-centred\[1\] theologies and cultures had some awareness of the workings of the female reproductive body, including its fertile and infertile phases. It is also reasonable to conjecture that they used that knowledge to avoid or achieve pregnancy.  Historical evidence suggests that any such knowledge or its application would have been devalued and lost during the rise of patriarchal rule.

 Over the centuries, with the rise of patriarchal rule and the penetration of androcentric, monotheistic religions throughout the world, feminine archetypes were progressively regarded negatively, and excluded or repressed from conscious life. All that was female or associated with the idea of female - menstrual blood, sex, birth, breasts, breast milk, the female body, and “women's intuition” was seen as dangerous to the perpetuation of patriarchal values and androcentric monotheism. Sacred menstrual rituals acquired a highly negative connotation and became menstrual taboos based on fear of woman-blood. (We discuss this topic in Section 5). Patriarchal and monotheistic religious leaders actively sought to diminish the sacredness of menstrual blood and female sexual nature, which was closely associated with the earth and rhythms of nature. The unpredictability of nature was regarded as threatening, because the patriarchy (most notably starting with the classical Greeks) valued the rational, predictable, and controllable. The more detached a thought or spiritual pursuit was from the physical body, the more highly it was valued. Masculine archetypes began to take-over the attributes associated with the divine feminine and archetypal midwife, of which Hermes and other Greek and Roman Gods are examples. As awareness of the archetypal and divine feminine figures was repressed, these figures began to emerge unconsciously in perverted, negative, or dangerous forms, giving birth to, for example, the Middle-Ages idea of the witch. The importance of women's contribution to society, their fertility, and their sexuality, was and is systematically obliterated and devalued.

 The realm of the midwife-wise-woman-witch was once sacred territory; governed by the initiated and protected by those they served. The tradition of allowing witches to preside over the mystery rituals associated with birth (Ehrenreich & English, 1973) is a vestige of the once sacred regard for midwifery, and the midwife's unique role in the transformational blood mysteries.

Before the 14th Century, witches were exempt from taboos related to menstrum and lochia (Walker, 1983). As initiates and ministers of the blood mysteries, it was thought they were able to withstand the nuministic power of woman-blood. After the 14th century, Christian, Jewish, and Muslim patriarchs, as well as the “fathers” of modern medicine declared the work and bodies of witches (midwives and wise-woman) unholy and set out to annihilate their bodies and their body of healing work, accumulated over hundreds of generations.**\[2\]**

### Required Reading {.unnumbered}

Ehrenreich, B., & English, D. (2010).  _Witches, midwives, and nurses: A history of women healers_ (2nd ed.). New York, NY: The Feminist Press. (see Unit A Reading List)

### References {.unnumbered}

1.  Ehrenreich, B., & English, D. (2010).  _Witches, midwives, and nurses: A history of women healers_ (2nd ed.). New York, NY: The Feminist Press. (see Unit A Reading List)
2.  Walker, Barbara G. (1983). "menstrual blood” and “menstrual calendar” In _The Woman's Encyclopedia Of Myths And Secrets._ San Francisco: Harper Row. pages 635-648



\[1\] Goddess-centred - the term goddess-centred is somewhat misleading, as such cultures focused on figures of the divine feminine in sacred union with figures of the divine masculine. When one considers issues of fertility and generativity this makes perfect sense as ideals of relatedness. The divine figures of patriarchal cultures idealize divine masculine figures that operate independently of a divine feminine partner (for example Yahweh) and all relationships are based on control and power over. Patriarchal gods (for example Zeus) acknowledging relationship to a divine feminine figure were so in an attitude of control and power over the feminine, devaluing and demonizing the divine feminine and using it for their own aggrandizement and assertion of power.

\[2\] Matus, Geraldine. _Psychologist as Midwife of Soul: A Labyrinthine Exploration of the Midwife Archetype in Psychological Practice_. Pacifica Graduate Institute Masters of Art Thesis, March 15, 2003, pp.27-28.


### Seeing Red {.unnumbered}

THIS IS AN OPTIONAL EXERCISE

They are misfits. Witches. Children. Just a few of the labels used to portray menstruating women over time. The Bible has described the bleeding woman as undergoing "customary impurity". In the Middle Ages, it was thought that women menstruated to release "sexual overflow". Their counterparts in the Victorian era were told that a period would deplete their body's precious resources. Twentieth century feminists worked hard to reclaim menstruation as a vital and positive part of womanhood. IDEAS producer **Mary O'Connell** explores menstruation from a cultural and historical perspective. One of her interviewees is Geraldine Matus. The title of the episode is "Seeing Red" Canadian Broadcasting Corporation (CBC) Digital Archives [http://www.cbc.ca/archives/](http://www.cbc.ca/archives/) 

You can search 'Seeing Red'- CBC Mary O'Connell.

Part 1 [http://www.cbc.ca/player/play/1522579650](http://www.cbc.ca/player/play/1522579650)

Part 2 [http://www.cbc.ca/player/play/1528882334](http://www.cbc.ca/player/play/1528882334)

The intention of inviting you to listen to this recording is to fuel your pioneering desires to help women become empowered in feminine spirit and vital in body.
  
----

## 3.3 - Ancient Times {.unnumbered}

In **ancient Greece**, Aristotle officially supported homosexuality as a form of birth control. Women used contraceptive practices that were part of the "feminine mysteries,” and though chronicles by male writers verify the existence of these practices, very little detail is known about the procedures. Contraception was preferable to abortion, which was considered dangerous. Abortion was not a moral issue, as the fetus was not considered a separate entity from the mother until its birth. Married women were expected to obtain their husband's permission before procuring an abortion. Unmarried women were expected to abort their babies.  To not do so would dishonor their fathers and risk the women being sold by them into slavery (Law of Solon).

Forms of natural birth control were openly discussed in the **Hellenic period** \[1\]. During this period women enjoyed a relative freedom and independence, and had access to education and were accustomed to active participation in religious rites as well as the arts and medicine. Many were attracted to some of the early Christian cults (c. 200 B.C.E.) that preached equality of the sexes. It must have been bitterly disappointing when the church changed its support of women's freedom and control of their bodies, and developed into a patriarchal, misogynistic, and hierarchical institution that increasingly insisted women become what was their “nature” - silent and subordinate to men. Only the Gnostic and Manichean cults (heretics to the Roman Christians) preserved women's freedom, encouraging them to preach and prophecy, condoning contraception and abortion.

In **ancient Rome**, husbands and wives desired to have enough children to inherit their wealth, without jeopardizing its abundance. As well, the women sought to preserve their health by limiting the number of children they had. There were no prohibitions against any contraception or sexual practice, including masturbation, withdrawal, abortion, or homosexuality. The ancient Romans' relationship to their bodies centred on hygiene and pleasure. Roman law referred to the fetus as “_spes animantis”_ (lower or despised animal) which was not living or _“anima”_ (ensouled) until birth. Once born it was referred to as _homo_ (human being) or _infans_ (child). Like the ancient Greeks, the ancient Romans considered the foetus as part of the mother until birth. Thus abortion was not a moral concern.

Documents from **Gallo-Roma**, during the early **Christian invasion into Gall**, record that women simply took what potions they saw fit to contracept or abort, believing their drinking of the potions was unconnected to their soul. Nor could Roman matrons be dissuaded from taking similar potions. Roman matrons believed that using abortifacient or contraceptive preparations was moral if their intentions for using them were honest and 'pure.' These women referred to their own conscience before the dictates of men, and used the help of wise women healers when procuring contraceptives or abortions.

\[1\] Hellenic period, from “Hellas,” Greek name for Greece, the classical period of ancient Greek civilization, from the first Olympic Games in 776 BC until the death of Alexander the Great in 323 BC.

## Journal Activity - A.3.3: Obtaining Permission to Abort {.unnumbered}

### Obtaining Permission to Abort {.unnumbered}

In ancient Greece and Rome abortion was not a moral issue, as the fetus was not considered a separate entity from the mother until its birth. Married women were expected to obtain their husband's permission before procuring an abortion, and unmarried women were expected to abort any pregnancies in order to safeguard their father's honour. Reflect on these ancient provisions in light of modern day 'permissions' to abort. What is similar or dissimilar about ancient times versus current times with respect to obtaining permission to abort? 

OR 

Find out information regarding abortion providers in your area. What is the legal status of abortion in your country? How accessible would the service be to you if you required it? What sorts of barriers might women in your community encounter in obtaining abortion? Reflect on your experience gathering information, and tell your journal your opinions of the information gathered.

----

## 3.4 - Christian Church and Sexual Morality {.unnumbered}

**Early and medieval Christians**, particularly Western Christians, were concerned with attaining holiness through victory over the 'primitive' nature of humanity, particularly power over 'desires of the flesh'. To this end, the Christian church gathered and closely guarded records of wise-women practices about birth control and abortion, fervently condemning such practices and using such records as evidence for the condemnation of witches. The church countered wise-women teachings and literature with rhetorical doctrines that created proscriptions against birth control and abortion, as well as certain sexual practices. These affected particularly single women and men, and married couples.

However, early Christian doctrine was ambivalent in its attitude towards women and the desires of the flesh so frequently associated with them. Jerome and John Chrysostom described the general nature of females to be evil. In the early years of witch persecutions, **Christian scholars such as Tertullian and Clement** made special appeals on behalf of women and womanly virtue, although they still believed them subordinate to men in all ways. Many women employed this ambiguity to make arguments for defying the husbands, fathers, and churchmen who sought to control their sexuality and reproductive bodies.

**From the 1500s through the 1700s**, the Christian church leaders aspired to make chastity the supreme virtue, as a way to reinforce their theological construal that a woman's woman-blood and primitive sexual nature interfered with the higher spiritual pursuits of men. Priests were given the ultimatum: to leave their wives and become celibate or leave the church. The advance of a celibate priesthood was as tied up with property laws that favoured the church as it was with spiritual perfection. Even men not in the priesthood or directly involved with the church were encouraged to deny sexual pleasure of all kinds, and follow the tenets of 'Courtly Love.' Those who could not control their sexual desire were encouraged to marry. The church conceded that while sex outside of marriage was a mortal sin, sex between husband and wife was justifiable for the purpose of procreation - not pleasure. It forbade birth control, abortion, and infanticide.

The **observance of celibacy** accompanied a denigration of women's reproductive power and sexuality, and more firmly placed the projection of collective Christian evil onto women and women's bodies and blood. Early Christian theologian Augustine of Hippo (Saint Augustine) proposed this strikingly misogynist idea, “If it is not to generate children that the woman was given to the man as a helpmate in what could she be a help for him?” The Christian defence of the celibate and contemplative life had powerful appeal for many women. The appeal was threefold, it gave a genuine opportunity to live a religious life, it represented an alternative to marriage and childbearing, and an opportunity to redefine sex roles.

For **Pagans**, raising and bearing children were equally important, thus adoption was widely employed, resulting in diffused concepts of maternity and paternity. The church aggressively condemned adoption, fostering, and wet-nursing, resulting in the placement of an unprecedented emphasis on the biological nature of procreation, and which lead to more interest in contraception, abortion, and sexual practices for avoiding conception. The church's rationale for their condemnation of adoption included fear of incest, the association of adoption with pagan worship, and the association of false heirs with plural marriages. However, the church's greatest concern was the loss of its influence on the family. Thus it adopted the notion that designated heirs were not as important as spiritual heirs.  From this the concept of 'god parenting' emerged as an increasingly important way for the church to maintain its influence on the family.

**Despite all the church's attempts to control family life** and enforce female compliance in the creation of large families, most medieval families were modestly sized. Economic constraints played a major role, with the practice of late marriage providing the most effective means of birth control. Since land was the primary source of wealth, sons usually had to wait for a father's death or retirement to gain the economic independence that would permit them to marry and establish a new household. A large percentage of people never married.  For those who did, short life expectancy combined with late age of marriage resulted in marriages lasting only about 12 to 16 years with consequently low reproductivity. As well, infant mortality was high (only half the population reached the age of 20), resulting in an average family size of between 2 and 3 children. There is also evidence in what remains of the works compiled by wise-women healers that women practiced birth control during the Middle Ages. This evidence is supported by the fact that most women gave birth to several children in quick succession and then stopped childbearing altogether around 30 years of age without apparent cessation of menses.

Ultimately, **during the Middle Ages**, the church was more concerned with the pleasure that resulted from unnatural acts than their contraceptive effect. For example, the church condemned excesses of undue passion, sodomy, unnatural positions, and multiple of couplings, while viewing contraception as a minor moral problem, less punishable than sodomy. It was certainly not subjected, as sodomy was from the 13th Century, to savage punishments. The church's real purpose in the condemnation of fertility control was simply to support its campaign to remake marriage and family. At that time, the alchemist and scholar Peter Abelard denied the church's idea of the intrinsic sinfulness of sexuality.

Regardless of church doctrine, **women secretly continued to control their reproductive bodies**, ever devising new ways to do so among themselves and in concert with wise-women. The church's continual reiteration of its condemnations demonstrates that its hope of determining a collective stance regarding women's reproductive and sexual selves remained unsustainable, and understandably so given the mercurial nature of human sexuality and reproduction. Historical evidence suggests that increasing recourse to contraception and abortion was due to growing urbanization and industrialization that made large families an economic burden rather than an economic necessity as it was for rural farming families.

The Christian Church entered the public debate about birth control and the status of women. Its frontline churchmen held special appeals for the oppressed, in particular slaves and women. The appeals included converting the urban male elite into Christianity and encouraging them to take responsibility for limiting births, preventing sexually transmitted disease by not using prostitutes and financially supporting the mother's of their children. However, the more ascetic churchmen and church scholars viewed women with fear and loathing, and sought to shield men from women's 'devilish' seductions, holding women responsible for any suffering they incurred at the hands of men or society as proof of their ungodliness.

**Not until the late 19th century, did Christian churches allow sex for pleasure**, recognizing it as a means to enrich marital life. Protestant churches, with reservations, concluded birth control a matter of individual conscience and choice, though some fundamentalist Christian groups align with the Vatican. The Vatican was rigid in its view that contraception was immoral and that the primary purpose of sex was procreation, while conceding that sex was a binding and enriching factor in marriage. The Vatican gave Catholics permission to use periodic abstinence as a means of birth control, based on the theory of a French scientist who purported that women were fertile during menses (like the estrous cycle of some mammals) and infertile during the rest of their cycle. This type of periodic abstinence was called **paternal prudence**, referring to Catholic idea of the patriarchs' responsibility of caring for the world, women, and the family. The Catholic position on contraception is highly influenced by the natural law theory of Aristotle, Augustine and Aquinas, which deems that sexuality has as its end purpose, procreation; to interfere in this end would be a violation of the natural law, and thus, a sin.

In response to increasing artificial contraceptive use during the 1960s the Roman Catholic Church reiterated its 1700-year-old condemnation of contraception in the papal [Encyclical Letter: Humanae Vitae](http://www.vatican.va/holy_father/paul_vi/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae_en.html) in 1968. The document sanctions only abstinence and periodic abstinence (NFP) as suitable methods of birth control for Catholics, as well as outlines the Vatican's views and rulings on appropriate sexual conduct and abortion. For example, the document forbids abortion under any circumstance, the practices of withdrawal or seminal retention, abortifacient contraceptives (IUD, RU 486 or morning after pills), any form of hormonal contraceptive), and sterilization except if pregnancy would be seriously detrimental to a woman's health. They do allow calendar calculation (Rhythm Method), all fertility awareness methods (FAM), and periodic and complete abstinence.

### Required Reading {.unnumbered}

Pope Paul VI. (1968). Humanae Vitae. [http://w2.vatican.va/content/paul-vi/en/encyclicals/documents/hf\_p-vi\_enc\_25071968\_humanae-vitae.html](http://w2.vatican.va/content/paul-vi/en/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae.html).

----

## 3.5 - Influences of Major World Religions {.unnumbered}

### Spiritual Influences of Some Major World Religions {.unnumbered}

#### Eastern Orthodox Church {.unnumbered}

Unlike the Catholic tradition, the Eastern Orthodox Church does not discern a moral difference between artificial or natural birth control methods, allowing married couples to follow their conscience on issues of birth control. Eastern Orthodox priests are not celibate and typically marry. The church does not limit sexual practices to procreation, and encourages sexual expression as a vital demonstration of love within marriage. However, it does condemn abortion, infanticide, and sterilization.

#### Hinduism {.unnumbered}

The Hindu tradition encourages prolific procreation within marriage, and has no prohibition against birth control, but condemns abortion. The Upanishads (sacred Hindu texts) describe a method of periodic abstinence (In Brihadaranyaka Upanishad) advocated in the Shastras. Mahatma Gandhi advocated his followers use total or periodic abstinence for birth control. Other Hindu scholars, Radhakrishnan and Tagore, promote all methods of birth control. India was the first nation to establish a government population strategy based on birth control measures. 

#### Islam {.unnumbered}

There is a widespread variation on attitudes to contraception in the Islamic faith. The Qur'an states: "You should not kill your children for fear of want" (17:31; and 6:151). Critics of birth control argue that this can be extended to include a ban on all family planning methods, while advocates of birth control indicate that this passage explicitly refers to infanticide, and note that there is no prohibition against birth control in the Qur'an. Further, the Hadith and Sunni literature clearly permits the practice of coitus interruptus ('azl), and sources indicate that 'azl was practiced by the prophet Muhammed himself (Sunna related by Jabir). Those in favour of contraception argue that artificial birth control is morally the same as 'azl and therefore should be accepted. Most Muslim traditions permit the use of birth control where health reasons are an issue or where the well-being of the family is concerned. This affords great flexibility and latitude in interpretation and is reflected by the vast differences in policies on family planning by distinct Muslim groups and countries. Despite varying viewpoints, the emphasis remains on procreation within the family as a religious duty. There is unanimous official rejection of sterilization and abortion. 


## Journal Activity - A.3.5 Collective Influences {.unnumbered}

**Collective Influences** 

Consider whether your own views of contraception have been in any way influenced by collective religious belief systems. In a journal entry, either describe briefly some ways in which this is true, or discuss in your view whether spiritual or moral direction is needed in contraceptive matters.

----

## 3.6 - 18th and 19th Centuries {.unnumbered}

Before the 18th Century, **in France** women typically began bearing children in their late 20s or early 30s, and widely spaced their pregnancies although they still had many children. By 1830, the widespread use of contraception caused the country's birth rate to drop significantly. The term _'French family'_ became a euphemism for a two-child household. Following the French trend, birth rates in England and the United States began declining, dropping by 50 per cent between 1800 and 1920, with family size being reduced from an average of 5 to 7 children to an average of 3 to 4 children. There is historical conjecture as to the underlying impetus for reducing family size. Some believe it was the peasantry's intent to avoid dividing land among heirs and the bourgeoisie's efforts to maintain a certain standard of life. Others, like French feminist Condorcet, purported that women limited their childbearing to avoid the misery of childbirth and child rearing. Others cite the economic advantage of a smaller family size as the impetus for the increasing use of contraception and abortion.

However, regardless of steadily increasing family incomes, especially among the newly emerging middle class, family size continued to decline. Birth rates did not fluctuate according to economic prosperity, leading to the supposition that women's more individual and intimate needs were instrumental in declining birth rates. As women better understood ways to prevent pregnancies, and preventing pregnancy became a viable option, views regarding child bearing changed radically. The stoicism once assumed when facing marriage and numerous unplanned pregnancies was replaced with concerns about managing fertility and preserving health and life. Available and reliable birth control, safer childbearing practices, and preserving the health of reproducing women did not come about in a sudden event. It was not until the mid 20th Century that these became clear options. (It was not until the 1940s that sulpha drugs were available to counteract post-partum infections.) Regardless, over time the increased ability to avoid pregnancies and their resulting complications made women more not less determined to avoid them. Couples determinedly used condoms, coitus interruptus, periodic abstinence, and continence (total abstinence) as methods of contraception despite church or state sanctions against them.

**Some attribute the 19th Century increase in the use of birth control to** women's growing sense of individualism, cultivated by literacy and a growing expectation of personal empowerment. In comparisons of literate and illiterate women married to men of the same class, literate women had the lowest birthrate. Many working-class women valued reciprocal communal assistance and mutuality. They approached marriage pragmatically, accepting relationship with their community and other women - not their spouse - as the primary source of personal fulfillment. These women - mothers, sisters, daughters, and friends - were a powerful network providing each other with birth control information and assistance in the most significant areas of their lives.

The **density of a populated area** is often positively correlated to birth control use and lower birth rates. A concentration of women in a social network facilitates the passing on of information and advice regarding birth control. The rapid spread of lowered birth rates among Westernized nations, regardless of attempts by male dominated groups to prohibit or regulate birth control and abortion, is related to the fact that female culture during the 18th and 19th Centuries was for the most part unanimous in its stance for the availability of birth control.

Up until the establishment of the **American Medical Association (AMA)** in 1848, a variety of efficacious folk medicine and scientific approaches to health and medicine held equal status in society. However when the AMA was established, medical doctors began to prevail as the almost exclusive authorities over health issues as the powerful and wealthy male dominated AMA sought to control mainstream healing practices. Groups similar to the AMA were simultaneously grappling for control over medical practice in Britain, Europe, and Canada. These groups had enormous impact on birth control practices, the establishment and regulation of laws governing birth control practices, and the feminist and anti-feminist movements that sought to shape birth control policies and practices. These groups sought to disassemble the traditional community of women providing support and advice for each other on matters of birth control, female reproductive health, childbirth and childrearing, and to have them turn to the male medical doctor for all this support. These groups thus grew in power and influence with regards to controlling women's reproductive bodies, sexuality, and by attrition, dismantling their relationship to wise-women and centuries of old wise-woman knowing. Women began to expect their doctors to provide advice on abortion and contraception. Evidence suggests, that in 19thCentury America, up to a quarter of all conceptions were terminated by induced abortion, most of them by medical doctors despite regulations against such practice.

**During the 1870s, early suffragists in North America and Europe** campaigned for _'voluntary motherhood'_, advocating celibacy and abstinence as methods of birth control. Protestant women supported voluntary motherhood through the use of condoms, even though this male form of contraception was associated with prostitution. Certain feminists and women from the _Social Purity_ groups opposed birth control as a mechanism for simply offering another means by which women could be subordinated to men. Social moralists campaigned to prohibit 'sex for pleasure” along with abortion, and birth control. They maintained that sex outside of marriage, as well as sex within marriage for the purposes of pleasure and not procreation were immoral. In response to the ardent social moralists, suffragists became ardent feminists, who spoke out publicly at their peril for the provision of contraceptive information and contraceptives. For example, American citizen, feminist, and eugenicist, **Margaret Sanger (1879-1966)** campaigned from 1914 until 1937 to remove the stigma of “obscenity” from contraception. Her goal was to make medically prescribed birth control legal and available regardless of personal, social, economic, or medical reasons.

###  Required Reading {.unnumbered}

Gordon, L. (2007). _The moral property of women: A history of birth control in America._ Chicago, IL: University of Illinois Press. **(Parts 2 and 3).** An earlier version of this text was Gordon, L. (1990). Woman's body, woman's right: Birth control in America (2nd ed.). New York, NY: Grossman/Viking.
  

### Journal Activity - A.3.6 Three Articles On Abortion {.unnumbered}

#### Three Articles on Abortion {.unnumbered}

Find three substantive articles on abortion, either from a pro-life or pro-choice stance that have been published within the last 5 years. 

-   What is your response to these articles?
-   Are they helpful to you?
-   Do they inform you or confuse you?
-   What emotional response do they trigger (e.g. rage, indifference, frustration, curiosity)?

AND

Reflect on your personal history about issues concerning abortion, birth control, and sexual politics.

----

## 3.7 - 20th and 21st Centuries {.unnumbered}

**During the 20th and 21st Centuries,** powerful motivations emerged for developing new methods of contraception and reviving ancient methods, which came about in three main ways:

1.  The industrial revolution, which increased women's mobility and changed breastfeeding habits thereby diminishing their contraceptive effect.
2.  Two world wars that put women into the workplaces which had for centuries been dominated by men, creating in women a greater sense of personal and financial independence, and increasing their opportunities for education and literacy.
3.  Improvements in public health which allowed more babies to survive infancy and childhood.

Popular campaigns against reproductive choice in North American and Europe focus attention on the gender roles placed on women by society. Much of the hostility to abortion comes from those who believe it to be a means by which middle-class professional women violate traditional gender roles. Although Catholic priests and fundamentalist ministers provide the leadership for the 'pro-life' movement, full-time homemakers who do not work outside the home and feel that their procreative labours are devalued by a society which blurs sex roles are the majority of women who provide the campaign's grass-roots support. There is logic in their stance. The traditional Western family structure is based on a spousal agreement over gender roles which require the husband to provide financial support and the wife to care for husband and children and be available for sex. Accessible birth control and abortion undercut the agreement that a woman can only risk bearing children and providing sexual favours if she is guaranteed the protection of a traditional marriage. It also provides greater opportunity for both spouses to seek sexual encounters outside of marriage without the fear of illegitimate pregnancies or births. The opponents of birth control and abortion vehemently argue that birth-control methods incite promiscuity, and that women and men will only remain chaste if they have reason to fear pregnancy.

Currently, Roman Catholic and certain fundamentalist Christian sects do not permit abortion, withdrawal or seminal retention, birth control that is abortifacient (IUD, RU486) or morning after pills, any form of hormonal contraceptive, any barrier method, and sterilization except if pregnancy would seriously be detrimental for the woman's health. They do allow calendar calculation (Rhythm Method), natural family planning methods (NFP), and periodic or complete abstinence. Similarly, fundamentalist Islamic and Jewish sects do not permit the use of birth control or abortion.

An international survey of Western nations from the 1980s revealed that about 90% of married couples used birth control. Average contraceptive use broke down to 30% sterilization, 20% oral contraceptives, 10% IUDs, and 10% barrier methods. Regardless of ever increasing availability and variety of birth control, _withdrawal and the male condom are still the most widely practiced methods of birth control worldwide_.

The most significant change in current trends in contraceptive use among Western nations is the increased use of oral and hormonal birth control (up to 45% in some countries), the decrease in the use of IUDs to 2%, and the newest push for women to make their menstruation obsolete through uninterrupted hormonal contraceptive use.

The majority of women today in Westernized nations have access to abortion, though rural women have more difficulties with access than urban women, and not all healthcare insurances cover the cost of abortion.

Though it is no longer expected in Western Culture that women have large numbers of children, governments of countries with declining birth rates, churches, and popular culture collectively exert pressure on women to 'fulfill' them by having at least one child. In the 1920s, over 20 per cent of white American women were childless at age forty; by the 1980s, the figure was down to 1 per cent. Women still gain social status through childbearing, and often go to great lengths to have at least one child, despite soaring infertility rates among Westernized women. This raises concern about the ways that birth control and new reproductive technologies exploit women's desire to have children by increasingly commodifying their reproductive capacities.

The development of birth control since ancient times has been phenomenal, as has been the significant social, scientific, and religious controversy associated with birth control's development. Religious groups have contributed theological discourse. Medicine and science have established domain and supplied solutions. Furthermore, virtually every group who enters the birth control dialogue - current and past - jostles for position to defend what they deem righteous based on religious, social, moral, or medical grounds. However, considerable questions remain among them - how does the historical dialogue about and development of birth control serve the individual woman today? Who is the woman who still struggles with reproductive issues and has been lost in the controversy of so many authorities trying to control her reproductive body or tell her what is best for her? Is she being heard?

The text, The Woman in the Body, by Emily Martin, is an exploration of how culture influences and shapes the scientific endeavor and in turn, what we believe to be true about female bodies and reproduction. The text has been chosen to introduce the reader to ways of critical analysis in science and medicine. As a western culture, we believe that science describes reality as it is, that it can uncover the truth, and yet, the questions we ask, the tools we use to see and engage with the world and the answers we create are the offspring of our cultural heritage. It is hoped that the student will apply critical thought to the materials they encounter, both the biomedical and scientific models, and to alternative health works.

It is certain that with the progression of patriarchal and monotheistic values, accompanied by the technology of the modern medical and pharmaceutical industry, there has been a tremendous loss of the tradition of women passing down knowledge to other women about menstruation, fertility, sexuality, childbirth, and the use of herbal and magical healing arts. Fertility awareness and holistic reproductive healthcare are the contemporary means for recovering that lost or hidden knowledge. It is one way to hear women on the topic of their relationship to their reproductive bodies.

It is important to consider how in our times the care of women -- women's health -- is not a capitalistic endeavor, that ever increases the necessity to pathologize women's bodies. The following article examines this issue. 

###  Required Readings {.unnumbered}

1.  Gordon, L. (2007). _The moral property of women: A history of birth control in America_. Chicago, IL: University of Illinois Press. **(Part 4).** An earlier version of this text was Gordon, L. (1990). Woman's body, woman's right: Birth control in America (2nd ed.). New York, NY: Grossman/Viking.
    
2.  Martin, E. (1987). T_he woman in the body: A cultural analysis of reproduction._ Boston, MA: Beacon Press.
3.  Thomas, J. E. & Zimmerman, M. K. (2007). Feminism and profit in American hospitals: The corporate construction of Women's Health Centres. Gender and Society, 21, 359 -383. doi:10.1177/0891243207299947. [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Feminism%20and%20Profit%20in%20American%20Hospitals.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Feminism%20and%20Profit%20in%20American%20Hospitals.pdf) 
    

## Journal Activity - A.3.7 Are women better informed? {.unnumbered}

### Are Women Better Informed? {.unnumbered}

Do you believe that contemporary women are, in general, better informed and able to exercise more choice regarding birth control than women in ancient times or even those of several decades ago?  

Draft a brief argument for your position in your journal.

OR

Reflect on who you believe are the most authoritative sources of information regarding menstruation, birth control, reproductive health, etc. Do you tend to receive information from women in your family, peers, or see your doctor only? Reflect on why this is so.

----

## 3.8 - International Discourse on Birth Control {.unnumbered}

### International Discourse on Birth Control {.unnumbered}

by Laura Salamanca (2014)

Governmental regulation of women's bodies first came into international discourse through concerns with uncontrolled fertility as a cause of stalled socio-economic development. The problem of population growth takes ideological inspiration from the writings of Thomas Malthus, a British clergyman turned economist who asserted in the early 1800s that unless constrained by 'preventive checks' human populations grow exponentially—outstripping the earth's capacity for food production, which was thought to follow an arithmetic progression (Corrêa and Reichmann 1994: 1; Hartmann 1995: 14; Marks 2001: 15; Wang 2010: 7). Population control ideology is but one of the social movements and intellectual currents active in the late 19th and early 20th centuries that culminated in organized birth control movements in Europe and the United States, and their exportation to the Third World. Growing feminist movements, class conflicts and drives for unionization, eugenic ideologies, sex radicalism among intelligentsia, and distinctly racialized and gendered social and moral reform created fertile ground for the discursive development of sexuality as a marker of modern technological sophistication.

 The first major public advocates of birth control were English neo-Malthusians who supported the technology as a means of improving the condition of the poor by limiting their numbers, feminists and socialists who believed it was a fundamental woman's right, and eugenicists who embraced it as a way of influencing genetic quality to improve the race (Hartmann 1995: 94). Originally started in Britain and led by the white, Anglo-Saxon, and educated upper middle-class, both neo-Malthusian and eugenics movements feared that differential fertility among the poor and middle classes signified the degeneration of the physical and mental health of the nation (Marks 2001: 17). Eugenicists maintained that the rich and powerful were _genetically_ superior to the poor, and whites in general superior to other 'races' (Hartmann 1995: 98). Eugenicist and hygienist groups advocated for fertility control among the poor and disabled; by the earlier part of the 20th century their reasoning led to calls for compulsory sterilization in the name of racial progress that resulted in coercive policies in a number of countries such as Sweden, Germany, and Norway (Marks 2001: 19-20). Between 1928 and 1972 2844 people, considered 'degenerate' and 'unfit' usually because they were poor or disabled, were forcibly sterilized in Alberta (Egan and Gardner 2007: 297). In the U.S, there were sterilization laws in 27 states by 1932 for the “feeble-minded, insane, criminal, and physically defective” (Corrêa and Reichmann 2994: 11; Hartmann 1995: 98). Efforts of organizations such as the American Birth Control League (founded by Margaret Sanger) were led with the goal of preventing “the American people from being replaced by alien or negro stock, whether it be by immigration or by overly high birth rates among others in this country” (Hartmann 1995: 99).

 Birth control was also supported by the growing feminist movement comprised of suffragists and moral reformers that argued for women's right to self-determination through personal and political emancipation, and was part of class formation processes that set the largely white, Protestant middle-class in stark contrast to the growing proportion of immigrants and working classes (Hartmann 1995: 95; Corrêa and Reichmann 1994: 11). Like many other social reformers, Margaret Sanger employed eugenic language as a means of adding powerful scientific credibility to her calls for greater access to contraception (Marks 2001: 20). World War I and the subsequent economic downturn, as well as later Nazi atrocities that helped to discredit eugenic ideologies, contributed to the decline of a radical birth control movement in the United States. The impoverishment of many white middle-class people during the Depression made it difficult to blame poverty on genetic inferiority—it came to be viewed as 'environmentally' caused and social reform through welfare programs lauded as the solution to improve the position of the individual and stabilize the family (Hartmann 1995: 100 - 101). As fertility became something that many thought should be and was susceptible to planning, there was a new concern about what constituted a healthy family; The Birth Control Federation of America changed its name to the Planned Parenthood Federation in 1942 and family planning became a new more acceptable euphemism for birth control (Marks 2001: 101).

 In the post-World War II period of economic recovery perceptions of demographic issues began to change. Emerging as a world power, the United States had a growing need for access to Third World raw materials in the midst of growing political instability of independence movements in the African continent and economic nationalism in Latin America. Rather than centuries of colonial domination, population growth was believed to fuel nationalist fires (Hartmann 1995: 101 - 102). By the 1950s hunger and food scarcity engendered a resurgence of Neo-Malthusianism, as works such as Paul Ehrlich's _The Population Bomb_ disseminated the belief that overpopulation is the main cause of our environmental crisis (Hartmann 1995: 21; Wang 2010: 8). Alarmist calls by organizations such as the Rockefeller Foundation, Planned Parenthood, demographers, conservationists and 'development experts' agreed that “the relationship of population to material and cultural resources of the world represents one of the most crucial and urgent problems of the day” (Population Council), and conceptualized population growth as a major threat to political stability both at home and abroad (Hartmann 1995: 102-103). The rhetoric and urgency instilled in efforts to control the growth of population allowed Euro-American discourse on global development in the most powerful institutions, such as the World Bank and the United Nations, to obscure the recent effects of colonialism and capitalist accumulation as the real causes of poverty through the breakdown of political institutions, unequal distribution of wealth, and land monopolization for unsustainable consumption patterns and wasteful agricultural technologies.

 Neo-Malthusianism blamed poverty and instability in the Third World on high birth rates and resulted in policies that focused on family planning and achieving “'contraceptive acceptance'” targets (Hartmann 1995: 38), to the exclusion of proper counselling, follow up, and provision of primary healthcare. Family planning was divorced from concerns with women's health and wellbeing (in delaying and spacing pregnancies) that inspired the first feminist campaigns for birth control (Ibid: 37 - 38). Distrust of women's abilities to use contraceptives effectively meant that the promotion and distribution of safer methods such as condoms and diaphragms took a back seat to the uptake, sometimes coerced, of methods with substantial health risks such as the pill, the IUD, Depo-Provera™ and Norplant™ (Ibid: 38). As if people had never sought to control fertility, new technologies were conceptualized as technocratic solutions to the 'problem of population', and their uptake as measures of a country's modernization of social policy. Discussions about birth control became not about the wish to plan one's births, but about the obligation to do so as a modern _self_\-controlling subject (Ruhl 2002: 643 - 644). 

### Setting World Standards: Political Limits to Consensus {.unnumbered}
by Laura Salamanca (2014)

At the World Population Conference in Bucharest in 1974 the U.S Neo-Malthusian perspective on population growth as the main obstacle to economic development was critiqued for being simplistic, ahistorical and ignoring the political causes of conflict, poverty, and environmental degradation (Wang 2010: 9). “Development is the best contraceptive” was registered as the Southern position (Corrêa and Reichmann 1994: 1). Despite U.S. opposition, the World Population Plan of Action that emerged from that Conference placed population growth within a broader context in which socioeconomic development itself could result in lower birth rates (Hartmann 1995: 109 - 110). However in the end, international rhetoric of “integrated development” (fighting poverty and population simultaneously) emerging from that meeting steered away from politically charged questions of power, gender inequalities and lack of mass education and healthcare, in the pernicious belief that governments and international donors could deliver goods such as family planning to the poor without fundamentally altering the social order (Ibid: 110 - 111). Critiques in Bucharest had little impact on the U.S government's commitment to population control, and today it is the largest single donor of population assistance through its Agency for International Development (USAID) (Ibid: 113 - 114). United States influence is pervasive, as the threat of withholding funds when recipient organizations or governments do not abide by certain expectations has a direct impact on the content of reproductive health programmes (Reichenbach 2009: 32). For example, the Global Gag Rule dictates that no U.S. family planning assistance may be provided to NGOs that perform abortions, provide counselling, referrals, or lobby to make the procedure available or legal in their country (Ibid: 235). 

 In the late 1970s and 80s demographic evidence that the enhancement of women's status is an important key to fertility decline became popular in the global population control apparatus, leading to the integration of income generation activities and credit schemes with family planning programs (Hartmann 1995: 133). As growing numbers of women were entering the professions and joining the global assembly lines of multinational corporations, they became strategically important to the international economy (Ibid). The interest of development institutions in their labour came against the backdrop of the growing women's health movement of the time. Activists questioned the rationale of government-sponsored population policies and criticized the failure of international organizations to address women's health and status in the family and society through their reproductive health programmes (Wang 2010: 13). Women began to employ the rhetoric of human rights cemented following World War II to claim that every woman has the right to control her body, sexuality, and reproductive life (Ibid: 11, 13). In recognition that taking women seriously as equal rights claimants with men required considerable rethinking of the concept of 'human' rights, feminists set out to build an internationally recognized legal framework for the defence of women's personhood and bodily integrity (Okin 2000: 28; Corrêa and Reichmann 1995: 56). The promotion of women's rights as the basis of gender equality and women's reproductive health and well-being in general was kick-started with the 1979 Convention on the Elimination of all Forms of Discrimination against Women (CEDAW) (Wang 2010: 12; Miller and Roseman 2011: 108; Corrêa and Reichmann 1995: 58).

 Population control schemes underwent a paradigm shift by the 1990s with a number of international conferences in which women's reproductive rights and health issues became the focal agenda and a new strategy emerged to link population reduction goals to the improvement of infant, child, and maternal mortality (Wang 2010: 1, 13). The 1994 United Nations International Conference on Population and Development (ICPD) in Cairo adopted a Programme of Action, affirmed by the 1995 Fourth World Conference on Women in Beijing, that confirmed the centrality of gender equality, reproductive rights, and sustainable development in advancing women's health worldwide (Ibid: 2). The ICPD in Cairo has earned a place in history as one of the most significant global conferences ever because it enabled a shift in the eyes of policymakers on how population programs should be formulated and implemented—a move away from top-down approaches and demographic goals toward program design that would seek to respond to the needs of 'couples and individuals' (Singh 2009: 1; Austveg 2011: 26). The Cairo document was the first to assert that women's reproductive health is important in its own right, and that it is embedded in social, economic, and political environments (Wang 2010: 13 - 14). In shaping the Programme of Action gender equality was a guiding principle, paying particular attention to the reduction of maternal mortality, education of girls, elimination of discriminatory laws and practices against women, and the creation of better economic and social opportunities (Singh 2009: 101).

###  References {.unnumbered}

1.  Austveg, Berit. 2011 “Perpetuating power: some reasons why reproductive health has stalled” in _Reproductive Health Matters._ 19(38): 6 - 34. 
2.  Corrêa, Sonia in collaboration with Reichmann, Rebecca. 1994. _Population and Reproductive Rights: Feminist Perspectives from the South._ London: Zed Books. 
3.  Egan, Carolyn, and Gardner, Linda. 2007.  “Racism, Women's Health and Reproductive Freedom” in _Gender Relations in Global Perspective._ Cook, Nancy, Ed. Toronto: Canadian Scholars' Press Inc. 
4.  Hartmann, Betsy. 1995. R_eproductive Rights and Wrongs: The Global Politics of Population Control and Contraceptive Choice._ Boston: South End Press. 
5.  Marks, Lara V. 2001. _Sexual Chemistry: a history of the contraceptive pill._ New Haven: Yale University Press.  
6.  Miller, Alice and Roseman, Mindy. 2011. “Sexual and reproductive rights at the United Nations: Frustration or Fulfillment” in _Reproductive Health Matters_. 19(38):102 - 118. 
7.  Okin, Susan Moller. 2000. “Feminism, Women's Rights, and Cultural Differences” in _Decentering the Center: Philosophy for a Multicultural, Postcolonial, and Feminist World._ Narayan, Uma, and Harding, Sandra, Eds. Bloomington, IN: Indiana University Press. 
8.  Reichenbach, Laura. 2009. “The Global Reproductive Health and Rights Agenda: Opportunities and Challenges for the Future” in _Reproductive Health and Human Rights: The Way Forward._ Richenbach, Laura and Roseman, Mindy Jane, Eds. Philadelphia: University of Pennsylvania Press. Pp. 21 - 39. 
9.  Ruhl, Lealle. 2002. “Dilemmas of the Will: Uncertainty, Reproduction, and the Rhetoric of Control” in _Signs_. 27(3): 641 - 663. 
10.  Singh, Jyoti Shankar. 2009. _Creating a New Consensus on Population: The Politics of Reproductive Health, Reproductive Rights and Women's Empowerment._ 2nd Ed. London: Earthscan. 
11.  Wang, Guang-zhen. 2010.  _Reproductive Health and Gender Equality: Method, Measurement, and Implications._ Farnham, England: Ashgate Publishing Limited. 

----

## 3.9 - Contraception & Abortion Timeline {.unnumbered}

This timeline focuses on the history of contraception and abortion primarily in Canada, Britain, & USA throughout the last two centuries. If you are living and working in a different region please correlate this information with the history of your area, and please feel free to share it with us.

Historical information that is particular to the development of fertility awareness and natural birth control appears as raspberry red font

### Before 1800 {.unnumbered}

-   Hippocrates (460 - 377 BCE) teaches the **“two seed” theory of conception**, asserting that a man and a woman each carry half of the germ-seeds necessary for conception. He proposes that the best time for conception to occur is at the beginning of menses or at its end.
    
-   Aristotle (384 - 322 BCE) teaches that conception is most like to occur when a woman's lips are rough and adherent on digital exam.
    
-   Pliny the Elder (22 - 79 ACE) and Galen (129 - 200 ACE) both teaches that conception is most likely to when menstruation is beginning or ceasing.
    
-   1157 Henry II of France declares it law that any concealed pregnancy that ended in the death of the child was to be presumed a murder.
    
-   1224  England passes a similar law in to the 1157 French law.

-   1542  Human ovaries were first observed by **Andreas Vesaliu**s, and later by **Gabriele Fallapio** (1561).

-   1573 **Volvherus Coiter** discovered an object on the ovary that in 1686 **Marcello Malpighi** would label as the **corpus luteum,** which **Alberta von Haller** would describe in 1765 as the product of the transformed ovarian follicle. 
    
-   1672  **Reignier de Graaf**, a Dutch physician, described the ovarian follicle of rabbits as “small vesicles full of fluid,” and misunderstood the mature follicle to be the ovum.
    
-   1672 **Marcello Malpighi** of Clevacore, considered to the 'father' of histology, noted millet seed sized object in the mature follicle, which is the first recorded visualization of the cumulus oopherous (a small accumulation of cells that surround the ovum). In 1686 Malpighi labed the corpus luteum
    
-   1679  Dutch microscopist **Anton Van Leeuwenhoek** publishes hand drawings of canine spermatozoa, viewing them as parasites or structures that stirred the semen and the male dog's sexual desire. The role of spermatozoa does no become known until the mid-1800s.
    
-   Prior to the 1800s - Protestant and Catholic **churches allow abortion until 'quickening'**—the moment the fetus was believed to gain life and become 'ensouled' - 40 days after conception of a boy and 80 days after conception of a girl.
    

### 1800 - 1900 {.unnumbered}

> This century sees Canada, the United States, Britain, and most other countries declare abortion (at any stage of foetal development) and birth control illegal, enacting laws that prohibit contraceptive use or sale, and the dissemination of information about contraceptives.
> 
> _The practices of periodic abstinence or total abstinence are acceptable forms of birth control. Calendar calculation (rhythm) methods combined with periodic abstinence are widely used._
> 
> _The common belief, based on observations of other mammals, is that women ovulate either during menstruation or just before it._
> 
> Abortionists perform abortions despite frequent arrests. Most of those arrested are acquitted by juries.

-   1827  Karl Ernest von Baer (1792-1879) finds an ovum in a canine ovarian follicle, and identifies it as a “female sex cell”.
    
-   1838  Von Fricke studies the body temperature of women in relation to menstruation. He takes their axillial (armpit), vaginal,and uterine temperatures days 8 and 4 before menses, and during menses. He concludes that the vagina has a higher temperature than either the axilla oruterus, and falsely concludes that menstruation and pregnancy have no influence on body temperature.
    
-   1845   Bischoff after his observations of the canine reproductive cycle, is the first to describe the folding of the follicle wall of the canine ovary before rupture, and the development of luteal tissue before ovulation. He extrapolates his results to women, concluding that women are fertile during or shortly before menses. (It takes nearly a century to prove his conclusions false.)
    
-   1847 Felix Archimede Pouchet observes that mucus discharge, for most women,  occurs from from the 10th to the 15th day of the menstrual cycle. He also notes the presence of intermenstrual pain or sensation of heaviness (mittelschmerz) on days, 6, 7, and 8 of the cycle. ( A Revolution in Christian Morals": Lambeth 1930-Resolution #15. History & Reception p. 135)
    
-   1859   The American Medical Association condemns the practice of abortion.
    

###  1860s - 1870s {.unnumbered}

> This decade marks the beginning of a **vigorous socio-political movement to make birth control available and acceptable** in North America and Europe. Abortions continue to be available through wise-women and physicians. The AMA intensifies its censure of abortion.
> 
> American physician **Dr. Edmund Bliss Foote** writes widely on birth control and sex, emphasizing women's rights. He publicly advocates the use of the condom and the 'womb veil', an early type of diaphragm.
> 
> Men begin to regard the condom as a means to develop personal power over procreation.
> 
> There are about 200 full time illegal abortionists working in New York.
> 
> **Required Reading:** Pro-choice Action Network. (2009). Legal History of Abortion in Canada  [http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml](http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml)

-   1868   Drs. William Squire and Mary Putnam Jacobi observe women's basal body temperatures (BBT) puerperal (postpartum) and in relation to events of the menstrual cycle. He concludes that the BBT is relatively high and stable during pregnancy, that it drops considerably at the onset of menstruation, and that it rises variably shortly before menses.
    
-   1868 to 1888 Dr. Marion Sims researched post-coital cervical mucus and discovers that cervical mucus can facilitate or block sperm migration. (Carrol, D.T. and Peterson, C.M, Reproductive Endocrinology and Infertility. 2010. p. 138)
    
-   1869    Canada passes legislation making abortion a criminal offence unless it is “necessary to save the life of a woman.” 
    
-   1869    Pope Pius IX abolishes the concept of delayed fetal ensoulment. He asserts that the soul enters the fetus the moment of conception, and declares abortion as murder at stage of fetal development and under any circumstance.
    
-   1870   **M. Rambuteau** observes in his study of one 28-year-old woman of normal health and with a regular menstrual cycle history that a decline in basal body temperature (BBT) occurred two days before menstruation and rose again to normal levels several days after menstruation.
    
-   1873   Anthony Comstock pushes a bill through American Congress (Comstock Laws) establishing a federal ban in 22 American states on the production, proliferation, sale, possession, or advertisement of “obscene” articles, which includes contraceptives. He becomes a special federal agent charged to enforce this ban. 
    
-   1875    Every American state now has laws prohibiting abortion.
    
-   1876    **Mary Putnam-Jacobi** studies the oral, axillary, vaginal and rectal BBT of six women over 2 or 3 cycles, and concludes that the BBT rises before menstruation and falls during menses to a level lower than that of the 'intermenstrual period'.
    
-   1879    The American states, Connecticut and Massachusetts pass the strictest ever laws against abortion and contraception.
    
-   1892   A law prohibiting the sale, advertisement, publishing of advertisements, or manufacture of any “medicine, drug, or article” that is meant to prevent conception is enacted into the Canadian Criminal Code.
    
-   1892   Abortion is made illegal in Canada. 
    

### Late 1800s - early 1900s ("turn of the century") {.unnumbered}

> Public debate over the need to balance food supply with population growth leads to advocacy for birth control implementation and women's well being with respect to birth control. This debate takes place in many philosophical and political arenas throughout the 'developed' nations, and includes the voices of prominent eugenicists who propose the creation of a perfect population by prohibiting or discouraging reproduction among those deemed 'unfit.' To that end, the eugenicists advocate birth control use and education. At this time, most feminists and female leaders of the birth control movement are eugenicists or are supported by eugenicists.

### 1900-1945 {.unnumbered}

> Feminist women (such as Canadians Mary Hawkins and Elizabeth Bagshaw; Britain's Mary Stopes, and Americans Margaret Sanger and Kathryn McCormick), along with other medical and philosophical birth control activists, initiate vigorous campaigns around the world for legalizing mass dissemination of contraceptives and contraceptive information. They speak out, get organized, use acts of civil disobedience by setting up clinics distributing illegal birth control information and devices, and get arrested, jailed, and acquitted. Two new branches of medical-science develop, endocrinology and biochemisty.  These fields develop their knowledge of the female reproductive and endocrine systems and direct their research towards “modern” methods of contraception. (In Germany, Helene Stocker and Marie Stritt, and in France Madeleine Pelletier campaign for the legalization of contraception and abortion.)

-   1901 **Gustav Born** proposed that the **corpus luteum** as a temporay gland of internal secretion prepared the uterus for implantation
    
-   1904   **Van de Velde** studies the axillary BBT of a group of women and observes a consistent pattern - a premenstrual high temperature phase, a temperature drop at menstruation's onset which continues through menstruation, reaching its lowest level about ten days after menstruation ceases. He purports that the BBT drop causes menstruation, and that there is a relationship between ovulation and BBT fluctuations. He correlates BBT Shift to ovulation.
    
-   1905   American President Theodore Roosevelt condemns birth control and the tendency towards smaller families as decadence and a sign of moral disease. He encourages women to give birth often to fill factories, industries, and new farming territories with American workers.
    
-   1909 **Pol Andrea Bouin** and **Paul Ancel,** pioneers in reproductive physiology before sex hormones were isolated, propose that the corpus luteum prepares the uterus for nidation (implantation) and the breasts for morphogenic changes associated with pregnancy from the 12th to 14th day prior to the onset of menstruation
    
-   1909 **Richter Ring:** In 1909 the Polish physician Richard Richter created a flexible ring with silk suture thread that was inserted into the uterus, which was claimed as an efficacious contraceptive. It took about 50 years for health care providers to accept this new style of IUD because of fear of fear of infections that were common with the 19th-century stem pessaries. German physician, Ernst Gräfenberg modified the Richter Ring c 1920-30 by coiling silver wire around the silk suture material.  
    
-   1914   **Margaret Sanger** publishes and distributes a magazine, “Women Rebel,” advocating birth control techniques she has learned of in France.
    
-   1916   **Margaret Sanger** sets up the American Birth Control League (now Planned Parenthood) in the Brownsville area of New York City. The league promotes contraception and abortion, and lobbies religious leaders to accept contraception as morally acceptable.
    

### 1920s and 1930s {.unnumbered}

> Canadian women's groups from British Columbia begin lobbying for the legalization of birth control. Later, other groups -United Farmer's of Canada, the Seventh Labour Women's Society and Economic Conference, National Council of Jewish Women) - join the campaign. 

**Required Reading:** Merhi D. (2002) [For their own good: Ontario's legal legacy of the “moral” woman](http://www.dominionpaper.ca/articles/4526). Dominion: News from the grassroots 84. This article addresses forcible sterilization and imprisonment of women for 'incorrigibility' in Canada: [http://www.dominionpaper.ca/articles/4526](http://www.dominionpaper.ca/articles/4526). Additionally, though not required, you might find the Canadian play [Jenny's Story](http://www.bettylambert.ca/works-jennie.htm) by Betty Lambert an interesting interpretation of one women's story who was forcibly sterilized. 

-   1920  Lambeth Conference (an international meeting of Anglican Church Bishops) - Anglican Church leaders endorse the use of periodic abstinence and current understandings of fertility awareness to avoid pregnancy, but warn against the use of artificial birth control.
    
-   1920 German physician, **Ernst Gräfenberg** modifies the Richter Ring IUD by coiling silver wire around the silk suture material. 
    
-   1921   **Dr. Marie Stopes** sets up Britain's first family planning clinic in Holloway, North London. (see more about Marie Stopes' birth control clinics worldwide [**http://www.mariestopes.org.uk/**](http://www.mariestopes.org.uk/) ) 
    
-   1923  **Margaret Sanger** speaks in Canada about her work with the American Birth Control League, inspiring several Canadian women's groups to set up the Canadian Birth Control League.
    
-   1928  **Van de Velde** discovers that the elevated BBT, which occurs in the second half of a woman's menstrual cycle, is related to the secretion of progesterone by the corpus luteum.
    
-   1929/1930 **Hermann Knaus** of Austria (1929) and **Kyusaku Ogino** of Japan (1930) discover that ovulation occurs about 12 to 16 days before the next menstruation. 
    
-   1929  Roman Catholic Pope Pius XI from the Vatican declares a total prohibition of artificial contraception, published in his papal encyclical, _Casi Connubii._ He allows for the practice of periodic abstinence or total abstinence. 
    
-   1930    Lambeth Conference - Anglican Church of England leaders endorse all birth control as morally acceptable, particularly the use of artificial contraception when abstinence is impracticable. Before this endorsement, all Christian denominations were united in their rejection of contraceptives.  
    
-   1930    **Marie Stopes** is instrumental in Britain setting up the “National Birth Control Council” (now the Family Planning Association).The council's mandate is to set up and promote birth control clinics for married women, particularly those with health problems. As a continuation of the eugenics movement, poor or unhealthy women are discouraged from “breeding.”
    
-   1930    Lambeth Conference - Anglican Church leaders endorse all contraception as morally acceptable -- a major victory for the birth control movement.
    
-   1931    The Federal Council of Churches (Protestant) adopts a policy of conservative advocacy for artificial contraception.
    
-   1931 A.H. Tyler, Protestant minister and author of many sex education and birth control publications during the 1930s and 1940s, founds the **Canadian Voluntary Parenthood League.**
    
-   1932   **Mary Hawkin**s, with **Dr. Elizabeth Bagshaw** as medical director, establishes the first Canadian birth control clinic in Hamilton, Ontario. 
    
-   1932    **Hermann Knaus** and **Kyusaku Ogino** individually develop methods of birth control based on their 1929/30 discoveries. They propose a set of calculations (precursors of the calendar rhythm method) for determining the time of ovulation, which they then (accounting for the length of sperm survival) use to identify “safe” and “unsafe” days to have sexual intercourse and avoid pregnancy. Ogino worked with Jay Nicolas and Joseph Smulders to develop the "Ogino-Smulders Method". Knaus developed the "Knaus Method". **Leo J. Latz** developed the "Rhythm Method"
    
-   1935    **Wilhelm Hillebrand** creates a practical application for Van de Velde's BBT discoveries to birth control, and develops the first BBT method and calendar-thermic methods. Others further develop the **BBT method of birth control** - Vollman  (1940), Ferin (1947), and Doring (1949).
    
-   1935    The Hamilton Hospital supports Hawkins' and Bagshaw's clinic.
    
-   1936/37   **Dorothea Palmer** is charged with illegally distributing contraceptive information (1936), and is acquitted (1937) of the charge. The court recognizes that provision of contraceptive information is permissible if done in the interest of the “public good,” tha tis, to the poor or unhealthy.  However,the sale and distribution of information remains illegal until 1969. 
    
-   1937    Birth control clinics are operating in Kitchener and Windsor, Ontario, modeled after Hawkins' and Bagshaw's clinic in Hamiltion. 
    

### 1940s and 50s {.unnumbered}

-   1949, German physician, **Herbert Hal**l, developed a stainless steel ring (Hall-Stone Ring) as and IUD
    
-   1951   Austrian physician **Dr. Joseph Roetzer** begins a study correlating BBT curves with other symptoms related to ovulation (cervical mucus, mittleschmertz, spotting). His work becomes the foundation for the first sympto-thermic (thermal) method of fertility awareness (FA). 
    
-   1952 **M.R. Cohen** Develops a schematic presentation of the properties of cervical mucus and the "biological valve" (endocervical canal) (Cohen MR, Stein IF and Kaye BM: Spinnbarkeit: A Characteristic of Cervical Mucus. Fertil Steril 3: 201, 1952)
    
-   1953    **Dr. John Billings**, Australian neurologist and expert on estrogen biochemistry, becomes involved in teaching and researching natural birth control, focusing on the failures of calendar rhythm and BBT methods. His research reveals that women experience a distinct and identifiable cervical mucus discharge that appears at the vulva close to the time of ovulation,and that 75% of women can reliably detect of this mucus. 
    
-   1955    **Rita and Gilles Bereault** found **SERENA Canada** (SErvice de REgulation des NAissances / Service for the Regulation of Birth).The service consists of Catholic couples teaching married or engaged couples the sympto-thermal method of fertility awareness (FA). They restrict service to those who plan to abide by Catholic Church doctrine regarding birth control and sexual conduct. By 1978 SERENA has teachers in most Canadian provinces, and begins collaboration with the World Health Organization (WHO) regarding its training program.  Publications include: “La Regulation de Naissances” by Dr. Jacques Baillargeon and HélènePelletier-Baillargeon (1963), “Love and Life,” and “Faire l'amour, faire un enfant”(1974), “Planning Your Family the S-T Way” (1975).  
    
-   1957    In America, Enovid, the first oral contraceptive pill (an estradiene compound of synthetic estrogen and progesterone) is submitted for regulatory approval to the US Food and Drug Administration (FDA) as a treatment for menstrual disorders and infertility, not as a contraceptive, though it had been developed as a contraceptive by medical organic chemist Frank B. Colton.
    
-   1959    At the Rockefeller Institute for Medical Research in New York City,the anatomist, obstetrician, and gynecologist Willard Allen, and obstetrician and gynecologist Dr. George Corner discover the hormone progesterone. 
    
-   1959    The FDA approves Depo-provera, Upjohn's synthesized progesterone derivative, medroxy-progesterone acetate (MPA), for the prevention of spontaneous abortion and premature delivery. 
    
-   1959    Brazilian, obstetrician, gynecologist, and medical researcher **Dr. Elsimar Coutinho** begins clinical trials in Brazil using Depo-provera, as approved by the FDA, and then later as an injectable contraceptive. Women subjects experience a suppression of menstruation, and a contraceptive effect, for up to 6 months.
    
-   1959 **Erik Odeblad** Begins his studies on the biophysical properties of cervical mucus.
    

### 1960s {.unnumbered}

> In Canada, Britain, the United States, and other countries where oral contraceptives are available, physicians unofficially begin using an “off label” prescription for the “Yuzpe Regimen” as a “morning after pill” or  “emergency contraceptive” for victims of rape. (See Unit D for more information on the emergency contraceptive pill.)

-   1960   In America, the FDA approves Enovid, as the first oral contraceptive. It is made available to married women by prescription from their doctor.
    
-   1960   American physician, Dr. C. Lee Buxton and Estelle Griswald open a birth control clinic in New Haven, Connecticut. They are arrested and fined.
    
-   1960 The Lippes Loop plastic 'inert' IUD is developed.
    
-   1961    The National Council of (Protestant) Churches unanimously declares a liberal policy on artificial birth control use, subject to mutual consent between couples. 
    
-   1962    American physician **Dr. Edward F. Keefe** publishes the first report on cervical changes in relation to ovulation. By the early 1970s SERENA is the first group to integrate his findings into fertility awareness education. 
    
-   1963    Neurologist **Dr. John Marshall** publishes his book, “The Infertile Period: Principles and Practice.” In1968 he publishes hisresults of the first prospective field trial of the BBT method.  
    
-   1964    **Dr. Lyn Billings**, an Australian pediatrician begins a study to prove that all women observing cervical mucus can determine their times of fertility if they are taught to do so by a woman. Her work with women teaching women is the single greatest advance in the practical application of natural birth control. Her method becomes known as the Ovulation Method (OM). Lynn's husband, Dr. John Billings and Dr. Jim Brown cooperate with her in establishing a scientific basis for the OM.
    
-   1965    Planned Parenthood League appeals the _Griswald vs. Connecticut_ case and the United States Supreme Court strikes down the1879 birth control law as unconstitutional - commonly called the "right to privacy" act. (After 86 years, birth control is legal in Connecticut, and contraceptive services become increasingly available to married couples and minors.) 
    
-   1967    The British National Health Service legislates the setup of birth control facilities and services to both unmarried and married couples. 
    
-   1967   Colorado becomes the first American state to allow abortion in the cases of rape, incest or threat to the mother's life. 
    
-   1967    **Pierre Elliot Trudeau** (as Canadian Minister of Justice) introduces the “Omnibus bill” that makes changes to the Canadian Criminal Code, some of which concern contraception and abortion. He makes what became a famous statement, “The state has no business in the bedrooms of the nation.” [https://en.wikipedia.org/wiki/Criminal\_Law\_Amendment\_Act,\_1968-69](https://en.wikipedia.org/wiki/Criminal_Law_Amendment_Act,_1968-69) See Bill-C150
    
-   1968    **Dr. Henry Morgentaler** opens his first abortion clinic in Montreal, Quebec, in a campaign of civil disobedience with respect to abortion laws. 
    
-   1968 The Dalkon Shield IUD is put on the North American market, and was taken off the market in 1974 due to its associated with increased incidence of pelvic inflammatory disease and death.
    
-   1969 Copper style IUDs reach the market.
    
-   1969    The Omnibus Bill passes into legislation,making contraception legal for all Canadian women, and abortion legal undercertain restrictive conditions. 
    
-   1970 Levonorgestrel based IUDs are developed 
    
-   1970    Fourteen American states allow abortion under certain restrictive circumstances. 
    

### 1970s and 1980s {.unnumbered}

> Use of the intrauterine device (IUD) becomes popular after publication of several studies questioning the safety of oral contraceptives. With greater IUD use comes an increase in the number of women experiencing life threatening and other harmful side effects. IUD safety, particularly the Dalkon Shield, is brought into serious medical and legal debate. 

-   1970    **Ms. Mercedes Arzu Wilson** designs the stamp chart used for the OM. 
    
-   1972    Drs. Lynn and John Billings introduce the Ovulation Method to North America.
    
-   1972 Eisenstadt v. Baird - The US Supreme Court decision extends the same invented right of privacy from Griswald to unmarried individuals desiring to use contraception. 
    
-   1973 The US Supreme Court decision Roe v. Wade legalizes abortion on demand using the "right to privacy" from Griswald, striking down all state laws that had place restrictions on abortion, and prohibiting states the authority to legislate against abortion for any reason. 
    
-   1973 The US Supreme Court decisions Doe v. Bolton defines the “health-of-the-mother” exception in ambiguous terms and further secures the right to abortion on demand through all nine months of pregnancy.
    
-   1973    The first of many computerized fertility awareness (FA) devices hit the market - Bioself designed by Edmund Desjaques. It uses electronically recorded basal body temperature (BBT) and calendar rhythm calculations to predict probable times of fertility.  A similar device, Rabbit (American patent) appears in 1984 and many variations follow. 
    
-   1974    **Shelia and John Kippley** found the **Couple-to-Couple League** in the United States - “The Art of Natural Family Planning” (1979). 
    
-   1974    British National Health Service makes all birth control distribution and information services free. 
    
-   1974    Canadian professor **Dr. Albert Yuzpe** publishes the first studies on emergency contraception, outlining his “Yuzpe Regimen.”
    
-   1974    The Canadian Abortion Rights Action League (CARAL) establishes itself as Canada's first national group promoting abortion rights.
    
-   1980    **Dr. Tom W. Hilgers** an American obstetrician and gynecologist, with the help of his co-workers launches the Creighton Model of NFP, a variation of the OM, which is designed to improve effectiveness through the application of a standardized approach to teaching women the vulvar mucus sign (1977), as well as for training Creighton Model NFP Educators. He deviates from Lynn Billings' original model, by training men, including priests, to be educators. 
    
-   1980    **Moghissi** publishes a review on the prediction and detection of ovulation, concluding that a period of 6 to 8 hours of uninterrupted rest is necessary for an accurate BBT. 
    
-   1980s  Bio-medical research begins around the world,to establish a biochemical test that detects ovulation easily and reliably. The results include home test kits for determining the luteinizing hormone (LH) surge, pH fluctuations in vaginal secretions and saliva, post-ovulatory progesterone levels, and enzymatic changes in urine in response to hormonal changes.
    
-   1983 **Billings** and **Odeblad** join in their research efforts.
    
-   1988    **Geraldine Matus**, Canadian lay homebirth midwife, develops the Justisse Method for Fertility Management based on the Creighton method. Justisse is the first systematized secular method of fertility awareness and differentiates itself from NFP methods by abiding by feminist tenets regarding reproductive freedom and informed choice, and by approaching reproductive health from a naturopathic, preventative, and complementary medicine approach. It is unique in its application of fertility awareness (FA), using all natural birth control methods (mucus, BBT, cervical changes, and other fertility signs) alone or in combination with barrier methods according to women's individual need, as well as its services in the areas of reproductive body awareness and holistic reproductive healthcare. Justisse carries on Lynn Billings' tradition of women teaching women as the most successful way for women to learn fertility awareness. 
    
-   1988    The Supreme Court of Canada makes its “Morgentaler Decision”, striking down Canada's abortion laws as unconstitutional.  This leaves Canada without abortion legislation, thus effectively making abortion legal. 
    
-   1988 France approves the use of RU 486 (Mifepristone or Mifeprex), commonly called the 'French Abortion Pill'or 'abortion pill,' eight years after its development by Etienne-Emile Baulieuof the French company Roussel-Uclaff. (see Unit D)
    
-   1995    Roman Catholic Pope John Paul II reaffirms the Vatican's position against abortion, artificial contraception, and certain sexual practices in his papal encyclical Evangelium Vitae (Gospel of Life). 
    
-   1997    The American FDA approves the use of “offlabel” prescriptions of oral contraceptives as emergency contraceptives. 
    
-   1998    The American FDA approves the first dedicated emergency contraceptive product, Preveno, which consists of a Yuzpe regimen kit. 
    

### Birth Control & Abortion Timeline Since 2000 {.unnumbered}
    

edited by Amy Sedgwick (2019), which was adapted and expanded from Wikipedia's [timeline of reproductive rights legislation](https://en.wikipedia.org/wiki/Timeline_of_reproductive_rights_legislation)

-   2000 The American FDA approves the use of RU 486.
    

-   2001 - The ten-week limit on abortion in France was extended to the twelfth week in 2001.
    
-   2001 - Minor girls no longer need mandatory parental consent for abortion in France. A pregnant girl in France under the age of 18 may ask for an abortion without consulting her parents first if she is accompanied to the clinic by an adult of her choice, who must not tell her parents or any third party about the abortion.
    
-   2003    Institute for Reproductive Health at New York's Georgetown University researches and develops the **Standard Days Method** - a revision of the calendar rhythm method using **“Cycle Beads”** for tracking infertile and fertile days. JHPIEGO Corporation (John Hopkins University, a Roman Catholic University, uses the method in education and training programs in developing countries  ([http://www.reproline.jhu.edu/video/sdm/tutorials/English/script\_sdm.htm](http://www.reproline.jhu.edu/video/sdm/tutorials/English/script_sdm.htm))
    
-   2003    Russia restricts abortion access and re-examines its abortion policy, which was instituted at the height of its communist era and the most permissive policy of all nations. It makes this move in an attempt to align Russian abortion policy with that of other Western nations, primarily America's. See “Russia restricts abortion access” Edmonton _Journal,_ Tuesday August 26, 2003, reprint of New York Times article by Steven Lee Meyers (Moscow). 
    
-   2003 - The U.S. enacted the [Partial-Birth Abortion Ban Act](https://en.wikipedia.org/wiki/Partial-Birth_Abortion_Ban_Act) and [President](https://en.wikipedia.org/wiki/President_of_the_United_States) [George W. Bush](https://en.wikipedia.org/wiki/George_W._Bush) signed it into law. After the law was challenged in three appeals courts, the U.S. Supreme Court held that it was constitutional because, unlike the earlier Nebraska state law, it was not vague or overly broad. The court also held that banning the procedure did not constitute an "undue burden," even without a health exception. (see also: [Gonzales v. Carhart](https://en.wikipedia.org/wiki/Gonzales_v._Carhart))
    
-   2006 - Governor [Kathleen Blanco](https://en.wikipedia.org/wiki/Kathleen_Blanco)of Louisiana signed into law a ban on most forms of abortion (unless the life of the mother was in danger or her health would be permanently damaged) once it passed the state legislature. The bill would only go into effect if the United States Supreme Court reversed [Roe v. Wade](https://en.wikipedia.org/wiki/Roe_v._Wade). Louisiana's measure would allow the prosecution of any person who performed or aided in an abortion. The penalties include up to 10 years in prison and a maximum fine of $100,000.
    
-   2007 - The Parliament of Portugal voted to legalize abortion during the first ten weeks of pregnancy. This followed a referendum that, while revealing that a majority of Portuguese voters favored legalization of early-stage abortions, failed due to low voter turnout. The second referendum passed, however, and President Cavaco Silva signed the measure into effect in April, 2007.
    
-   2007 - The government of Mexico City legalizes abortion during the first 12 weeks of pregnancy, and offers free abortions. On August 28, 2008, the [Mexican Supreme Court](https://en.wikipedia.org/wiki/Supreme_Court_of_Justice_of_the_Nation) upholds the law.
    
-   2007 - The U.S. Supreme Court upholds the Partial Birth Abortion Ban Act of 2003.
    
-   2008 - The Australian state of [Victoria](https://en.wikipedia.org/wiki/Victoria_(Australia)) passes a bill which decriminalizes abortion, making it legally accessible to women in the first 24 weeks of the pregnancy.
    
-   2009 - In Spain a bill decriminalizes abortion, making it legally accessible to women in the first 14 weeks of the pregnancy.
    
-   2010 - In Chile, came into force the Morning After Pill Law, which set the rules on information, advice and services relating to fertility regulation, allowing the free distribution of the pill in all country public clinics.
    

-   2012 - Uruguay legalizes abortion in the first trimester, making it legally accessible to women.
    
-   2013 - United States, Kansas lawmakers approved sweeping anti-abortion legislation ([HB 2253](http://www.kslegislature.org/li/b2013_14/measures/hb2253/)) on April 6, 2013 that says life begins at fertilization, forbids abortion based on gender and bans Planned Parenthood from providing sex education in schools.
    
-   2014 - The [Protection of Life During Pregnancy Act 2013](https://en.wikipedia.org/wiki/Protection_of_Life_During_Pregnancy_Act_2013)([Irish](https://en.wikipedia.org/wiki/Irish_language)): An tAcht um Chosaint na Beatha le linn Toirchis 2013) was signed into law on 30 July by [Michael D. Higgins](https://en.wikipedia.org/wiki/Michael_D._Higgins), the President of Ireland; it commenced on 1 January 2014. The [Protection of Life During Pregnancy Act 2013](https://en.wikipedia.org/wiki/Protection_of_Life_During_Pregnancy_Act_2013)  [Act](https://en.wikipedia.org/wiki/Act_of_Parliament)35 of 2013; previously Bill No.66 of 2013) is an Act of the Oireachtas which defined the circumstances and processes within which abortion in Ireland could be legally performed. The Act gave effect in statutory law to the terms of the Constitution of Ireland as interpreted by the Supreme Court in the 1992 judgment [Attorney General v. X](https://en.wikipedia.org/wiki/Attorney_General_v._X) (the "X case"). That judgment (see above events in 1992) allowed for abortion where pregnancy endangers a woman's life, including through a risk of suicide.
    
-   2015 - Health Canada approved the use of the medical abortion drug RU-486 (also known as Mifepristone)
    
-   2015 - Until 2015, the law in France imposed a seven-day "cool-off" period between the patient's first request for an abortion and a written statement confirming her decision (the delay could be reduced to two days if the patient was getting close to 12 weeks). That mandatory waiting period was abolished on 9 April 2015.
    
-   2015 - Kansas became the first state in the United States to ban the [dilation and evacuation](https://en.wikipedia.org/wiki/Dilation_and_evacuation) procedure, a common second-trimester abortion procedure.[\[86\]](https://en.wikipedia.org/wiki/Timeline_of_reproductive_rights_legislation#cite_note-87) But the new law was later struck down by the [Kansas Court of Appeals](https://en.wikipedia.org/wiki/Kansas_Court_of_Appeals) in January 2016 without ever having gone into effect.
    
-   2016 - [Whole Woman's Health v. Hellerstedt](https://en.wikipedia.org/wiki/Whole_Woman%27s_Health_v._Hellerstedt), [579](https://en.wikipedia.org/wiki/List_of_United_States_Supreme_Court_cases,_volume_579)[S.](https://en.wikipedia.org/wiki/United_States_Reports) \_\_\_ (2016), was a [United States Supreme Court](https://en.wikipedia.org/wiki/Supreme_Court_of_the_United_States) case decided on June 27, 2016, when the Court ruled 5-3 that Texas cannot place restrictions on the delivery of abortion services that create an undue burden for women seeking an abortion. It has been called the most significant abortion rights case before the Supreme Court since [Planned Parenthood v. Casey](https://en.wikipedia.org/wiki/Planned_Parenthood_v._Casey) in 1992.
    
-   2017 - In Poland, a new law restricted emergency contraception by changing its availability, from being an over-the-counter drug to a prescription drug, requiring a visit to a doctor.
    
-   2017 - Mifegymiso becomes available for purchase in Canada.

-   2019 - The [Health (Regulation of Termination of Pregnancy) Act 2018](https://en.wikipedia.org/wiki/Health_(Regulation_of_Termination_of_Pregnancy)_Act_2018) (Act No. 31 of 2018; previously Bill No. 105 of 2018) came into effect; it is an Act of the Oireachtas which defines the circumstances and processes within which abortion may be legally performed in Ireland. It permits terminations to be carried out up to 12 weeks of pregnancy; or where there is a risk to the life, or of serious harm to the health, of the pregnant woman; or where there is a risk to the life, or of serious harm to the health, of the pregnant woman in an emergency; or where there is a condition present which is likely to lead to the death of the foetus either before or within 28 days of birth.
    
-   2019 - The government of [South Korea](https://en.wikipedia.org/wiki/South_Korea) criminalized abortion in the [1953 Criminal Code](https://en.wikipedia.org/wiki/Penal_code_(South_Korea)) in all circumstances. This law was later amended but not repealed. However, the Constitutional Court on 11 April 2019 ruled the abortion law unconstitutional and ordered the law's revision by the end of 2020.
    

### Required Readings {.unnumbered}

1.  Pro-choice Action Network. (2009). _A legal history of abortion in Canada._ Vancouver, BC. [http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml](http://www.prochoiceactionnetwork-canada.org/abortioninfo/history.shtml)
2.  Merhi, D. (2012). For their own good: Ontario's legal legacy of the “moral” woman. _Dominion: News from the grassroots 84_. [http://www.dominionpaper.ca/articles/4526](http://www.dominionpaper.ca/articles/4526)
3.  Gibbs, N. (2007). Abortion in America: 1 Woman at a time (pp. 15 - 23). _Time. [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Wars.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Abortion%20Wars.pdf)_
4.  Saletan, W. (2006). Where the rubber meets Roe: The pro-life case for contraception. _Slate._ [http://www.slate.com/articles/health\_and\_science/human\_nature/2006/09/where\_the\_rubber\_meets\_roe.single.html](http://www.slate.com/articles/health_and_science/human_nature/2006/09/where_the_rubber_meets_roe.single.html) 

### References {.unnumbered}

1.  Baldwin, John W. (1994) _The Language of Sex: Five Voices from Northern France around 1200_. Chicago, IL: University of Chicago Press,. p. 95
2.  Broedel, Hans Peter (2004). _The Malleus Maleficarum and the Construction of Witchcraft: Theology and Popular Belief_. Manchester, UK: Manchester University Press, p. 34.
3.  Bullough, Vern L. (Ed.). (2001) _Encyclopedia of Birth Control_. Santa Barbara. CA. ABC-CLIO. pp. 95, 125-128
4.  Critchlow, Donald T. (1999). _Intended consequences: birth control, abortion, and the federal government in modern America_. Oxford: Oxford University Press. 
5.  Cuomo, Amy (2010). Birth Control. In O'Reilly, Andrea. _Encyclopedia of motherhood_. Thousand Oaks, Calif.: Sage Publications. pp. 121-126.
6.  Farier, Philip M. (Ed.). (2007). _Natural Family Planning: Webster's Timeline History, 1968 - 2007._ Icon Group International.
7.  Fryer, Peter (1965). _The Birth Controllers_. London, UK: Secker & Warburg.
8.  Gordon, Linda (2002). _The Moral Property of Women: A History of Birth Control Politics in America_. Chicago, IL: University of Illinois Press.
9.  Greer, Germaine (1984). _Sex and Destiny_. London, UK: Secker and Warburg. p. 306.
10.  Hilgers, T.W. (2002) _Reproductive Anatomy and Physiology: A Primer for FertilityCare Professionals._ (pp. 1-14)
11.  History of Abortion Timeline. [**http://www.nrlc.org/abortion/history/**](http://www.nrlc.org/abortion/history/). United States 1959 to 1998. Published by the National Right to Life Coalition.
12.  Hull, N. E. H.; Peter Charles Hoffer. (2001). _Roe v. Wade: the abortion rights controversy in American history_. Lawrence, Kansas: University Press of Kansas.
13.  Lipsey, Richard G.; Carlaw, Kenneth; Bekar, Clifford (2005). _Historical Record on the Control of Family Size:_  _Economic Transformations: General Purpose Technologies and Long-Term Economic Growth_. Oxford University Press. pp. 335-40.
14.  Planned Parenthood Council. Timeline: 100 Years of Birth Control. [**http://www.plannedparenthoodaction.org/elections-politics/blog/timeline-100-years-birth-control/**](http://www.plannedparenthoodaction.org/elections-politics/blog/timeline-100-years-birth-control/).
15.  Reagan, Leslie J. (1997). _When abortion was a crime: women, medicine, and law in the United States, 1867-1973_. Berkeley, California: University of California Press.
16.  Rubin, Eva R. (1994). _The Abortion controversy: a documentary history_. Westport, Connecticut: Greenwood Publishing Group.
17.  Wiesner-Hanks, Merry. (1999) Christianity _and Sexuality in the Early Modern World:_ _Regulating Desire, Reforming._ London, UK: Taylor and Francis.  

  

## Journal Activity - A.3.9: Contraception and Abortion Timeline {.unnumbered}

Contraception and Abortion Timeline

List the major events in your country and region over the past 5 years with respect to changes in laws, availability, practices, and trends regarding contraception and abortion.

----

## 3.10 - Pill Timeline {.unnumbered}

Read this article: [Pill Timeline](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Pill%20Timeline.pdf), which is a timeline of the birth control pill created by PBS, and addresses some of the controversy surrounding its integration into birth control practices.

See also [A Brief History of the Birth Control Pill](https://web.archive.org/web/20210719152039/http://www.pbs.org/wnet/need-to-know/health/a-brief-history-of-the-birth-control-pill/480/) from PBS.

----

## 3.11 - Conclusion {.unnumbered}

We have spent considerable time now reviewing the variety of ways people have sought to control conception and the number of live births since ancient times. Our explorations have taken us through many considerations for controlling birth and population, physical, psychological, social, environment, and economic. Typically, birth control concerns shape and inform human sexual practices.

At this point you now have a sketch of the key historical periods and trends related to the development of birth control. You will have new insights into the socio-religious influences on sex practices and birth control, and just how entrenched those influences can be. Hopefully, you have taken the opportunity to understand your own family history of birth control, and the ways your culture has influenced your attitudes towards birth control, sexual agency.

