# 4: Ethics in Sexuality and Birth Control {.unnumbered}

## 4.1 - Introduction {.unnumbered}

Though we may each personally favor a certain way of relating to and dealing with menstruation and the menstrual cycle, as well as related ideas about women's body, sexuality, and fertility, it is important for the HRHP to be mindful that other women may not share our assumptions or practices or socio-religious perspective on the ethics of sexuality and birth control. Thus it benefits the HRHP to be familiar with various socio-religious perspectives, some of which we have previously been touched on. Developing a reflective awareness of such perspectives prepares the HRHP to meet each woman where she is at as regards that woman's individuation approach to dealing with and relating to menstruation.

The [Justisse Site](https://justisse.ca/index.php/pages/page/100241) states that:

> **Justisse Holistic Reproductive Health Practitioners (HRHP)** are professional reproductive health care providers. They are well grounded in knowledge of human sexuality, basic counseling, and all methods of birth control; they are committed to reproductive health education. Justisse practitioners are trained to respect the ethnic and cultural diversity and the ideological and religious beliefs of their clientele. Justisse believes in empowering women with a well founded knowledge about and an awareness of their bodies and reproductive systems. This awareness helps women better understand themselves and make sound health care decisions.

Menstruation is symbolically powerful both psychologically and socially. Throughout all the recorded histories of every society and culture, menstruation has been assigned distinctive meaning, whether it is as a mystery, contamination or peril, substance of ritual, or symbolic carrier of archetypal misogyny. Many myths consider the uterus to be symbolically and even autonomously imbued with a life and power independent of the woman in whom it is housed.

Menstrual blood was a central substance of spiritual consideration in Goddess-centred theologies and cultures. Menstrual blood was sacred. Women were the recognized carriers of this nuministic substance (the magic blood, the wise blood, the “holy dreadful”(Walker, 1983.). In many of these cultures, men could not be crowned king, marry into sovereign families, or be seen fit as leaders or wise men unless they had had sexual intercourse with a menstruating holy woman. Menstrual rituals honoured the nuministic power of the magic blood. According to some schools of feminist thought, many patriarchal cultures maintained menstrual taboos but perverted the original meaning of these taboos by employing them not to honour the sacred power of menstrual blood but to depotentiate it as a symbol of women's power, generativity, and intimate connection to the life-death threshold.

**The general intent of menstrual taboos and laws is the regulation of sexuality & sexual behavior.** Often the purpose of such regulation is to sanctify sexuality and marital intimacy. Such sanctification is believed to allow  the individual and couple to develop spiritually and come into unity with the divine. Understanding the psycho-social-spiritual context of a menstrual taboo or law assists the HRHP in empathically meeting the needs of the women they work with who practice these taboos or laws. The HRHP can be helpful in supporting the individual woman in finding meaningfulness in her practice of menstrual taboos and laws. There is a very large and often heated discourse on the topic of menstrual taboos and laws. Following is a sample, not definitive, of menstrual myths and taboos.

----

## 4.2 - History of Contraception: Some Things to Ponder {.unnumbered}

Here are a few more items about the ideologies regarding and history of birth control, specifically from Canada and the United States. If you do not live in these countries, do you have information from your region?

### Canadian Elizabeth Bagshaw (1881-1982) {.unnumbered}

[Elizabeth Bagshaw](http://en.wikipedia.org/wiki/Elizabeth_Bagshaw) was the medical director of the first birth control clinic in Canada. The Parenthood Society Hamilton provides a brief history of this courageous, tenacious, and inspiring woman [http://members.tripod.com/~ppsh/history.htm](http://members.tripod.com/~ppsh/history.htm). 

> In December 1931 local public service-minded Mary Hawkins convened the charter meeting of the Maternal Health Clinic. The doors opened to Canada's and North America's first and longest operating birth control clinic on March 2, 1932. Within two months Hamilton physician, Dr. Elizabeth Bagshaw, joined the clinic staff and later became the Clinic's Medical Director. 1932 saw the Clinic name changed to the Birth Control Society. The League of Nations unanimously passed a resolution accepting contraception as a normal part of preventive medicine in 1932. Later, on October 9,1952, the Birth Control Society officially changed its name to the Planned Parenthood Society of Hamilton. Eleven years later the Society became one of the charter members of the new national organization The Federation of Societies for Population Planning. Officially chartered by the Ontario Government in 1966, the Society saw the removal of three words "prevention contraception or" removed from the Criminal Code permitting it to operate legally for the first time. Shortly thereafter the Society obtained its status of a charitable institution under the Income Tax Act. In tribute to Dr. Bagshaw's outstanding 33 years of service, the Clinic within the Planned Parenthood Society was officially named for Dr. Elizabeth Bagshaw.
> 
> On the subject of funding, Planned Parenthood began to receive provincial funding from the Ministry of Health in the early 1970's. Interestingly the first budget submitted to the Ministry for family planning programs was $20,000. The Ministry utilized the Society's services as a guideline for establishing similar Public Health service delivery. The Region of Hamilton Wentworth was directly involved in the financial administration of the Society until 1992 when the Society assumed full responsibility for its administrative operations. The provincial Ministry of Health continued the Society's financial support until December 1997. Provincial funding amounted to 72% of the Society's 1997 budget of $502,000. Additional revenues are from individual donations, fund raising sources and grants. Traditionally, the provincial revenues have sustained the clinic expenses while other fund raising sources have supported the educational programs.
> 
> What began in modest circumstances gradually expanded to a community service organization with a modern clinic staffed by professionals managing 20,000 clients annually. An important resource within the community Planned Parenthood has been well recognized by local professionals and community agencies. As part of their teaching, medical and nursing students request to attend educational sessions in the clinic. The Society is also a popular student placement each year. Local agencies and family physicians often refer clients for services. The Clinic services are enhanced by the Thelma Will Resource Centre, the Multicultural Family Planning Education and Services Program and Parent and Youth health sexuality programs. A further program, the Women's Midlife Health Planning Access Centre provides opportunities for information counseling and support groups.

### Children of Fire and Shadow {.unnumbered}

Breed, little mothers,  
With the tired backs and the tired hands,  
Breed for the owners of mills and the owners of mines,  
Breed a race of danger-haunted men,  
A race of toiling, sweating, miserable men,  
Breed, little mothers,  
Breed for the owners of mills and the owners of mines,  
Breed, breed, breed!

Early 20th Century poet and feminist Lucia Trent, Children of Fire and Shadow.

As quoted in “The Poetry of Lucia Trent.” Birth Control Review, Volume XIV, Number 4 (April 1930), page 113.

### The Hierarchy Will Find a Way to Reverse Its Former Position {.unnumbered}

> Nor will the decision _that favours birth control_ be confined to Protestantism where it is already unofficially registered in the practice of the people. Roman Catholicism is bound to follow suit. This will not be Rome's first change of front ... When the inevitable hour arrives in this case; the hierarchy will find a way to reverse its former position. Already there are priests of social mind who confess privately that this will be only a matter of time ... Scarcely two generations ago the church, both Roman and Protestant, was scandalized by this instrument of mercy. Ere long there will be a similar change of opinion upon the vexed question of Birth Control.
> 
> Reverend J.A. MacCallum, Minister of the Walnut Street Presbyterian Church, Philadelphia. "The Church of the Future." Birth Control Review, Volume XIV, Number 5 (May 1930), pages 141 and 142.

### The Church Has Not Done Its Duty Until It Has Endorsed Birth Control {.unnumbered}

> _Those married_ know that God is revealed in human love, not in spite of physical union but also through it. With that vision of marriage, all its elements are lifted to a higher plane. On that level the church has not done its duty until it has endorsed Birth Control and fought to the end to remove the present legal stigmas upon it.
> 
> Reverend L. Griswold Williams, Chairman of the Committee on Birth Control of the Universalist General Convention.
> 
> “Conscious Creation -- Divinity in Action.” Birth Control Review, Volume XIV, Number 5 (May 1930), page 145.

### Hypocrisy Is a Form Of Vicarious Atonement {.unnumbered}

> To many people who feel themselves to be religious, hypocrisy is a form of vicarious atonement. Amid the breakdown of certain principles of human conduct once considered moral or conventional, we cling to outgrown slogans and precepts because our cowardly souls are afraid; we seek to cover up heterodox human nature by orthodox protestations of piety. I don not maintain that these statements accurately describe the attitude of many sincere Roman Catholic priests and Orthodox rabbis on Birth Control, but they undoubtedly apply to the rank and file of the followers of these well-meaning religious leaders ... A most interesting injunction of Talmudic law quoted by Dr. Lauterbach _Talmudic scholar_ lines up very closely with some of our modern scientific attitudes toward favoring the enforced use of contraceptives, or the sterilization of those whose children may become delinquents.
> 
> Rabbi Edward L. Israel, Chairman of the Social Justice Commission of the Central Conference of America Rabbis. “A Divine Mandate.” Birth Control Review, Volume XIV, Number 5 (May 1930), pages 142 and 143.

###  All That the Priest Can Do Is to Repeat the Law of the Church {.unnumbered}

>  It is more than useless for any individual Roman Catholic to try to tempt his confessor to discuss the matter of Birth Control from a sympathetic or psychological standpoint. Sentiment enters as little into such a law in the Roman Church, as it does into business. All that the priest can do is to repeat the law of the Church, and that closes the door on any further discussion. . . . The result is that we have an unrestricted birth-rate among the poor and degenerate, and a lamentable decline in the offspring of the well-to-do and intelligent classes.
> 
> Reverend Leo Lehman, pastor of the Chapel of the Good Shepherd, New York, American Catholic Church. “Another Catholic Viewpoint.” Birth Control Review, Volume XIV, Number 5 (May 1930), page 148.

----

## 4.3 - The Greatest Experiment Ever Performed On Women {.unnumbered}

**JOURNALIST OF THE MONTH:  Barbara Seaman: Muckraker for Women's Health**

By Joe Lauria - We News correspondent  (October 2003) 

> (WOMENSENEWS)--During the Second World War, the Nazis experimented with a bold, new drug by slipping it into the soup of Jewish inmates at Auschwitz. The plan was to secretly sterilize the prisoners as part of the Nazis' drive to racially "purify" Germany. The drug, liquid estrogen, was a precursor of the Pill. The Nazis' soup scheme was just part of what journalist and author Barbara Seaman calls "The Greatest Experiment Ever Performed on Women," the title of her latest book, published this year by Hyperion. This link provides more information about the book [Greatest Experiment Ever Performed](http://www.amazon.com/Greatest-Experiment-Ever-Performed-Women-ebook/dp/B003R7L04I/ref=sr_1_1?ie=UTF8&qid=1422476902&sr=8-1&keywords=greatest+experiment&pebp=1422476838938&peasin=B003R7L04I)
> 
> The practice of slipping women drugs without their knowing the consequences is an experiment, she argues, that is still going on, not by Nazis, but by large corporate interests and complicit doctors, with an eerily similar disregard for women's rights to acceptable drug testing standards.
> 
> The revelation of the Auschwitz deception and the Nazis' unsavoury role in developing the Pill is the kind of muckraking journalism that has made Seaman a leading U.S. advocate for women's health.
> 
> Since her 1969 book, "The Doctors' Case against the Pill," published by Hunter House, Seaman has persistently taken on the medical establishment and powerful pharmaceutical companies, exposing their drive for profit at the expense of women's health.
> 
> "The U.S. drug industry's responsibility is to employees and share holders. It's the doctors who have the duty to the patients. Too many of them let themselves be snookered, by the gifts and flattery of the drug (representatives) and the misplaced faith in certain eminent doctors and medical professors," Seaman said in an interview with Women's eNews. "If I could tell a good study from a bad study, I have the right to expect that doctors would also do their homework."

### Passions for Writing, Justice Begin at Home {.unnumbered}

Born in Depression-era Brooklyn, Seaman acquired a passion for social justice that came from her father; a love of writing and literature that came from her mother; and a drive to stop health-industry abuses against women that came from two profoundly disturbing experiences.

Her mother, an English teacher, motivated her by saying she wasn't as smart as her some of her students, in particular one girl, Ruth Bader. "It made me feel better when she grew up to be so smart," Seaman said of the formidably intellectual U.S. Supreme Court Justice Bader Ginsburg.

Her parents belonged to the once-thriving socialist Jewish community in New York. But they expressed the fierce independence that rubbed off on their daughter when they returned from their Soviet Union honeymoon denouncing Stalin. That did not rest well with some comrades in Brooklyn. They thought Seaman's father sold out when he worked for New York Mayor Fiorello LaGuardia as the chief financial officer and helped develop the city's first welfare program. During LaGuardia's legendary reading of the funny papers over the radio during a New York newspaper strike in 1945, Seaman was one of the children sitting on his knee at City Hall.

At Oberlin College in Ohio in the 1950s at the height of the McCarthy era, she had a slight interest in medicine that had been instilled by her uncle, a doctor. But her first shocking experience laid out her future as a champion of women's health. Under pressure to market infant formula, doctors discouraged breast-feeding in the 1950s. In 1957, Seaman told her doctor said she would feed her newborn son anyway. He ignored her and prescribed a laxative breastfeeding mothers should never take. Her son nearly died. "He recovered, but in one sense I did not, for I would never again trust a doctor blindly," Seaman wrote in "The Greatest Experiment Ever Performed on Women."

The second incident came in 1959 as she watched her 49-year-old aunt dying of cancer. Her doctor told Seaman not to take the estrogen-based drug Premarin. "Don't take it. Please don't ever take it," he said. "You may have the same susceptibilities."  That conversation inspired Seaman, who had begun writing for small women's magazines, to begin work on her first book, "The Doctors' Case against the Pill." The book shook up the medical establishment. It put Seaman in the 1970s pantheon of feminist stars, though some accused the then-married Seaman of being blinded by her middle-class lifestyle to the point that she could not understand the issues faced by poor women. But they didn't argue with her book, which showed the Pill posed risks of cancer, heart disease, diabetes and stroke. It also showed that very poor women in Puerto Rico were used in the Pill's early testing at very high doses, without thorough study. Several died of apparent heart attacks, with little medical attention and no autopsies.

The book led to Congressional hearings in 1970. The U.S. Senate barred women harmed by the Pill from testifying. Protesting women interrupted the hearings, an event known as the Boston Tea Party of the women's movement. After the hearings, birth control pills carried warning labels and for the first time the Federal Drug Administration allowed input from patients as part of the drug's regulation. Science Magazine said the book spurred the women's health and patients' rights movements. The New York Times wrote: "Barbara Seaman triggered a revolution, fostering a willingness among women to take issues of health into their own hands." The Hite Report on the Family called her "one of the most influential women in the twentieth-century women's movement" and New York Congressman Jerrold Nadler said she was a "national role model" who "has saved the lives of countless women."

But Seaman made enemies too. A reviewer from The Journal of the American Medical Association called it "a strange book . . . I cannot in all good conscience recommend it for either the public or the profession." Pharmaceutical companies pressured magazines to stop running Seaman's articles and columns by threatening to pull advertising. So she wrote on a completely new subject: a biography of Jacqueline Susann, the author of "Valley of the Dolls" whom Seaman saw as a tough advocate for women's rights, though firmly ensconced in popular culture.

### Returning to Investigating Hormonal Medicines {.unnumbered}

In "The Greatest Experiment Ever Performed on Women," Seaman has returned to the subject of her first book: the dangers of hormonal medicines and the cavalier way they are tested and peddled to women.

"They have been used, in the main, for what doctors and scientists hope or believe they can do, not for what they know the products can do," she writes. "Medical policy on estrogens has been to 'shoot first and apologize later' . . . Over the years, hundreds of millions, possibly billions of women, have been lab animals in this unofficial trial. They were not volunteers. They were given no consent forms. And they were put at serious, often devastating risk."

British scientist Charles Dodd had been working on estrogen five years before the Nazis. When he learned of their intent he published his formula in 1938 to keep them from controlling the world market for hormones, Seaman reports. Within months, thousands of drug companies and doctors worked on the formula. "Products made from chemicals that mimicked the feminizing effects of a woman's natural secretions were marketed fresh out of the lab," Seaman writes. They've been sold since to slow aging, stop hot flashes and avoid pregnancy or miscarriage. What was rarely acknowledged then, and wouldn't be now if not in large part for Seaman's work, is that estrogen drugs can cause cancer, blood clots and other diseases. Dodd pointed out the risks and by 1941 and they should have been well known.

In 1942, Ayerst Laboratories introduced its estrogen-based Premarin (from pregnant mares' urine) in the U.S. It has been one of the most profitable drugs in history. Sixty years later, a five-year study on the synthetic estrogen Prempro (composed of estrogens and progestin) with 16,608 women was stopped when it became clear that the hormones increased the risk of invasive breast cancer and cardiovascular disease at a rate that clearly outweighed any benefits. There were fewer cases of hip fractures and colon cancer--benefits not considered worth the risk.

The findings vindicated Seaman. Looking back on her career, she said: "I just started out to try and give women plain facts that would help them to make their own decisions and not have to rely on authority figures. I didn't start out to be a muckraker." Countless women are grateful that, when it came to their health, she did become one in the best tradition of journalism.

Joe Lauria is a freelance journalist whose work appears in the Boston Globe, the Sunday Times of London, The Business and other publications. Copyright 2003 Women's eNews. The information contained in this Women's eNews report may--with the prior written authorization of Women's eNews--be published, broadcast, rewritten or otherwise distributed. To obtain permission, send an e-mail to permissions@womensenews.org and provide the publication or broadcast date and the name of the newspaper, magazine, radio or television station, cable network, Web site, newsletter or list serve where it will be replicated. Please include the approximate size of the audience you intend to reach.

[Women's eNews](http://womensenews.org/).is a nonprofit independent news service covering issues of concern to women and their allies. An incubator program of the Fund for the City of New York, Women's eNews is supported by our readers; reprints and licensing fees; and the John S. and James L. Knight Foundation, the Barbara Lee Family Foundation, the Rockefeller Family Fund, The Helena Rubinstein Foundation and the Starry Night Fund. The donations from readers are critical to our success. They are an important measure that we are serving our audience--the yardstick that our foundation supporters will measure us by.

This article has been reprinted with permission granted on January 19, 2004 by [permissions@womensenews.org](mailto:permissions@womensenews.org)

----

## 4.4 - Assisted Human Reproduction {.unnumbered}

Bill C-6, Canada's _Assisted Human Reproduction Act_, received royal assent in 2004. It is the Canadian federal legislation governing new reproductive technologies (NRT), cloning, use of human embryos, and stem cells. New reproductive technology refers to the many medical procedures used to treat infertility, such as invitro fertilization, egg harvesting, and sperm donation. The bill outlines principles and procedures for governing NRT, cloning, and embryo research and use.

Bill C-6  has been controversial since its introduction.  Some people believe its passing into legislation is critical for protecting the health of women and children by assuring the safety and efficacy of new reproductive technologies. They want strict governance of NRT, a ban on cloning, and regulation of the creation and use of embryos. Others believe that the passing of the bill limits scientific research, and puts the government in the bedrooms of the people. Pro-life groups argue that the bill allows for the destruction of human embryos produced through NRT.

In 2010, some provisions of the _Assisted Human Reproduction Act_ were found to be unconstitutional by the Supreme Court of Canada. The _Act_ was amended by Parliament in 2012 to reduce the federal role in regulating assisted reproduction, dissolve the Assisted Human Reproduction Agency, and transfer regulatory responsibilities to the Minister of Health.

### Required Reading {.unnumbered}

#### HRHP Trainees living in Canada {.unnumbered}

1.  Unit A Section 4.4 [Bill C-6 Assisted Human Reproduction Act](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#:~:text=Bill%20C-6%2C%20An%20Act,stages%20on%2011%20February%202004.&text=The%20bill%20later%20died%20on,of%20the%201997%20federal%20election). You only need to read the 

-   [BACKGROUND](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#backgroundtxt)
-   [COMMENTARY](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#commentarytxt)
-   [BRIEF CHRONOLOGY OF RELATED FEDERAL GOVERNMENT ACTIONS](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#brieftxt)

#### HRHP Trainees living outside of Canada {.unnumbered}

 Please preview the readings for Canadian students and find 2 similar references to literature that is relevant to your country/community. Please share your findings with your trainer and keep it on hand to use to complete Unit A Section 4.4. Journal Activity #5.

## Journal Activity - A.4.4 Policies on Reproductive Technologies {.unnumbered}

Review HRHP Courseware reading: Unit A Section 4.4 [Bill C-6 Assisted Human Reproduction Act](https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/LegislativeSummaries/373LS466E#:~:text=Bill%20C-6%2C%20An%20Act,stages%20on%2011%20February%202004.&text=The%20bill%20later%20died%20on,of%20the%201997%20federal%20election) (Background, Commentary, Brief Chronology)

If you are **living and working in Canada** respond to the reading by comparing and contrasting your personal perspective on New Reproductive Technologies (NRT) and some of your practical experience with them personally or through clients/friends/family/. 

If you are **NOT living and working in Canada** find 2 similar references to literature that is relevant to your country/community. Please share your findings with your trainer. Then respond to the literature that you found; compare and contrast your personal views and experience with NRTs. to that described in the literature with which you are working.

----

## 4.5 - Beyond Sexual Fundamentalism {.unnumbered}

### Required Reading {.unnumbered}

Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 1: Sexuality in perspective. In _Understanding Human Sexuality_ (3rd ed.) (pp. 1-19). Toronto: McGraw-Hill Ryerson. **[Understanding Human Sexuality](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g)**

Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 21: Sexuality education. In _Understanding Human Sexuality_ (3rd ed.) (pp. 596 - 622). Toronto: McGraw-Hill Ryerson. **[Understanding Human Sexuality](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g)**

Ellison, M. (2001). Beyond sexual fundamentalism: The call for an ethical eroticism. _Sexual Addiction & Compulsivity, 8_, 3-11. Doi:1072-0162/01 [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Sexual%20Ethics%20Paper.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Sexual%20Ethics%20Paper.pdf)

**Abstract:**

In a culture whose sexual mores have been influenced largely by Christian teaching, sex is typically presumed guilty until proven innocent. This essay explores the cultural roots of this sex negativity, analyzes the contemporary crisis in sexuality, and proposes a progressive sex ethic that is sex-positive, respectful of sexual diversity, and responsive to sexual abuse and exploitation. Renewal of sexual ethics requires a break with sexual fundamentalism—the notion that there is a singular, ideal sexuality (heterosexual, marital, procreative) and that those conforming to this standard have a right to police and control others. In contrast, a justice framework is developed to promote an ethical eroticism that values the bodily integrity of every person and honors the variety of ways in which people live sexually whole, morally responsible lives.

## Journal Activity - A.4.5 Sexual Fundamentalism {.unnumbered}

Review HRHP Courseware page [http://justisse.ca/index.php/college/courseware/page/1037](https://justisse.ca/index.php/college/courseware/page/1037) on sexual fundamentalism.

How would you define sexual fundamentalism? Reflect on how you might get caught in sexual fundamentalism. How do you get caught in collective ideologies that belie your own truth?

----

## 4.6 - Why not FAM? {.unnumbered}

As a student studying the Justisse Method and the basis of FAM it is worthwhile to consider the questions introduced here, as you will encounter them in the field. It is the hope of the author that you may one day participate in addressing some of the larger concerns behind this inquiry. If the ideas addressed in this reading excite you, you may consider using some part of it as a theme for the essay part of the Unit A Exam and Evaluation.

### Statistics {.unnumbered}

British government statistics from 1986 show 2% of women (200,000) in that country used natural birth control. Yet, only .001% (200) was taught natural birth control methods at family planning clinics involved with the study. (In the same year 23% of women were prescribed the birth control pill. The percentage of birth control pill users in 2003 varies by country and region. For example in 2003 43% of women in Britain and 19% in Canada report using the pill.) In 1999, 1% of British women used natural birth control. (Botting, Dunnell. 2000).

___

1.  The Family Planning Association. (Nov. 2007) [Contraceptive Patterns of Use Factsheet](http://www.fpa.org.uk/sites/default/files/contraception-patterns-of-use-factsheet-november-2007.pdf). London, UK.
2.  Botting, B., Dunnell, K. (2000) [Trends in Fertility and Contraception in the Last Quarter Century](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Trends%20in%20Fertility%20and%20Contraception%20in%20the%20Last%20Quarter%20Century.pdf). Population Trends. Summer 2000. (100) 32.9.

___

Most natural birth control statistics do not differentiate between types of natural birth control, categorizing them all under the ubiquitous name of “safe period” or “calendar,” which considerably skews understanding of the statistics meaning and misinforms potential users of the more reliable types of natural birth control.

Do anecdotes about people who get pregnant using natural birth control really represent its effectiveness? What are the specific methods to which these anecdotes refer? Are those stories reflective of statistics that clearly indicate a very high effectiveness rate (96.6%) with proper use and education? Empirical clinical feedback among FAM educators indicates that most unplanned pregnancies when using natural birth control are related to problems of correct practice, motivation, and confidence based on correct knowledge or understanding of the method.

### Demographics of FAM Users {.unnumbered}

Relative to information about other methods of birth control, there is scant information on the demographics of natural birth control users, or how they learn about natural birth control or their outcome. It is difficult to accurately suppose what how those demographics would appear, and such pondering raises more questions than it answers.

Who are the women that choose natural birth control? How are women learning? From whom are they learning, are they teaching themselves or learning from each other? Are women using successfully by themselves? How many combine withdrawal, seminal retention, or barrier methods with natural methods? Of the 200,000 reported British women using natural birth control, what types were they using? Would natural birth control be more widely studied if it could profitably commodified by pharmaceutical or medical industries? If there were many centres for educating women about natural birth control, how would that change the face of modern contraceptive practice (and the health of women)?

Empirical clinical evidence gathered by the author over the last four decades indicates many factors that might be part of why only 1 to 2 % of women report using natural birth control, and why of those only a fraction are taught in family planning clinics.

1.  Natural birth control users tend to be self-motivated and self-responsible, wanting to take charge of their own bodies, and more likely than other contraceptive users to be self-taught.
2.  Many natural birth control users have difficulty finding people qualified and suitable to their needs to teach them.
3.  Few people in the health professions have the skills or training to teach natural birth control - it is not standard curriculum for nurses, nurse practitioners, midwives, medical or naturopathic doctors.
4.  Most birth control clinics are not mandated to teach natural birth control and rarely refer clients to natural birth control educators, due to the often mistaken notion that natural birth control is not effective and that women would not be able to learn it.
5.  Government or private health insurance does not cover the price of learning natural birth control.
6.  Natural birth control is often association with the religious rhetoric, ethics, and dogma of the Roman Catholic church (and other fundamentalist religious ideologies) with respect to contraception, abortion, and sexual practice. This dissuades the mainstream scientific community from embracing the method.

### Quality of FAM Instruction {.unnumbered}

Many women are self-taught or learn from books or friends. While this is a very healthy sign, in that more women are consciously participating in taking control of their fertility, it does raise questions about the instruction quality, and why this information is not more widely available. Self-taught women are often not knowledgeable in how to handle the more complex reproductive situations or reproductive health concerns. Of the many women who do use natural birth control, most do not have ready access to precise and comprehensive information or teaching or follow-up guidance through all their reproductive situations.

### Body Literacy {.unnumbered}

How does the relationship women have to their physical body and reproductive body invite them or dissuade them from using FAM? Many women express a dislike of FAM because it requires them to touch themselves and examine bodily fluids, and even be aware of “what is going on down there.” What are the factors that cause women to be squeamish about their fertile body, or to distrust their own body knowing and defer to bio-chemical or technological solutions for birth control or deal with their reproductive body? How might the invitation to sexual agency and conscious relationship to one's unfolding menstrual cycle be off putting for some women?

### Natural Birth Control and Church Doctrine {.unnumbered}

The majority of natural birth control educators follow the Roman Catholic model - natural family planning (NFP). The vast majority of the promotion for and research into natural birth control are done by the same groups. These groups reserve its information for married couples or celibate women, and only those who maintain an anti-choice philosophy.

One of the shortcomings of NFP groups is that they encourage laymen and priests to teach women about their cervical mucus secretions. Not only do women find this embarrassing, they also find it disquieting that men who know nothing at all about the experience of these changes in mucus patterns should attempt, with conviction, to help women understand the signs of fertility. (What happened to Lynn Billings' discovery that “with women teaching women, 100% of women can determine their fertile time,” a discovery that launched what was to become the worldwide use of the Billings Method, albeit, associated with Roman Catholic doctrine?)

 During the past 10 to 15 years, groups and individuals not affiliated with religious groups have created their own approaches to the sympto-thermal, BBT, and mucus methods. They include in their teaching ways to combine fertility awareness with barrier method use. They make no distinction between the married or unmarried; are predominantly of a pro-choice persuasion; and are generally women teaching women. Feedback from women who have used the services of these groups and individuals is positive. They report relief at not having to wade through religious agenda to learn FAM. They appreciate knowledge about combining barriers methods with FAM.

### Natural Birth Control and Feminism {.unnumbered}

 Why has the women's movement not given more support to the growth of natural birth control and fertility awareness? One barrier is that most women, feminist or otherwise, are mostly of the belief that natural birth control is the justifiably unacceptable and ineffective Calendar Rhythm method. The feminist community is still battling to have contraception of any sort and abortion made available in their communities. More voices from the collective feminist voice are needed to articulate feminist concerns about birth control methods, with respect to health, the trade off of freedom to conceive or not conceive for a dependency on a health and medical industries that are rife with misogynistic underpinnings that commodify and profit from women's body's, the still present fears of a patriarchal minded society that fears women having power and control over their bodies and the symbolic power of women's menstruation and power to give birth, or make choices to not give birth.

### The Future of FAM {.unnumbered}

Are methods of natural birth control likely to change much in the near future? Because the total pregnancy rates for natural methods are higher (by only a fraction with proper teaching, follow-up, and use) than the Pill or IUD, the World Health Organization (1980) recommends that the focus of research should be on developing increasingly reliable ways for identifying the fertile period. New methods will increase effectiveness and user confidence and compliance. For the World Health Organization's  recent recommendations of selected practice recommendations for contraceptive use see the following.

### Required Readings {.unnumbered}

1.  **[WHO Selected Practice Recommendations for Contraceptive Use](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/WHO%20Selected%20Practice%20Recommendations%20for%20Contraceptive%20User.pdf)** This guide provides guidance on how to provide contraceptives, with the goals of maximizing effectiveness and managing side effects and other problems. The second edition contains 33 recommendations ranging from when to start a method, how to manage problems women experience using certain methods, how to provide emergency contraception, and what clinical exams to perform before a method can be initiated. **[2015 UPDATE of the WHO Guide](http://www.who.int/reproductivehealth/publications/family_planning/MEC-5/en/)** On 1-4 April 2008, WHO convened an expert Working Group in Geneva, Switzerland, to revise the second edition in response to newly published evidence and requests for clarification of specific recommendations from users of the guideline. This document summarizes the changes made to recommendations related to questions 6, 9, 11, 18 and 22 in the second edition of the _Selected practice recommendations for contraceptive use_. The revised recommendations will appear in the 3rd edition of the guideline when it is published. In addition, this document includes a clarification of the recommendation related to question 17.
2.  **[WHO Medical Eligibility Criteria for Contraceptive Use](http://www.who.int/reproductivehealth/publications/family_planning/MEC-5/en/)** This document reviews the medical eligibility criteria for use of contraception, offering guidance on the safety of use of different methods for women and men with specific characteristics or known medical conditions. The recommendations are based on systematic reviews of available clinical and epidemiological research. It is a companion guideline to Selected practice recommendations for contraceptive use. Together, these documents are intended to be used by policy-makers, programme managers, and the scientific community, to support national programmes in the preparation of service delivery guidelines.
3.  What Young Adults Know—and Don't Know—About Women's Fertility Patterns: Implications for Reducing Unintended Pregnancies  **[What Young Adults Know and Do Not Know About FABM](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/What%20Young%20Adults%20do%20not%20Know%20About%20FABM.pdf).** This Research Brief draws on data from the National Survey of Reproductive and Contraceptive Knowledge to describe the level of “fertility awareness knowledge”—defined as being able to identify the point during a woman's menstrual cycle at which she is able to become pregnant—among a sample of unmarried young adults in the United States between the ages of 18 and 29. Child Trends' analyses of these data show that fertility awareness knowledge among this group is low - only one-third can correctly identify a woman's fertile period. This brief examines differences in fertility awareness knowledge by gender, race/ethnicity, education, age, receipt of sex education or sexual health care, sexual experience, pregnancy or childbearing status, and use of various contraceptive methods.

  
## Journal Activity - A.4.4: What Young Adults Know {.unnumbered}

#### What Young Adults Know {.unnumbered}

Reflect on your reading of the required reading  [What Young Adults Know and Do Not Know About Women's Fertility Patterns](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/What%20Young%20Adults%20do%20not%20Know%20About%20FABM.pdf).

Why do you think fertility awareness and natural birth control remain outside the circle of acceptable or common practice?

----

## 4.7 - Conclusion {.unnumbered}

> “Good does not become better by being exaggerated, but worse, and a small evil becomes a big one through being disregarded and repressed. The shadow is very much a part of human nature, and it is only at night that no shadows exist.” Carl Jung (1948) _CW_11, Para 286.

In this section we have explored the diversity of human sexuality, attitudes towards the menstrual cycle, socio-religious and legal concerns regarding birth control and reproductive justice. The HRHP is challenged to come to know their shadow, that which is not yet in the light of their own attitudes towards menstruation, sexual agency, fertility awareness, abortion, birth control, etcetera in order to better serve the women who come to them for guidance. They are challenged to find harmony with their own ways of relating to and dealing with menstruation and the menstrual cycle, and related ideas about women's body, sexuality, and fertility, and equally important to learn tolerance for the beliefs and assumptions of  other women that may differ from theirs.

Women's body's, and fertile cycle has powerful archetypal influence in the psyches of people. Attending to the shadow of those influences becomes the ethical stance for reproductive justice and ethical practice.