# 5: Menstruation: Socio-Religious Perspectives {.unnumbered}

## 5.1 - Introduction {.unnumbered}

This section is not meant to be definitive, but rather serve as a brief introduction to the perspectives of some of the major world religions as regards menstruation, cleanliness, and purification. You will have the opportunity to investigate other religious traditions as part of your reflective journal entries.

Many religions include **ritual purification** as part of their rites. Ritual purification is a preparatory rite with the purpose of preparing a person to worship or pray to a deity or enact a sacred rite.  It is supposed that ritual purification cleanses one of particular bodily fluids (e.g., blood, menses, semen, urine) associated with a state of sin or unworthiness in the eyes of the deity. Such uncleanness is not that of ordinary dirt and grime of daily activity.

Ritual purification existed before there was a clear understanding of the source of infection and contamination (germ theory of disease). There is evidence of these rituals in the earliest religious systems of the ancient Near East. Originally, these rituals were enacted to honor primitive taboos. In modern times, they still honor certain taboos, as well as serve hygienic purposes.[\[1\]](https://en.wikipedia.org/wiki/Ritual_purification#cite_note-1) Certain authors and scholars suggest that the 'dimension of purity' that is common to many religions has a transcendent function, moving us away from the pain, hunger, disgust, guilt, shame we might experience regarding the corporeal body. [\[2\]](https://en.wikipedia.org/wiki/Ritual_purification#cite_note-2)[\[3\]](https://en.wikipedia.org/wiki/Ritual_purification#cite_note-3)

As HRHP practitioners it is valuable to be aware of how a client's historical and ancestral attitudes towards bodily fluids and ritual purification shape her attitudes towards her body and bodily fluids.

### Required Reading {.unnumbered}

1.  **The Woman's Encyclopedia of Myths and Secrets**. Barbara G. Walker. San Francisco: Harper Row. 1983. “menstrual blood” & “menstrual calendar” pages 635-648. 
    
    Do You Know: Where the legend of a cat's nine lives comes from? Why "mama" is a word understood in nearly all languages? How the custom of kissing began? Whether there really was a female pope? Why Cinderella's glass slipper was so important to the Prince? The connection between Tantra and the Sacred Heart of Jesus?  The answers to these and countless other intriguing questions are given in this compulsively readable feminist encyclopedia. Twenty-five years in preparation, this unique and comprehensive source book focuses on mythology anthropology, religion, and sexuality to uncover precisely what other encyclopaedias leave out or misrepresent. _The Woman's Encyclopedia_ presents the fascinating stories behind word origins, legends, superstitions, and customs. A browser's delight and an indispensable resource, it offers 1,350 entries on magic, witchcraft, fairies, elves, giants, goddesses, gods, and psychological anomalies such as demonic possession; the mystical meanings of sun, moon, earth, sea, time, and space; ideas of the soul, reincarnation, creation and doomsday; ancient and modern attitudes toward sex, prostitution, romance, rape, warfare, death and sin, and more. _The Woman's Encyclopedia_ is a revolutionary book that offers a rare opportunity to see our cultural heritage in a fresh light, and draw upon the past for a more humane future.
    

### References {.unnumbered}

1.  Gutierrez, Rafael _H. Nitten Soji: and the Prevention of Infections_. Creative Flow Media. Vol. 2 No.18., p. 65
2.  Haidt, Johnathan (2005). _The Happiness Hypothesis_. Basic Books.  
    
3.  Eliade, Mircea (1996). _The Sacred and the Profane._ In _From Primitives to Zen._ Harcourt Brace Jovanovich.

----

## 5.2 - Jewish Family Purity Laws {.unnumbered}

This section provides a brief introduction to Purity Laws in some Judaic traditions. It is not meant to be an exhaustive review. The student will have a chance to explore other religious traditions in their journal entries.

In Judaism, menstruation is treated as part of the Family Purity Laws, which govern the married life of couples. The original instructions for handling menstrual flow and seminal emissions are to be found in the Book of Leviticus; however, over time, there has been much discussion and evolution of practices around menstruation. Contemporary Jews abide by Family Purity Laws to varying degrees, dependent upon the type of Judaism they practice (Orthodox, Ultra Orthodox, Conservative, Reform, or other interpretations of Judaism). Adherence to Purity laws is also influenced by the area of the world a Jewish woman lives in, and her particular culture.

In order to contextualize menstrual blood taboos it is important to understand that Jewish Purity Laws are particularly concerned with the impurity of blood of animals and human blood.

> Jewish Law upholds the sanctity of life, prohibiting murder (one of the Ten Commandments) and also absolutely prohibits the consumption of blood. As Rabbi Moss of Sydney points out, 'the shedding of human blood is the only prohibition repeated in all five books of the Torah . . . . Consumption of blood is a crime of extreme gravity … dietary laws, known as the laws of kashrut, forbid the consumption of anything that is not designated as kosher … ingesting blood it is clear, does render … one impure. … The Torah prohibits Jews to consume the blood of animals. … Torah Law requires the blood to be drained … The Code of Jewish Law (Sculchan Aruch Yoreh Deah 66:10) states that if, while eating an apple for instance, blood from the mouth is found on the apple, then that part of the apple is not kosher and must be sliced off before eating further. (Boccalatte and Jones, 2013, p. 23)

Understanding the above attitude toward blood helps one contextualize the menstrual taboos a Jewish woman is required to abide by. In essence, a woman's own blood is impure not only to others but to herself. One must consider here the psychological projections that blood collectively carries for Jews, and that the laws of Niddah described below represent the Jewish aversion to blood as an unclean substance.

At the commencement of menstrual flow and for seven days following its cessation, the menstruating women becomes Niddah, which refers to a state of ritual impurity. The meaning of the word **Niddah** and its history is long and complex. Many sources indicate that it originally meant "separateness". Currently, it refers to a state of ritual impurity, but should not be understood to indicate physical impurity.

**Ritual impurity** refers to the state of being of a person, place, or object that is contaminated by a specifically defined substance that is taboo in association with certain rituals or worship of a deity. The contaminating substance is typically associated with menstrum, semen, certain other bodily fluids, diseased states of the skin, some animals or animal parts, or the corrupt flesh of dead people or animals. Niddah is one such state of being.

Blood from the uterus discharged through the vagina—menstrual blood as well as lochial flow—define the state of being Niddah. Uterine flow which continues beyond eleven days is placed in a separate category which reflects its “abnormal” state. When a girl begins her menstrual flow, she enters a state of perpetual Niddah and is forbidden contact with males. Before her wedding, she completes her first Mikveh, a complete immersion in a ritual bath, which ends her state of Niddah and allows her physical and sexual contact with her husband following her wedding. Each menstrual cycle, the woman again becomes Niddah and completes the Mikveh. The practice of these menstrual laws is part of spiritual practice for the individual and the couple. Current practice of these laws varies in strictness among Jewish peoples who call themselves “observant” or “Orthodox” Jews. 

Women who practice Jewish menstrual laws use a method similar to the Calendar Rhythm Method for determining the onset of menstruation. This method has been in use since the early introduction of Talmudic Laws, predating Christianity by several hundred years. (This method is a retrospective method, see Unit D2). Although the woman observes the signs of menstruation, she is not specifically taught how to observe or identify menstrual cycle events associated with fertile days, such as cervical mucus or thermal shift. With respect to the Laws of Niddah, a woman's main concern is identifying whether or not she is bleeding from her uterus and to anticipate the hour and day of menstruation's onset. Calculations are based on the rabbinic assumption that women have 30-day menstrual cycles. If a woman's menstrual cycle history indicates otherwise, she adjusts her calculations accordingly, after consulting with her rabbi.

The time when a married woman is no longer Niddah and is permitted to resume sexual relations with her husband often coincides with her fertile phase. It is a rabbinical assumption that a woman is capable of conceiving anytime from the 8th day following the last day of her menstrual bleeding, approximately 10 to 16 days from the onset of menstruation, until just before the onset of the next menstruation. Thus the couple is strongly encouraged by Talmudic law to engage in sexual relations during this time and engage such that their actions are procreative, that is, without intention to avoid pregnancy. This involves refraining from any form of birth control, withdrawal, or seminal retention (neither of the latter are permitted in Judaism).

There are several considerations for women observing family purity laws and charting their menstrual cycles and/or practicing fertility awareness: If a woman wishes to avoid pregnancy, she must consider when to end Niddah with the Mikveh. She may consider delaying the Mikveh until her fertile phase has ended or at the correct time, but avoid intercourse. She may need to consult with a Rabbi, a Niddah counselor, or bridal counselor to be sure of the correct procedure in this circumstance. If a woman wishes to conceive and finds that her fertile phase occurs during her period of Niddah, then she will need to consult with her Rabbi to discuss completing her Mikveh early in order to be able to have intercourse when she is fertile. She will also need to consult with a Rabbi for any unusual bleeding episodes.

### Required Reading {.unnumbered}

1.  Nishmat: Women's Online Information Centre. The Jerusalem Centre for Advanced Study for Women. Read the section on “Becoming Niddah” **[https://www.yoatzot.org/becoming-niddah/the-niddah-status/](https://www.yoatzot.org/becoming-niddah/the-niddah-status/)**
2.  Jewish Women's Archive: Jewish Women: A Comprehensive Historical Encyclopedia: **[http://jwa.org/encyclopedia/article/female-purity-niddah](http://jwa.org/encyclopedia/article/female-purity-niddah)**

### Reference {.unnumbered}

1.  Boccalatte, S., & Jones, M. (2013). _Trunk_ (Volume Two: Blood). Self-published.

----

## 5.3 - Christianity and Catholicism {.unnumbered}

### Christianity and Catholicism {.unnumbered}

This section provides a brief introduction to menstrual laws in some Christian traditions. It is not meant to be an exhaustive review. The student will have a chance to explore other religious traditions in their journal entries.

The text of Leviticus 15:19-30 used in Judaism, which pertains to menstruation, is also part of the Christian scriptures. Attitudes to menstruation varied among the Church fathers, influenced by Judaism as well as Hellenic and Greek culture, which were both part of the growth of early Christianity.

Early in Church history, Tertullian (155-245 BCE), a Church father, argued that sexuality, even within the confines of marriage, was sinful. St. Jerome (347-419 BCE) wrote that menstrual fluids make women unclean. Timothy of Alexandria wrote in 680 BCE that the taking of communion was prohibited for the menstruating woman, as well as baptism and visits to the church at Easter. Theodore of Canterbury also forbade menstruating women from attending church or receiving communion. Although the Apostolic Constitutions declared that a menstruating woman was not unclean and did not require any ritual ablution, the prohibition on menstruating women attending church or receiving communion, along with performance of any other mass-related activities (such as distribution of communion) continued. The primary concern was that contact by a menstruating woman would defile the altar and sanctum of the church.

The ritual uncleanliness of menstruating women became part of official Catholic Church law in 1234 BCE as part of the Corpus Iuris Canonici and remained in effect until 1916. During the **Medieval Ages,** menstruation was connected to the devil worship of witches, and the idea that women by virtue of their menstrual blood were without a soul. The Medieval Christian fear of woman-blood and woman-flesh reached hysterical proportions. It lead to witch hunts and massacres which took place over several centuries.

Later church leaders revised their original menstrual taboos, allowing women participation in Christian worship only when they were not experiencing menstrual or lochial flow. Postpartum women required a special blessing, after the cessation of lochial flow, before they could re-enter the church or participate in the ritual and sacraments.

The belief in the polluting power of the menstruating woman has historically been one of the arguments against the ordination of women in the Catholic Church. In 1983, a new Code of Canon Law came into effect, which allowed women contact with vestments, communion wafers, altar items, and allowed them to perform some functions within the church, although they are still barred from ordination. The meaning of menstruation has, of course, changed significantly over the course of Catholic history, in response to changing social and economic factors.

#### Required Readings {.unnumbered}

1.  Women were considered ritually unclean. [**http://www.womenpriests.org/traditio/unclean.asp**](http://www.womenpriests.org/traditio/unclean.asp "http://www.womenpriests.org/traditio/unclean.asp") This text outlines Christian beliefs regarding purity derived from the Jewish tradition.
2.  Macbeth, A. (2013). **[Buddhism and Menstrual Taboos](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitA/Buddhism%20and%20Menstruation.pdf)**  (This paper was compiled by Macbeth as a journal response. We are sharing it here for the benefit of others.)

----

## 5.4 - Menstrual Myths and Taboos {.unnumbered}

### Required Readings {.unnumbered}

The readings listed below provide a variety of comments on menstrual taboos. As you browse through them pay attention to your responses, both in your body and your intellect. Explore other sources on your own as there is a wide variety of thought on the topic of menstruation and menstrual taboos. Pass on any websites or articles that you find interesting to your fellow HRHPs and instructors. 

1.  The HRHP Courseware Unit A Section 5

3.  Museum of Menstruation and Women's Health [mum.org](http://www.mum.org/)
    
4. [The menstruation taboo](https://www.youtube.com/watch?v=jH1sh7aU-mk) Diana Fabianova at TEDxBratislava 2013: (click on the CC button at the bottom right to see the English subtitles)
    
5. Video of [A Taboo-Free Way to Talk about Periods](https://www.ted.com/talks/aditi_gupta_a_taboo_free_way_to_talk_about_periods?language=en) Aditi Gupta at TedxGateway Women May 2015.
6. [Menstrual Hygiene Management: A taboo that must be broken!](https://blogs.adb.org/blog/menstrual-hygiene-management-taboo-must-be-broken) blog by Anupma Jain, Senior Social Sector Specialist. June 06, 2013. 
7. [Decolonising your body: Maori attitudes towards menstruation](https://thespinoff.co.nz/atea/17-04-2019/decolonising-your-body-maori-attitudes-to-periods/?fbclid=IwAR1Pf37WoHpantiH30diCO5s5s4C_3e0KfOLEgSkeOm6_6y0krRfmO_KvzA) Leonie Hayden April 17, 2019

Historical Sampling of Menstrual Myths and Taboos

The following excerpts are from Barbara Walker (1983) "Menstrual Blood" In _Women's Encyclopedia of Myths and Secrets.__Women's Encyclopedia of Myths and Secrets_ (1983). Harper Row,  San Francisco, CA. pp. 635-645.

Walker's perspective on attitudes toward menstrual blood represents only a very brief sketch of the very complex field of menstrual taboos and menstrual beliefs. It is not meant to be comprehensive. For example, the attitudes of medieval doctors regarding menstruation were considerably more variable and diverse than Walker indicates. The diversity of thought would be related to such issues as whether or not the medieval doctor was an alchemist, astrologer, physician or philosopher. It is important to be mindful in considering that Walker is neither the only source nor the definitive source on the topics of her encyclopedia, and so be encouraged to strike out on your own investigations. The excerpts from Walker's work are offered with the intention of stimulating the HRHP's thinking with respect to the topic, and hopefully encourage discourse and independent research.

**Christianity** - From the beginning of Christianity, menstrual blood has been shrouded in fear-based beliefs and doctrines. Throughout time and variously, menstrual blood has been considered unclean; a menstruating woman who touched anything caused it to become unclean or imbued with evil; menstruating women were denied access to churches or church buildings, and refused communion and other holy rites; women were taught to hate their bodies as the producers of the unclean blood; it was believed that menstrual blood gave birth to demons and devils. Ironically, medieval peasants (often still practicing pagan worship) believed that menstrual blood fertilized the earth and protected crops. One of the arguments against the ordination of women into the Catholic Church is that a menstruating woman priest would 'pollute' the altar and the sacrament of communion. The “Blood of Christ” that is one symbol of the Christian communion rite was once a symbol of  the divine feminine; the blood was the menstrual blood of the divine feminine, symbol of her power over life and death. The witch-hunt craze arose out of the Christian fear of menstrum and woman's intimate connection to the life-death mysteries.

**Medieval Doctors** - medieval doctors considered menstrual blood a cure for leprosy and an aphrodisiac. 19th century doctors, believing erroneous notions of witchcraft, claimed that menstruating women were unhealthy and that men who had sexual relations with them would become infected with urethritis or gonorrhea. In fact, they believed women's bodies alone were the source of gonorrhea.

**Elusinians** (Ancient Greeks of the cult of Demeter and Persephone) - menstrual blood was used in Elusinian mystery and fertility rites as a generative power, and menstruating women were considered to have magic power for influencing the Earth's fertility.

**Laws of Manu** (Hindu doctrine, or Brahman law) - state that if a man even approached a menstruating woman (or worse still had sexual intercourse with her) he would lose wisdom, energy, sight, strength, and vitality. “Brahmans ruled that a man who lay with menstruating women would suffer a punishment one-quarter as severe as the punishment for Brahmanicide, which is the worst crime a Brahman could imagine. Vedic myths were designed to support the law, such as the myth that Vishnu dared copulate with the Goddess Earth while she was menstruating, which caused her to give birth to monsters who nearly destroyed the world.” This is considered patriarchal propaganda designed to undermine the Tantric Maharutti.

**Persian Patriarchs** - were deathly afraid of menstrual blood and followed the Brahman Law, “maintaining that menstruating women must be avoided like poison . . . \[and\] belonged to the devil; were forbidden to look at the sun, to sit in water, to speak to a man, or to behold an altar fire ... Pre-patriarchal Persian religion incorporated the common ancient belief that the first onset of menses must be caused by copulation with a supernatural snake \[that\] renders women fertile and helps her conceive children.” Minoan Crete and Phrygian “Snake-born people” held similar beliefs, and menstrual taboos were honoured out of a sense of the sacredness of menstrual blood and the menstruating woman rather than out of fear and hatred of woman-blood.

**Thessalian witches** - considered 'moon dew', “the menstrual blood collected from a girl's first menstruation shed during an eclipse of the moon,” as the worst possible poison. It was believed capable of blasting the fruits of the field, souring wine, clouding mirrors, rusting iron, and blunting knives. The witches believed that bees would fly away from their hive and never return if a menstruating woman touched it, and that a man who lay with a menstruating woman during a lunar eclipse would quickly become sick and die. 

**Zoroastrians** - “held that any man who lay with a menstruating woman would beget a demon and would be punished in hell by having filth poured into his mouth.” 


### Modern Perspectives on Menstrual Taboos {.unnumbered}

#### Bleeding Creatively: Menstrual Activism  {.unnumbered}

December 2015, Laura Salamanca: Response to Unit A Section 5 Journal #6 "Menstrual Taboos: Three Articles"

Taboos that compel menstruating women to be ashamed, hide, and deny their experience of cyclical bleeding are rampant in our society. The process of menstruation is thought to be polluting, primal, and reminds us that we are not the rational beings society would have us believe. In most of the world, menstruation is wrapped up in discourses of shame, pollution, and filth - misogynistic attitudes that will become outdated as women speak out and slowly change our relationship with the flow. Women everywhere are challenging each other to not be silent about our blood, and to expose it and use it in creative practice (e.g. Ogden Trotta, 2013). Menstrual blood has been used in ways that expose its beauty, strike up conversations about body image and shame, and (most importantly) bring attention to particular social justice campaigns. The world of menstrual art is fertile with possibility.

Menstrual art has probably been around as long as devices that are used to catch (instead of soak) menstrual blood have been around. Yet significant media attention has only emerged in the past few years as women seek to expose menstruation as a normal human function of the body, and bring it out into the open through various creative forms (Gray, 2012; Hecht 2012). In the _Vice_ photo series by Emma Arvida Bystrom, several women are depicted going about their daily activities - jogging, reading, texting, etc. - and each woman is bleeding through her clothing. The images were admittedly shocking to me at first, but reveal the fact that (while powerful) menstruation is also a mundane act that women can go through without raging from PMS or hiding from the public eye (Gray, 2012). The hiding of menstrual blood and shame around its very existence is an almost universal experience for women - and as we agonize over the process we rarely stop to admire the beauty in this symbol of procreative power.  

In a macrophotography series, artist Jen Lewis shines the spotlight on the blood itself - its vibrant colour, substance, and movement in water (Frank, 2015). Teaming up with her husband Rob Lewis, the couple create prints that take this usually reviled substance and expose its beauty as nothing to be ashamed of or fear. Similarly, artist Vanessa Tiegs uses menstrual blood mixed with acrylics to create beautiful paintings on canvas. She has even coined the word _Menstrala_ to refer to her menstrual art (Tiegs, n.d). With blood as the medium, these artists both challenge the discourse of pollution and celebrate the cyclical nature of our bodies' release of energy and regenerative power.

Tiegs calls on women to empower themselves through an understanding of the cyclical nature of our bodies and to turn menses into an “intellectually creative” time (Tiegs as quoted in Hecht, 2012, para. 4). Bystrom, Lewis, and Tiegs allude to the ubiquity of blood and guts in media while natural cyclical bleeding is “scrubbed from the visual landscape” (Lewis, quoted in Gray 2012). Male blood has a patriotic and nationalistic appeal at the same time as menstrual blood is regarded as “impure biological waste” (Barman, 2015, para. 5).  Tiegs remarks: “menstrual blood is the only blood that is non-violent … women are creators of life, but women are also creators of renewed life on a cyclical basis” (Lapekas, n.d.)

While exposing and discussing menstrual bleeding alone is a political act, some have gone further in their activism by using taboos against periods in their campaigns for social justice, including against violence against women (Barman, 2015), against homophobia (Jamie, 2012), and for immigrant worker's rights (Levy, 2015). In New Delhi, a city where 92% of women will experience some form of sexual violence in their lifetime (UN brief, p. 2), student activists used sanitary pads with fake blood to bring attention to the Nirbhaya documentary ban. The Nirbhaya documentary “India's Daughter” was based on the story of Jyoti Singh, a young woman who was gang raped and assaulted by 6 men on a bus in December 2012 and subsequently died from her injuries. The documentary features an interview with one of the rapists, Mukesh Singh, who showed no remorse and remarked that “when being raped, she shouldn't fight back. She should just be silent and allow the rape … a girl is far more responsible for rape than a boy” (quoted in Rawlinson, 2015, para. 5). These events sparked outrage and prompted the banning of the documentary - yet many argued that his comments were indicative of prevailing attitudes (including newspaper coverage of the assault) in Indian society. When the students protested (with the hashtag #SanitaryPadsAgainstSexism), pads were used to circulate messages in Hindi and English, some of which read “Imagine if men were as disgusted by rape as they are by periods” (Barman, 2015, para. 3).

Similarly, artist and activist Zanele Muholi uses menstrual art to bring attention to the problem of “corrective”, or “curative rapes” against lesbians in South Africa (Jamie, 2012, para. 2, 5). Her project, entitled _Isilumo siyaluma_ or _Period Pains_ was meant to tackle the taboo of this secretive time of the month and speak against the experiences of violence and erasure of the lesbian community. It inspires people to “personally recognize and respect the humanity of the “others” experiencing brutal violence” (Jamie, 2012, para. 11). Through her artwork and words we think of the more than 30 lesbians who have been killed in “corrective rape” cases since 1998 whose attackers go unpunished. Of the women who are told they are being taught a lesson in “how to be a real woman” (Carmen, 2011, para. 7). The actions of both Muholi and the student activists in New Delhi remind us that in our current state of affairs the only blood acceptable on a woman is that inflicted through men's violence.

Violence against women is a problem worldwide, and in North America rape culture is alive and well. In the recent United States presidential debate, candidate Donald Trump attacked moderator Megyn Kelly for asking tough questions by remarking he could see blood “coming out of her whatever” (as quoted in Levy, 2015, para. 2). Many women tweeted at Trump about their periods with the hashtag #periodsarenotaninsult, but artist Sara Levy thought that a campaign with humor would go a longer way. Levy believes that fighting the body shame that disgust around menstruation engenders is “one small step toward raising a generation of confident women who have the courage to fight for equality for themselves and others” (Levy, 2015, para. 8). She painted a picture of Donald Trump's face with her own menstrual blood and a brush and titled it _Whatever_. In light of Trump's racist comments about immigrants Levy donated 100% of the sale of the painting (US $4050) to VOZ, an organization that empowers diverse day labourers and immigrants to improve their working conditions and protect civil rights in Portland, Oregon ([www.portlandvoz.org](http://www.portlandvoz.org/)).

Using menstrual blood in creative practice exposes its own beauty, forces us to consider the legitimacy of our body shame, and reminds us that feminism still has a lot of work to do. As women everywhere reclaim their power and challenge each other to change our relationship with menstruation, we hold ourselves and our communities accountable to the violence we experience and inflict upon others. Whether we merely break the taboo of silence and recognize that the experience of menstruation is mundane and beautiful, or use our blood in art and activism, it is time that those of us who menstruate change our relationship with this regenerative process and stop silencing our experience. In its literal use of our creative power I find menstrual art provocative, inspiring, and absolutely necessary.

### References

1.  Barman, R. (2015, March 20). Menstrual blood is more than a stain. Now it's art, verse and protest. _Daily O._ Retrieved from:[http://www.dailyo.in/lifestyle/du-jamia-women-india-sexism-menstruation-blood-art-culture/story/1/2669.html](http://www.dailyo.in/lifestyle/du-jamia-women-india-sexism-menstruation-blood-art-culture/story/1/2669.html)
2.  Bystrom, E. A. (2012, May 17). There will be blood \[Photo series\]. _Vice_. Retrieved from: [http://www.vice.com/en\_au/read/there-will-be-blood](http://www.vice.com/en_au/read/there-will-be-blood)
3.  Carmen. (2011, April 15). “Corrective Rape” in South Africa: Not getting better. _Autostraddle_. Retrieved from:[http://www.autostraddle.com/corrective-rape-still-a-thing-and-still-not-a-hate-crime-85097/](http://www.autostraddle.com/corrective-rape-still-a-thing-and-still-not-a-hate-crime-85097/)
4.  Frank, P. (2015, May 5). Artist explores the unexpected beauty of menstrual blood using macrophotography. _The Huffington Post._ Retrieved from: [http://www.huffingtonpost.com/2015/05/05/jen-lewis-beauty-in-blood\_n\_7205908.html](http://www.huffingtonpost.com/2015/05/05/jen-lewis-beauty-in-blood_n_7205908.html)
5.  Gray, E. (2012, May 18). Menstruation taboo challenged by VICE 'There will be blood' series (PHOTOS). _The Huffington Post._ Retrieved from: [http://www.huffingtonpost.com/emma-gray/menstruation-taboo-vice-there-will-be-blood-photos\_b\_1528826.html](http://www.huffingtonpost.com/emma-gray/menstruation-taboo-vice-there-will-be-blood-photos_b_1528826.html)
6.  Hecht, M. (2012, March 28). Sm{art}: 5 menstrual blood artists / projects worth seeing. _Bitchmedia._ Retrieved from:_[https://bitchmedia.org/post/smart-menstrual-blood-art-feminism](https://bitchmedia.org/post/smart-menstrual-blood-art-feminism)_
7.  Jamie. (2012, February 20). Artist attack! Zanele Muholi boldly archives the difficult love of South Africa's Black lesbian community._Autostraddle._ Retrieved from:  [http://www.autostraddle.com/artist-attack-zanele-muholi-13277/](http://www.autostraddle.com/artist-attack-zanele-muholi-13277/)
8.  Lapekas, J. (Interviewer) & Tiegs, V. (Interviewee). (n.d.). _An interview with Vanessa Tiegs by Jenny Lapekas_ \[Interview transcript\]. Retrieved from: [http://www.vanessatiegs.com/creations/menstrala/](http://www.vanessatiegs.com/creations/menstrala/)
9.  Levy, S. (September 16, 2015). Who made Donald Trump go red in the face? \[Web log comment\]. Retrieved from:[http://socialistworker.org/2015/09/16/who-made-trump-go-red-in-the-face](http://socialistworker.org/2015/09/16/who-made-trump-go-red-in-the-face)
10.  Ogden Trotta, S. (2013, February 10). 5 Reasons why menstruation is awesome (Despite what we're told) \[web log post\]. _Everyday Feminism._ Retrieved from: [http://everydayfeminism.com/2013/02/menstruation-is-awesome/](http://everydayfeminism.com/2013/02/menstruation-is-awesome/)
11.  Rawlinson, K. (2015, March 3). “India's Daughter: Delhi gang-rape film airs early on BBC following objections”. _The Guardian._ Retrieved from: [http://www.theguardian.com/world/2015/mar/05/delhi-gang-rape-documentary-airs-early-on-bbc-following-objections](http://www.theguardian.com/world/2015/mar/05/delhi-gang-rape-documentary-airs-early-on-bbc-following-objections)
12.  Tiegs, V. (n.d.). _Menstrala_ (Weblog)_._ [http://menstrala.blogspot.ca/](http://menstrala.blogspot.ca/)
13.  UN (n.d.). “In brief: Safe cities global initiative”. _UN Women._ Retrieved from:[http://www.unwomen.org/~/media/headquarters/attachments/sections/library/publications/2013/12/un%20women-evaw-safecities-brief\_us-web%20pdf.ashx](http://www.unwomen.org/~/media/headquarters/attachments/sections/library/publications/2013/12/un%20women-evaw-safecities-brief_us-web%20pdf.ashx)

#### Decolonise your body! The fascinating history of M?ori and periods

[](https://thespinoff.co.nz/author/leonie-hayden/ "View all posts by Leonie Hayden")  April 17, 2019 Accessed August 05, 2020 

[https://thespinoff.co.nz/atea/17-04-2019/decolonising-your-body-maori-attitudes-to-periods/?fbclid=IwAR1Pf37WoHpantiH30diCO5s5s4C\_3e0KfOLEgSkeOm6\_6y0krRfmO\_KvzA](https://thespinoff.co.nz/atea/17-04-2019/decolonising-your-body-maori-attitudes-to-periods/?fbclid=IwAR1Pf37WoHpantiH30diCO5s5s4C_3e0KfOLEgSkeOm6_6y0krRfmO_KvzA)

A lot of knowledge has been lost about traditional M?ori attitudes to menstruation, but some extraordinary M?ori women are making sure it's not lost forever.

See the YouTube video [https://www.youtube.com/watch?time\_continue=9&v=sHhUAxuwO6Y&feature=emb\_logo](https://www.youtube.com/watch?time_continue=9&v=sHhUAxuwO6Y&feature=emb_logo)


## Journal Activity - A.5.4 Menstrual Taboo Literature Review {.unnumbered}

#### Menstrual Taboo Literature Review: Modern Menstrual Taboos {.unnumbered}

After completing the Required Reading for Unit A Section 5, consider which piece of literature inspires you most strongly to respond. 

2. Museum of Menstruation and Women's Health [mum.org](http://www.mum.org/)
    
3. [The menstruation taboo](https://www.youtube.com/watch?v=jH1sh7aU-mk) Diana Fabianova at TEDxBratislava 2013: (click on the CC button at the bottom right to see the English subtitles)
    
4. [A Taboo-Free Way to Talk about Periods](https://www.ted.com/talks/aditi_gupta_a_taboo_free_way_to_talk_about_periods?language=en) Aditi Gupta at TedxGateway Women May 2015
5. [Decolonising your body: Maori attitudes towards menstruation](https://thespinoff.co.nz/atea/17-04-2019/decolonising-your-body-maori-attitudes-to-periods/?fbclid=IwAR1Pf37WoHpantiH30diCO5s5s4C_3e0KfOLEgSkeOm6_6y0krRfmO_KvzA) Leonie Hayden April 17, 2019
6. [Menstrual Hygiene Management: A taboo that must be broken!](https://www.ted.com/talks/aditi_gupta_a_taboo_free_way_to_talk_about_periods?language=en) blog by Anupma Jain, Senior Social Sector Specialist. June 06, 2013.

Using your choice of the above readings, comment on what you understand are the modern menstrual taboos that persist, despite the current menstrual rhetoric and socio-political actions to de-taboo menstruation. 

Comment on what disturbs you most personally. If you were the leader of the world, what changes might you make regarding menstrual taboos. How might you reframe menstrual practices to be constructive and healthful. 

----

## 5.5 - Conclusion {.unnumbered}

Our walk through this section, though not definitive, has called your attention to the variety of social and religious perceptions and responses to menstruation, and in particular rituals of purification. What we do and say about menstruation, when done so regularly may itself become a ritual,that reflects out own attitudes towards woman's blood. It has been the purpose of this section to invite the HRHP into reflection about their own attitudes towards menstruation, and to be open minded to those of others. Every woman's historical and ancestral attitudes towards menstruation and her fertile body, that is capable of producing a living person, shape her attitudes towards her body and self-concept.


## Journal Activity - Unit A Reflections {.unnumbered}

Now that you have come to the end of the unit, please take a moment to reflect on Unit A. Provide a brief answer (1-2 sentences) to the following questions:

1.  Which of the readings did you appreciate most and why?
2.  Which of the readings did you least appreciate and why?
3.  Which of the journals was most useful to your learning process and why?
4.  Which of the journals was least useful to your learning process and why?
5.  Is there a book, article, journal paper, podcast, or video that is not included in the Unit A curriculum but which you have found beneficial to your understanding of the topics in Unit A? If so, please share it here.
6.  Is there anything else you would like to share about your feedback on this unit?

Lastly, if you would like your feedback to be acted on by the college, please **choose one or more of the above pieces of constructive feedback** and share them in our [curriculum feedback form](https://docs.google.com/forms/d/e/1FAIpQLSdEDwTn_2awBl-y147dDm4zDtHIsUR3A42SiWgvtw6AKufDJw/viewform).