# (PART\*) Unit B: Human Sexuality {.unnumbered}

# Overview {.unnumbered}

## 1.1 - Overview {.unnumbered}

**Please Review [Exam, Essay, and Journal Policies](https://justisse.ca/index.php/college/courseware/page/1646)** {.unnumbered}

**You are responsible to conduct yourself with academic honesty.** {.unnumbered}

## Section 1 Syllabus {.unnumbered}

**For Unit B: Author: Geraldine Matus (2003) 2017. Editorial Revisions: Laura Salamanca 2015. Justisse Faculty Collaborative 2014 to date.**

**SUGGESTED TIME TO COMPLETION: 6 to 8 weeks to complete**

### _SEX:  Too much information -- Too little understanding_. {.unnumbered}

_Unable to sleep one night, I thought I'd soothe myself with a late-night movie on Canada's artful_ Showcase _channel. I turned on (no pun intended) to what appeared to be a friendly family scene of husband and wife at breakfast together. However, as she was absorbed in the morning paper, he was groping the lean and lengthy leg of a scantily clad maid.  “Oh, man, is he in trouble,” I thought.  Wrong.  Next thing ya know, the wife snaps to attention only to focus on the maid; both take off their clothes and roll around together on an adjacent mat. Believe it or not, the plot thins. Lots of breathy encounters of the sexual kind, very little discernable dialogue._

So, you want a quick close up on what sex is all about? Just turn on the TV. This latest lens to indulge in sexual voyeurism does not't shy away from the naked truth.  But like all the lenses before it -- religious revelations, psychological perspectives, and medical mind sets -- this lens does not't capture what human sexuality is in all of its physical, intellectual and spiritual realms.  And it does not't even pay lip service to the awesome diversity of sexual experience across cultures or, for that matter, from any one individual to the next.  Even the naked truth is just one part of the truth.

As your textbook _Understanding Human Sexuality_ points out, the variations in human sexual behavior are legion. To make matters more complex, we all tend to see the world through our own individual lenses, and our viewpoints on sexuality are no exception to this limitation. (Erotocentricity reigns!)

So as you diligently study this course and search your own soul to strive to learn how to best serve others, and their partners, as a Holistic Reproductive Health Practitioner, you are challenged to wrestle with a huge question:  How do I build a solid foundation of understanding of human sexuality that is fluid enough to allow for understanding, empathy and respect for the viewpoints and reality of others?

Unit B introduces you to the physiological foundations of sexuality as well as the cultural and scientific lenses that have been applied to the study of it.  As you explore the material in this unit of your course, keep an open mind and heart.  Think critically and be aware that all “truths” about human sexuality carry biases. Unit B will explore human sexuality in depth, including diversity and tolerance in society. It will prepare you for understanding the issues you may encounter when serving your clients as an HRHP. It will also develop and understanding of the vastness of the topic and that no single idea or approach serves the sexual needs for all persons. It is important for you to understand human sexuality for your preparation to teach Justisse.

It is important to understand that neither the text, nor the material provided here represent the one truth about human sexuality. It is unavoidably biased by the experience and education of the authors, and by the times and environment we live. You are encouraged to research on your own, develop your own responses, and examine your own biases. Allow yourself to be surprised, outraged, sceptical, curious, and challenged, and you will have fun with this unit.

The Required Text _Understanding Human Sexuality_ provides you with the primary background material you will need for this unit. All required readings for Unit B are listed in the syllabus, as well as throughout the text of the unit sections.

**Unit B contains the following sections:**

Unit B Section 1 Syllabus

Unit B Section 2 Foundations of Human Sexuality

Unit B Section 3 Diversity and Respect

Unit B Section 4 Understanding Sexual Diversity

Unit B Journals

Unit B Evaluation

Essay

Multiple Choice exam

Short Answer exam
