# 1: Syllabus {.unnumbered}

## 1.2 - Learning Objectives {.unnumbered}

### The readings and exercises in this unit of study will help you to: {.unnumbered}

1.  Develop a foundation for understanding how historical and environmental influences affect human sexuality.
2.  Develop a foundation for understanding human sexuality in its myriad expressions.
3.  Prepare a foundation for understanding issues of diversity and tolerance with respect to individual sexuality and its myriad expression.
4.  Develop a foundation for understanding sexual development, and sexual deviations and dysfunctions.
5.  Differentiate between contraceptive and non-contraceptive viewpoints.
6.  Be able to identify the major concerns of the reproductive justice movement.

### After completing the readings and activities in Unit B Section 2, you should be able to: {.unnumbered}

1.  Identify some of the sociological events that have influenced our attitudes toward sexuality.
2.  Identify some of the physiological and psychological aspects of human sexuality and discuss some of the models and theories used to interpret them.
3.  Understand the considerations involved in sexual lifestyle and decision making; and become better acquainted with facets of your own sexual lifestyle.
4.  Distinguish between contraceptive and non-contraceptive viewpoints.
5.  Identify some sexual difficulties, dysfunctions and deviations.

----

## 1.3 - Required Readings {.unnumbered}

###  Unit B Required Reading {.unnumbered}

**All on-line Justisse courseware text is required reading as well as the readings listed below according to unit section.** 

Required reading from Understanding Human Sexuality is accessible on Google Drive. Click on this link: [https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE\_g?usp=sharing](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g?usp=sharing)

### 2.2 Influences of Culture and Society {.unnumbered}

1.  Adams, V., & Pigg, S. L. (2005). [**Introduction: The moral object of sex. In** _**Sex in development: Science, sexuality, and morality in global perspective.**_](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Moral%20Object%20of%20Sex.pdf "Moral Object of Sex") London, UK: Duke University Press. READ ONLY THE INTRODUCTION “Sex in Development examines how development projects around the world intended to promote population management, disease prevention, and maternal and child health intentionally and unintentionally shape ideas about what constitutes “normal” sexual practices and identities. … \[the book\] combines the cultural analysis of sexuality, critiques of global development, and science and technology studies” Download PDF here [Moral Object of Sex](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Moral%20Object%20of%20Sex.pdf)
2.  Women's Rights Movement
    1.  Eisenberg, B., & Ruthsdotter, M. (1998). **[Living the legacy: The women's rights movement (1949 - 1998)](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Eisenberg%20and%20Ruthsdotter.pdf)**  in the USA. (you will be examined on this article\_
    2.  You may also wish to compare the USA women's rights movement with that of your own country or 
3.  If you can obtain it watch the **Netflix movie Elisa y Marcela (2019)**, which is based on a true story that took place in 1901, when Elisa Sanchez Loriga took on the identity of Mario Sánchez to marry her lover of fifteen years, Marcela Gracia Ibeas. Director:  Isabel Coixet Writers: Isabel Coixet (screenplay by), Narciso de Gabriel (based on the literary essay by) Stars:  Natalia de Molina, Greta Fernández, Sara Casasnovas. 
4.  **Timeline of same-sex rights:**
    1.  CBC News. (2012, January 12). Timeline: Same-sex rights in Canada. Retrieved from: **[http://www.cbc.ca/news/canada/timeline-same-sex-rights-in-canada-1.1147516](http://www.cbc.ca/news/canada/timeline-same-sex-rights-in-canada-1.1147516)**
    2.  Alternatively find a site that discusses the timeline for same sex rights in your country or region. If you want to do this please discuss it with your trainer. You may also wish to compare Canada's rights with your country or region.
5.  **Legal recognition of same-sex unions:**
    1. Department of Justice Canada. (2002). Marriage and legal recognition of same-sex unions (A discussion paper). [http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Marriage%20and%20Legal%20Recognition%20of%20Same%20Sex%20Unions.pdf](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Marriage%20and%20Legal%20Recognition%20of%20Same%20Sex%20Unions.pdf)
    2. Schneider, B. (2003, June 20). Canada acts on same-sex marriages. CNN.com/Inside Politics. Retrieved from:[http://www.cnn.com/2003/ALLPOLITICS/06/20/ip.pol.opinion.canada.marriages/](http://www.cnn.com/2003/ALLPOLITICS/06/20/ip.pol.opinion.canada.marriages/)   
    3.  Alternatively find a site that discusses legal recognition of same-sex rights in your country or region. If you want to do this please discuss it with your trainer. You may also wish to compare Canada's rights with your country or region.
6.  Lunman, K. (2003, August 2). Priests carry same-sex attack to pulpit. The Globe and Mail. Retrieved from: **[http://www.theglobeandmail.com/news/national/priests-carry-same-sex-attack-to-pulpit/article1164774/](http://www.theglobeandmail.com/news/national/priests-carry-same-sex-attack-to-pulpit/article1164774/)**  
7.  History of HIV/AIDS. Canadian Foundation for AIDS Research. Retrieved from: [https://canfar.com/awareness/about-hiv-aids/history-of-hiv-aids/](https://canfar.com/awareness/about-hiv-aids/history-of-hiv-aids/)
8.  Sexual Orientation Rights
9.  1.  A Brief History of Sexual Orientation Rights in Canada -- [A Brief Canadian History of Laws-Gay Right](http://www.justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/A%20Brief%20Canadian%20History%20of%20Laws-Gay%20Rights.pdf)
    2.  Alternatively find a site that discusses sexual orientation rights in your country or region. If you want to do this please discuss it with your trainer. You may also wish to compare Canada's rights with your country or region.

### 2.3 Sex and Gender Identity {.unnumbered}

### 2.4 Theories and Research {.unnumbered}

1.  _[How to Lie With Statistics](http://www.horace.org/blog/wp-content/uploads/2012/05/How-to-Lie-With-Statistics-1954-Huff.pdf)_ by Darrell Huff.
2.  [Kinsey: Let's Talk About Sex (The Film)](https://en.wikipedia.org/wiki/Kinsey_(film)) Movie Trailer [https://www.youtube.com/watch?v=5UxVz4tn7ZA](https://www.youtube.com/watch?v=5UxVz4tn7ZA) It is worth watching.

### 2.5 Sexual Response {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 9: The physiology of sexual response. In Understanding human sexuality (3rd ed.) (pp. 247 - 270). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 10: Techniques of arousal and communication. In Understanding human sexuality (3rd ed.) (pp. 271 - 304). Toronto, ON: McGraw-Hill Ryerson.

### 2.6 Sexuality and the Life Cycle {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 11: Sexuality and the life cycle: Childhood and adolescence. In _Understanding human sexuality_ (3rd ed.) (pp. 305 - 333). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 12: Sexuality and the life cycle: Adulthood. In _Understanding human sexuality_ (3rd ed.) (pp. 334 - 366). Toronto, ON: McGraw-Hill Ryerson.

### 3.3 Relationships and Sexual Expression {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 13: Attraction, intimacy, and love. In _Understanding human sexuality_ (3rd ed.) (pp. 367 - 390). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 15: Sexual orientation: Gay, lesbian, bi, or straight? In _Understanding human sexuality_ (3rd ed.) (pp. 418 - 451). Toronto, ON: McGraw-Hill Ryerson.
3.  [Ulanov: Fear of the Feminine](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Ann%20Ulanov%20Fear%20of%20the%20Feminine.pdf) an excerpt
4.  Matus, G. (2014) "Clarifying the use of the terms feminine and masculine" [In World's geography of love](https://www.academia.edu/23239183/WORLDS_GEOGRAPHY_OF_LOVE_AN_ALCHEMICAL_HERMENEUTIC_INQUIRY_INTO_THE_HEROIC_MASCULINES_REBIRTH_AS_INFLUENCED_BY_LOVE_AS_THE_GLUTINUM_MUNDI_AND_THE_FEMININE_INCORPORATIO). 

### 3.4 Contraceptive and Non-Contraceptive Viewpoints {.unnumbered}

1.  Religious Coalition for Reproductive Choice **[http://www.rcrc.org/](http://www.rcrc.org/)**
2.  Catholics for Choice **[http://www.catholicsforchoice.org](http://www.catholicsforchoice.org/)**
3.  International Technical Guidance on Sexuality Education: An evidence-informed approach, UNESCO 2018 in collaboration with UNAIDS, UNFPA, unicef, UNWomen, and World Health Organization. Take a quick look through the Download here: [https://www.who.int/publications/m/item/9789231002595](https://www.who.int/publications/m/item/9789231002595) 
4.  How I Lost Faith in the Pro-Life Movement [http://www.patheos.com/blogs/lovejoyfeminism/2012/10/how-i-lost-faith-in-the-pro-life-movement.html](http://www.patheos.com/blogs/lovejoyfeminism/2012/10/how-i-lost-faith-in-the-pro-life-movement.html) 
5.  Baker, Aspen (2015). **_ProVoice: How to Keep Listening When the World Wants a Fight._** Oakland: Berrett Koehler. Chapter 1 and 2.
    1.  **Aspen Baker's **TedX Talk** [A Better Way to Talk About Abortion](https://www.youtube.com/watch?v=P5Mpo4JQZhw&t=1s).**

### 3.5 Sexuality and Birth Control {.unnumbered}

### 3.6 Sexual Difficulties, Dysfunctions, and Deviations  {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 16: Variations in sexual behaviour. In _Understanding human sexuality_ (3rd ed.) (pp. 453 - 477). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 17: Sexual coercion. In _Understanding human sexuality_ (3rd ed.) (pp. 478 - 508). Toronto, ON: McGraw-Hill Ryerson.
3.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 19: Sexual disorders and sex therapy. In _Understanding human sexuality_ (3rd ed.) (pp. 537 - 566). Toronto, ON: McGraw-Hill Ryerson.

----

## 1.4 - Comparative Readings {.unnumbered}

The following readings are meant to provide material that you may compare and contrast with the required test _Understanding Human Sexuality_ (2006). You will not be tested on these readings, but we strongly suggest that you review them as possible resources for the future, and to see how they might differ in tone and intent from the required text. 

1.  Unit B Section 2.1 Influences of Culture and Society
    1.  The Boston Women's Health Book Collective. (2011). Chapter 6: Social influences on sexuality. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 140 - 152). New York, NJ: Touchtone. Hailed by _The New York Times_ as a “feminist classic,” and “America's bestselling book on women's health,” the comprehensive guide to all aspects of women's health and sexuality, including menopause, birth control, childbirth, sexual health, sexual orientation, gender identity, mental health and general well-being. Six years after the 2005 overhaul of this classic guide to women's health, the 2011 edition focuses on what _Our Bodies, Ourselves_ does best: provide information on women's reproductive health and sexuality; practical information on how find and access health information; and resources, stories, and information to educate women about health care injustices and inspire them to work collectively to address them. This new edition of _Our Bodies, Ourselves_ includes the latest vital information on: • Changes in the health care system—especially how health care reform affects women and how to get the care you need. • Safer sex—how to engage in pleasurable, satisfying sexual experiences while protecting your health and the health of your partner.• Environmental health risks—including minimizing exposure to everyday pollutants that endanger reproductive health. • Body image—resisting negative media stereotypes and embracing healthier approaches to looking and feeling good.• Local and global activism—using social media and organizing tactics to build community and advocate for policies that improve women's lives.• As well as crucial information about gender identity, sexual orientation, birth control, abortion, pregnancy and birth, perimenopause, and sexuality and sexual health as we age.Together with its companion website, [ourbodiesourselves.org](https://www.ourbodiesourselves.org/), _Our Bodies, Ourselves_ is a one-stop resource for women of all generations. (Amazon.com) 
2.  Unit B Section 2.2 Sex and Gender Identity
    1.  The Boston Women's Health Book Collective. (2011). Chapter 4: Gender identity and sexual orientation. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 72 - 96). New York, NJ: Touchtone. 
3.  Unit B Section 2.4 Human Sexuality: Physiological Response.
    1.  The Boston Women's Health Book Collective. (2011). Chapter 7: Sexual pleasure and enthusiastic consent. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 153 - 180). New York, NJ: Touchtone.
4.  Unit B Section 2.5 Sexuality and the Life Cycle
    1.  The Boston Women's Health Book Collective. (2011). Chapter 20: Perimenopause and Menopause. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 505 - 546). New York, NJ: Touchtone.
    2.  The Boston Women's Health Book Collective. (2011). Chapter 21: Our later years. In _Our bodies: Ourselves_ (pp. 547 - 583). New York, NJ: Touchtone.
    3.  Kitzinger, S. (1985). _Woman's experience of Sex: The facts and feelings of female sexuality at every stage of life_. Harmondsworth, Middlesex, England: Penguin. Far more than a "how-to" manual or an ABC of sex, this comprehensive book covers the full range of female sexuality. Kitzinger writes about sex in the context of real life, women's feelings about themselves and their bodies, and the many difference dimensions of sexual experience. (Amazon.com)
5.  Unit B Section 3.2 Relationships and Sexual Expression
    1.  The Boston Women's Health Book Collective. (2011). Chapter 5: Relationships. In _Our Bodies Ourselves: Completely Revised and Updated_. (pp. 99 - 139). New York, NJ: Touchtone.
6.  Unit B Section 3.4 Sexuality and Birth Control
    1.  Granzow, K. (2007). De-constructing 'choice': The social imperative and women's use of the birth control pill. In _Culture, Health & Sexuality, 9_(1): 43- 54. OR (2008). The imperative to choose: A qualitative study of women's decision-making and use of the birth control pill. In _Social Theory & Health, 6_: 1 - 17.
    2.  The Boston Women's Health Book Collective. (2011). Chapter 9: Birth Control. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 201 - 256). New York, NJ: Touchtone.
    3.  Boyd, Jay. [Natural Family Planning: Trojan Horse in the Catholic Bedroom?](https://www.amazon.ca/Natural-Family-Planning-Catholic-Bedroom/dp/1482570394/ref=mp_s_a_1_15?adgrpid=62789550924&gclid=CjwKCAjw9dboBRBUEiwA7VrrzQIUgN9i7XNWzWeI4f1an11aXFcN5H_d9tW-66bqjySpR7Q1vfCKVxoC4s4QAvD_BwE&hvadid=310044156431&hvdev=m&hvlocphy=9061281&hvnetw=g&hvpos=1t2&hvqmt=b&hvrand=12183873933397565153&hvtargid=kwd-20632381&hydadcr=8068_9619792&keywords=fertility+awareness+method&qid=1561718737&s=gateway&sr=8-15) Dr. Boyd argues that NFP dissuades couples from trusting divine providence, and practicing marital chastity. She takes a fundamentalist Roman Catholic view of birth control and marital sex.
7.  1.  The Boston Women's Health Book Collective. (2011). Chapter 8: Sexual Challenges. In _Our Bodies Ourselves: Completely Revised and Updated_.  (pp. 181 - 197). New York, NJ: Touchtone.
    2.  Greer, G (1985). _Sex and destiny: The politics of human fertility_. New York, Harper and Row.
    3.  Lindenbaum, S. (1984, April 29). Getting the world in a family way. _The New York Times: Books._ Retrieved from: [https://www.nytimes.com/books/99/05/09/specials/greer-fertility.html](https://www.nytimes.com/books/99/05/09/specials/greer-fertility.html)
    4.  Mutrux, G. (Producer), & Bill Condon (Director). (2004). _Kinsey_ \[motion picture\] United States, Fox Searchlight Pictures._Kinsey_ is a 2004 American biographical drama film written and directed by Bill Condon. It describes the life of Alfred Charles Kinsey (played by Liam Neeson), a pioneer in the area of sexology. His 1948 publication, _Sexual Behavior in the Human Male_ (the first of the Kinsey Reports) was one of the first recorded works that tried to scientifically address and investigate sexual behaviour in humans. The film also stars Laura Linney (in a performance nominated for the Academy Award for Best Supporting Actress), Chris O'Donnell, Peter Sarsgaard, Timothy Hutton, John Lithgow, Tim Curry, and Oliver Platt.
    5.  Schalet, A. T. (2004). Must we fear adolescent sexuality? _MedGenMed 6_(4), 44. [http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1480590/](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1480590/)
    6.  Schalet, A. T. (2011). _Not under my roof: Parents, teens, and the culture of sex._ Chicago, IL: The University of Chicago Press.For American parents, teenage sex is something to be feared and forbidden: most would never consider allowing their children to have sex at home, and sex is a frequent source of family conflict. In the Netherlands, where teenage pregnancies are far less frequent than in the United States, parents aim above all for family cohesiveness, often permitting young couples to sleep together and providing them with contraceptives. Drawing on extensive interviews with parents and teens, "Not Under My Roof" offers an unprecedented, intimate account of the different ways that girls and boys in both countries negotiate love, lust, and growing up. Tracing the roots of the parents' divergent attitudes, Amy Schalet reveals how they grow out of their respective conceptions of the self, relationships, gender, autonomy, and authority. She provides a probing analysis of the way family culture shapes not just sex but also alcohol consumption and parent-teen relationships. Avoiding caricatures of permissive Europeans and puritanical Americans, Schalet shows that the Dutch require self-control from teens and parents, while Americans guide their children toward autonomous adulthood at the expense of the family bond. (Amazon.com)

           8. Unit B Section 3: Diversity and Respect

1.  Chattopadhyay, P. (2019, September 27). _Out In The Open_ \[Audio Podcast\]. Retrieved from [https://www.cbc.ca/listen/live-radio/1-131-out-in-the-open/clip/15738149-120-mona-eltahawys-seven-necessary-sins](https://www.cbc.ca/listen/live-radio/1-131-out-in-the-open/clip/15738149-120-mona-eltahawys-seven-necessary-sins)
2.  Moran, Caitlin. (2011). _How To Be A Woman_. New York: HarperCollins.
3.  Ross, Loretta & Solinger, Rickie. (2017). _Reproductive Justice: An Introduction_. Oakland: University of California Press

----

## 1.5 - Unit B Final Evaluation {.unnumbered}

### The final evaluation for Unit B includes {.unnumbered}

You are responsible to conduct yourself with academic honesty.

### Unit B Journals {.unnumbered}

**NOTE:** Each journal is embedded in the section of courseware literature that is relevant to that journal. Do the journals as they appear in the literature you are reading. Do not do them in numerical order.

-   [Journal # 1 B4.1 Tolerance and Diversity Self Survey](https://justisse.ca/index.php/college/ad_courseware/page/1615)
-   [Journal # 2 B4.1 Understanding the McGarrys](https://justisse.ca/index.php/college/ad_courseware/page/1615)
-   [Journal # 3 B4.1 Sexual Purity Test](https://justisse.ca/index.php/college/ad_courseware/page/1615)
-   [Journal # 4 B2.2 Sleeping With the McGarrys](https://justisse.ca/index.php/college/ad_courseware/page/1045)
-   [Journal # 5 B3.3 Coming Out](https://justisse.ca/index.php/college/ad_courseware/page/1053) 
-   [Journal # 6 B3.3 Sexual Identity, Orientation, and Expression](https://justisse.ca/index.php/college/ad_courseware/page/1053)
-   [Journal # 7 B2.4 Different Views about Sex](https://justisse.ca/index.php/college/ad_courseware/page/1046)
-   [Journal # 8 B3.4 Our Fertility, Our Ideologies](https://justisse.ca/index.php/college/ad_courseware/page/1616)
-   [Journal # 9 B3.4 Listening When the World Wants to Fight](https://justisse.ca/index.php/college/ad_courseware/page/1616)
-   [Journal # 10 B3.4 Dominion Over "Life"](https://justisse.ca/index.php/college/ad_courseware/page/1616)
-   [Journal # 11 B 3.5 Shared Responsibility](https://justisse.ca/index.php/college/ad_courseware/page/1617)
-   [Journal # 12 B3.5 Unplanned Pregnancy](https://justisse.ca/index.php/college/ad_courseware/page/1617)
-   [Journal # 13 B3.5 Your Style of Communication with Your Partner](https://justisse.ca/index.php/college/ad_courseware/page/1617)
-   [Journal # 14 B2.6 Sexuality in My Lifespan](https://justisse.ca/index.php/college/ad_courseware/page/1048)
-   [Journal # 15 B2.6 Sex and Older Adults](https://justisse.ca/index.php/college/ad_courseware/page/1048)
-   [Journal # 16 B3.6 Sex Positive and Consent](https://justisse.ca/index.php/college/ad_courseware/page/1618) 

### Multiple Choice and Short Answer Exams {.unnumbered}

Do not open up the multiple choice or short answer exam until you are ready to take it.

-   multiple choice exam: 50 questions with 100 minutes to complete
-   short answer exam: 40 questions with 120 minutes to complete

----

## 1.6 - Unit B Essay Topics {.unnumbered}

### Unit B Essay Topics {.unnumbered}

Discuss what essay you want to write with your trainer before you begin researching and writing. **Only open up the essay in the courseware when you are ready to submit it.**

Choose **one** essay topic from the six topics listed below. Write a 3 to 5-page essay (about 500 words per page). Be concise. Provide rationale for your ideas and enrich your work with examples,metaphors, or allegories to illustrate your main points. Please include citations where you directly or indirectly present the ideas others. Choose themes that can be treated in this size of an essay. If your proposed topic seems like it could be a book, then narrow it down to one elements of the topic, or part of an element. Lengthiness only matters if it has substance. If none of the topics suit you, you may request, in a formal letter, consideration of an essay topic of your choosing. A topic of your choosing must be relevant to this unit.

1.  How does the increased focus on gaining freedom for individual expression of sexuality change the collective idea of human sexuality?
2.   In general, how might sexual dysfunction be related to psychosocial issues?
3.  Develop your own model of sexual response or human sexuality;support your ideas soundly.
4.  Create a dialog between two persons with respect to choosing a contraceptive. Have them address in their dialog at least 6 factors addressed in both Sections 3.4 and 3.5  regarding contraceptive and non-contraceptive viewpoints and choosing a contraceptive. Then create your own comments about the couple's dialog with respect to how might their choice have been influenced by religious, spiritual, and/or cultural factors. What unconscious or uneducated factors might be at play?
5.  Research the relationship between sexual dysfunction and either one of the following: 3 prescription drugs; 3 non-prescription or street drugs; or 3 medical conditions.
6.  Create a mock seminar or in-service of approximately 10 to 20 minutes for either the caregivers of the elderly OR for the elderly themselves about the expression of sexuality in the elderly.
7.   What do you understand about what makes a healthy sexual relationship, and in practical terms how might sexual partners achieve that?
8.  In chapter 3 of pro-voice, Baker reflects on the gendered aspects of different types of political action and how non-violent political action might reinforce certain stereotypes about femininity and passivity.  Listen to this [CBC interview](https://www.cbc.ca/radio/outintheopen/i-want-patriarchy-to-fear-women-mona-eltahawy-says-the-time-for-being-civil-peaceful-and-polite-is-over-1.5296597) with queer feminist and activist Mona Eltahawy and make a case for or against the use of “justifiable violence” in the fight against patriarchy.

### Format {.unnumbered}

1.  Use APA publication manual 7th ed.to cite references, format quotes, create a bibliography, etc.
2.  Document needs to be either a PC compatible Word document or a plain text file
3.  Use a 12 pt font, preferably with serifs, like Courier or Times New Roman
4.  Double space text 5.Page margins - 1” top and bottom: 1.25” left and right

### Breakdown of essay evaluation 100 points {.unnumbered}

-   format = 20
-   support & rationale for ideas = 30
-   organization & development  = 25
-   originality & imagination = 25
