# 3: Diversity and Respect {.unnumbered}

## 3.1 - Introduction {.unnumbered}

An anthropological study undertaken by Ford and Beach in 1951 concluded that there is such wide variation in sexual behavior between cultures that it is virtually impossible to find one global “norm” \[1\] \[2\]. However, the human phenomenon of **erotocentricity** causes a person to assume that their sexual beliefs are “normal” and therefore unanimously held by those around them. It is always a challenge for a person to discover that it might be otherwise \[3\].

Western society's accepted sexual “norm” (heterosexual, patriarchal), does not represent the practices of all people.  Those whose sexuality falls outside the established hegemonic “norm” frequently suffer discrimination and ridicule—to the detriment of their overall well-being.

The nature of fertility awareness education and holistic reproductive health care always places the HRHP in close proximity to their client's concerns regarding sexuality and intimate relationships. It is wise for the HRHP to develop understanding and respect for diversity, and to challenge their own ideas of what is 'normal'.

The objective of Unit B Section 3 is to have you begin an enquiry into your beliefs and attitudes about human sexuality, sexual desire, sexual response, sexual behavior, etc, as well as explore and clarify your values around human sexual expression. Its purpose is to stimulate discussion, rather than to propose what is or is not true. In Unit B Section 3 you will find the following sub-sections:

-   Section 3.1 Witnessing experience
-   Section 3.2 Relationships and Sexual Expression
-   Section 3.3 Contraceptive and Non-contraceptive Viewpoints
-   Section 3.4 Sexuality and Birth Control
-   Section 3.5: Sexual Difficulties, Dysfunctions, and Deviations

### References {.unnumbered}

1.  Anne Bolin & Patricia Whelehan (1999), _Perspectives on human sexuality,_ SUNY Press, p.10
2.  [George P. Murdock](https://en.wikipedia.org/wiki/George_P._Murdock "George P. Murdock") (1974) "Clellan Stearns Ford, 1909-1972," _[American Anthropologist](https://en.wikipedia.org/wiki/American_Anthropologist "American Anthropologist")_, New Series, Vol. 76, No. 1 (Mar., 1974), pp. 83-85
3.  Anne Bolin & Patricia Whelehan (1999), _Perspectives on human sexuality,_ SUNY Press, p.203

----

## 3.2 - Witnessing Experience {.unnumbered}

The expression **_witnessing experience_** refers to a way of being with people who are different from ourselves or from what we expect of others. It is foundational to developing understanding and respect for diversity. Witnessing experience is an elemental part of the compassionate stance towards self and others that fuels the energetic force which supports the continuous unfolding process of human sexuality.

We might find reference to these ideas in psychological theories such as Gestalt, Depth Psychology, Intersubjectivity, Client-Centered-Therapy, Active Listening, Contemplative Dialogue, the Principle of Non-Interference (Buddhism, many North American indigenous Nations, Ancient Egypt), or Contemplative Dialogue, and Non-Violent Communication.

Witnessing experience proclaims itself as a cooperative process of interchange between two individuals or groups who agree to adopt an attitude of respect for the differences between them. Additionally, they agree to willingly witness the process of each other's unfolding sexuality without judgement, without trying to change, or trying to influence the other. Witnessing experience facilitates the seeing, understanding, and supporting of the 'other' and 'self' in the context of the individual's life. It is continuous revelation and interchange between what might be, what is coming to be, and what is-many small buds of developing sexuality coming into full bloom.

The lack of witnessing experience between individuals or groups leads to intolerance, which often leads to persecution. Throughout history, persons pursuing sexual behaviours and interests counter to the established norm (though not deviant) have been oppressed and persecuted. Whether persecution is implicit or explicit, its intention is to interfere with a persons' free expression of their sexuality, and to instill in them fear of personal and social reprisal as a means to coerce them into adopting the norm. Intolerance, violence, and persecution takes place in many expected and unexpected ways.

For example, older adults are often regarded as asexual and treated as if the expression of their sexuality is unnecessary, indulgent, or even deviant. Although aging bodies cause sexual desire to decrease, as well as the capacity to act on that desire, a person's sexuality is much greater than sexual desire, and it is part of human expression throughout the lifespan. People caring for or helping to care for the elderly are often uncomfortable with their expressions of sexuality, and discourage them. Controversy around the sexuality of older adults, particularly in long term care, does not draw a great deal of media attention—though it is a thorny debate among those involved with elder care and support services.

An issue that has received more media attention recently is the fight against transphobia, and violence against transpeople. Trans men and women, and gender non-conforming people are shunned from many parts of society, and denounced by religious and other groups as immoral and inhuman. To be true to one's sexual and gender expression when it is at odds with hegemonic ideas of sexuality and gender is never an easy path. The process of accepting one's individual sexuality requires self-reflection in the context of our hopes, dreams, and desires for sexual expression. It is wise for an HRHP trainee to be gain awareness of as many as possible different expressions of sexuality in order to better understand and support their clients' choices.

The HRHP is encouraged to always undertake their own research regarding issues of sexuality as such issues arise in their practice, especially when encountering a client they feel they cannot compassionately serve. It is of utmost importance to be responsible; for HRHPs to clarify their values, accept their limitations, as well as provide support and referrals in a non-judgmental and anti-oppressive manner. The development of understanding and respect of difference, and an attitude of witnessing experience, takes time, practice, and patience with self and others. However, is not to say that all sexual inclinations are healthy. At the center of any positive sexual relationship is consent - if this does not exist, the sexual behavior in question is immoral and should be addressed.

----

## 3.3 - Relationships and Sexual Expression {.unnumbered}

The defining parameters of what are considered normal sexual and erotic behaviors vary widely between societies, and according to individual beliefs. They are shaped by prevailing social, religious, and cultural hegemonic norms. For example, although **heterosexuality** (sexual orientation toward persons of the opposite gender) is most common among people, yet it is not the preference of all. Many persons are **homosexual** (experience sexual orientation toward persons of the same sex or gender) or **bisexual** (experience sexual orientation toward persons of both genders) or **asexual** (do not feel sexual attraction to other people). 

Differences in sexual orientation often instigate prejudice and violence. For example, many people regard homosexuality or bisexuality as abnormal or deviant, and demonstrate irrational fear, contempt, or negative attitudes and reactions to homosexual or bisexual behaviors - **homophobia** or **biphobia** respectively. Those in the helping fields of sexual and reproductive health care and education need to understand gender and sexual orientation diversity, and how this impacts an individual's experience of their sexuality. Every client comes with their own relationship to what is or is not considered 'normal' in our heterosexist society. 

You will find that sexual identity, sexual behaviour, and people's tolerance for diversity in this area are complicated topics. The journal activity for this section will help you reflect and clarify your values regarding sexual diversity. 

### Looking at Diversity Symbolically {.unnumbered}

Looking at the issue of gender, what is female/feminine as so forth it is also important to consider the symbolic relationship humans have to the idea of male, female, hermaphrodites and all the other possible combinations. 

Read Ann Belford Ulanov, [In Receiving Woman - Studies in the Psychology and Theology of the Feminine](https://www.amazon.com/Receiving-Woman-Psychology-Theology-Feminine-ebook/dp/B012Z258DY/ref=sr_1_1?dchild=1&keywords=receiving+woman&qid=1587514854&s=digital-text&sr=1-1) addresses how the fear of the feminine can aggravate issues of sexual diversity. She invites us to think of sexuality symbolically first. See this PDF which has a quote from her book. [Ulanov: Fear of the Feminine](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Ann%20Ulanov%20Fear%20of%20the%20Feminine.pdf) 

Read Matus, G. (2014) ["Clarifying the use of the terms feminine and masculine"](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Matus%20clarify%20fem%20and%20masc.pdf) [In World's geography of love](https://www.academia.edu/23239183/WORLDS_GEOGRAPHY_OF_LOVE_AN_ALCHEMICAL_HERMENEUTIC_INQUIRY_INTO_THE_HEROIC_MASCULINES_REBIRTH_AS_INFLUENCED_BY_LOVE_AS_THE_GLUTINUM_MUNDI_AND_THE_FEMININE_INCORPORATIO). 

### Required reading {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 13: Attraction, intimacy, and love. In _Understanding human sexuality_ (3rd ed.) (pp. 367 - 390). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 15: Sexual orientation: Gay, lesbian, bi, or straight? In _Understanding human sexuality_ (3rd ed.) (pp. 418 - 451). Toronto, ON: McGraw-Hill Ryerson.
3.  [Ulanov: Fear of the Feminine](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitB/Ann%20Ulanov%20Fear%20of%20the%20Feminine.pdf) an excerpt
4.  Matus, G. (2014) "Clarifying the use of the terms feminine and masculine" [In World's geography of love](https://www.academia.edu/23239183/WORLDS_GEOGRAPHY_OF_LOVE_AN_ALCHEMICAL_HERMENEUTIC_INQUIRY_INTO_THE_HEROIC_MASCULINES_REBIRTH_AS_INFLUENCED_BY_LOVE_AS_THE_GLUTINUM_MUNDI_AND_THE_FEMININE_INCORPORATIO). 

### Comparative reading {.unnumbered}

1.  The Boston Women's Health Book Collective. (2011). Chapter 5: Relationships. In _Our bodies: Ourselves_ (pp. 99 - 139). New York, NJ: Touchtone.  

---

## Journal Activity - B3.3 Coming Out  {.unnumbered}

**Coming Out**

Marci McGarry - a single, 23-year old business professional - knew from her early teens that she was sexually attracted to other women. However, as a devout Catholic, Marci believes that her natural inclinations are wrong and must be suppressed. After careful and conflicted thought, Marci decides to “come out of the closet” and let her family know she is a lesbian.

How would you respond if Marci was your daughter or sister?

What biases might you have about her reality?

In what ways could you support her decision to come out?

What resources might you use to discover more about lesbianism, gender fluidity, and other issues of sexual diversity?

Find out what sorts of resources are available in your area and tell your Journal and HRHP Educator.

----

## 3.5 - Sexuality and Birth Control {.unnumbered}

### Choosing a Contraceptive {.unnumbered}

Choosing a method of birth control is both personal and political. Many compelling factors have fueled the search for effective birth control methods throughout recorded history.

Some people use birth control as a political statement, citing certain world issues as their motivating factor. Birth control has been employed in large scales for many political-ideological reasons, including:

-   The belief that global overpopulation is a threat to environmental sustainability
-   The belief that breeding for genetic purity will assure a better human race (eugenics)
-   The belief that smaller families allow for better health and more opportunities for the children that are born - that the exodus from rural to urban centers makes smaller families more economical
-   The belief that limiting pregnancies facilitates women maintaining or gaining greater social freedoms
-   The belief that teenage pregnancies must be prevented
-   Other changes in collective psycho-social-spiritual belief systems

Keeping in mind that the personal is also political, many people chose birth control for what they would describe as personal reasons. For example, they use birth control to limit family size, temporarily prevent pregnancy, or remain childless for economic, health, or lifestyle reasons. Regardless, a person's decision to use birth control and their choice of birth control varies according to his or her religious, spiritual, and cultural upbringing, access to health services, ability to afford birth control, etc. Ultimately, the decision to use birth control is a personal one, significantly influenced by individual psychosocial and physiological factors that in turn are shaped by the socio-political context. Factors that influence a person's choice of birth control method include: 

-   Appropriateness for reproductive age
-   Appropriateness for reproductive health and individual physiology
-   Individual acceptability
-   Cost & availability
-   Understanding of and familiarity with correct use
-   Ability to use a particular method
-   Appropriateness of method for individual lifestyle
-   Length of time the method will be used
-   Willingness to experience side effects
-   Appropriateness with respect to the individual's philosophical, psychological, cultural, and religious orientation  

You will be deepening into this topic in [Unit D Section 13: Sexual Health Counselling](https://justisse.ca/index.php/college/courseware/page/1723)

### Birth Control and Shared Responsibility {.unnumbered}

The responsibility for birth control (for example, discussion about type and cost) is best shared between sexual partners. However, most modern contraceptive methods are designed for use by women. There are two methods used by men: the external condom and male sterilization\[1\]. In the majority of cases, women assume and/or initiate responsibility for contraception, even when it involves the use of the condom or male sterilization. Couples who openly discuss their birth control needs with one another are more likely to have a satisfying sexual relationship. Couples who avoid this discussion because they feel awkward broaching it (or for other reasons) often run into significant difficulties later if they experience unplanned pregnancy or sexually transmitted infection. There are many ways that partners may address contraception, including:

-   Asking about what methods their partner uses (before intercourse)
-   Reading and discussing options together
-   Attending classes or health clinics together to discuss contraception with a qualified professional
-   Sharing costs and helping each other become accustomed to using their method of choice

Your role as a Holistic Reproductive Health Practitioner will be to help initiate dialogue between partners, support their awareness around the choices they make, and encourage the mutual support of each other's decisions and needs with respect to contraception.

###  Comparative Readings {.unnumbered}

1.  Granzow, K. (2007). De-constructing 'choice': The social imperative and women's use of the birth control pill. In _Culture, Health & Sexuality, 9_(1): 43- 54. OR (2008). The imperative to choose: A qualitative study of women's decision-making and use of the birth control pill. In _Social Theory & Health, 6_: 1 - 17.  
2.  The Boston Women's Health Book Collective. (2011). Chapter 9: Birth Control. In _Our bodies: Ourselves_ (pp. 201 - 256). New York, NJ: Touchtone.



## Journal Activity - B 3.5 Shared Responsibility {.unnumbered}

### Shared Responsibility {.unnumbered}

Michael's girlfriend, Linda, wants to go on the birth control pill in order to protect herself from an unwanted pregnancy. Michael is strongly opposed to this, as artificial birth control is explicitly prohibited by the Catholic Church. Linda, however, feels this argument is hypocritical, as they are having premarital sex. Linda confided in Angela, who supports her son's view wholeheartedly. However, Maggie, Michael's grandmother, told Angela she's not being fair to Linda - and that she should listen to both points of view with an open mind. Consider for your Journal: Is either Linda or Michael correct in this situation? Or do they both need help in developing a contemplative dialogue with each other? If the couple approached you, how would you respond? Would your response be different if they approached you individually, or together? 

----

## 3.6 - Sexual Difficulties, Dysfunction, and Deviations {.unnumbered}

Whether watching television, listening to the radio, surfing the web, or viewing a movie, we are deluged with romanticized and idealized images of human sexual relations. These media representations set the sexual-expectation bar quite high in Western society. Consequently, this often skews individual expectations or perceptions of sexual performance and relations to unrealistic proportions. Many couples do have sexual experiences similar to those portrayed in the media but, just as often, their experiences are much less than ideal.

Commonly, couples will experience occasional difficulties in their sexual encounters. Sexual difficulties tend to affect one of three phases of the sexual cycle: desire, arousal, or orgasm. Not all sexual difficulties become sexual dysfunctions. For example, the occasional inability to have an orgasm during sex, although perhaps a difficulty, is a natural occurrence. The difficulty becomes a dysfunction when the person experiences orgasm rarely or not at all and they and/or their partner are distressed by it. A sexual difficulty becomes a **sexual dysfunction** when the difficulty is predominant and interferes with the pleasure of the total sexual experience.

### Common sexual dysfunctions include: {.unnumbered}

1.  **Dyspareunia:** Painful sexual intercourse due to several possible causes, including vaginal infection or dryness, and vaginismus.   
2.  **Vaginismus**: Painful sexual intercourse due to involuntary muscle spasms constricting the vaginal introitus and making penetration painful or difficult.
3.  **Post ejaculatory pain**: Painful involuntary muscle spasms following penile ejaculation by the same muscles that make ejaculation possible.
4.  **Premature ejaculation (PE)**: Penile ejaculation that occurs either just before penetration or very shortly following penetration (most common sexual dysfunction in men)
5.  **Hypoactive sexual desire disorder (HSDD):** Low or impaired sexual desire, which may be related to use of prescription and recreational drugs, perimenopause, menopause, andropause, disease, or chronic illness.
6.  **Erectile disorder (E****D):** Difficulty getting or maintaining an erection.
7.  **Female sexual arousal disorder:** Lack of response to sexual stimulation in women.
8.  **Orgasmic disorder:** The inability to have an orgasm. Called **retarded ejaculation** in men, and **anorgasmia** in women.
9.  **Discrepancy of sexual desire:** One person in the couple desires sexual contact more frequently than the other.

### Prescription Drugs and Sexual Dysfunction {.unnumbered}

Recent research has highlighted the role of prescription drugs in impairing normal sexual functioning. Here are three sites you can check out. Also do some searching on your own.

-   [Sex Drugs and Alcohol Don't Mix](https://web.archive.org/web/20170218080532/http://www.drthemi.com.au/sex-drugs-and-alcohol-taking-care-of-your-mate/)
-   [Drugs That Affect Sexual Function and Response](http://health.howstuffworks.com/sexual-health/sexual-dysfunction/drugs-that-can-affect-sexual-response.htm)
-   [Antidepressants and sex](http://www.biopsychiatry.com/sexndrugs.htm)

There are physiological or psychological treatments available for most sexual dysfunctions, which may include prescription drugs or devices, cognitive-behavioral therapy, couples' therapy, hypnosis, or group therapy. Treatment modalities are varied and we encourage HRHP trainees to find out what is available in their geographical areas in case they need to make referrals. Often sexual difficulties or dysfunctions are related to other relational challenges the couple is facing, and these need to be identified to make sure the couple is referred to the right help. Factors that contribute to sexual difficulties or dysfunctions are physical and psycho-social stress, poor nutrition, existing medical issues, prescription drug use or abuse, alcohol or illicit substance abuse, relational difficulties, or differences in sexual make-up and expectations.

### Sexual Deviations (DSM-IV-TR4th) {.unnumbered}

Some people have sexual desires and exhibit sexual behaviors that vary from the norm and which are not acceptable to the general population. Some of these are associated with a group of psychosexual disorders called **sexual deviations** or **paraphilias.** The diagnostic determination of paraphilias as outlined in the diagnostic criteria manual of the American Psychiatric Association (DSM-IV-TR 4th ed.) states: “The essential features of a paraphilia are recurrent, intense, sexually arousing fantasies, sexual urges, or behaviors involving a nonhuman object, the suffering or humiliation of oneself or one's partner, or children or other non-consenting persons over a period of at least 6 months.” Paraphilias develop out of a person's personal psychology and are influenced by spiritual, religious, social, and/or cultural upbringing.

Some sexual deviations (paraphilias) include:

1.  **Fetishism:** The fetishist is sexually obsessed with objects not typically considered sexual. Their fixation may focus on everything from an aardvark to a Zamboni.
2.  **Exhibitionism:** The exhibitionist is aroused by exposing their naked bodies (particularly their genitals) to others, with or without permission, and without the other person responding mutually.
3.  **Frotteurism (frottage) / toucherism**: The practice of achieving sexual stimulation or orgasm by touching or rubbing against a person without the person's consent, and generally in a public place.
4.  **Voyeurism:** The voyeur is sexually aroused by watching others' involvement in sexual activities.
5.  **Sadomasochism:** The sadomasochist is sexually aroused by experiencing or inflicting pain and/or humiliation.
6.  **Other Sexual Deviations** include necrophilia (sex with dead bodies), bestiality, (sex with animals), and other similarly deviant sexual interests and behaviors.

Here are some links provided by Lisa Leger HRHPE for your further investigation.

1.  Holly Grigg-Spall discusses many side effects of hormonal contraceptives in _Sweetening the Pill_, including depression and mood disorders. [http://www.sweeteningthepill.com/](http://www.sweeteningthepill.com/). You might want to follow her on Twitter and Facebook because she posts some good contemporary commentary on the subject.
2.  Amy Schalet researched attitudes of Dutch and American parents about teen sexuality in **_Not Under My Roof: Parents, Teens and the Culture of Sex_**: [http://www.amyschalet.com/not-under-my-roof-parents-teens-and-the-culture-of-sex/](http://www.amyschalet.com/not-under-my-roof-parents-teens-and-the-culture-of-sex/). _"For American parents, teenage sex is something to be feared and forbidden, and sex is often a source of family conflict. In the Netherlands, where teenage pregnancies are far less frequent than in the United States, parents aim above all for family cohesiveness, often permitting older teenage couples to sleep together and providing them with contraceptives. Probing our child-rearing for what it tells us about our culture, Not Under My Roof offers an unprecedented, intimate account of the ways girls and boys in both countries negotiate sex, love, and growing up."_
3.  Joy Dickson Becker, RN BSN MPH(C): Social Skills Educator/Facilitator/Consultant, is a registered nurse, a certified sexual health educator and a parent of two individuals on the autism spectrum who are now successfully transitioning into adulthood. During her 30 years as a health care educator, facilitator, and consultant, she has become well known for her personable and hands-on approach. Joy has delivered courses and workshops to students, professionals, service providers, community groups, parents, and individuals with special needs. [JDB Associates Consulting](https://www.facebook.com/pg/Awetiszm/about/?ref=page_internal)

### Required reading {.unnumbered}

1.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 16: Variations in sexual behaviour. In _Understanding human sexuality_ (3rd ed.) (pp. 453 - 477). Toronto, ON: McGraw-Hill Ryerson.
2.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 17: Sexual coercion. In _Understanding human sexuality_ (3rd ed.) (pp. 478 - 508). Toronto, ON: McGraw-Hill Ryerson.
3.  Hyde, J. S., DeLamater, J. D., & Byers, E. S. (2006). Chapter 19: Sexual disorders and sex therapy. In _Understanding human sexuality_ (3rd ed.) (pp. 537 - 566). Toronto, ON: McGraw-Hill Ryerson.
  

### Journal Activity - B3.6 Sex Positive and Consent {.unnumbered}

Sex Positive and Consent

What does the phrase "Sex Positive" specifically refer to, and how does "Consent" interplay with being sex positive. Reflect on your personal boundaries about what is and is not okay for you with respect to sexual activity (you do not need to share this). How might your ideas of what is okay and not okay affect your response to a client's sharing of what is okay and not okay with them. If you feel comfortable share an example.
