# 4: Understanding Sexual Diversity {.unnumbered}

# 4.1 - Sexual Diversity Self Survey {.unnumbered}

This test is for your own use only, and does not need to be sent to your trainer. Questions are provided to help you develop a sense of your feelings on this controversial topic. How you feel about these topics and the answers you choose to reflect feelings that are important for you to be aware of as you continue your HRHP studies. Equally important is to attend to how you might feel if a client were to express feelings or opinions in direct opposition to yourself; feelings or opinions that might make you feel uncomfortable, distressed, threatened, or even disgusted. If you would like to discuss these questions with your trainer, you can either send your responses by e-mail, or contact your trainer directly.

Read the following statements carefully, and select the option that most nearly describes your attitude or feeling towards that situation. If more than one choice is relevant, number them in order of your preference.

## Attitudes toward Sexuality {.unnumbered}

1.  Sexual feelings are:
    1.  limited to people under forty.
    2.  limited to people over sixteen.
    3.  are normal and healthy at any age.
    4.  are stronger in men than in women. 
2.  Nudity portrayed on the screen or stage affects you in the following way:
    1.  it offends me and I avoid the production if possible.
    2.  it is acceptable if it is limited to female nudity.
    3.  nudity is acceptable if either sex is seen nude separately.
    4.  it is acceptable if both sexes are nude together, as long as they are not involved in sexual acts.
    5.  I find it acceptable. 
3.  When showering or changing clothes with groups of my own sex:
    1.  I always feel completely at ease.
    2.  I am generally at ease.
    3.  I am usually somewhat uncomfortable.
    4.  I am quite uncomfortable.
    5.  I would not allow myself to participate in such a situation. 
4.  If there were a nudist camp within reasonable proximity in my province:
    1.  I would be interested in visiting with a friend of the opposite sex.
    2.  I would be interested in visiting by myself.
    3.  I would never consider visiting it by myself.
    4.  I have ambivalent feelings about public nudity.
    5.  I would want the police to close the camp. 
5.  Use of slang terminology in discussing sex with children or young people:
    1.  must be avoided at all costs.
    2.  is never necessary.
    3.  is lowering oneself to the level of youth in a way that is not helpful to them.
    4.  may open up communication or show acceptance, but my lack of understanding of the terms would make it embarrassing and/or difficult. 
6.  Sex education should be discussed and taught:
    1.  not at all because people already know enough.
    2.  to young people before they get in trouble.
    3.  only to children who have their parents' signed consent.
    4.  as a regular part of the education system. 
7.  Masturbation, as practiced by children or youth, is:
    1.  harmful to their physical development.
    2.  a sign of some emotional disturbance.
    3.  indulging in immoral behavior.
    4.  to be expected occasionally.
    5.  a normal aspect of sexual development.
8.  Masturbation, for a person in a committed intimate partnership, is:
    1.  usually an indication of serious maladjustment in the marriage.
    2.  an acceptable outlet for the female.
    3.  an acceptable outlet for the male.
    4.  acceptable only when prolonged absence from mate or illness prevents intercourse.
    5.  a normal outlet in addition to intercourse. 
9.  Mutual masturbation, for person not in an intimate committed partnership is:
    1.  a perversion under any circumstances.
    2.  an immoral practice.
    3.  unacceptable to me; masturbation should always be individual behavior in private.
    4.  acceptable behavior for engaged couples.
    5.  an acceptable practice for any unmarried young couple.

## Contraception and Birth Control {.unnumbered}

1.  Do you feel that the use of methods of artificial birth control:
    1.  results in long lasting effects on the user's health, and should not be used.
    2.  can be used by couples, though short-term health impacts could be experienced.
    3.  are immoral according to my religious beliefs, and should never be used.
    4.  is not harmful, providing the method is used correctly and on a short-term basis
    5.  is not harmful, and can be the best decision for some couples
2.  Information and advice about contraception:
    1.  should be limited to married couples.
    2.  may be freely given to engaged couples.
    3.  should be given to any couple that intend to have intercourse.
    4.  should be given to any individual who asks for it.
    5.  should be restricted to individuals over 18 years of age. 
3.  Access to contraceptive devices or medications should be made easily available:
    1.  to any individual.
    2.  to any individual over 16 years of age.
    3.  to any individual over 18 years of age.
    4.  to any individual over 21 years of age.
    5.  to no one unless they are married or engaged. 
4.  Abortion should be made available:
    1.  when the pregnancy is the result of rape, incest, or the mother is underage or married
    2.  when the mother's physical or mental health is endangered.
    3.  if it is likely that the baby will be handicapped or deformed
    4.  whenever a woman feels it would be the best decision.
    5.  under no circumstances since it would be an immoral act.

## Sexual Intimacy {.unnumbered}

1.  Necking (hugging and kissing):
    1.  is a natural part of the growing up experience for young people.
    2.  is not to be indulged in lightly without real affection being present.
    3.  Have positive benefits that lead toward a heterosexual orientation.
    4.  should be discouraged as it leads to a desire for further touch experience and petting.
    5.  is immoral behavior for people until engaged. 
2.  Petting (stimulating caress of any or all parts of the body):
    1.  is immoral behavior, unless the couple is engaged or married.
    2.  is a natural part of the growing up experience for young people.
    3.  should be discouraged strongly as it leads too easily into intercourse.
    4.  is a normal experience only as a prelude to intercourse for couples ready for sexual relations.
    5.  to orgasm is a practical, acceptable, and preferable substitute for intercourse for married couples. 
3.  Premarital sexual intercourse for people:
    1.  is never acceptable to me on moral-religious grounds.
    2.  is never acceptable to me as the chance of illegitimate birth is too great.
    3.  is acceptable if an affectionate relationship exists.
    4.  is acceptable if the couple are engaged.
    5.  is acceptable, without affection existing, if both partners agree. 
4.  Sexual relationships for divorced or separated people are:
    1.  not acceptable.
    2.  acceptable for males only.
    3.  acceptable for females only.
    4.  acceptable for both with consenting partners.
5.  Sexual fantasies are:
    1.  harmful and should never be discussed.
    2.  alright for single people.
    3.  a normal part of masturbatory activity.
    4.  not acceptable for married people.
    5.  a healthy part of any sexual relationship. 
6.  Extra-marital sexual intercourse:
    1.  is immoral under any circumstances.
    2.  is acceptable, under extenuating circumstances for my mate but not for me.
    3.  is acceptable, under extenuating circumstances for me but not for my mate.
    4.  is acceptable for both partners if it will not adversely affect the marriage.
    5.  can sometimes be a healthy experience; there is nothing wrong with it.
7.  The sexual behavior that would be most difficult for me to accept in my partner is: 
    1.  solitary masturbation when intercourse is available.
    2.  seduction of a young person 16 years of age.
    3.  intercourse with an alternate partner.
    4.  an incestuous sexual experience
    5.  sexual activity with a member of the same sex. 
8.  Oral-genital (Mouth to sex organ) contacts:
    1.  are abnormal or perverted behavior.
    2.  are acceptable between husband and wife if both agree.
    3.  are immoral under any circumstances.
    4.  are acceptable between consenting adults of the opposite sex.
    5.  are acceptable between consenting individuals regardless of age or sex.
9.  I am sure I could discuss my sexual feelings and behavior, if there was a valid reason:
    1.  only with someone of my own sex.
    2.  with no one: my feelings and behavior are a private matter.
    3.  only with a professional counselor.
    4.  with close friends of either sex.
    5.   with anyone if I felt it would be helpful.

## Sexual Expression {.unnumbered}

1.  Reading material or pictures that would be labeled pornographic by the courts:
    1.  seriously threatens our moral standards in society.
    2.  is a major cause of sex crimes.
    3.  should be made legal for adults in our country as some other countries have done.
    4.  should be left to the discretion of the individual.
    5.  provides an outlet for some individuals who might otherwise be driven to indulge in illegal or anti-social behavior.
2.  Homosexual behavior:
    1.  indicates a basic personality maladjustment
    2.  is immoral under any circumstances.
    3.  is acceptable between consenting adults.
    4.  is acceptable between consenting partners at any age.
    5.  is a normal healthy variation in sex outlet for adults. 
3.  In thinking about homosexual behavior, I feel that
    1.   I can understand and accept lesbian behavior between females more easily than such behavior between males.
    2.  I can understand and accept homosexual behavior between males more easily than such behavior between females.
    3.  I can understand and accept same sex behavior for either sex equally.
    4.  I am equally repulsed by same sex behavior for either sex under any circumstances.
    5.  I can understand and accept same sex behavior for either sex most easily if they are young and unmarried. 
4.  There are some deviations and sex practices that are usually revolting to talk about that can be discussed:
    1.  with no one, including my marriage partner.
    2.  with no one, except my marriage partner.
    3.  only with members of my own sex.
    4.  on an optional basis in an educational group as frank consideration of these practices is necessary to ensure honest communication with people. 
5.  Laws regarding prostitution:
    1.  are necessary to protect our society from further spread of venereal diseases.
    2.  should treat the customer as equally guilty as the prostitute.
    3.  should be more strictly enforced to protect our morals.
    4.  should concentrate on establishing health regulations and licensing rather than prohibiting it. 
6.  Laws pertaining to sexual behavior:
    1.  should be more strictly enforced.
    2.  should be repealed.
    3.  are unnecessarily harsh; the present laws should be kept but the penalties reduced.
    4.  should be repealed with the exception of those protecting minors.
    5.  are useless as morality cannot be legislated into being.   

### Journal Activity - B4.1 Tolerance and Diversity Self Survey {.unnumbered}

### Tolerance and Diversity Self Survey {.unnumbered}

Once you have completed the survey above review your answers carefully. How do you think your choices fit in with collective attitudes and values? Where do your opinions fit when compared to what is viewed as “normal” sexual behavior? 

You may want to read a little about [Osho-Insights on Sex](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3705694/) to compare western and tantric views and where you stand on both.

----

## 4.2 - Unit B Completion {.unnumbered}

### Journal Activity - Unit B Reflections {.unnumbered}

Now that you have come to the end of the unit, please take a moment to reflect on Unit B. Provide a brief answer (1-2 sentences) to the following questions:

1.  Which of the readings did you appreciate most and why?
2.  Which of the readings did you least appreciate and why?
3.  Which of the journals was most useful to your learning process and why?
4.  Which of the journals was least useful to your learning process and why?
5.  Is there a book, article, journal paper, podcast, or video that is not included in the Unit B curriculum but which you have found beneficial to your understanding of the topics in Unit B? If so, please share it here.
6.  Is there anything else you would like to share about your feedback on this unit?

Lastly, if you would like your feedback to be acted on by the college, please **choose one or more of the above pieces of constructive feedback** and share them in our [curriculum feedback form](https://docs.google.com/forms/d/e/1FAIpQLSdEDwTn_2awBl-y147dDm4zDtHIsUR3A42SiWgvtw6AKufDJw/viewform).