# (PART\*) Unit C: Anatomy & Physiology {.unnumbered}

# Overview {.unnumbered}

**For Unit C: Author: Geraldine Matus (2003) 2017. Editorial Revisions Justisse Faculty as a Collaborative 2014 to date.**

**SUGGESTED TIME TO COMPLETION: 8 to 10 weeks to complete**

**Please Review [Exam, Essay, and Journal Policies](https://justisse.ca/index.php/college/courseware/page/1646)**

**You are responsible to conduct yourself with academic honesty.**

## Introduction: Reproductive Anatomy and Physiology, and the Menstrual Cycle

One would think that we survivors of the “sexual revolution” and offspring of the “information age” by now must surely know all there is to know about our fundamental sexual functions and reproductive powers. However, between the scientific facts of our anatomical parts with attendant physiological functions and their mysterious and miraculous place and meaning in our lives there is room for much speculation, confusion, misdirection, and the stuff of which “old wives tales” are made. In fact, our reproductive “parts” and “functions,” which we will be looking at in detail in this unit of the course are often regarded with shame or treated with little respect for their complex interplay with our total physiology and psychology. Many of us come to know our reproductive anatomy by licentious or euphemistic nicknames, if we really get to know them at all. Many of us give birth to children, have active sexual lives, and still do not understand how our reproductive systems really work, or what their workings mean for us. For many  self-knowledge in this area is made even more complex given that our external genitalia are much less visible than that of men.  

In a way we suffer from too much information, from too many teachers - parents, family, religious leaders, governments and media medics like Dr. Ruth and Dr. Laura - not to mention those most persuasive teachers of all: our testosterone- and estrogen-charged, post-pubescent contemporaries who are inclined to take us to the great story's climax before we get to know the major players. Yet, how do the prospects for ecstatic pairing and new life get their start?

While we sort out the facts of reproductive anatomy and physiology of the menstrual cycle, and reproduction keep in mind that there is a difference between a problem and a mystery. A problem lends itself to intellectual analysis and quantification. Working on problems can generate solutions. Mysteries, on the other hand, do not have solutions. They involve the questions to which there are no objective answers; no answers beyond the answers that develop out of body-gnosis, intuition and the curious workings of the intrapsychic and archetypal realms. Mysteries are meant to be explored through experience not reduced to a rationale understanding.  What is beautiful? What is a divine creator? What is the meaning of my life? My fate? Am I free, or is my life predetermined? What does it mean to be alone? These are mysteries because we have only the questions we ask and the answers we create and believe. (Dick Richards _Setting Your Genius Free_, p. 46).

Now, on to the work of deepening into the rationale understanding of sexual and reproductive anatomy and physiology as well as its mystery as it relates to the cis-gendered female reproductive (menstrual and ovarian) cycle. In Unit C Section 8 and in Unit G Section 14.1 we address the persons who do not identify as cis-gendered female or male, and ho may be intersexed, nonbinary, transgendered, or transitioning. For now we draw your attention to the cis-gendered female and male anatomy and physiology as it relates to fertility awareness and considerations for HRHP practice. Once you have that foundation it will be easier to understand other physiological variations of human sexuality. 

**Important Note:** The material in Unit C is not intended to be categorical, but rather a good representation, from within an ever-evolving field of discovery about the human being. Always the HRHP Trainees are encouraged to not only explore the material presented in this unit, but to independently devise their individual discoveries and conclusions and share them with their HRHP Trainer and peers. 

## Contained in Unit C, you will find the following Sections

-   Unit C Section 1: Unit C Overview
-   Unit C Section 2: Female Reproductive Anatomy and Physiology
-   Unit C Section 3: Male Reproductive Anatomy And Physiology
-   Unit C Section 4: Hormonal and Endocrine Considerations
-   Unit C Section 5: Normal Parameters of the Menstrual Cycle
-   Unit C Section 7: Mapping the 5th Vital Sign

## Unit Multiple Choice

Instructions for taking the Unit C Multiple Choice exam are provided when you select the "multiple choice" exam.

## Unit Short Answer

 Instructions for the Unit C Short Answer are provided in the "short answer" section of Unit C.

## Learning Objectives

1.  Describe and identify the structure of the female and male reproductive anatomy.
2.  Describe the function of the female and male reproductive physiology
3.  Describe and identify normal parameters of the menstrual cycle
4.  Describe and identify indicators of fertility and infertility
5.  Describe the mammary gland anatomy and process of lactogenesis
6.  Describe the various considerations with respect to ovulation
7.  Identify and describe the particular elements of female and male reproductive anatomy in relation to fertility awareness, the climacteric & menopause, postpartum breastfeeding, postpartum not breastfeeding, and  “coming off the birth control pill”
8.  Identify and describe individual hormones and hormonal feedback with respect to the reproductive system 