## 1.2 - Required Readings {.unnumbered}

### How to Approach Unit C Readings {.unnumbered}

Some of these readings are similar. However, you are required to read all of them so you may familiarize yourself with how various texts regarding reproductive anatomy and physiology differ in language, style, particular focus, and the degree of comprehensive material and/or misinformation regarding fertility awareness.

You will be responsible to identify how the DeLamater, Hyde, and Byers text differs from the courseware text, and to become curious and informed about the difference regarding reproductive anatomy and physiology that is important for deepening into an understanding of fertility awareness. So read carefully.

NOTE: read the Required Readings in the order they are listed below. You may find it helpful to re-read some of the texts in order to compare and contrast texts in order to solidify your understanding.

\*Required reading from Understanding Human Sexuality is accessible on Google Drive. Click on this link:  **[https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE\_g?usp=sharing](https://drive.google.com/drive/folders/170WXmuPrLICht31n8fvKDQUcGQXmQE_g?usp=sharing)**

### Required Readings {.unnumbered}

1.  Unit C in entirety.
2.  Understanding Human Sexuality 3rd Canadian Edition. Janet Shibley, Hyde, John D. DeLamater, & E. Sandra Byers. Toronto: McGraw-Hill Ryerson. 2006 (Please click on the link to access Google Drive where the text is located.)  
    1.  Chapter 4 pages 79 to 106 "_Sexual anatomy”_
    2.  Chapter 5 pages 107 to 136 "_S_ex Hor_mones, Sexual Differentiation, and Menstruation"_
    3.  Chapter 6 pages 137 to 175 _"Conception, Pregnancy, and_ _Childbirth"_
    4.  Chapter 11 pages 306 to 333 _"Sexuality and the Life Cycle: Childhood and Adolescence"_
    5.  Chapter 12 pages 334 to 366 _"Sexuality and the Life Cycle: Adulthood"_
3.  **Justisse Method for Fertility Awareness and Body Literacy: A User's Guide**. Geraldine Matus. Revised Edition (2009) Justisse-Healthworks for Women. Edmonton, AB. 2009.
4.  **Solved: The Riddle of Illness.** Stephen Langer, 2006. This is a helpful resource on recognizing and assessing hypothyroidism, which is key to understanding many common menstrual cycle disorders.
5.  [BBT LH Testing](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Basal%20body%20temperature%3B%20LH%20test%3B%20Infertility%3B%20Ovulation.pdf) Unit C Supplement 2: Basal body temperature; LH test; Infertility; Ovulation
6.  [Menstruation Explained in a Simple Way](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/MENSTRUATION%20EXPLAINED%20IN%20A%20SIMPLE%20WAY.pdf) Unit C Supplement 3 Menstruation Explained in a Simple Way
7.  [BBT, Nocturnal Sleep, and Ovulation](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/BBT%20and%20Nocturnal%20Sleep%20Research.pdf) BBT, Nocturnal sleep, and ovulation; Joseph Eldor, MD
8.  [Tanner's Stages of Breast Development](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/BREAST%20DEVELOPMENT%20Tanner%20Stages.pdf)
9.  [Hymen Renamed to Vaginal Corona](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Hymen-renamed-vaginal-corona2009.pdf)
10.  [Male Steroids and Female Preferences for Male Body Odor](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Male%20steroids%20and%20female%20pref.pdf) Male Steroids and Female Preferences for male body odor.
11.  [Menstruation a Dynamic and Directed Event](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Menstruation%20A%20Dynamic%20and%20Directed%20Affair.pdf) In her book Woman: An Intimate Geography (1999.) Natalie Angier describes the mechanism of menstruation poetically and dynamically. Her book is on the recommended reading list and surely you will enjoy reading the whole text. However, until then I share this excerpt from her description of menstruation.
12.  [Aging Gametes](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Aging%20Gonads%20Glands%20and%20Gametes.pdf) Aging gonads, glands, and gametes: immutable or partially reversible changes?
13.  [New Anatomy of the Lactating Breast](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/new%20anatomy%20of%20the%20breast.pdf)
14.  [Progestin Families](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/progestin%20families.pdf)
15.  [Observer Response to LadyComp](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Observer%20response%20to%20Lady%20Comp.pdf)
16.  [Sperm Capacitation](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/sperm%20capacitation.pdf)
17.  [Cervicovaginal Fluid Changes to Detect Ovulation Accurately](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Cervicovaginal%20fluid%20AJOG%2005.pdf)
18.  [Estimation of the Day Specific Probabilities of Conception](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/conceptionprobabilities.pdf)
19.  [Erik Odeblad Discovery of Different Types of Mucus](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Odeblad_Discovery%20of%20Cervical%20Mucus_1994.pdf)
20.  [Erik Odeblad: Investigations on the Physiological Basis of Fertility Awareness](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Odeblad_Investigations.pdf)
21.  [Some Investigations of the Cervical Z-secretions](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/Some%20Investigations%20of%20the%20Cervical%20Z_Odeblad.pdf)
22.  [Variability in the Phases of the Menstrual Cycle](http://epublications.marquette.edu/cgi/viewcontent.cgi?article=1010&context=nursing_fac) Fehring, Schneider, Raviele (2006) 
23.  [Making sense of the many names for women's reproductive aging by Dr. Jerilynn C. Prior](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitC/SMCR-Position-statement-Perimenopause-and-Menopause-naming-2012.pdf "Making sense of the many names for women's reproductive aging")

### References You May Want to Acquire {.unnumbered}

1.  Any well-illustrated atlas of human anatomy, and/or a text on human anatomy and physiology used by nursing or medical students are good references to have. Try a local library or purchase yourself one from a used bookstore. We suggest the following: 1st recommendation **Essentials of Human Anatomy and Physiology** by Elaine M. Marieb 8th, 9th, or 10th ed. -- 2nd recommendation Principles of Anatomy and Physiology, Control Systems of the Human Body Vol. 3 10th Ed. by Gerard J Tortora & Sandra R. Grabowski
2.  **Reproductive Anatomy and Physiology: A Primer for FertilityCare Professionals**. Thomas W. Hilgers. Pope Paul Vi Institute Press. (2002)

----

## 1.3 - Comparative Readings {.unnumbered}

1.  **A New View of a Woman's Body.** Federation of Feminist Women's Health Centres. Los Angeles: Feminist Health Press. (1995). Originally written in 1982, updated in 1991. Presents clear, detailed descriptions of vaginal and breast self examination, the complete anatomy of the clitoris, common infections, lab tests, fertility detection, donor insemination, birth control, menstrual extraction, abortion care, surgical procedures and home remedies. Beautiful illustrations by Suzann Gage.
2.  For a purely decadent read and for engaging with pure pleasure at the amazing ways of our bodies have a look at: **The Architecture and Design of Man and Woman: The Marvel of the Human Body**. by Alexander Tsiaras and Barry Werth 
    -   **A glorious, unparalleled view of the human body . . . Revolutionary computer images from the creator of _From Conception to Birth_ reveal the wonders and complexities of every system in the male and female bodies.** 
    -   The human body is a marvel of engineering. From the muscular and skeletal systems of the hand working in concert to allow us to type, eat, and caress, to the circadian rhythms of the heart and digestive system keeping things moving despite our consciousness being elsewhere, our bodies are far more complex and awe inspiring than any man-made creation. Not since Andreas Vesalius's _On the Fabric of the Human Body,_illustrated by the scholar in the mid-16th century, has there been a work examining human anatomy for both the scientific and lay communities.
    -   _The Architecture and Design of Man and Woman_ is the ultimate illustrated look at the internal structures and processes that sustain us as living, thinking, social beings. Using the most advanced medical and computer technology—including body scans, ultrapowerful microscopes, and molecular surveillance tools—Alexander Tsiaras, founder of a widely acclaimed medical-imaging company, hones in on the body's intricately constructed systems and isolates structures that have never been seen before. In more than 500 astonishing images, he dismantles each system, highlights the anatomical difference between men and women, and rebuilds the body from the molecular level on up. Barry Werth's lyrical, informative text enhances the power of the images, providing an array of startling and fascinating facts.
    -   _The Architecture and Design of Man and Woman_ is a milestone in science, art, and technology. As Werth writes in the Introduction, “For the first time we see the body not _like_ something, or represented by human hands, or as a grainy negative or video, but very nearly as it is.”
3.  **Breastfeeding and Natural Child Spacing: How Ecological Breastfeeding Spaces Babies.** Sheila Kippley. New edition (1999).
    -   Sheila Kippley, mother of five, has been active in the natural family planning movement since 1969. Her teaching of ecological breastfeeding for natural child spacing has helped many mothers enjoy a natural form of mothering. She has spoken on the importance of the mother during the early years, natural child spacing, and the spiritual aspects of breastfeeding. Her latest book is Breastfeeding and Catholic Motherhood, and she and her husband are co-founders of NFP, International.
    -   John and Sheila Kippley founded the Couple to Couple League in 1971 for three purposes: 1. To meet the need for a nationwide, independent, and organized way of delivering NFP services; 2. To provide instruction in NFP that includes moral and religious values along with physiological and scientifically accurate information; 3. To train volunteer married couples to be proficient counselors and teachers in a 99% effective method of NFP, and at no cost to those who generously undertake this training. With the assistance of Konald A. Prem, M.D., then a Professor of Obstetrics and Gynecology at the University of Minnesota School of Medicine, a plan was developed to meet those needs. The CCL concept has proven successful, not only in the U.S., but in countries throughout the world. Each year sees new areas opening up to being served by CCL.
    -   The Couple to Couple League (CCL) is an international, interfaith, non-profit organization dedicated to teaching Natural Family Planning (NFP) to married and engaged couples. It is essentially a volunteer organization because services are provided by professionally-trained volunteers who are supported by a relatively small staff at the international headquarters in Cincinnati, Ohio. Local Chapters of the organization consist mainly of certified Teaching Couples and Promoters, along with other supportive members.
4.  The Boston Women's Health Book Collective. (2011). Chapter 1 _Our Female Bodies: Sexual Anatomy, Reproduction, and Menstrual Cycle._ pp. 3-29 Chapter 21 _Our Later Years_ pp. 547-584. In ****_Our Bodies Ourselves: Completely Revised and Updated_.**** New York: Simon & Schuster. 
5.  [**Women's Anatomy of Arousal**](http://www.amazon.com/Womens-Anatomy-Arousal-Sheri-Winston/dp/057803395X/ref=sr_1_1?s=books&ie=UTF8&qid=1423016053&sr=1-1&keywords=women%27s+anatomy+of+arousal "Women's Anatomy of Arousal") Sheri Winston.
    -   WINNER, 2010 BOOK OF THE YEAR AWARD! THE AMERICAN ASSOCIATION OF SEX EDUCATORS, COUNSELORS & THERAPISTS (AASECT). Find out why Dr. Christiane Northrup has called Women's Anatomy of Arousal "the most comprehensive, user-friendly, practical and uplifting book on women's sexuality I've ever read. It's the gold standard!" Women have a largely unknown network of structures responsible for arousal and orgasm that their owners and even most medical professionals don't know about. We're not just talking about Ye Olde G-Spot here. Women have an entire erectile network that, if properly stimulated, can elevate their erotic experience from "Oh!" to "Oh! Oh! Oh!" Join celebrated sexuality teacher Sheri Winston as she integrates ancient wisdom, lost knowledge and modern sexuality information in a sexy, fun, empowering guidebook that illuminates every woman's secret paths to fabulous, orgasmically abundant sex. Whether you're a woman or a man who loves women, this book is for you! There's great information here, but that's not why Winston wrote the book. She wrote it to transform people's lives and support them to reclaim their erotic birthright. And what she shares works! When people apply the information and techniques she provides, the result is often a whole new level of sexual pleasure. Many women experience their first ejaculations and/or become multi- or mega-orgasmic. Men learn how to make their female partner REALLY happy. Women's Anatomy of Arousal includes discussions of anatomy and energetics, female ejaculation and expanded orgasm, and much more. It's packed with sidebars providing great tips to women and their lovers. There's even a short chapter for guys ("The Easy Girl's Guide to Making It Easy for Guys") summarizing the main points of the book! Winston's background includes over twenty years as a nurse-midwife, gynecology practitioner and student of the ancient erotic traditions. Over the years, she has developed her own unique approach to sexuality education, called Wholistic Sexuality. She gets rave reviews as a teacher. Now her teaching is available in this fun, fascinating, immensely readable book that can transform your sex life for the better. Winston is the executive director of the Kingston, NY-based Center for the Intimate Arts.
6.  **A New View of a Woman's Body: A Fully Illustrated Guide**. Federation of Feminist Women's Health Centers. Feminist Health Press. Los Angeles; CA (1991)
    -   This is one of the most helpful books on woman's sexuality & sexuality I have encountered because of its sheer audacity at showing women's bodies as they really are, and with out apology. I bought my copy back when this book was first published and still own it.
7.  **Your Hormones** this is a website [http://www.yourhormones.com/](http://www.yourhormones.com/) that has a detailed discussion of hormonal health for women and some natural product suggestions for balancing and healing hormones using more functional medicine approaches. It takes some navigating to get through it all but may well be worth your while. At the very least bookmark the page.

----

# Section 1

## 1.4 - Unit C Final Evaluation {.unnumbered}

### Multiple Choice and Short Answer Exams {.unnumbered}

**Do not open up the multiple choice or short answer exam until you are ready to take it.**

-   multiple choice exam: 75 questions with 185 minutes to complete
-   short answer exam: 85 questions with 300 minutes to complete

You are responsible to conduct yourself with academic honesty.