# 6: References {.unnumbered}

## 6.1 - References {.unnumbered}

### General References for Unit C {.unnumbered}

1.  See all _Required Readings and Comparative Readings for Unit C_
2.  Arvigo, Rosita. & Epstein, N. _Rainforest Home Remedies_, p. 91
3.  Fehring, R. (2002). Accuracy of the peak day of cervical mucus as a biological marker of fertility. _Contraception, 66_, 231-235.
4.  Hilgers, Thomas W. _Reproductive Anatomy and Physiology: A Primer for FertilityCare Professionals._ Pope Paul Vi Institute Press. (2002)
5.  Hilgers, T., Abraham, G., & Cavanagh, D. (1978). Natural Family Planning I, the Peak System and Estimated Time of Ovulation. _The American College of Obstetrics and Gynecologists, 52_ (5), 575-582.
6.  Hilgers TW. (2004). _Medical and surgical practice of NaPro technology_. Omaha, Nebraska: Pope Paul VI Institute Press.
7.  Marieb, Elaine M. _Essentials of Human Anatomy and Physiology_ 8th, 9th, and 10th ed.
8.  Porth, C. _Pathophysiology: Concepts of Altered Health States_, p. 1206
9.  Ramsy DT, Kent JC, Hartman PE. 2005. _Anatomy of the human breast redefined with ultrasound imaging._ Journal of Anatomy, 206 pp. 525-534.
10.  Tortora, Gerard J., Grabowski, Sandra R. _Principles of Anatomy and Physiology, Control Systems of the Human Body_ Vol. 3 10th Ed.  
11.  Tarin, Juan J., Pérez-Albalá, Sonia., Cano, Antonio. _Cellular and Morphological Traits of Oocytes Retrieved from Aging Mice after Exogenous Ovarian Stimulation. Biology of Reproduction 65(1):141-150. 2001 doi: [http://dx.doi.org/10.1095/biolreprod65.1.141](http://dx.doi.org/10.1095/biolreprod65.1.141)_ 
12.  Yen SSC, Jaffe RB, eds. 1978. Reproductive endocrinology: Physiology, pathology and clinical management W.B. Saunders.

### References for Coming Of the Pill (Matus 2007) {.unnumbered}

1.  Ambani LM, Joshi NJ, Vaidya RA, Devi PK. 1977. Are hormonal contraceptives teratogenic? Fertility and Sterility 8:791-797.
2.  Berkson LD. 2000. Hormone deception: How everyday foods and products are disrupting your hormones. Contemporary Books.
3.  Boston Women's Health Collective. 1992. New our bodies, ourselves: A book by and for women. Simon and Schuster.
4.  Chesler G. 2006. Period: The end of menstruation? Pages 54. USA: The Cinema Guild Inc.
5.  Czeizel A. 1980a. Are contraceptive pills teratogenic? Acta Morphol Acad Sci Hung. 28:177-188.
6.  Czeizel E. 1980b. Fetal damage caused by contraceptive tablets \[Article in Hungarian\]. Orv Hetil. 121 3-9.
7.  David T, O'Callaghan S. 1974. Letter: Birth defects and oral hormone preparations. Lancet Jun 15;1:1236.
8.  Erasmus U. 1993. Fats that heal, fats that kill. Alive.
9.  Gaspard U, Lambotte R. 1984. Fertility and characteristics of ovulation after discontinuing oral contraception \[Article in French\]. Contracept Fertil Sex (Paris) Sep;12:1005-1010.
10.  Hassan MAM, Killick SR. 2004. Is previous use of hormonal contraception associated with a detrimental effect on subsequent fecundity? Human Reproduction 19:344-351.
11.  Hilgers TW. 2004. Medical and surgical practice of NaPro technology. Pope Paul Vi Institute Press.
12.  Hudson T. 1999. Women's encyclopedia of natural medicine: Alternative therapies and integrative medicine. Keats.
13.  Martinez-Frias M, Bermejo E, Rodriguez-Pinilla E, Prieto L. 2001. Periconceptional exposure to contraceptive pills and risk for Down syndrome. Journal of Perinatology July-Aug;21:288-292.
14.  Mills D, Vernon M. 2002. Endometriosis: A key to healing through nutrition. . Thorsons.
15.  Murray M. 1996. Encyclopedia of nutritional supplements. Prima Publishing.
16.  Murray M, Pizzorno J. 1998. Encyclopedia of natural medicine. Prima Health.
17.  Panzer C, Wise S, Fantini G, Kang D, Munarriz R, Guay A, I. G. 2006. Impact of oral contraceptives on sex hormone-binding globulin and androgen levels: a retrospective study in women with sexual dysfunction. Journal of Sexual Medicine 3:104-113.
18.  Rako S. 2006. No more periods?: The blessings of the curse. iUniverse Inc.
19.  Seymour H, Databank I, December 22, UKPID Sf, CONTRACEPTIVES CO, Helen Seymour BH, . 1997. Combined oral contraceptives. ([http://www.intox.org/databank/documents/pharm/progest/ukpid08.htm](http://www.intox.org/databank/documents/pharm/progest/ukpid08.htm))
20.  Spira A. 1983. Fertility following hormonal contraception (author's transl) \[Article in French\]. Contracept Fertil Sex (Paris) Jul-Aug;11:903-907.
21.  Yen SSC, Jaffe RB, eds. 1978. Reproductive endocrinology: Physiology, pathology and clinical management W.B. Saunders. 

----

## 6.2 - Unit C Completion {.unnumbered}

## Journal Activity - Unit C Reflections {.unnumbered}

Now that you have come to the end of the unit, please take a moment to reflect on Unit C. Provide a brief answer (1-2 sentences) to the following questions:

1.  Which of the readings did you appreciate most and why?
2.  Which of the readings did you least appreciate and why?
3.  Is there a book, article, journal paper, podcast, or video that is not included in the Unit C curriculum but which you have found beneficial to your understanding of the topics in Unit C? If so, please share it here.
4.  Is there anything else you would like to share about your feedback on this unit?

Lastly, if you would like your feedback to be acted on by the college, please **choose one or more of the above pieces of constructive feedback** and share them in our [curriculum feedback form](https://docs.google.com/forms/d/e/1FAIpQLSdEDwTn_2awBl-y147dDm4zDtHIsUR3A42SiWgvtw6AKufDJw/viewform).