# (PART\*) Unit D: Contraception {.unnumbered}

# 1.3 - Overview {.unnumbered}

### Overview of Unit D

**Unit D Section 1** includes an overview of the complete unit, lists of readings and journals required, and this brief introduction to the current international context of contraception and abortion. **Section 2** includes a detailed discussion of how the efficacy of birth control technologies is understood and how we measure effectiveness. **Section 3** provides a complete view of barrier methods: the internal condom, cervical cap and diaphragm, as well as spermicide or barrier gel. We include a discussion of vaginal health and wellness in exploring the risks and side effects of barrier methods.  

In Unit D **Section 4** we cover artificial CEDs, including the pill, patch, ring, injectables, implants, intrauterine systems, and non-steroidal SERM. We discuss the controversies around menstrual suppression, and 'therapeutic' use of artificial CEDs in the context of their side effects and risks. **Section 5** covers herbal CEDs, with careful attention to the misleading assumption that herbal solutions are inherently safer than artificial. **Section 6** includes a discussion of copper intrauterine devices. 

**Section 7** provides a comprehensive overview of all Fertility-Awareness-Based Methods, including retrospective / calculated methods, and those based on direct observation. We discuss highly technological sympto-hormonal methods, as well as charting mobile applications. We include a discussion of BAFting and FABM effectiveness. In Unit D **Section 8** we turn our attention to surgical methods, putting tubal ligation, occlusion, and hysterectomy in historical context. We include a discussion of consent in sterilization practices, and the difficult history of forced sterilization and eugenics. 

**Section 9** offers an overview of methods of contraception targeting the male body, including withdrawal, external condoms, and vasectomy. We introduce current research on male methods and some insights on why this process has stalled. **Section 10** offers information on all methods of emergency contraception, including oral CEDs, IUD, and herbal preparations. 

In Unit D **Section 11** we explore abortion, including medical and herbal options, aspiration, menstrual extraction and regulation. We provide a holistic discussion of abortion care and include information about procedures from the most commonly performed in the first trimester, to abortion at 24 weeks and beyond. Following this section, we include lesser known methods of contraception, including those using lunar or astrological principles. 

We end Unit D with a discussion in **Section 13** of sexual and reproductive health counselling that will assist the HRHP in developing a supportive and reflexive practice. The goal with Unit D material is to create a comprehensive knowledge base about birth control methods, and an understanding of the social nature of these technologies. We encourage your own self-reflection so that you can have a compassionate, client centred, intersectional, and anti-oppression stance when counselling and supporting clients through their reflections and decision-making vis a vis sexuality and fertility management.

### Learning Objectives

Once you have completed the readings and exercises in this unit of study, you will be able to: 

1.  Identify the different types of birth control with respect to 1) modes of action, 2) use and theoretical effectiveness, and 3) advantages and disadvantages
2.  Understand how use of artificial birth control methods can impact long-term fertility.
3.  Explain how Emergency Contraception works.
4.  Identify when Emergency Contraception is indicated for a client.
5.  Identify the different types of abortion procedures and how they are performed.

#### Unit D Section 1: Syllabus

-   Section 1.1: Reproductive Rights in International Context
-   Section 1.2: Introduction: Contraception and Reproductive Justice
-   Section 1.3: Syllabus
-   Section 1.4: Required Readings
-   Section 1.5: Suggested Readings
-   Section 1.6: Journals

#### Unit D Section 2: Contraceptive Effectiveness

-   Section 2.1: Contraceptive Effectiveness
    -   Journal #2: Reflection on Contraceptive Effectiveness

#### Unit D Section 3: Barrier Methods, Spermicide, and Barrier Gel

-   Section 3.1: Introduction to Barrier Methods, Spermicide, and Barrier Gel
-   Section 3.2: Internal Condom
-   Section 3.3: Cervical Cap & Diaphragm
-   Section 3.4: Spermicide and Barrier Gel
-   Section 3.5: Side Effects and Risks of Barriers and Spermicide
    -   Journal  #22: Literature on Barrier Methods, Spermicide, and Barrier Gel

#### Unit D Section 4: Artificial Contraceptive Endocrine Disruptors

-   Section 4.1: Introduction to Artificial Contraceptive Endocrine Disruptors
-   Section 4.2: Combined Artificial CEDs
    -   Oral Contraceptive Pill
    -   Contraceptive Patch
    -   Combined Intravaginal Ring
    -   Combined Injectable
    -   Journal # 3: Being on the Pill is just like being pregnant
-   Section 4.3: Non-steroidal SERM
-   Section 4.4: Progestin - Only Artificial CEDs
    -   Progestin-Only Pill
    -   Progesterone Intravaginal Ring
    -   Long-Acting Reversible Contraceptives
        -   Progestin-Only Injectable
        -   Implant
        -   Intrauterine System
-   Section 4.5: Menstrual Suppression through Artificial CEDs
    -   Extended Cycle Oral Contraceptive Pill
-   Section 4.6: 'Therapeutic' Use of Artificial CEDs
    -   Journal # 25: Contraceptive Endocrine Disruptors
-   Section 4.7: Side Effects and Risks of Artificial CEDs
    -   Journal # 29: Literature on “Hormonal” Contraceptives
-   Section 4.8: Controlling Fertility: A Matter of Choice?

#### Unit D Section 5: Herbal Contraceptives

-   [Section 5.1](https://justisse.ca/index.php/college/courseware/page/1105) - Introduction Herbal Contraceptives
    
-   [Section 5.2](https://justisse.ca/index.php/college/courseware/page/1106) - Herbal Birth Control Mechanisms
    

-   -   Journal # 4: Engaging with Herbs for Contraception

#### Unit D Section 6: Intrauterine Device  

-   Section 6.1: Intrauterine Device (IUD)
    -   Journal # 1: Not your Mother's IUD 

#### Unit D Section 7: Fertility Awareness-Based Methods (FABMs)

-   Section 7.1: Introduction to Fertility Awareness-Based Methods (FABMs)
-   Section 7.2: A Brief History of FABMs
-   Section 7.3: Philosophical Approaches to Teaching and Applying FABMs
-   Section 7.4: Retrospective / Calculated Methods
    -   Calendar - Based Methods
    -   Lactational Amenorrhea Method (LAM)
-   Section 7.5: Direct Observation Methods
    -   Cervical Mucus
    -   BBT only
    -   Cephalad Shift
    -   Sympto-thermal
    -   Journal # 23: Literature on “Natural” Methods
-   Section 7.6: Fertility Awareness-Based Charting Apps   
    -   Journal # 26 Charting Apps
-   Section 7.7: Sympto-Hormonal Methods
-   Section 7.8: Effectiveness rates FABMs
    -   Journal # 30: Justisse Method Effectiveness
-   Section 7.9: Using Barriers at Fertile Times (BAFTing)

#### Unit D Section 8: Surgical Methods  

-   Section 8.1: Introduction to Surgical Methods
-   Section 8.2: Tubal Ligation and Occlusion
    -   Journal # 5: Literature on Tubal Sterilization Methods
-   Section 8.3: Hysterectomy  
    -   Journal # 10: Hysterectomy in your Country or Region 
-   Section 8.4: Side Effects & Risks of Surgical Sterilization
-   Section 8.5: Consent & Sterilization Access
-   Section 8.6: Forced Sterilization, Eugenics, and Reproductive Coercion
    -   Journal # 27: Forced Sterilization in Your Country or Region 

#### Unit D Section 9: Male Contraception

-   Section 9.1: Introduction to Male Contraception
-   Section 9.2: External Condom
-   Section 9.3: Withdrawal
-   Section 9.4: Vasectomy
    -   Journal # 16: Literature on Male Contraceptive Methods 
-   Section 9.5: Research on Male Contraception
-   Section 9.6: Do people want contraception for male physiology?
    -   Journal # 28: A reflection on contraception research

#### Unit D Section 10: Emergency Contraception (EC)

-   Section 10.1: Introduction to Emergency Contraception
-   Section 10.2: Emergency Artificial CEDs   
    -   Levonorgestrel and Ulipristal Acetate
    -   Mifepristone
    -   Yuzpe Regimen
-   Section 10.3: Emergency IUD   
    -   Journal # 11: Literature on Emergency Contraception
    -   Journal # 12: Wisest use of EC
-   Section 10.4: Other Emergency CEs
    -   Journal [#17 Unit D 10.4 Herbal CED / EC Critique](https://justisse.ca/index.php/college/ad_courseware/page/1714)

#### Unit D Section 11: Abortion

-   Section 11.1: Introduction to Abortion
-   Section 11.2: Medical Abortion (<12 weeks)  
    -   Misoprostol
    -   Mifepristone (RU486) and Misoprostol
    -   Methotrexate and Misoprostol
-   Section 11.3: Aspiration Abortion (<12 weeks)  
    -   (Electric / Manual) Vacuum Aspiration
    -   Journal # 13: Compassionate Abortion Counselling
-   Section 11.4: Aspiration Abortion (12 - 19 weeks)    
    
    -   Week 12 - 15
    
    -   Week 15 - 18
    -   Laminaria Japonica
-   Section 11.5: Abortion >19 weeks    
    -   Medical Abortion Beyond 12 Weeks
    -   Aspiration Abortion Weeks 19 - 24
    -   Aspiration Abortion >24 Weeks
    -   Dilation & Evacuation / Extraction
-   Section 11.6 Menstrual Extraction & Regulation
-   Section 11.7: Herbal Abortion
-   Section 11.8: Abortion After Care

#### Unit D Section 12: Other Methods

-   Section 12.1 Other Methods
    -   Astrological / Lunar Cycle
    -   Lunaception

#### Unit D Section 13: Sexual Health Counselling

-   Section 13.1: Introduction to Sexual Health Counselling
-   Section 13.2: Sexual Health Counselling
    -   Journal # 7: Cross-cultural Aspects of Sexual Health Counselling
    -   Journal # 8: Sexual and Reproductive Health Genogram
    -   Journal # 6: Which method of contraception is right for you?
    -   Journal # 9: Matching the Contraceptive to the Client - 17 Factors 
-   Section 13.3: Birth Control Myths and Misinformation
    -   Journal # 14: Myths and Misconceptions
    -   Journal # 15: "Pro-Life" Perspectives on ECPs
-   Section 13.4: Pregnancy Options Counselling   
    -   Pregnancy Care Centres
    -   Journal # 17: If these walls could talk
    -   Journal # 19: Problematic Sources
    -   Journal # 20: Values Clarification
    -   Journal [# 21 Aspen Baker Needs Help](https://justisse.ca/index.php/college/ad_courseware/page/1726)
-   Section 13.5: Is Contraception Contra Naturam?
    -   Journal # 24: Reflection  
