# 1: Syllabus {.unnumbered}

## 1.1 - Reproductive Rights in International Context {.unnumbered}

## Unit D Section 1.1 Reproductive Rights in International Context {.unnumbered}

Excerpt from: **Salamanca, L. (2017). Reproductive Justice in Canada: Exploring Immigrant Women's Experiences. In Stettner, S., Burnett, K., & Hay, T. (Eds.).** **_Abortion: History, Politics, and Reproductive Justice after Morgentaler._** **Vancouver, BC: UBC Press. pp. 292-312.** 

Perhaps the clearest illustration of privilege in the voices dominating discussions about reproductive rights is in the international context of commitments made toward the improvement of women's health and reproductive health issues since the beginning of the millennium. A number of influential international women's conferences were held in the 1990s, most notably the 1994 International Conference on Population and Development (ICPD) in Cairo, and the 1995 United Nations Fourth World Conference on Women in Beijing, in which discourse on reproductive health came to be understood within the framework of human rights, gender equality, and the empowerment of women.\[1\]  Advocates established the application of human rights standards to sexual and reproductive health issues, gaining the formal recognition of some sexuality and reproduction rights as outlined by documents such as the _Yogyakarta Principles_ _on Sexual Orientation and Gender Identity,_ and the International Planned Parenthood Federation's _Declaration on Sexual Rights_. \[2\]

The sense of imminent change felt by the international community at the time was reinforced when concern with reproductive health issues was dominant in conceptualizing the United Nations Millennium Development Goals (MDGs), where reduction of child mortality, maternal mortality, and HIV/AIDS was part of the agenda. Specific targets called for significant improvements between 1990 and 2015: to reduce by three-quarters the maternal mortality ratio, to reduce by two-thirds the under-five mortality rate, and to have halted and begun to reverse the spread of HIV/AIDS.\[3\] UN member states recognize that most maternal deaths arise from complications of childbirth, in the immediate postpartum period, or after unsafe abortion.\[4\] These deaths are linked with the absence of skilled health personnel during childbirth, lack of services able to provide emergency care and deal with “complications of unsafe abortion,” and ineffective referral systems.\[5\] At the international level, advocacy for the provision of safe abortion, and not merely the elimination of unsafe abortion, is carefully spoken about as limited “to the extent allowed by law.”\[6\]

International human rights law has a tendency towards fragmentation; for the sake of realizability, we limit the protections that can be afforded by any one right in isolation. Given the lack of official arbiters across political and expert bodies, considerable tensions between United Nations member states have stalled the realization of standardized applications of established human rights law to address reproductive health problems.\[7\] Measures of maternal mortality, widely regarded as the most important indicator of the status of women and their access to adequate health care, show that we are nowhere near achieving the goals of the ICPD Programme of Action, or of the Millennium Summit of 2000.\[8\] In fact, none of the Millennium Development Goals (MDGs) in relation to reproductive health were met by 2015. At the global level, maternal mortality decreased by less than 1 percent per year between 1990 and 2005.\[9\] By 2015, the maternal mortality ratio had declined by 45 percent worldwide,\[10\] falling well short of the target reduction of two-thirds, or 66 percent. Reproductive health has not fared as well as originally hoped by member states, and the international community remains far from achieving agreed upon targets.\[11\]  

In practice, maternal health is a poor indicator of women's reproductive health. As countries concentrated on maternity, they focused on health care for women giving birth to ensure mothers remained alive for their children. Maternal health became linked to newborn mortality.\[12\] Berit Austveg, Senior Adviser of the Norwegian Board of Health Supervisors, asserts that maternal health, rather than encompassing only the health of women giving birth and their newborns, was meant to be about pregnancy and all its possible outcomes: miscarriage, delivery of stillbirth, living child, or abortion.\[13\] However, these latter dimensions were lost through the interpretation and use of this measure as an overall indicator.  

While the International Conference on Population and Development (ICPD)'s application of human rights to reproductive rights was pivotal in advancing international discourse, so was its discussion of abortion. Removed from its reality, the ICPD's discussion of the procedure was couched in moralistic language regarding its undesirability. The ICPD Programme of Action reads: “Prevention of unwanted pregnancies must always be given the highest priority and every attempt should be made to eliminate the need for abortion ... In circumstances where abortion is not against the law, such abortion should be safe.”\[14\] In effect, instead of treating abortion as a legitimate health service and means of fertility regulation, the Programme of Action recommends that we prioritize preventing unwanted pregnancies, and not the provision of abortion on demand.\[15\] Once again, a narrow focus on pregnancy decision-making and national imperatives to constrict the actions of individual women dominated the discussion, ignoring the approximately 8 million women who suffer life-threatening complications related to pregnancy each year worldwide,\[16\] and the estimated 68,000 women globally who die each year from unsafe abortion complications.\[17\]  

Further, preventing unwanted pregnancies is not, statistically, a feasible task. As Marge Berer asserts, “contraceptive methods are not perfect and people are not perfect users of them ... in some cases men stop women from using contraception, while in other cases rape, sexual abuse and coercive sexual relations” are the reason for pregnancy.\[18\] Moral judgment of abortion consistently undermines the public health directive to save women's lives - the language of initiatives such as the 1994 Programme of Action is simply not based on evidence of what is required to reduce women's mortality. Indeed, this stigmatizing language was felt by those at the table to be the only way in which a conversation about abortion could be included in the ICPD at all. International discourse asserting that contraceptive technology negates the need for safe abortion is saturated both with an inflated expectation about the effectiveness of the newest modes of birth control, most notably the contraceptive pill, and a blind belief in scientific and technocratic solutions to social problems. The pervasive ideology of the power of technology both to depoliticize and fix problems of power inequity is maintained by willful ignorance of statistical and ethnographic data on the suitability and efficacy of contraception, violence against women, and the complex and socially determined ways in which human sexuality is negotiated.

___

\[1\] Berit Austveg, “Perpetuating Power: Some Reasons Why Reproductive Health Has Stalled,” Reproductive Health Matters 19, 38 (2011): 26.

\[2\] Alice Miller and Mindy Roseman, “Sexual and Reproductive Rights at the United Nations: Frustration or Fulfillment,” Reproductive Health Matters 19, 38 (2011): 102.

\[3\] World Health Organization, “Reproductive Health Strategy to Accelerate Progress towards the Attainment of International Development Goals and Targets,” Department of Reproductive Health and Research, 2014, 7.

\[4\] Ibid., 11.

\[5\] Ibid.

\[6\] Ibid., 22.

\[7\] Miller and Roseman, “Sexual and Reproductive Rights at the United Nations,” 106; Austveg, “Perpetuating Power,” 26.

\[8\] Austveg, “Perpetuating Power,” 28; Jyoti Shankar Singh, Creating a New Consensus on Population: The Politics of Reproductive Health, Reproductive Rights and Women's Empowerment, 2nd ed. (London: Earthscan, 2009), 199.

\[9\] Singh, Creating a New Consensus, 199.

\[10\] United Nations, “The Millennium Development Goals Report 2015,” https://mdgs.un.org/unsd/mdg/Resources/Static/Products/Progress2015/English2015.pdf.

\[11\] Austveg, “Perpetuating Power,” 27.

\[12\] Ibid., 29.

\[13\] Ibid., 28.

\[14\] International Conference on Population and Development, Report of the International Conference on Population and Development Cairo, 5-13 September, 1994 (New York: United Nations, 1995), 41.

\[15\] Marge Berer, “The Cairo 'Compromise' on Abortion and Its Consequences for Making Abortion Safe and Legal,” in Reproductive Health and Human Rights: The Way Forward, ed. Laura Reichenbach and Mindy Roseman (Philadelphia: University of Pennsylvania Press, 2009), 153.

\[16\] World Health Organization, “Reproductive Health Strategy,” 10.

\[17\] Ibid., 14.

\[18\] Berer, “The Cairo 'Compromise,'” 154.

----

## 1.2 - Introduction: Contraception and Reproductive Justice {.unnumbered}

### Authorship for Unit D {.unnumbered}

-   **Geraldine Matus (1987, 2003, 2017)**
-   **Justisse Faculty as a Collaborative copy edit and minor revisions (ongoing)**
-   **Laura Salamanca and Geraldine Matus (2019) major revisions and updates**

**SUGGESTED TIME TO COMPLETION: 5 to 7 weeks to complete**

Unit D will focus specifically on methods of birth control.

Please Review [Exam, Essay, and Journal Policies](https://justisse.ca/index.php/college/courseware/page/1740). You are responsible to conduct yourself with academic honesty.

### Unit D Introduction {.unnumbered}

#### Contraception and Reproductive Justice {.unnumbered}

The material in unit D is designed to equip the HRHP with a well-rounded understanding of the complex ways that we engage with our bodies and reproductive capacities. Birth control technologies are rich with meaning, and our interactions with them are by no means neutral. As we saw in Unit A, examining birth control in historical context allows us to see changing societal attitudes towards women, evolving understandings of sexuality, and the complexity of power dynamics. In unit D we examine all birth control strategies currently available, exploring clinical information and socio-cultural nuances of their use. This section provides an overview of the current international context of contraception and abortion, with a focus in North America. We are interested to know more information about your country or region through your journal submissions. 

In the international discourse, issues of reproductive health are linked to development goals within a global commitment to curb infant, child, and maternal mortality (Wang, 2010, p. 13). 2015 was the final year for the United Nations Millennium Development goals set in 2000 (WHO, 2019). Progress was made when it comes to sexual health, as deaths related to pregnancy and childbirth did fall by 40% overall in that time (short of the 75% target) (WHO, 2019). 

In 2015, 193 governments adopted a new 2030 Agenda for Sustainable Development which includes 17 Sustainable Development Goals (SDGs) (WHO, 2019; UNFPA, 2019, p. 18). The new agenda includes two targets relevant for family planning under broader goals pertaining to health, gender equality, and the empowerment of women and girls. The targets are to achieve “…universal access to sexual and reproductive health-care services, including for family planning, information and education, and the integration of reproductive health into national strategies and programs” by 2030 (target 3.7), and “…universal access to sexual and reproductive health and reproductive rights as agreed in accordance with the Programme of Action of the \[ICPD\] and the Beijing Platform of Action” (target 5.6). (UN, 2015, p. 3). 

The current international discourse centres contraception as essential to women's autonomy and well-being, and as crucial to community development (WHO, 2017). The World Health Organization has continued to focus on family planning as a strategy to prevent pregnancy-related adverse health outcomes (including unsafe abortion), reduce infant mortality (by reducing adolescent or closely spaced pregnancy), reduce HIV transmission (between partners and mom to baby), and empower people to make informed choices about their health (2018a).  We have much work to do to meet these targets, and advocacy in ensuring that abortion care is included as part of these initiatives, given the language agreed upon in the ICPD (see Section 1.1 Reproductive Rights in International Context). 

#### Reproductive Justice {.unnumbered} 

At an international level we have laid the groundwork for understanding sexual health issues as human rights issues, but we have stopped short of linking these to other indicators using the theoretical framework of reproductive justice. The fragmentation that is typical of international agreements means that the nuances are left to regional and national efforts. In the United States and Canada healthcare is mostly the domain of states and provinces, and there are vast differences in contraception provision and abortion access. 

Intellectual currents informed by critical race theory (particularly by women of colour in the United States) have, over the past twenty years, expanded discussions of reproductive rights to conceptualize _reproductive justice_ as the complete physical, mental, spiritual, political, social, and economic well-being of women and girls (Ross, 2006, p. 14). For example, the American organization SisterSong: Women of Colour Reproductive Health Collective discusses reproductive justice as linked to the ability of any woman to determine her reproductive destiny in relation to the conditions in her community, and not just as a matter of individual choice and access (Ross, 2006, p. 14). 

Given the history of sexual violence and lack of choice in reproduction, for Indigenous women and women of colour fighting for the right not to have children is equally as important as fighting for the right to have children, and the right to safely parent the children we have (Ross, 2006, p. 14). In a society where women earn less than men, where quality and affordable daycare and housing are scarce, and where racism is systemic, the opportunities for women to realize their goals are complex and systemically regulated (Egan and Gardner, 2007, p. 302). Thus, drawing on reproductive justice as a theoretical framework is important because it shifts the focus to reproductive oppression - “the control and exploitation of women, girls and individuals though our bodies, sexuality, labour and reproduction.” (Ross, 2006, p. 14). 

While gender as a theoretical lens used to shape health policy is necessary, persistent inequities in the design of our healthcare systems demand a paradigm shift towards an intersectional analysis. In the local context of Canada there are diverse factors influencing the sexual health of women and girls. We cannot ignore how continued colonialism, the oppressive approach of Canada's multiculturalism, and inequity in immigration policy contribute to health disparities. Feminists in the Global South and racialized women in the Global North have critiqued pro-choice movements for portraying women as overly autonomous and self-interested, failing to pay enough attention to their embeddedness in social environments. 

Applying a Reproductive Justice approach necessarily entails addressing the effects of colonialism and the economic and environmental inequalities that shape women's health in Canada and internationally. Autonomy is socially situated, contextualized by multiple public and personal relationships with political dimensions that structure our individual sense of self (Sherwin, 1998). This is particularly true for our ability to exert substantive power over our bodily autonomy. The HRHP will be well served to nestle teachings of body literacy well within the client's unique situation. 

#### Contraception {.unnumbered}

Contraception is by no means a universal given, and there is a high unmet need for choices in contraception worldwide. According to the World Health Organization, 214 million women who want to avoid pregnancy worldwide are not using a 'modern' contraceptive method (2018a). In the African continent 24.2% of women of reproductive age have an unmet need for contraception; In Latin America and the Caribbean, as well as Asia, levels of unmet need hover around 10% (UN, 2015). 

International bodies divide contraception into categories of 'traditional' and 'modern' methods for the purpose of data collection. 'Modern' methods include all CEDs, IUD, condoms, sterilization, Lactational Amenorrhea Method (LAM), Standard Days Method (SDM), Basal Body Temperature (BBT), TwoDay, and Sympto-thermal method (STM) (2018a). 'Traditional methods, according to the WHO, include calendar rhythm, and withdrawal (2018a). Further, most research focuses on married or 'in-union' women, and in many countries the needs of unmarried women are not considered when inquiring about contraceptive practices. This is an important gap in research data, as we also know that young women 15 - 19 years of age are more likely to have low birth weight babies, and to die during pregnancy or childbirth (WHO, 2011, p. 2). Thus, we do not have an accurate picture of contraceptive practices and needs of all women of reproductive age, let alone of folks who are non-binary, trans, or gender diverse. 

We know that on an international level contraception is used by a majority of women who are married or in unions in almost all regions of the world (UN, 2015, p. 1; Singh et al, 2018, p. 36). In 2015, 64% of married or in-union women of reproductive age worldwide were using some form of contraception. Contraceptive use tends to be higher in the global north than the global south, but access is uneven. For example, contraceptives are used by 75% of reproductive age married or in-union women in North America, 59% in Oceania, and 33% in Africa (UN, 2015, p. 1). Within these areas there are of course wide differences by region and across countries. 

Worldwide female sterilization and IUD are the two most common methods used by women in unions or married (UN, 2015, p. 2). 1 in 3 married or in-union women use female or male sterilization, IUDs, or implants - these methods account for 56% of worldwide contraceptive prevalence in 2015 (UN, 2015, p. 2). Shorter-term methods are less common among married or in-union women worldwide. In 2015 9% were using the pill, 8% relied on external condoms, and 5% used injectables (UN, 2015, p. 2). About 6% of these women were using traditional methods (rhythm or withdrawal). 

Overall, short-term and reversible methods such as the pill, injectable, and external condoms are more common than others in Africa and Europe, whereas long acting and permanent methods such as sterilization, implants, and IUDs are more common in Asia and North America (UN, 2015, p. 2). Worldwide there are at least 45 countries in which a single method constituted 50% or more of all use in 2015. The methods that dominate in this way include the oral CED (15 countries), injectables (10 countries), and IUD (7 countries) (UN, 2015).  

There are many technologies in use that have never seen the light of day in some countries, while they are ubiquitous in others. In 2004 Canadian women had access to about 35% of all contraceptive products available worldwide, and to 37% of all artificial CEDs available worldwide (SOGC, 2015, S9). By comparison, women in the United States have access to 58% of all contraceptive products worldwide; those in the UK had access to 52%, and those in France and Sweden had access to 44% of all contraceptive products worldwide (SOGC, 2015, S9). 

A narrower range of contraceptive options available may be due to lack of applications by drug manufacturers, non-conformity with local requirements such as the stringent requirements of Health Canada, and time delays to approval (SOGC, 2015, S9). There is inequality in access worldwide because markets are uneven, because health regulations vary widely, and when innovation in contraceptive technologies is driven by profit, those who will pay for it will receive first pick. 

According to the Society of Obstetricians and Gynecologists of Canada, sexually active women in Canada will spend 3 years or fewer pregnant, attempting to conceive, or immediately postpartum (SOGC, 2015, S5). In Canada, about 54.3% of sexually active women not trying to conceive used the external condom as their contraceptive (ARCC 2017, p. 1). As of 2015, the most commonly used methods of contraception in Canada were oral CEDs (44%), external condoms, and withdrawal (12%) (ARCC, 2017, p. 1). Only about 2.4% of sexually active women practice some form of “Natural Family Planning” (ARCC, 2017, p. 1). 

In Canada, major barriers to contraceptive use include regional and economic differences (ARCC, 2017, p. 2). There are significantly higher odds of no contraceptive use in women over 40, those with a high school education or less, those living in PEI or Newfoundland, married people, and those with household incomes under 100K (ARCC, 2017, p. 2). Recently arrived immigrant women are less likely than those Canadian-born to be using more effective methods of contraception at the time of conceiving an unintended pregnancy, and more likely to have experienced barriers to accessing contraception (SOGC, 2015, S6). 

Unit D provides a comprehensive curriculum on all methods of birth control available, including discussion of contraceptive counselling to prepare the HRHP for supporting clients and their reflections and engagement with their sexual and reproductive health. 

#### Abortion {.unnumbered}

Abortion is an internationally common procedure, yet access is not uniformly legal or safe. There are wide differences in abortion legislation among member states of the United Nations, however, it is agreed upon that improving access and quality of post-abortion care is essential to minimizing harm from unsafe abortion (Singh et al, 2018, p. 6). There are often substantial gaps between a country's specified abortion laws, and the services that women can actually obtain (Singh et al, 2018, p. 14). 

As of 2010 - 2014, about 35 abortions occur each year per 1,000 women aged 15 - 44 worldwide (Singh et al, 2018, p. 8). We know abortions occur as frequently in countries where there are legal restrictions as they do in countries where legislation is liberal (Singh et al, 2018, p. 4). Illegality does nothing to decrease abortion—it only makes it more likely to be unsafe (Singh, et al, 2018, p. 5). Still, only 37% of the world's 1.64 billion women of reproductive age live in a country where abortion is available without restriction as to reason, although there are gestational limits in all cases (Singh et al, 2018, p. 15). 

Abortion is considered safe when provided via a recommended method by an appropriately trained provider; it is considered less safe if only one of these criteria is met, and least safe is neither criteria are met (Singh et al, 2018, p. 5). An estimated 55% of all abortions worldwide are safe, 31% are less safe, and 14% are least safe (Singh et al, 2018, p. 5). Of the more than 25 million unsafe abortions that occur every year globally, about 97% take place in the Global South (Singh et al, 2018, p. 10). Between 2010 and 2017, 28 countries made legislative changes moving away from outright prohibition towards broadening reasons under which abortion is permissible (Singh et al, 2018, p. 17). 

Among the many barriers that can exist to abortion care, one of the most critical is lack of trained providers (WHO, 2015, p. 3). There is a serious global deficit of skilled health care professionals and moving from exclusive OB/GYN care towards a wider range of health workers is an increasingly important strategy (WHO, 2015, p. 3). Many abortion techniques, particularly those in early pregnancy, can be provided on an outpatient basis at the primary care level. Medical abortion techniques have simplified the health worker skills needed for abortion provision, making it possible to consider expanding roles towards including non specialist doctors, physician assistants, nurse practitioners, nurse-midwives, midwives, and pharmacists. These types of health professionals are still insufficiently used in many settings, including Canada.  

The complexity of legality vs. access, and of logistical barriers where there is access, means that some people who live in countries such as Canada where abortion is available for any reason, are still unable to get one. There is great need for advocacy both in securing access to safe and free abortion, and comprehensive counselling in contraception. Unit D provides the HRHP with an introduction to the topic. 

### Bibliography {.unnumbered}

-   ACOG - American Congress of Obstetricians and Gynecologists. (2011). 2011 Women's Health Stats & Facts. _American Congress of Obstetricians and Gynecologists._ Washington, DC. 
-   ARCC - Abortion Rights Coalition of Canada. (2017, July). Position Paper #37: Contraceptive Use in Canada. _Abortion Rights Coalition of Canada._ Vancouver, BC. 
-   Darroch, J., Woog, V., Bankole, A., Ashford, L. S. (2016). _Adding it up: Costs and benefits of meeting the contraceptive needs of adolescents._ New York: Guttmacher Institute. 
-   Egan, C., Gardner, L. (2007). Racism, Women's Health and Reproductive Freedom. In _Gender Relation in Global Perspective._ N. Cook (Ed.). Toronto: Canadian Scholar's Press. 
-   Ross, L. (2006). Understanding Reproductive Justice: Transforming the Pro-choice movement. _Off Our Backs, 36_(4). 
-   Sherwin, S. (1998). A Relational Approach to Autonomy in Health Care. _The Politics of Women's Health: Exploring Agency and Autonomy_ (p. 19 - 47)_._ Philadelphia: Temple University. 
-   SOGC. (2015). Chapter 1: Contraception in Canada. Canadian Contraception Consensus (Par 1 of 4). _Journal of Obstetricians and Gynecologists of Canada, Oct_ (S1 - S12). 
-   Singh, S., Remez, L., Sedgh, G., Kwok, L., & Onda, T. (2018). _Abortion Worldwide 2017: Uneven Progress and Unequal Access._ Guttmacher Institute. [https://www.guttmacher.org/report/abortion-worldwide-2017](https://www.guttmacher.org/report/abortion-worldwide-2017) 
-   United Nations Department of Economic and Social Affairs. (2015). Trends in Contraceptive Use Worldwide. New York, New York. 
-   UNFPA Division of Communications and Strategic Partnerships. (2019). _State of the world population 2019: Unfinished Business the pursuit of rights and choices FOR ALL._ 
-   Wang, G. (2010). _Reproductive Health and Gender Equality: Method, Measurement, and Implications._ Farnham, England: Ashgate Publishing Limited. 
-   World Health Organization - WHO. (2014). _Reproductive Health Strategy to Accelerate Progress towards the Attainment of International Development Goals and Targets._ Department of Reproductive Health and Research. Geneva: World Health Organization.
-   World Health Organization - WHO. (2015). _Health worker roles in providing safe abortion care and post-abortion contraception._ Department of Reproductive Health and Research. Geneva: World Health Organization. [https://www.actioncanadashr.org/sites/default/files/2019-04/WHO\_RHR\_15.15\_eng.pdf](https://www.actioncanadashr.org/sites/default/files/2019-04/WHO_RHR_15.15_eng.pdf)
-   World Health Organization - WHO. (2017). _Family Planning / Contraception Fact Sheet._ Geneva: World Health Organization. [http://www.who.int/mediacentre/factsheets/fs351/en/](http://www.who.int/mediacentre/factsheets/fs351/en/) 
-   World Health Organization - WHO. (2018a). _Family Planning / Contraception Fact Sheet._ Geneva: World Health Organization. [https://www.who.int/en/news-room/fact-sheets/detail/family-planning-contraception](https://www.who.int/en/news-room/fact-sheets/detail/family-planning-contraception) 
-   World Health Organization - WHO. (2018b). _Adolescent Pregnancy Fact Sheet_. Geneva: World Health Organization. [https://www.who.int/en/news-room/fact-sheets/detail/adolescent-pregnancy](https://www.who.int/en/news-room/fact-sheets/detail/adolescent-pregnancy) 
-   World Health Organization - WHO. (2018c). World Health Statistics 2018: Monitoring Health for the Sustainable Development Goals. Geneva: World Health Organization. [https://apps.who.int/iris/bitstream/handle/10665/272596/9789241565585-eng.pdf](https://apps.who.int/iris/bitstream/handle/10665/272596/9789241565585-eng.pdf) 
-   World Health Organization - WHO (2011). _WHO Guidelines on Preventing Early Pregnancy and Poor Reproductive Outcomes Among Adolescents in Developing Countries_. Geneva: World Health Organization. [https://www.who.int/immunization/hpv/target/preventing\_early\_pregnancy\_and\_poor\_reproductive\_outcomes\_who\_2006.pdf](https://www.who.int/immunization/hpv/target/preventing_early_pregnancy_and_poor_reproductive_outcomes_who_2006.pdf) 
-   WHO, UNICEF, UNFPA, World Bank Group and UN Population Division. (2019). _Executive summary: Trans in Maternal Mortality 2000 to 2017._ Geneva: World Health Organization. [https://apps.who.int/iris/bitstream/handle/10665/327596/WHO-RHR-19.23-eng.pdf](https://apps.who.int/iris/bitstream/handle/10665/327596/WHO-RHR-19.23-eng.pdf) 

----

# 1.4 - Required Readings {.unnumbered}

## **Unit D Required Readings**

**All online material is Required Reading in addition to the following links, books, articles, etc. listed below.**

### Unit D Section 2: Contraceptive Effectiveness   {.unnumbered}

1.  Polis, C. B., Bradley, S. E. K., Bankole, A., Onda, T, Croft, T., & Singh, S. (2016). **Typical-use contraceptive failure rates in 43 countries with Demographic and Health Survey data: summary of a detailed report.** _Contraception 94,_ p. 11 - 17. [http://dx.doi.org/10.1016/j.contraception.2016.03.011](http://dx.doi.org/10.1016/j.contraception.2016.03.011)
2.  Trussell, J. (2011). **Contraceptive failure in the United States**. _Contraception 83_, p. 397 - 404. DOI:10.1016/j.contraception.2011.01.021

### Unit D Section 3: Barrier Methods, Spermicide, and Barrier Gel {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Non-Hormonal Contraception”** section [https://www.sexandu.ca/contraception/non-hormonal-contraception/](https://www.sexandu.ca/contraception/non-hormonal-contraception/)
2.  Planned Parenthood Federation of America Website. Explore the following sections: **Condom, Diaphragm, Cervical Cap, Birth Control Sponge, Spermicide**. [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control)
3.  The Family Planning Association (UK) Website. Explore the following sections: **Condoms (male and female), and Diaphragms and caps.** [https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help)
4.  The Boston Women's Health Collective. (2011). **“Barrier Methods: Male condom, Female Condom, Diaphragm, Cervical Cap, Sponge, Spermicides”** In _Our Bodies, Ourselves,_ pp. 211 - 222. NY: Touchtone - Simon & Schuster.
5.  Angier, Natalie. (1999). **Chapter 3: Default Line: Is the Female Body a Passive Construct? In** _**Woman: An Intimate Geography**._ New York, NY: Haughton Mifflin Co.

### Unit D Section 4: Artificial Contraceptive Endocrine Disruptors {.unnumbered}

1.  Grigg-Spall, H. (2013). **_Sweetening the Pill or How We Got Hooked on Hormonal Birth Control_****.** Alresford, UK: Zero Books.
2.  Marks, L. V. (2001). _**Sexual chemistry:**_ **_A history of the contraceptive pill._** New Haven, CT: Yale University Press.
3.  Rako, S. (2003). **_No More Periods? The Blessings of the Curse._** Lincoln, NE: Universe, Inc.
4.  Pharmacia & Upjohn Company. (2004). Depo-Provera® **Contraceptive Injection.** Physician Information. NY, NY: Pfizer Inc. 
5.  The Society of Obstetricians and Gynaecologists of Canada Website, “**Hormonal Contraception”** section [https://www.sexandu.ca/contraception/hormonal-contraception/](https://www.sexandu.ca/contraception/hormonal-contraception/)
6.  Planned Parenthood Federation of America Website. Explore the following sections: **Implant, Patch, Pill, Shot.** [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control)
7.  The Family Planning Association (UK) Website. Explore the following sections: **Combined Pill, Implant, Injection, Patch, vaginal ring, IUS, Long acting reversible contraception (LARC), and protestogen-only pill (POP)**. [https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help)
8.  The Boston Women's Health Collective. (2011). **“Hormonal Methods: Pill, Minipill, Ring, Patch, Shot” and “Implanon”** In _Our Bodies, Ourselves,_ pp. 223 - 237. NY: Touchtone - Simon & Schuster.

### Unit D Section 5: Herbal Contraceptive Endocrine Disruptors {.unnumbered}

1.  Hoffman, David **[Medical Herbalism: The Science and Practice of Herbal Medicine](https://drive.google.com/file/d/1dqe9hj5t7Ej_4FYYKPHK9OgSBbyF92lp/view?usp=sharing)** Chapters 18 Reproductive System, Chapter 20 Immune System, and Chapter 21 Endocrine System. Click on the LINK to download a PDF version of the book.
2.  Weed, S. (1996), **[_Wise woman herbal for the childbearing year_.](https://www.amazon.com/Wise-Woman-Herbal-Childbearing-Year/dp/0961462000)** Ash Tree Publishing. 

### Unit D Section 6: Intra Uterine Device {.unnumbered}

1.  Shaniqua. (2011, January 11). **[Not Your Mother's IUD: Benefits and Risks of Modern IUDs](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/Not%20Your%20Mothers%20IUD%20NWHN.pdf)****.** _Women's Health Activist Newsletter._ 

### Unit D Section 7: Fertility Awareness-Based Methods (FABMs) {.unnumbered}

1.  Matus, G. (2017). [**Fertility Awareness Based Methods (FABMs)**.](https://docs.google.com/presentation/d/1GC_wtm94wc9GfnYiiEDwKrqheXfp6FO4BUrg7kS-gXY/edit) Public Introductory Talk. See JuPA Members Access Section 8: HRHP Practice Resources in the HRHP Courseware
2.  Priests for Life. (n.d.). **_Birth Control and NFP: What's the difference?_** \[Weblog post\] Retrieved from:  [http://www.priestsforlife.org/library/4741-birth-control-and-nfp-whats-the-difference](http://www.priestsforlife.org/library/4741-birth-control-and-nfp-whats-the-difference) Download PDF here **[Priests for Life](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/FABM%20Required%20Reading/2.%20Priests%20For%20Life%20-%20Birth%20Control%20and%20NFP_%20What%27s%20the%20Difference_.pdf)**
3.  Smothers, H. (2018, February 28). 1**5 Facts About the Rhythm Method** of Contraception: What you need to know about the “calendar method” of birth control. In _Cosmopolitan._ Retrieved from: [https://www.cosmopolitan.com/sex-love/a18925095/calendar-rhythm-method/](https://www.cosmopolitan.com/sex-love/a18925095/calendar-rhythm-method/)  Download PDF here **[15 Facts about the Rhythm Method](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/3.%20Smothers_15%20Facts%20about%20the%20Rhythm%20Method.pdf)**
4.  Mason, C. (2008, September 24). **Cyclebeads:** The UNFPA Discovers Natural Family Planning, Sort Of. In _The Population Research Institute 10_(39). Retrieved from: [https://www.pop.org/cyclebeads-the-unfpa-discovers-natural-family-planning-sort-of/](https://www.pop.org/cyclebeads-the-unfpa-discovers-natural-family-planning-sort-of/)  Download PDF here **[Cyclebeads](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/4.%20Mason_%20Cyclebeads_%20The%20UNFPA%20Discovers%20Natural%20Family%20Planning%2C%20Sort%20Of.pdf)**
5.  D'Agostino, J. A. (2011, April 26). **The Uses and Abuses of Cyclebeads.** In _The Catholic World Report._ Retrieved from: [http://www.catholicworldreport.com/2011/04/26/the-uses-and-abuses-of-cyclebeads/](http://www.catholicworldreport.com/2011/04/26/the-uses-and-abuses-of-cyclebeads/) Download PDF here **[The Uses and Abuses of Cyclebeads](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/5.%20D%27Augustino_The%20Uses%20and%20Abuses%20of%20CycleBeads.pdf)**
6.  Marston, C. A., & Church, K. (2016). **Does the evidence support global promotion of the calendar-based Standard Days Method® of contraception?** In _Contraception 93_, p. 492 - 497. DOI: [http://dx.doi.org/10.10116/j.contraception.2016.01.006](http://dx.doi.org/10.10116/j.contraception.2016.01.006) Download PDF here **[Marston on Standard Days](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/FABM%20Required%20Reading/6.%20Marston%20Church_Does%20the%20evidence%20support%20SDM.pdf)**
7.  Townsend, J. W. & Wright, K. (2016). **The pitfalls of using selective data to represent the effectiveness, relevance and utility of the Standard Days Method (SDM) of contraception** \[Letter to the editor\]. In _Contraception 94,_ p. 374. DOI:  [http://dx.doi.org/10.1016/j.contraception.2016.06.003](http://dx.doi.org/10.1016/j.contraception.2016.06.003) Download the PDF here **[Townsend on Pitfalls of Selective Data](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/7.%20Wright%20%26%20Townsend%2C%208.%20Sinai_SDM%20debate.pdf)**
8.  Sinai, I. (2016). **Standard Days Method effectiveness: Opinion disguised as scientific review** \[Letter to the editor\]. _Contraception 94_, p. 375. DOI: [http://dx.doi.org/10.1016/j.contraception.2016.04.020](http://dx.doi.org/10.1016/j.contraception.2016.04.020) Dowload the PDF here **[Sinai 2016](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/1.%20Sinai%202016%20SDM%20debate.pdf)**
9.  Marston, C., & Church, K. (2016). **Response to the Letters to the Editor from Irit Sinai** “Standard Days Method Effectiveness: opinion disguised as scientific review” and Kelsey Wright, Karen Hardee, and John Townsend “The pitfalls of using selective data to represent the effectiveness, relevance and utility of the Standard Days Method of contraception” \[Letter to the editor\]. In _Contraception 94_, p. 376 - 377. DOI: http://dx.doi.org.10.1016/j.contraception.2016.06.003 Download the PDF here **[Marston & Church 2016](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/FABM%20Required%20Reading/9.%20Marston%20and%20Church_SDM%20debate.pdf)**
10.  Green, A. (2018). **Not your mother's rhythm method.** In _U.S. Catholic: Faith in Real Life._ Retrieved from: [http://www.uscatholic.org/life/2009/04/not-your-mother%E2%80%99s-rhythm-method](http://www.uscatholic.org/life/2009/04/not-your-mother%E2%80%99s-rhythm-method) Download PDF here **[Not your mother's rhythm method](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/11.%20Green_Not%20your%20mothers%20rhythm%20method.pdf)**
11.  The Society of Obstetricians and Gynaecologists of Canada Website, “Natural Methods” section [https://www.sexandu.ca/contraception/natural-methods/](https://www.sexandu.ca/contraception/natural-methods/)
12.  Planned Parenthood Federation of America Website. Explore the following sections: Breastfeeding as Birth Control, Fertility Awareness Methods (FAMs), Outercourse and Abstinence. [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control) 
13.  The Family Planning Association (UK) Website. Explore the following section: Natural family planning. [https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help) 
14.  The Boston Women's Health Collective. (2011). Chapter 1 “Fertility Awareness Method (FAM) and Other Natural Methods” _pp. 26-29_ and _Chapter 9 Birth Control_ the section on fertility awareness based methods pp. 248 - 251. In: **_Our Bodies Ourselves: Completely Revised and Updated_.** New York: Simon & Schuster. 
15.  FACTS. (2016, July). **[_A Rating of Fertility Apps Marketed to Avoid Pregnancy_](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/16.%20FACTS_Rating%20of%20Apps%20Synopsis.pdf)****[.](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/16.%20FACTS_Rating%20of%20Apps%20Synopsis.pdf)** (one-page synopsis). 
16.  Grigg-Spall, H. (2016, May 20). **Basal Body Thermometer vs. Daysy Fertility Computer** \[Weblog post\]. In _Daysy®._ Retrieved from: [https://usa.daysy.me/blog/basal-body-thermometer-vs-daysy-fertility-computer/](https://usa.daysy.me/blog/basal-body-thermometer-vs-daysy-fertility-computer/)  Download the PDF here [**Grigg-Spall 2016 on Daysy**](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/3.%20Natural%20fertility%20awareness%20-%20fertility%20tracking%20with%20Daysy%21.pdf)
    1.  Alternatively you can watch the following Podcast [MMP Ep. 83: The Daysy Fertility Tracker and Fertility Awareness with Holly Grigg-Spall](https://www.bullhorn.fm/themodernmamaspodcast/posts/M9yMxrm-mmp-ep-83-the-daysy-fertility-tracker-and-fertility-awareness-with-holly-grigg-spall)
17.  Ong, T. (2018, January 16). Contraceptive app hit with complaints after being blamed for 37 unwanted pregnancies: The _Natural Cycles_ app uses an algorithm to determine when women are fertile. In _The Verge_. Retrieved from: [https://www.theverge.com/2018/1/16/16895978/natural-cycles-contraceptive-app-unwanted-pregnancies-complaint](https://www.theverge.com/2018/1/16/16895978/natural-cycles-contraceptive-app-unwanted-pregnancies-complaint) 
18.  **[Unit D Supplement 1 NFP and FAM Effectiveness](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/Unit%20D%20Supp%203%20NFP%20and%20FAM%20Effectiveness.pdf)**
19.  **[Unit D Supplement 2 1981 NFP Effectiveness](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/Unit%20D%20Supp%202%20NFP%20effectiveness%20Aldred.pdf)**
20.  Frank-Herrmann, P., Heil, J., Gnoth, C., Toledo, E., Baur, S., Pyper, C., … & Freundl, G (2007). The **effectiveness of a fertility awareness based method to avoid pregnancy in relation to a couple's sexual behaviour** during the fertile time: a prospective longitudinal study. Human reproduction, p. 1 - 10. DOI:10.1090/humrep/dem003  Download the PDF here **[Frank-Hermann 2007](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/4.%20Frank-Herrmann%202007%20NFP%20effectiveness.pdf)** 
21.  Manhart, M. D., Duane, M., Lind, A., Sinai, I., & Golden-Tevald, J. (2013). **Fertility awareness-based methods of family planning: A review of effectiveness for avoiding pregnancy using SORT.** Osteopathic Family Physician 5, 2 - 8. [http://dx.doi.org/10.1016/j.osfp.2012.09.002](http://dx.doi.org/10.1016/j.osfp.2012.09.002)  Download the PDF here **M[anhart FABM SORT](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/5.%20Manhart%20et%20al%202013.pdf)**
22.  **[Justisse 2015 Continuing Education Event on BAFTing](https://drive.google.com/drive/folders/1GMUI7S1sb0ISbI-zg0ux8L2wDa1Xe0xy?usp=sharing)**

### Unit D Section 8: Surgical Methods {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Tubal Ligation & Tubal Occlusion”** section [https://www.sexandu.ca/contraception/non-hormonal-contraception/#tc8](https://www.sexandu.ca/contraception/non-hormonal-contraception/#tc8)
2.  Planned Parenthood Federation of America Website. Explore the section on **Sterilization.** [https://www.plannedparenthood.org/learn/birth-control/sterilization](https://www.plannedparenthood.org/learn/birth-control/sterilization)
3.  The Family Planning Association (UK) Website. Explore the section on **Sterilisation (male and female)**. [https://www.fpa.org.uk/contraception-help/sterilisation-male-and-female](https://www.fpa.org.uk/contraception-help/sterilisation-male-and-female) 
4.  The Boston Women's Health Collective. (2011). **“Permanent Methods: Female and Male Sterilization”** In _Our Bodies, Ourselves,_ pp. 242 - 244. NY: Touchtone - Simon & Schuster.
5.  Stacey, D. (2018, April 30). **Adiana Permanent Birth Control**. _Verywellhealth.com_. Retrieved from: [https://www.verywellhealth.com/adiana-permanent-birth-control-906804](https://www.verywellhealth.com/adiana-permanent-birth-control-906804) and [https://www.verywellhealth.com/the-essure-procedure-906906](https://www.verywellhealth.com/the-essure-procedure-906906)
6.  Planned Parenthood Federation of America Website. Explore the section **What do I need to know about trans health care?** [https://www.plannedparenthood.org/learn/sexual-orientation-gender/trans-and-gender-nonconforming-identities/what-do-i-need-know-about-trans-health-care](https://www.plannedparenthood.org/learn/sexual-orientation-gender/trans-and-gender-nonconforming-identities/what-do-i-need-know-about-trans-health-care)
7.  The Boston Women's Health Collective. (2011). **“Hysterectomy and Oophorectomy”** In Our Bodies, Ourselves, pp. 628 - 634. NY: Touchtone - Simon & Schuster.
8.  Browse the **HERS Foundation** website. [https://www.hersfoundation.org/](https://www.hersfoundation.org/)
9.  Browse the **Coalition for Post Tubal Women's** website [http://tubal.org/](http://tubal.org/)
10.  Angier, Natalie. (1999). **Chapter 5 “Suckers and Horns: The Prodigal Uterus In** **_Woman: An Intimate Geography._** New York, NY: Haughton Mifflin Co. 
11.  Angier, Natalie. (1999). **Chapter 6 “Mass Hysteria: Losing the Uterus” In** **_Woman: An Intimate Geography._** New York, NY: Haughton Mifflin Co. 
12.  Ontario's Expert Panel on **Best Practices in the Use of Hysterectomy.** (2002). _Achieving Best Practices in the Use of Hysterectomy_. Toronto, ON: Ontario Women's Health Council
13.  The Current (CBC Radio). (November 13, 2018). [Indigenous women kept from seeing their newborn babies until agreeing to sterilization, says lawyer](https://www.podchaser.com/podcasts/the-current-34462/episodes/indigenous-women-kept-from-see-33627730).
14.  ACOG - American College of Obstetricians and Gynecologists. (2017). **[Sterilization of women: ethical issues and considerations](https://www.acog.org/-/media/project/acog/acogorg/clinical/files/committee-opinion/articles/2017/04/sterilization-of-women-ethical-issues-and-considerations.pdf).** Committee Opinion No. 695. _The American College of Obstetricians and Gynecologists._

### Unit D Section 9: Male Contraception {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Male Condom” s**ection [https://www.sexandu.ca/contraception/non-hormonal-contraception/](https://www.sexandu.ca/contraception/non-hormonal-contraception/) 
2.  Planned Parenthood Federation of America Website. Explore the section on the **Condom** [https://www.plannedparenthood.org/learn/birth-control/condom](https://www.plannedparenthood.org/learn/birth-control/condom) 
3.  The Family Planning Association (UK) Website. Explore the section on **Condoms (external)** [https://sexwise.fpa.org.uk/contraception/condoms-external](https://sexwise.fpa.org.uk/contraception/condoms-external) 
4.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Withdrawal (Coitus interruptus)”** section https://www.sexandu.ca/contraception/natural-methods/#tc3
5.  Planned Parenthood Federation of America Website. Explore the section on **Withdrawal (Pull Out Method).** https://www.plannedparenthood.org/learn/birth-control/withdrawal-pull-out-method
6.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Vasectomy”** section [https://www.sexandu.ca/contraception/non-hormonal-contraception/#tc7](https://www.sexandu.ca/contraception/non-hormonal-contraception/#tc7) 
7.  Planned Parenthood Federation of America Website. Explore the section on **Vasectomy** [https://www.plannedparenthood.org/learn/birth-control/vasectomy](https://www.plannedparenthood.org/learn/birth-control/vasectomy) 
8.  The Family Planning Association (UK) Website. Explore the section on **Sterilisation (male and female).** https://www.fpa.org.uk/download/your-guide-to-male-and-female-sterilisation/
9.  The Boston Women's Health Collective. (2011). **“Permanent Methods: Female and Male Sterilization”** In _Our Bodies, Ourselves,_ pp. 242 - 244. NY: Touchtone - Simon & Schuster. 
10.  Behre, H. M., Zitzmann, M., Anderson, R. A., Handelsman, D. J., Lestari, S. W., McLachlan, R. I., … Colvard, D. S. (2016). **Efficacy and Safety of an Injectable Combination Hormonal Contraceptive for Men**. _Journal of Clinical Endocrinology Metab (101),_ 4779 - 4788. DOI:10.1210/jc.2016-2141
11.  The Current (CBC Radio). (2019, March 29). **Researchers are getting closer to a male birth control gel, but will men use it?** (Article and audio). Retrieved from [https://www.cbc.ca/radio/thecurrent/the-current-for-march-29-2019-1.5076529/researchers-are-getting-closer-to-a-male-birth-control-gel-but-will-men-use-it-1.5076533](https://www.cbc.ca/radio/thecurrent/the-current-for-march-29-2019-1.5076529/researchers-are-getting-closer-to-a-male-birth-control-gel-but-will-men-use-it-1.5076533)

### Unit D Section 10: Emergency Contraception {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Emergency Contraception”** section https://www.sexandu.ca/contraception/emergency-contraception/
2.  Planned Parenthood Federation of America Website. Explore the section on **Emergency Contraception.** [https://www.plannedparenthood.org/learn/morning-after-pill-emergency-contraception](https://www.plannedparenthood.org/learn/morning-after-pill-emergency-contraception)
3.  The Family Planning Association (UK) Website. Explore the section on **Emergency Contraception** [https://www.sexwise.fpa.org.uk/contraception/emergency-contraception](https://www.sexwise.fpa.org.uk/contraception/emergency-contraception) 
4.  The Boston Women's Health Collective. (2011). **“Emergency Contraception”** In _Our Bodies, Ourselves,_ pp. 251 - 256. NY: Touchtone - Simon & Schuster. 
5.  Unit D Supplement 9 **[Effective Use of the Emergency Contraceptive Pill](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/D%2010.2%20Emergency%20Contraception%20and%20Fertility%20Awareness.pdf)**
6.  Follow the links in-text in Section 10.4 to read more about each herb at [www.sisterzeus.com](http://www.sisterzeus.com/) 
7.  Bennett, R. (2017, May 26). **Wild Carrot Exploration**, Summary, August 2011. _Wise Woman Healing Ways._ [https://www.robinrosebennett.com/resources/wild-carrot-exploration-summary-august-2011](https://www.robinrosebennett.com/resources/wild-carrot-exploration-summary-august-2011) 

### Unit D Section 11: Abortion {.unnumbered}

1.  NAF - National Abortion Federation (January 28, 2021). [Celebrating 33 Years of Legal Abortion in Canada](https://prochoice.org/celebrating-33-years-of-legal-abortion-in-canada/). 
2.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Abortion” section** [https://www.sexandu.ca/pregnancy/unplanned-pregnancy/#tc4](https://www.sexandu.ca/pregnancy/unplanned-pregnancy/#tc4) 
3.  Planned Parenthood Federation of America Website. Explore the section on **Abortion**. [https://www.plannedparenthood.org/learn/abortion](https://www.plannedparenthood.org/learn/abortion) 
4.  The Family Planning Association (UK) Website. Explore the section on **Abortion**. [https://www.sexwise.fpa.org.uk/unplanned-pregnancy/abortion-your-questions-answered](https://www.sexwise.fpa.org.uk/unplanned-pregnancy/abortion-your-questions-answered) 
5.  The Boston Women's Health Collective. (2011). **“Abortion”** In _Our Bodies, Ourselves,_ pp. 316 - 346. NY: Touchtone - Simon & Schuster. 
6.  NAF - National Abortion Federation. (n.d). [_**Has Your Physician Refused to Provide a Referral for Abortion Care? A Patient's Guide to Action**._](https://justisse.ca/index.php/college/ad_courseware/page/Has%20Your%20Physician%20Refused%20to%20Provide%20a%20Referral%20for%20Abortion%20Care?%20A%20Patient%E2%80%99s%20Guide%20to%20Action) PDF 
7.  **_[Steps for Performing Manual Vacuum Aspiration (MVA) Using the Ipas MVA Plus® and Ipas EasyGrip® Cannulae.](https://www.ipas.org/resource/steps-for-performing-manual-vacuum-aspiration-using-the-ipas-mva-plus-and-easygrip-cannulae/)_** Chapel Hill, NC: Ipas. 
8.  Ipas. (2018). [Roots of Change: A step-by-step advocacy guide for expanding access to safe abortion](https://www.ipas.org/resource/roots-of-change-a-step-by-step-advocacy-guide-for-expanding-access-to-safe-abortion/)_._ Chapel Hill: Ipas. Read pages 1 - 9. 
9.  Follow the links in-text to read more about each herb at [www.sisterzeus.com](http://www.sisterzeus.com/) 
10.  **Pregnancy & Herbal Abortion: Week by Week** (excerpt from _Herbal Abortion - The Fruit of the Tree of Knowledge_ by Uni M. Tiamat). [http://www.sisterzeus.com/hsp4wbw.htm](http://www.sisterzeus.com/hsp4wbw.htm)
11.  **How Herbs Can Interfere with Pregnancy** by Sisterzeus. [http://www.sisterzeus.com/hInterfPr.htm](http://www.sisterzeus.com/hInterfPr.htm)
12.  **A Word About Pregnancy Termination** by Sisterzeus. (2014). [http://www.sisterzeus.com/PregT.htm](http://www.sisterzeus.com/PregT.htm)
13.  Weed, S. (1986). **_Wise Woman Herbal for the Childbearing Year._** Woodstock, NY. Ash Tree Publishing. 

### Unit D Section 12: Other Methods {.unnumbered}

There are no required readings for this section. However, you may want to read some of the material provided in Section 12.3 Bibliography for your own reference and pondering. 

### Unit D Section 13: Sexual Health Counselling {.unnumbered}

1.  Loeber, O. (2001). **Cross-Cultural Aspects of Contraceptive Counselling.** _Proceedings from the XI International Meeting of the Society for the Advancement of Reproductive Care._ [Click here for link](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitF/cross%20cultural%20aspects.pdf) 
2.  The Society of Obstetricians and Gynaecologists of Canada Website, **“It's a plan” section** https://www.sexandu.ca/contraception/its-a-plan/ 
3.  Planned Parenthood Federation of America Website. Which birth control is right for me? Quiz. https://www.plannedparenthood.org/bc/birth\_control\_quiz 
4.  The Family Planning Association (UK) Website. Explore the section **Which method of contraception is right for me?** [https://www.sexwise.fpa.org.uk/contraception/which-method-contraception-right-me](https://www.sexwise.fpa.org.uk/contraception/which-method-contraception-right-me)
5.  Fleener, P. E. (n.d.). **“How to Make Your Own Genogram”** in _Mental Health Today._ [http://www.mental-health-today.com/articles/genogram.htm](http://www.mental-health-today.com/articles/genogram.htm) 
6.  Exploring Your Mind. (2018, March 24). **“A Step-by-Step Guide to Making a Genogram”** in _Exploring Your Mind._ [https://exploringyourmind.com/step-by-step-guide-genogram/](https://exploringyourmind.com/step-by-step-guide-genogram/)
7.  **_If These Walls Could Talk_** **,1996.** HBO Home Video Prod., Cher and Nancy Savoca Dirs., HBO Studios
8.  Action Canada for Sexual Health and Rights. (2014). _**Access at a Glace: Abortion Services in Canada.**_ (pdf). [https://www.actioncanadashr.org/sites/default/files/2019-09/7904\_ActionCanada\_AccessAtaGlanceTables\_F.pdf](https://www.actioncanadashr.org/sites/default/files/2019-09/7904_ActionCanada_AccessAtaGlanceTables_F.pdf) 
9.  National Abortion Federation - NAF. (2005). **_the abortion option - [A Values Clarification Guide for Health Care Professionals](http://prochoice.org/pubs_research/publications/downloads/professional_education/abortion_option.pdf)_**[**.**](http://prochoice.org/pubs_research/publications/downloads/professional_education/abortion_option.pdf) Washington, DC. **Complete Sections A and B of Part II - Tools for Clarifying Our Values (p. 7 - 15).**
10.  Baker, Aspen (2015). _**ProVoice: How to Keep Listening When the World Wants a Fight**._ Oakland: Berrett Koehler. Chapter 1 and 2. 
    1.  Alternatively, listen to Aspen Baker's **TedTalk [https://www.ted.com/talks/aspen\_baker\_a\_better\_way\_to\_talk\_about\_abortion?language=en](https://www.ted.com/talks/aspen_baker_a_better_way_to_talk_about_abortion?language=en)**

----

# 1.5 - Suggested Readings {.unnumbered}

### Unit D Suggested Readings {.unnumbered}

1.  **_A Co-operative Method of Natural Birth Control._** Margaret Nofziger. 4th ed. Summertown, TN: The Book Publishing Company
2.  **_Taking Charge of Your Fertility_.**  Revised Edition. Toni Weschler, MPH New York: Harper Collins. 2002
3.  _**A New View of a Woman's Body.**_ Federation of Feminist Women's Health Centers. Los Angeles: Feminist Health Press. 1995
4.  **_The New Our Bodies Ourselves_.** The Boston Women's Health Book Collective. New York: Simon & Schuster, 1992.
5.  **_Sex, Lies, & Menopause: The Shocking Truth About Hormone Replacement._** T.S. Wiley. New York: Harper Collins. 2004
6.  **_The Greatest Experiment Ever Performed on Women: Exploding the Estrogen Myth_.** Barbara Seaman. New York: Hyperion. 2003.
7.  **_The Garden of Fertility_.** Katie Singer. New York: Penguin Avery. 2004.
8.   _**Is menstruation obsolete**_**.** Elsimar Coutinho. Oxford University Press. 1999
9.  **_The Woman's Guide to Hysterectomy: Expectations & Options._** Adelaide Haas, Susan L. Puretz, 2002, Celestial Arts.
10.  **_No More Hysterectomies_** by Vicki G. Hufnagel, Susan K. Golant, Plume Books
11.  Yen and Jaffe. **_Reproductive Endocrinology;_** Chapter 29 “Contraception”. ed. Jerome Strauss, and Robert Barbieri. 2004. Elsevier Saunders.
12.  See this site for Birth Control Info at a really helpful level. [http://bedsider.org/](http://bedsider.org/)
13.  Yewchuk, Rose (2006). **[Women's Reflections on Learning Fertility Awareness: Barriers, Encouraging Factors, Effects, and Motivations](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/Thesis%20-%20Rose%20Yewchuk.pdf)**. for fulfillment of a Masters of Arts Degree for Royal Roads University, Victoria, British Columbia, Canada
    1.  [Executive Summary](https://justisse.ca/MediaGallery/HRHP%20Documents/HRHP/UnitD/Executive%20summary.pdf)
14.  [https://fc2femalecondom.com/](https://fc2femalecondom.com/)
15.  [http://ixullc.com/](http://ixullc.com/)
16.  [https://www.path.org/projects/womans\_condom.php](https://www.path.org/projects/womans_condom.php)
17.  [https://buydiaphragms.com/](https://buydiaphragms.com/)
18.  [https://femcap.com/](https://femcap.com/)
19.  [https://buyfemcap.com/](https://buyfemcap.com/)
20.  [http://www.caya.eu/en/](http://www.caya.eu/en/)
21.  [https://contragel.co.uk/](https://contragel.co.uk/)
22.  University of British Columbia, Canada Emergency Contraception Free Online Course. You have to register to access but it is free. [https://elearning.ubccpd.ca/enrol/index.php?id=39](https://elearning.ubccpd.ca/enrol/index.php?id=39&fbclid=IwAR0N24mgwhNhQEWdsDtB1QnrZATKkIsJAA1VtpYfxP9Yu22jtc_PTNCkzsA) 

----

# 1.6 - Unit D Final Evaluation {.unnumbered}

## The final evaluation for Unit D includes {.unnumbered}

You are responsible to conduct yourself with academic honesty.

### Unit D Journals {.unnumbered}

**NOTE:** Each journal is embedded in the section of courseware literature that is relevant to that journal. Do the journals as they appear in the literature you are reading. Do not do them in numerical order.

#### Unit D Section 2: Contraceptive Effectiveness

-   Journal #2: Reflection on Contraceptive Effectiveness

#### Unit D Section 3: Barrier Methods, Spermicide, and Barrier Gel

-   Journal  #22: Literature on Barrier Methods, Spermicide, and Barrier Gel

#### Unit D Section 4: Artificial Contraceptive Endocrine Disruptors

-   Journal # 3: Being on the Pill is just like being pregnant
-   Journal # 25: Contraceptive Endocrine Disruptors
-   Journal # 29: Literature on “Hormonal” Contraceptives

#### Unit D Section 5: Herbal Contraceptives

-   Journal # 4: Engaging with Herbs for Contraception

#### Unit D Section 6: Intrauterine Device  

-   Section 6.1: Intrauterine Device (IUD)
-   Journal # 1: Not your Mother's IUD 

#### Unit D Section 7: Fertility Awareness-Based Methods (FABMs)

-   Journal # 23: Literature on “Natural” Methods
-   Journal # 26 Charting Apps
-   Journal # 30: Justisse Method Effectiveness

#### Unit D Section 8: Surgical Methods  

-   Journal # 5: Literature on Tubal Sterilization Methods
-   Journal # 10: Hysterectomy in your Country or Region 
-   Journal # 27: Forced Sterilization in Your Country or Region 

#### Unit D Section 9: Male Contraception

-   Journal # 16: Literature on Male Contraceptive Methods 
-   Journal # 28: A reflection on contraception research

#### Unit D Section 10: Emergency Contraception (EC)

-   Journal # 11: Literature on Emergency Contraception
-   Journal # 12: Wisest use of EC
-   Journal [#17 Unit D 10.4 Herbal CED / EC Critique](https://justisse.ca/index.php/college/ad_courseware/page/1714)

#### Unit D Section 11: Abortion

-   Journal # 13: Compassionate Abortion Counselling

#### Unit D Section 12: Other Methods

-   no journals

#### Unit D Section 13: Sexual Health Counselling

-   Journal # 7: Cross-cultural Aspects of Sexual Health Counselling
-   Journal # 8: Sexual and Reproductive Health Genogram
-   Journal # 6: Which method of contraception is right for you?
-   Journal # 9: Matching the Contraceptive to the Client - 17 Factors 
-   Journal # 14: Myths and Misconceptions
-   Journal # 15: "Pro-Life" Perspectives on ECPs
-   Journal # 17: If these walls could talk
-   Journal # 19: Problematic Sources
-   Journal # 20: Values Clarification
-   Journal [# 21 Aspen Baker Needs Help](https://justisse.ca/index.php/college/ad_courseware/page/1726)
-   Journal # 24: Reflection  

### Multiple Choice and Short Answer Exams {.unnumbered}

**Do not open up the multiple choice or short answer exam until you are ready to take it.**

-   multiple choice exam: 90 questions with 180 minutes to complete
-   short answer exam: 66 questions with 198 minutes to complete