# 3: Barrier Methods, Spermicide, and Barrier Gel {.unnumbered}

## Unit D HRHP 3.1 - Introduction to Barrier Methods, Spermicide, and Barrier Gel {.unnumbered}

Barrier methods act as physical barriers preventing contact between sperm and vagina or ovum. Barrier methods include: external condom, internal condom, cervical cap, diaphragm, barrier gel, as well as spermicide film, sponge, gel, cream, or foam. The most commonly used barrier method is the external condom (to be discussed in Section 9).

Condoms provide significant protection for each partner against sexually transmitted infections (STIs), including gonorrhea, chlamydia, trichomonas, syphilis, HIV, and to a lesser extent herpes (HSV), and Human Papilloma Virus (HPV). Condoms reduce the risk of infection, including Pelvic Inflammatory Disease, because they reduce the likelihood of pathogens being transferred between partners.

It is important to note that there may be reduced protection against the above infections for users of diaphragms, cervical caps, and spermicidal sponges when these barriers are not used in a hygienic manner and / or are left in the body for too long after intercourse (see Section 3.5)

###  Contents {.unnumbered}

-   Section 3.2: Internal condom
-   Section 3.3: Cervical Cap & Diaphragm
-   Section 3.4: Spermicide and Barrier Gel
-   Section 3.5: Side Effects and Risks of Barriers and Spermicide

### Journals {.unnumbered}

Section 3.5 Journal 2: Literature on Barrier Methods, Spermicide, and Barrier Gel  

####  Required Readings {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, “Non-Hormonal Contraception” section **[https://www.sexandu.ca/contraception/non-hormonal-contraception/](https://www.sexandu.ca/contraception/non-hormonal-contraception/)**
2.  Planned Parenthood Federation of America Website. Explore the following sections: Condom, Diaphragm, Cervical Cap, Birth Control Sponge, Spermicide. **[https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control)**
3.  The Family Planning Association (UK) Website. Explore the following sections: Condoms (male and female), Diaphragms and caps. **[https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help)**
4.  The Boston Women's Health Collective. (2011). **“Barrier Methods: Male condom, Female Condom, Diaphragm, Cervical Cap, Sponge, Spermicides”** In _Our Bodies, Ourselves,_ pp. 211 - 222. NY: Touchtone - Simon & Schuster.
5.  Angier, Natalie. (1999). **_Woman: An Intimate Geography._** New York, NY: Haughton Mifflin Co.

  

___

  

## Unit D HRHP 3.2 - Internal Condom {.unnumbered}

The internal condom was first introduced in 1984 (Peters, Jansen, & Van Driel, 2010). It has been studied for use worldwide, including in Japan, United Kingdom, India, United States, Thailand, Zambia, Kenya, Zimbabwe, South Africa, Nigeria, France, and Latin-America (Gollub, 2000; Kerrigan et al, 2000). One of the motives for its creation is the well-documented refusal of some men to use external condoms. Community research studies and interventions in various sites, including with drug users and sex trade workers, have described changes in sex dynamics, women's self-esteem, and their ability to negotiate safer sex when they use a condom under their control (Gollub, 2000). Overall, the internal condom has received less attention than expected and is not as widely accessible as the external condom.

Systematic reviews of the literature suggest that access to internal condoms is not hampered by obstacles on the user's side, or unwilling governments, but has been problematic at the international policy level (Peters, Jansen, & Van Driel, 2010). Global public policymakers have barely contributed to its research and development, even though their involvement could lead to a breakthrough in price and costs. Some national governments use their own health budgets to purchase these condoms, such as South Africa and Brazil (Peters, Jansen, & Van Driel, 2010, p. 125).

Some research has suggested the internal condom can be washed and reused from 5 - 10 times without losing its structural integrity (Potter et al 2003; McIntyre, Pettifor, & Rees, 1998). However, reuse has not been researched extensively, and the manufacturer does not recommend it. The internal condom is the only barrier that is under women's control for STI prevention. Yet the cost of this condom has been caught in a cycle of perceived low demand and acceptability, unwillingness of governments to invest in programs of distribution, high prices, and frustrated demand. 

<table><tbody><tr><td colspan="2"><h2><strong>Internal Condom</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><p><span>Thin, loose-fitting, soft sheath with a closed end and an open end. 6.7” in length</span></p></li><li><p><span>At the closed end, there is a flexible ring used to insert the condom inside the vagina and hold it in place during intercourse. The ring at the open end of the condom sits approximately 1” outside the vagina, covering part of the vulva</span></p></li><li><p><span>Lubricated inside and out</span></p></li><li><p><span>Made of polyurethane (FC1), synthetic nitrile (FC2), or latex (VA WOW®)</span></p></li></ul></td></tr><tr><td><h3><span>How does it work?</span></h3></td><td><ul><li><span>Prevents contact between sperm and vagina</span></li><li><span>The sheath lines the inside of the vagina, and covers the vulva</span></li><li><span>Should be used once, then thrown away</span></li><li><span>May require additional lubrication for comfort during intercourse (water or silicone-based lubricants)</span></li><li><span>Must NOT be used in combination with an external condom</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>Allergic reaction to latex (VA WOW®)</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 95%</span></li><li><span>Typical use: 79%</span></li><li><span>Continuance: 49% (Reality®)</span></li></ul></td></tr><tr><td><h3><span>How Available</span></h3></td><td><ul><li><span>Available in some countries worldwide in drugstores, sexual health clinics, or online</span></li></ul></td></tr><tr><td><h3><span>Name Brands &amp; Manufacturers</span></h3></td><td><ul><li><span>Reality®, Femidom®, Dominique®, Femy®, Myfemy®, Protectiv® and Care®</span></li><li><span>Reddy, V Amour, L'amour, Sutra and VA WOW Manufactured by Medtech Products Ltd, India.</span></li><li><span>FC2 Female Condom™ (FDA approved, available in the U.S and Canada)</span></li><li><span>VA W.o.W ® (CE Certified, South Africa, Brazil, India)</span></li><li><span>The Woman's Condom (China)</span></li><li><span>The Natural Sensation Panty Condom (U.S. distribution by the ACME Condom Company)</span></li><li><span>The Phoenurse® (Europe, Brazil, China, Sri Lanka, Kenya, Mexico)</span></li><li><span>Cupid's Female Condom (Europe, manufactured in India by Cupid Ltd.)</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use it only when you have sex</span></li><li><span>Can be inserted up to 24 hours before sex</span></li><li><span>No prescription required</span></li><li><span>No side effects if polyurethane or nitrile</span></li><li><span>No hormones</span></li><li><span>Does not interfere with the menstrual cycle</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>Protects against STIs</span></li><li><span>Because of the larger surface area of outside ring, user is better protected from STIs such as HSV and HPV than with external condom</span></li><li><span>Gives user control over condom use</span></li><li><span>Can be used by those with latex allergy (if polyurethane or nitrile)</span></li><li><span>Not dependent on partner's maintenance of erection to stay in place</span></li><li><span>Partner may find it more comfortable and less constricting than external condom</span></li><li><span>Coated on the inside with a silicone-based lubricant</span></li><li><span>Approved by the FDA for vaginal use, but can be used off-label for anal and oral use</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Disposable (creates waste)</span></li><li><span>Must be inserted every time before sex</span></li><li><span>User must be comfortable with touching their genitals</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>Must check periodically to ensure it is still in the correct place</span></li><li><span>Rings may cause discomfort during sex</span></li><li><span>Possible latex allergy</span></li><li><span>Generally, more expensive than external condom</span></li><li><span>Unlike external condom, it comes in only one shape and size</span></li><li><span>Polyurethane condom may be noisy</span></li><li><span>Should not be used with oil-based lubricants or vaginal medications, as they may cause deterioration (for example, do not use with petroleum jelly or other oils)</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>Free at some sexual health clinics</span></li><li><span>CAD $12 - 15 for a pack of 3</span></li><li><span>USD $ 2 - 4 per unit</span></li></ul></td></tr></tbody></table>

### Suggested Readings {.unnumbered}

-   [https://fc2femalecondom.com/](https://fc2femalecondom.com/)
-   [http://ixullc.com/](http://ixullc.com/)
-   [https://www.path.org/projects/womans\_condom.php](https://www.path.org/projects/womans_condom.php)

### Bibliography

-   Gollub, E. L. (2000). The Female Condom: Tool for Women's Empowerment. _American Journal of Public Health_. 90: 1377 - 1381.
-   McIntyre, J., Pettifor, A., & Rees, VH. (1998). Female condom re-use: assessing structural integrity after multiple wash, dry and re-lubrication cycles. _Int Conf AIDS_ 12: 616.
-   National Collaborating Centre for Women's and Children's Health. (2005). _Long-acting reversible contraception: the effective and appropriate use of long-acting reversible contraception._  London, UK: RCOG Press at the Royal College of Obstetricians and Gynacologists.
-   Peters, Jansen, & Van Driel. (2010). The female condom: the international denial of a strong potential. _Reproductive Health Matters_ 18(35): 119-128.
-   Potter, B., Gerofi, J. Pope, M, Farley, T. (2003). Structural integrity of the polyurethane female condom after multiple cycles of disinfection, washing, drying and relubrication. _Contraception_ 67(1) 65 - 72.

  

___

  

## Unit D HRHP 3.3 - Cervical Cap & Diaphragm {.unnumbered}

The idea of blocking the cervix to prevent pregnancy is thousands of years old. Today cervical caps and diaphragms are some of the least popular methods of contraception, partly due to their inaccessibility. In many cases, they are not presented as options in initial birth control counselling, because of their lower effectiveness compared with artificial contraceptive endocrine disruptors (CEDs), and reliance on user commitment. The diaphragm and cervical cap are generally recommended by health care practitioners (if at all) for people who cannot or will not use artificial CEDs, who have infrequent sex, or for whom other forms of contraception are not acceptable. 

<table><tbody><tr><td colspan="2"><h2><strong>Cervical Cap</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small, thimble or sailor's hat-shaped, latex rubber or silicone cap</span></li><li><span>Cap is around 22 - 30 mm in diameter (smaller than a diaphragm)</span></li><li><span>Available in different sizes to accommodate various cervix sizes</span></li></ul></td></tr><tr><td><h3><span>How does it work?</span></h3></td><td><ul><li><span>Fits as a “seal” over the cervix, acting as a barrier to sperm</span></li><li><span>Must be used with gel that immobilizes or kills sperm to be effective</span></li><li><span>It is recommended that the cap be put in place before sexual arousal to ensure correct placement (FDA)</span></li><li><span>Cap must remain in place for at least 6 hours after last intercourse</span></li><li><span>Spermicide or barrier gel must be reapplied with each act of intercourse, or every 2 hours</span></li><li><span>User can wash with soap and water, air dry, and store (away from extreme heat or cold)</span></li><li><span>Every now and then user must inspect cap for holes, cracks, wrinkles, or weak spots</span></li></ul></td></tr><tr><td><h3><span>Possible Short - Term Side Effects</span></h3></td><td><ul><li><span>Increased risk of Toxic Shock Syndrome (TSS)</span></li><li><span>Possible allergy to rubber</span></li><li><span>Possible allergy to nonoxynol-9 if using spermicide</span></li><li><span>Increased risk of urinary tract infections</span></li><li><span>Abrasions / irritation of vagina or cervix</span></li><li><span>Unpleasant odour</span></li><li><span>Unusual vaginal discharge</span></li><li><span>Discomfort to user and /or partner</span></li></ul></td></tr><tr><td><h3><span>Possible Long-Term Side Effects</span></h3></td><td><ul><li><span>Cervical erosion / inflammation due to irritation from spermicide</span></li><li><span>Twofold risk for recurrent urinary tract infection due to altered vaginal flora</span></li><li><span>Infectious or chemical vaginitis / cervicitis</span></li><li><span>Cervical or vaginal ulcer or trauma caused by excessive rim pressure or prolonged frequent use</span></li><li><span>Does not interfere with future fertility unless damage to cervix is extensive from cervicitis (chemical / infectious)</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect Use:</span><ul><li><span>Parous: 68 - 74 %</span></li><li><span>Nulliparous: 84 - 91%</span></li></ul></li><li><span>Typical Use: No data available</span></li><li><span>Continuance: 60% (Powell et al, 1986, p. 226)</span><ul><li><span>Parous: 46% (NCCWCH, 2005, p.31)</span></li><li><span>Nulliparous: 57% (NCCWCH, 2005, p.31)</span></li></ul></li><li><span>FemCap® perfect use: 92% (as reported by the manufacturer - there is no independent data)</span></li></ul></td></tr><tr><td><h3><span>How Available</span></h3></td><td><ul><li><span>Most cervical caps are available by prescription only through some sexual health clinics</span></li><li><span>FemCap® is available online without a prescription</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>FemCap® (One size only, available online)</span></li><li><span>Shanghai Lily (China).</span></li><li><span>Ovès® (UK; discontinued)</span></li><li><span>Dumas®, Vimule® (Europe, Australia; discontinued)</span></li><li><span>Lea®&nbsp;Shield (discontinued in U.S in 2008)</span></li><li><span>Prentif™ (made of latex, withdrawn from U.S market in 2005)</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Reusable (good for the environment)</span></li><li><span>Can be inserted into vagina up to 2 hours before sex</span></li><li><span>No prescription required (except in the U.S)</span></li><li><span>Use it only when you have sex</span></li><li><span>No hormones</span></li><li><span>Does not interfere with menstrual cycle</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>May not require partner involvement (discrete)</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be correctly fitted by a doctor (except FemCap®)</span></li><li><span>Must be refitted after pregnancy (regardless of pregnancy outcome)</span></li><li><span>Refitting may be necessary after significant weight gain or loss, or pelvic surgery</span></li><li><span>Should not be used with oil-based lubricants or vaginal medications (may cause deterioration of the device)</span></li><li><span>Must be inserted every time before sex</span></li><li><span>User must be comfortable touching their genitals</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>User must check periodically to ensure that it is still in the correct place</span></li><li><span>Should not be worn for more than 48 hours at a time, due to the increased risk of TSS</span></li><li><span>Does not protect against STIs</span></li><li><span>It is recommended they are replaced every year</span></li><li><span>Not recommended for those with vaginal abnormalities, or history of frequent urinary tract infections</span></li><li><span>Not recommended for those with a history of toxic shock syndrome</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>Varies worldwide</span></li><li><span>FemCap®: CAD $115, USD $89, £49.99</span></li></ul></td></tr></tbody></table>

Several brands of caps were manufactured during the late 20th and early 21st centuries. Use of cervical barriers dropped dramatically after the 1960s with the introduction of the combined hormonal endocrine disruptor. In 1976, the U.S. enacted the Medical Device Amendment, a law which required manufacturers of medical devices to submit data on the safety and efficacy of cervical barriers to the Food and Drug Administration. The only manufacturer at the time failed to provide the information, and the cervical cap was banned in the United States until the late 1970s, when it was reclassified as an “investigational” device. Currently the only caps available are FemCap®, and Shanghai Lily. FemCap® is FDA approved.

<table><tbody><tr><td colspan="2"><h2><strong>Diaphragm</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Dome shaped rubber, latex, or silicone cup with flexible rim</span></li><li><span>Diaphragm is between 50 - 105mm in diameter (larger than a cervical cap)</span></li><li><span>Available in different sizes to accommodate various cervix sizes</span></li><li><span>Four different types available (Shoupe 2006, p. 170-172):</span><ul><li><strong>Flat Spring Diaphragm: </strong><span>Thin, flat, delicate rim with gentle spring strength (thinner than coil spring). Intended for users with very firm vaginal tone, nulliparous, with a shallow pubic arch, or moderate descent of bladder or rectum.</span></li><li><strong>Coil Spring Diaphragm: </strong><span>Soft, flat, flexible rim with intermediate spring strength. Intended for users with strong vaginal tone (good strength of the vaginal muscles) and no genital abnormalities</span></li><li><strong>Arcing Spring Diaphragm: </strong><span>Firm, sturdy rim with firm spring strength. For users with decreased vaginal tone, moderate descent of the pelvic organs, or with their uterus bent far forward or backward</span></li><li><strong>Wide-seal Rim Diaphragm: </strong><span>Has a flexible, 1.5cm wide flange attached to inner edge of the rim which forms a tight seal between the vaginal wall and the diaphragm, providing increased suction</span></li></ul></li></ul></td></tr><tr><td><h3><span>&nbsp;How does it work?</span></h3></td><td><ul><li><span>Acts as a mechanical barrier between sperm and cervix. Dome is placed in the vagina and wedged between the back of the symphysis pubis and the posterior side of the cervix such that it is held by the vaginal walls as it covers the cervix</span></li><li><span>Must be used with gel that immobilizes or kills sperm to be effective</span></li><li><span>Diaphragm must remain in place for 6-8 hours after last intercourse</span></li><li><span>Spermicide or barrier gel must be reapplied with each act of intercourse, or every 2 hours</span></li><li><span>User can wash with soap and water and store (away from extreme heat or cold)</span></li><li><span>Every now and then user must inspect diaphragm for holes, cracks, wrinkles, or weak spots &nbsp;</span></li></ul></td></tr><tr><td><h3><span>&nbsp;Possible Short - Term Side Effects</span></h3></td><td><ul><li><span>Increased risk of Toxic Shock Syndrome (TSS)</span></li><li><span>Possible allergy to rubber</span></li><li><span>Possible allergy to nonoxynol-9 if using spermicide</span></li><li><span>Increased risk of urinary tract infections</span></li><li><span>Increased risk of vaginal soreness / cramps</span></li><li><span>Increased risk of vaginal infection due to altered vaginal flora</span></li></ul></td></tr><tr><td><h3><span>Possible Long - Term Side Effects</span></h3></td><td><ul><li><span>Cervical erosion / inflammation due to irritation from spermicide.</span></li><li><span>Risk for recurrent urinary tract infection due to trauma</span></li><li><span>Altered vaginal flora</span></li><li><span>Infectious or chemical vaginitis / cervicitis.</span></li><li><span>Generally, does not interfere with future fertility unless damage to cervix is extensive from cervicitis (chemical / infectious)</span></li><li><span>Vaginal ulcer or trauma caused by excessive rim pressure or prolonged or frequent use.</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 92 - 96%</span><ul><li><span>96% if fitted by doctor</span></li><li><span>92% if not fitted by doctor</span></li></ul></li><li><span>Typical use: 82 - 90 % &nbsp;&nbsp;</span></li><li><span>Continuance: 57% (NCCWCH, 2005, p.31)</span></li></ul></td></tr><tr><td><h3><span>How Available</span></h3></td><td><ul><li><span>By prescription, must be fitted by a physician at some sexual health clinics or hospitals</span></li><li><span>Diaphragms can be purchased online, but you may still need a physician fitting to know what size to order. See for instance&nbsp;</span><a href="https://buydiaphragms.com/"><span>Buy Diaphragms Online</span></a></li></ul></td></tr><tr><td><h3><span>Brand Names&nbsp;&amp; Manufacturers</span></h3></td><td><ul><li><span>SILCS (Caya®, available in U.S., Canada, and Europe)</span></li><li><span>Ortho-White® (Flat-spring)</span></li><li><span>Millex Omniflex®, Koromex®, Ramses Flexible Cushioned® (Coil-spring)</span></li><li><span>Koroflex®, Allflex®, Ramses Bendex® (Arching-spring)</span></li><li><span>Milex® (Wide seal, available in U.S., Canada, Europe, Asia, and the Middle East)</span></li><li><span>Semina® Diaphragm (Brazil)</span></li><li><span>Ortho® Coil Spring (discontinued in 2008)</span></li><li><span>Ortho® Arching Spring (discontinued in 2013)</span></li><li><span>Reflexions® Flat Spring (discontinued in 2014)</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Reusable (good for the environment)</span></li><li><span>Can be inserted into vagina up to 2 hours before sex</span></li><li><span>Use it only when you have sex</span></li><li><span>No hormones</span></li><li><span>Does not interfere with menstrual cycle</span></li><li><span>No prescription required (except in the U.S)</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>Partner does not need to be involved (discrete)</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be correctly fitted by a doctor (except Caya®)</span></li><li><span>Must be refitted after pregnancy (regardless of pregnancy outcome)</span></li><li><span>Refitting may be necessary after significant weight gain or loss, or pelvic surgery</span></li><li><span>Should not be used with oil-based lubricants or vaginal medications, as they may cause deterioration</span></li><li><span>User must be comfortable touching their genitals</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>Must be inserted every time before sex</span></li><li><span>Should not be left in place for more than 24 - 30 hours, due to increased risk of TSS</span></li><li><span>Does not protect against STIs</span></li><li><span>Not recommended for those with vaginal abnormalities, or history of frequent urinary tract infections</span></li><li><span>Not recommended for those with a history of toxic shock syndrome</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $50 - $100 at sexual health clinics</span></li><li><span>Caya®: around USD$ 90, CAN$ 100, £39.99</span></li></ul></td></tr></tbody></table>

The diaphragm has been with us nearly as long as the external condom, yet the latter is not considered old-fashioned. In 1882, Wilhelm J.P. Menesinga (1936 -1910), a Dutch gynaecologist working in Germany, published the first description of a rubber contraceptive device for vaginal use (under the pseudonym Dr. Carl Hasse) (Loeber, 2012, p. 89).

If a doctor sizes these devices, they may not consider the user's menstrual cycle. Given the cyclical cephalad shift, this may mean discomfort at different parts of the cycle. The correct size of cap or diaphragm is one that the user can wear comfortably throughout their cycle.

Keep in mind that the following products may degrade latex condoms, diaphragms, or cervical caps (Shoupe, 2006, p. 149)

-   Vaseline petroleum jelly
-   Hand lotions
-   Cold cream
-   Baby oil, peanut oil, or suntan oil
-   Corn or sunflower oil, or massage oil
-   Whipping cream
-   Vaginal yeast medications
-   Estrogen cream
-   Coconut oil

#### Suggested Readings {.unnumbered}

-   [https://buydiaphragms.com/](https://buydiaphragms.com/)
-   [https://femcap.com/](https://femcap.com/)
-   [https://buyfemcap.com/](https://buyfemcap.com/)
-   [http://www.caya.eu/en/](http://www.caya.eu/en/)

#### Bibliography {.unnumbered}

-   Powerll, M.G, Mears, B. J., Deber, R. B, & Ferguson, D. (1986). Contraception with the Cervical Cap: Effectiveness, Safety, Continuity of Use, and User Satisfaction. In _Contraception_ 33(3): 215 - 232.
-   Loeber, O. (2012). “Editorial: A cheer for the diaphragm” in _The European Journal of Contraception and Reproductive Health Care._ 17: 89 - 92. doi:10.3109/13625187.2011.636461
-   NCCWCH - National Collaborating Centre for Women's and Children's Health. (2005). _Long-acting reversible contraception: the effective and appropriate use of long-acting reversible contraception._  London, UK: RCOG Press at the Royal College of Obstetricians and Gynacologists.
-   Shoupe, D. (2006). “Barrier Contraceptives: Male Condoms, Vaginal Spermicides, and Cervical Barrier Methods” in _The handbook of Contraception: A Guide for Practical Management_ (pp. 147 - 178)_._ Shoupe, D., & Kjos, S.L. (Eds). Totowa, N.J: Humana Press.  

  

___

  

## Unit D HRHP 3.4 - Spermicide and Barrier Gel {.unnumbered}

There are various substances, naturally occurring and artificial, that have been historically employed for their spermicidal properties. Spermicides and barrier gels are used together with barrier methods, such as condoms and diaphragms or cervical caps, to increase the effectiveness of the latter. They are generally not recommended for use alone, as their failure rates can be up to 28% with typical use.

Until recently, nonoxynol-9 was the only marketed spermicide available worldwide (Banerjee et al, 2014, p. 7). Nonoxynol-9 kills sperm on contact. It is sold as a film, sponge, or gel / cream / foam (which can be used with caps or diaphragms). Spermicides are some of the least popular contraceptive methods today. This is partly due to difficulty with insertion, messiness, and user discontent with the timing of insertion (Raymond et al 2005, p. 441).

Barrier Gels are newer, and non-toxic alternatives to spermicide sold for use only with cervical caps or diaphragms. Barrier gel does not contain nonoxynol-9, so it cannot legally be called spermicide. Barrier gel immobilizes sperm, mimicking the body's gelatinous mucus plug. It lowers vaginal pH, which reduces sperm mobility and may kill them.

Many naturally occurring substances have not undergone as much scientific research as artificial compounds, but they are known to have spermicidal properties. These include, but are not limited to (Banerjee et al, 2014, p. 3, 5):

-   Gossypol (isolated from the seeds of cotton)
-   Allitridium (isolated from garlic)
-   Curcumin (yellow pigment in the rhizomes of turmeric)
-   Neem Oil - please note that barrier contraceptive effectiveness is often reduced when used in combination with oil based compounds.
-   Lactic acid 

<table><tbody><tr><td colspan="2"><h2><strong>Vaginal Contraceptive Film</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Square (2” x 2”) of clear, soluble film, that dissolves into a gel</span></li><li><span>Unscented and non-staining</span></li><li>Contains nonoxynol-9</li></ul></td></tr><tr><td><h3><span>How does it work? &nbsp;</span></h3></td><td><ul><li><span>With clean and dry hands, user folds film twice, then inserts into vagina as far back as possible</span></li><li><span>User must wait 10 - 15 minutes for the film to dissolve</span></li><li><span>When film dissolves it creates a gel, coating the vagina with nonoxynol-9</span></li><li><span>A new film must be inserted with each act of intercourse</span></li><li><span>Washes away with natural vaginal discharge</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 94%</span></li><li><span>Typical use: 72%</span></li><li><span>Continuance: 36 - 42</span></li><li><span>According to the manufacturer, once dissolved, VCF® is effective for up to 3 hours</span></li></ul></td></tr><tr><td><h3><span>How available</span></h3></td><td><ul><li><span>See below<br></span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>VCF® (manufactured in U.S.A)</span></li></ul></td></tr><tr><td><h3><span>Advantages &amp; Disadvantages</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $12 or USD$ 9 - 15 for a box of 9</span></li><li><span>CAD $1 - 2 per film at sexual health clinics</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Contraceptive (Spermicidal) Sponge</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Circular polyurethane white foam, less than 2” wide (one size only)</span></li><li><span>Foam disk has a concave dimple on one side that fits over the cervix, and a cotton loop on the other side to facilitate removal</span></li><li><span>Contains spermicide (nonoxynol-9)</span></li></ul></td></tr><tr><td><h3><span>How does it work?</span></h3></td><td><ul><li><span>Foam is moistened with clean tap water until sudsy, then inserted in the vagina against the cervix</span></li><li><span>Acts as a barrier to block sperm, and traps or absorbs sperm</span></li><li><span>Releases spermicide containing nonoxynol-9 and/or Benzalkonium Chloride (BKC)</span></li><li><span>Sponge must remain in place for 6 hours after last intercourse</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use:</span><ul><li><span>Parous: 80%</span></li><li><span>Nulliparous: &nbsp;91%</span></li></ul></li><li><span>Typical use:</span><ul><li><span>Parous: 76%</span></li><li><span>Nulliparous: 88%</span></li></ul></li><li><span>Continuance (NCCWCH, 2005, p. 31):</span><ul><li><span>Parous: 46%</span></li><li><span>Nulliparous: 57%</span></li></ul></li><li><span>Once in place, spermicidal sponges are effective for up to 12 - 24 hours (depending on brand)</span></li></ul></td></tr><tr><td><h3><span>How Available&nbsp;</span></h3></td><td><ul><li><span>See below<br></span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Protectaid® (Canada and Europe)</span></li><li><span>Today® by Mayer Laboratories (U.S. and Canada)</span></li><li><span>Pharmatex® (Quebec and France)</span></li><li><span>Avert®</span></li></ul></td></tr><tr><td><h3><span>Advantages<br></span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Disposable, creates waste</span></li><li><span>User must have access to clean water</span></li><li><span>Not recommended for those with a history of TSS</span></li><li><span>Not recommended for use during menstruation</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $16 or USD $11 - 15 for a box of 3 (Today®)</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Spermicidal Gel, Cream, or Foam</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Gel, cream, or foam containing nonoxynol-9</span></li><li><span>Can be inserted into vagina via applicator, suppository, or tablet &nbsp;</span></li><li><span>Meant for use with cervical caps, diaphragms, or condoms</span></li></ul></td></tr><tr><td><h3><span>How does it work?</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 82%</span></li><li><span>Typical use: 72%</span></li><li><span>Continuance: 42% (NCCWCH, 2005, p. 31)</span></li><li><span>Contraceptive effect begins immediately and lasts up to 1 hour</span></li><li><span>A 5-minute interval must be allowed between insertion and intercourse to allow for foam to distribute within vagina</span></li></ul></td></tr><tr><td><h3><span>How Available&nbsp;</span></h3></td><td><ul><li><span>On the shelf in most pharmacies, supermarkets, and some grocery stores.</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Vaginal Contraceptive Foam®; Vaginal Contraceptive Gel®</span></li><li><span>Advantage-S® (U.S. and China)</span></li><li><span>Options Delfen® Foam, Encare®, Enko®, Ramses® Crystal Clear, VagiGard</span></li><li><span>Conceptrol®</span></li><li><span>Ortho-Gynol®</span></li><li><span>Ortho-Cream®</span></li><li><span>Grynol II®</span></li><li><span>Preceptin®</span></li><li><span>Kormex II®</span></li><li><span>Menfegol (foaming tablet available in Europe)</span></li></ul></td></tr><tr><td><h3><span>Advantages &amp; Disadvantages</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>USD&nbsp; $8.98 or CAD $11 for VCF (Foam)</span></li><li><span>USD $11 for 10 pre-filled applicators of VCF Gel</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>All Spermicides</strong></h2></td></tr><tr><td><h3><span>Mechanism of Action</span></h3></td><td><ul><li><span>Consist of two components, an inert base and a spermicidal chemical (usually nonoxynol-9 or octoxinol-9) which kills sperm.</span></li><li><span>Nonoxynol-9 (N-9) is a surfactant that breaks down the cell membrane of sperm</span></li></ul></td></tr><tr><td><h3><span>Possible Short -Term Side Effects</span></h3></td><td><ul><li><span>Unpleasant taste of chemical during oral-genital sex</span></li><li><span>Unpleasant odour (sponge)</span></li><li><span>Temporary skin irritation of the genitals</span></li><li><span>N-9 breaks down cells of the vaginal wall, and of the penis, leading to irritation (rash and or itchiness)</span></li><li><span>N-9 can kill beneficial bacteria, disrupting vaginal flora and creating susceptibility to yeast or BV infections</span></li></ul></td></tr><tr><td><h3><span>Possible Long -Term Side Effects</span></h3></td><td><ul><li><span>Chronic vaginitis / cervicitis</span></li><li><span>Increased risk of sexually transmitted infections</span></li><li><span>Associated with higher rates of UTIs, BV, and yeast infections (Shoupe, 2006, p. 154)</span></li><li><span>Health Canada has issued a warning that spermicides containing nonoxynol 9 may increase the risk of HIV transmission due to irritation of the vaginal or anal lining</span></li><li><span>Generally does not interfere with future fertility unless damage to cervix is extensive from cervicitis (chemical/infectious)</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>Available over the counter in the U.S and Canada</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use it only when you have sex</span></li><li><span>No prescription required</span></li><li><span>No hormones</span></li><li><span>Does not interfere with menstrual cycle</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>Provides extra lubrication</span></li><li><span>Inexpensive</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be inserted every time before sex</span></li><li><span>Disposable, creates waste</span></li><li><span>Must be reapplied with each act of intercourse (except sponge)</span></li><li><span>User must be comfortable touching their genitals</span></li><li><span>User must have access to clean water (sponge)</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>Can be messy (foams, creams, and jellies may ooze out of vagina)</span></li><li><span>Has an unpleasant taste (must be applied before oral sex)<br></span></li><li><span>Does not protect against STIs</span></li><li><span>Frequent use can cause skin irritation, making STI transmission easier</span></li><li><span>Not recommended for use within 6 weeks postpartum</span></li><li><span>Not recommended for those with history of TSS (sponge)</span></li><li><span>Not recommended for using during menstruation (sponge)</span></li><li><span>Not approved by Health Canada</span></li></ul></td></tr></tbody></table>

Spermicide containing nonoxynol-9 (N-9) has been studied most of the time as a supplement to the external condom, and somewhat in studies of cervical cap and diaphragm effectiveness. There is no evidence that external condoms lubricated with nonoxynol-9 are any more effective against pregnancy or STIs than condoms used alone (WHO).

In the 1970s and 1980s spermicide was thought to function also as a microbicide, providing protection against STIs (WHO). In 1998, the most conservative studies placed the microbicidal effect at 10 - 25% (Roddy, Schulz, & Cates, 1998). However, research has shown that while it is a microbicide, the genital irritation caused by N-9 leads to higher incidence of new HIV infection (e.g. Forbes & Heise, 2000). Most research studies that have shown this finding have been done with populations at the highest risk of HIV infection, such as sex workers in the Global South. There are complex challenges with designing ethical microbicide trials, given that some seroconversion is likely to occur despite condom promotion (Forbes & Heise, 2010, p. 157). These findings are not promising for the future of microbicides in HIV prevention research, however if there is adequate funding, it is likely we will see a microbicide capable of offering STI protection in the future. 

<table><tbody><tr><td colspan="2"><h2><strong>Barrier Gel</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Gel that increases the effectiveness of barrier methods</span></li><li><span>Ingredients: Water, Lactic acid, sodium lactate, methyl cellulose, sorbic acid. pH value of 3.8.</span></li><li><span>Each 60g tube typically provides 15 - 20 applications.</span></li></ul></td></tr><tr><td><h3><span>How does it work?</span></h3></td><td><ul><li><span>Gel is applied to diaphragms or cervical caps with an applicator or finger, with each act of intercourse</span></li><li><span>Reduces vaginal pH to make vagina inhospitable to sperm (limiting sperm mobility)</span></li><li><span>Physically traps sperm within the viscous gel of thick methyl cellulose</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>None</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Intended for use only with a cervical cap or diaphragm, not on its own</span></li><li><span>Effectiveness has not been studied as compared with N-9 containing spermicide</span></li></ul></td></tr><tr><td><h3><span>How available</span></h3></td><td><ul><li><span>Available at health food stores, some pharmacies, or online</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Caya® Gel</span></li><li><span>ContraGel® (Made in Europe)</span></li><li><span>Contracep® green (1972 - 2002, Holland). &nbsp;</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use it only when you have sex</span></li><li><span>No hormones</span></li><li><span>Does not interfere with menstrual cycle</span></li><li><span>No prescription required</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>Water soluble</span></li><li><span>Vegan</span></li><li><span>Not tested on animals</span></li><li><span>CE Approved (ContraGel)</span></li><li><span>Can be used off-label to increase effectiveness of condoms</span></li><li><span>Neutral flavor. Does not interfere with oral sex.</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>User must be comfortable touching their genitals</span></li><li><span>Must be used with a diaphragm or cervical cap</span></li><li><span>Must be inserted every time before sex</span></li><li><span>Can be messy</span></li><li><span>Does not protect against STIs</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>£14.99</span></li><li><span>CAD $23 - 24</span></li></ul></td></tr></tbody></table>

### Suggested Readings {.unnumbered}

-   [https://vcfcontraceptive.com/](https://vcfcontraceptive.com/)
-   [http://www.todaysponge.com/](http://www.todaysponge.com/)
-   [https://buycaya.com/caya-contraceptive-gel.html](https://buycaya.com/caya-contraceptive-gel.html)
-   [https://contragel.co.uk/](https://contragel.co.uk/)

### Bibliography {.unnumbered}

-   Banerjee, M., Hazra, A., Bharitkar, Y., & Mondal, N. (2014). Insights of Spermicidal Research: An Update. In _Journal of Fertilization: in Vitro, IVF-Worldwide, Reproductive Medicine, Genetics & Stem Cell Biology._ 3(1): 1 - 15. doi:10.4172/2375-4508.1000138
-   NCCWCH - National Collaborating Centre for Women's and Children's Health. (2005). _Long-acting reversible contraception: the effective and appropriate use of long-acting reversible contraception._  London, UK: RCOG Press at the Royal College of Obstetricians and Gynacologists.
-   Raymond, E.G, Chen, P. L, Condon, S., Luoto, J, Barnhart, K.T, Creinin, M. D., … Blackwell, R. (2005). Acceptability of five nonoxynol-9 spermicides. In _Contraception_ 71: 438 - 442.
-   Roddy, R.E., Schulz, K. F, & Cates, W. (1998). Microbicides, meta-analysis, and the N-9 question: where's the research? In _Sexually Transmitted Diseases_ 25: 151 - 153.
-   Shoupe, D. (2006). “Barrier Contraceptives: Male Condoms, Vaginal Spermicides, and Cervical Barrier Methods” in _The handbook of Contraception: A Guide for Practical Management_ (pp. 147 - 178)_._ Shoupe, D., & Kjos, S.L. (Eds). Totowa, N.J: Humana Press.  
-   WHO. (n.d). _Nonoxynol-9 ineffective in preventing HIV infection._ Media centre post. Retrieved from: [http://www.who.int/mediacentre/news/notes/release55/en/](http://www.who.int/mediacentre/news/notes/release55/en/)

  

___

  

## Unit D HRHP 3.5 - Side Effects and Risks of Barriers and Spermicide {.unnumbered}

### Barriers {.unnumbered}

All internal barrier methods, including the **cervical cap, diaphragm, and spermicidal sponge**, share similar risks and side effects. Inserting devices in the vagina may alter vaginal flora, and lead to infections of microbial imbalance such as bacterial vaginosis (BV) or candidiasis (yeast), as well as those of the urinary tract (UTIs). These infections are not conventionally considered serious, but changes to vaginal flora can lead to greater susceptibility to a range of urogenital infections (both sexually transmitted and not).

**Additionally, the cervix may respond to these barriers as if to an irritant and produce more or continuous G-type mucus (gummy, gluey, yellow) to protect itself, or more vaginal cell slough may be produced resulting in a continuous non-peak mucus production. Also the charter may experience a continuous non-peak type of discharge -- 6PC (sticky pasty-cloudy) or 6C (sticky cloudy).**

The symptoms of BV, yeast, and UT infections can present similarly to sexually transmitted infections. Users of these methods are advised to seek testing to confirm diagnosis before completing over the counter treatments.

Less frequently, barrier use and resulting changes in vaginal flora can lead to Toxic Shock Syndrome (TSS) and Pelvic Inflammatory Disease (PID). This section provides a brief overview of infections commonly caused by contraceptive barrier methods. [More in-depth discussion of vaginal and urethral wellness is found in Unit G Section 12.2 Care of the Vulva, Vagina, and Cervix.](https://justisse.ca/index.php/college/courseware/page/1571)

### Vaginal Flora {.unnumbered}

Normal vaginal flora has been well-established to be critical in maintaining genital health and homeostasis. Bacteria is crucial in protection against urogenital pathogens, particularly the presence of lactobacilli bacteria, which dominate in a healthy vaginal environment. The vaginal microenvironment is dynamic, and commonly changing in ecological composition with menstruation, adolescence, sexual activity, and / or menopause.

Research among pregnant and non-pregnant subjects has established that those with normal vaginal flora are less likely to be infected with pathogens that are sexually transmitted, postoperative, or other gynecologic infections. Those with low levels of vaginal lactobacilli are known to have a greater likelihood of acquisition of gonorrhea, chlamydia, trichomonas, HSV-2, HPV, HIV, and PID infections, particularly in subjects younger than 21 years of age (Wiesenfeld, Hillier, Krohn et al, 2003, p. 667; de Castro-Sobrinho et al, 2015, p. 80; Anahtar et al, 2015, p.965, Green, Zarek, & Catherino, 2015, p. 1353; Mirmonsef & Spear, 2014, p. 532). The risk of HIV transmission is higher in subjects with altered vaginal flora in both female-to-male, and mother-to-child transmission (Mirmonsef & Spear, 2014, p. 532). Shifts in vaginal flora can also damage vaginal epithelium and degrade cervical mucus.

The crux of the vaginal ecosystem is a symbiosis between macroenvironment and microorganism. We provide lactobacilli with food and shelter -“the comfort of the vaginal walls, the moisture, the proteins, the sugar of our tissue”—and by living and metabolizing, lactobacilli flora protects the vagina from potentially pathogenic bacteria by lowering vaginal pH, and producing lactic acid, hydrogen peroxide (Hillier, as discussed in Angier, 1999, p. 52 - 56), and bacteriocins (antimicrobial compounds) (Mirmonsef & Spear, 2014, p. 533). Keeping a healthy vaginal environment boosts the body's own innate protection against infectious disease.

### Bacterial Vaginosis (BV) {.unnumbered}

Bacterial Vaginosis is the most common vaginal infection among women of reproductive age. It is caused by an overgrowth of anaerobic bacteria such as _gardenella vaginalis_, _prevotella_, _peptostreptococcus_, and _bacteroides spp_ (Turovskiy et al, 2011, p. 1105 - 1106).

In pregnancy, BV has been linked to premature birth, or early breaking of the amniotic sac (TPH 2014). BV has been implicated in Pelvic Inflammatory Disease (PID), but its role in the etiology of the condition has not been studied extensively (DePaoli Taylor, Darville, & Haggerty, 2013, p. 117). BV can cause bothersome symptoms, including:

-   White or grey vaginal discharge
-   Discharge with unusual odour (sometimes fish-like), especially after vaginal sex
-   Itching or burning around or inside the vagina
-   Burning with urination, or with vaginal sex 

BV is also associated with increased susceptibility to sexually transmitted infections, including chlamydia, gonorrhea (Wiesenfeld, Hillier, Krohn et al, 2003, p. 663), and HIV (Sewankambo, Gray, Wawer et al 1997; Anahtar et al, 2015, p.965). Research has shown a positive association between BV and cervical HPV infections, and a possible link between BV and cervical cancer (de Castro-Sobrinho et al, 2015, p. 80, 84). 

### Vaginal Candidiasis (Yeast) {.unnumbered}

A vaginal yeast infection is caused by overgrowth of the fungus candida, which is normally found in the vagina, mouth, gastrointestinal tract, and on the skin. Yeast infections are common, and HIV-positive women tend to get them more often than those who are HIV-negative. Yeast infections can cause:

-   vaginal itching and/or burning
-   redness and swelling of the vulva
-   thick, white vaginal discharge
-   burning with urination
-   pain during intercourse

### Urinary Tract Infection (UTI) {.unnumbered}

Bacterial infection in the urinary tract (the urethra and bladder) can spread onto the kidneys if untreated. UTIs are very common; 1 in 5 people with a vagina will experience a UTI in their lifetime (PPT). Symptoms include:

-   More frequent urination
-   Feeling the need to urinate right after urinating
-   Feeling the need to urinate, but only a small amount comes out
-   Burning or pain with urination
-   Blood in urine
-   Foul-smelling or cloudy urine
-   Pain or pressure in lower abdomen, side, or back  

### Toxic Shock Syndrome (TSS) {.unnumbered}

The term Toxic Shock Syndrome (TSS) was first used in 1978, and the condition gained notoriety as a public health concern in the early 1980s when the Centre for Disease Control in the United States reported an epidemic of TSS in menstruating women who used highly absorbent tampons. Toxic Shock Syndrome is a condition caused by bacterial toxins. TSS that is menstrually related, or related to the use of barrier contraceptives, is caused by _Staphylococcus aureus_ - a bacteria sometimes found in the vagina. Using a barrier or tampon can cause it to multiply and produce a harmful toxin.

The Today contraceptive sponge, and Ortho All-Flex diaphragms have been reported to cause TSS, as well as other latex diaphragms or latex products (Tierno & Hanna, 1994, p. 144). _S. aureus_ bacteria grows in the presence of blood, semen, and vaginal fluids, and it increases dramatically in the contraceptive sponge. There is increased incidence of TSS in women who use contraceptive sponges and diaphragms than in women who don't (Ibid).

In response to a demonstrated relationship between absorbency and chemical composition, tampon manufacturers have removed components used to enhance absorbency such as polyester foam, carboxymethylcellulose, and polyacrylate rayon (Reingold, 1991, p. 1236). Despite these changes, menses-related cases of TSS accounted for 50 to 70% of all cases of TSS in women of reproductive age in the 1990s (Ibid). The incidence of both menstrual and non-menstrual cases has remained stable over the past decade at about 0.3 - 0.5 cases per 100,000 population (Low, 2013, p. 651).

The risk of death from TSS is around 5% and the condition may be lethal within 2 days (Tierno & Hanna, 1994, p. 144).  Symptoms of TSS include:

-   high fever
-   low blood pressure
-   vomiting
-   dizziness
-   muscle aches and weakness
-   a sunburn-like rash

### Pelvic Inflammatory Disease (PID) {.unnumbered}

Pelvic Inflammatory Disease refers to the infection and inflammation of the female genital tract, including the ovaries, tubes, and endometrium. PID occurs when bacteria move from the lower genitals to the upper genital tract, and it can result in infertility and ectopic pregnancy.

PID has been linked to gonorrhea, chlamydia, mycoplasma, and some bacteria associated with bacterial vaginosis (DePaoli Taylor, Darville, & Haggerty, 2013, p. 117). A causal association between BV and PID has not been well established (Ibid). PID is often caused by untreated sexually transmitted infections, but can also be caused by a variety of other bacterial pathogens. 

**Symptoms of pelvic inflammatory disease**

-   **pain** in the lower abdomen (the most common symptom)
-   **pain** in the upper abdomen.
-   **fever**.
-   painful sex.
-   painful urination.
-   irregular bleeding.
-   increased or foul-smelling vaginal discharge.
-   tiredness.

### Spermicide {.unnumbered}

Spermicide use, in whatever its form, is reported to be associated with vaginal irritation and the appearance of lesions in the epithelium (Banerjee, 2014, p. 7). The active ingredient in most spermicides, nonoxynol-9, kills normal vaginal bacteria _Lactobacillus_, disturbing normally acidic vaginal pH (Ibid). Use of nonoxynol-9 has been associated with vaginal burning, itching, vulvar burning, and increased risk of BV (Schreiber et al, 2006, p. 4-5). High exposure to this spermicide has a demonstrated association with increased HIV acquisition in sex workers (Ibid). Barrier gel does not include this chemical and does not have side effects or cause increased risk of infection.

### Vaginal Wellness {.unnumbered}

For all clients, and most importantly for users of barrier methods, it is important to discuss the following guidelines for encouraging vaginal hygiene and wellness in vaginal flora.

1.  Always wipe from FRONT to BACK
2.  Wear cotton underwear that is breathable
3.  Avoid underwear that is tight or made of synthetic material
4.  Do NOT use feminine 'hygiene' sprays or soap inside the vagina
5.  Use tampons only when flow is moderate to heavy, and change them often
6.  Do not use tampons with light or very light flow
7.  Change out of wet swimsuits or exercise clothes as soon as possible
8.  Change soiled pads often, and/or use cotton pads

To reduce the risk of genital infection:

1.  Wash hands thoroughly with soap and water before inserting or removing barrier
2.  Do not leave a barrier device inside of the vagina for more than 24 hours
3.  Do not use barriers during menstruation, or if abnormal vaginal discharge or infection is present
4.  Use a condom for 6 to 12 weeks after full term pregnancy, or for 4 weeks after abortion or miscarriage
5.  Change tampons every 4 - 8 hours, and use the lowest absorbency possible
6.  Use condoms to prevent sexually transmitted infections

[See also Unit G Section 12: Care of the Vagina, Vulva, and Cervix](https://justisse.ca/index.php/college/courseware/page/1571)  
 

### Required Readings {.unnumbered}

1.  The Society of Obstetricians and Gynaecologists of Canada Website, “Non-Hormonal Contraception” section [https://www.sexandu.ca/contraception/non-hormonal-contraception/](https://www.sexandu.ca/contraception/non-hormonal-contraception/)
2.  Planned Parenthood Federation of America Website. Explore the following sections: Condom, Diaphragm, Cervical Cap, Birth Control Sponge, Spermicide. [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control) 
3.  The Family Planning Association (UK) Website. Explore the following sections: Condoms (male and female), Diaphragms and caps. [https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help) 
4.  The Boston Women's Health Collective. (2011). “Barrier Methods: Male condom, Female Condom, Diaphragm, Cervical Cap, Sponge, Spermicides” In _Our Bodies, Ourselves,_ pp. 211 - 222. NY: Touchtone - Simon & Schuster.
5.  Angier, Natalie. (1999). Chapter 3: Default Line: Is the Female Body a Passive Construct? in _Woman: An Intimate Geography._ New York, NY: Haughton Mifflin Co.

### Bibliography {.unnumbered}

-   Angier, Natalie. (1999). _Woman: An Intimate Geography._ New York, NY: Haughton Mifflin Co.
-   Anahtar, M. N., Byrne, E. H, Doherty, K. E, Bowman, B. A., Yamamoto, H. S, Soumillon, M. …, Kwon, D. S. (2015). Cervicovaginal Bacteria Are a Major Modulator of Host Inflammatory Responses in the Female Genital Tract. In _Immunity_ _42_: 965 - 976. Doi: 10.1016/j.immuni.2015.04.019
-   Banerjee, M., Hazra, A., Bharitkar, Y., & Mondal, N. (2014). Insights of Spermicidal Research: An Update. In _Journal of Fertilization: in Vitro, IVF-Worldwide, Reproductive Medicine, Genetics & Stem Cell Biology 3_(1): 1 - 15. doi:10.4172/2375-4508.1000138
-   De Castro-Sobrinho, J. M., RAbelo-Santos, S. H., Fugueiredo-Alves, R. R, Derchain, S, Sarian, L. O. Z, Pitta, D. R.,… Zeferino, L. C. (2015). Bacterial Vaginosis and Inflammatory Response Showed Association with Severity of Cervical Neoplasia in HPV-Positive Women. In _Diagnostic Cytopathology_ _44_(2): 80 - 86. DOI: 10.1002/dc.23388
-   DePaoli Taylor, B., Darville, T., & Haggerty, C. L. (2013). Does Vacterial Vaginosis Cause Pelvic Inflammatory Disease? In _Sexually Transmitted Diseases 40_(2): 117 - 122. doi: 10.1097/OLQ.0b013e31827c5a5b  
-   Green, K. A., Zarek, S. M., & Catherino, W. H. (2015). Gynecologic health and disease in relation to the microbiome of the female reproductive tract. In _Fertility and Sterility_ _104_(6): 1351 - 1357. Doi: 10.1016/j.fertnstert.2015.10.010
-   Low, D. E. (2013). Toxic Shock syndrome: Major Advances in Pathogenesis, But not Treatment. In _Critical Care Clinics 29_ (3): 651 - 675. [https://doi.org/10.1016/j.ccc.2013.03.012](https://doi.org/10.1016/j.ccc.2013.03.012)
-   Mirmonsef, P, & Spear, G. T (2014). The Barrier to HIV Transmission Provided by Genital Tract _Lactobacillus_ Colonization. In _American Journal of Reproductive Immunology 71_: 531 - 536. Doi: 10.1111/adj.12232
-   PPT (Planned Parenthood Toronto). (n.d.). _Urinary Tract Infections (UTI)._
-   Reingold, A. (1991). Toxic Shock Syndrome: An update. In _American Journal of Obstetrics and Gynecology 4_(2): 1236-1239.
-   Schreiber, C. A, Meyn, L. A, Creinin, M. D, Barnhart, K. T, & Hillier, S. L. (2006). Effects of Long-Term Use of Nonoxynol-9 on Vaginal Flora. In _Obstetrics & Gynecology_ _107_(1): 136 - 143.
-   Sewenkambo, N., Gray, R.H., Wawer, M.  J, et al. (1997). HIV-1 infection associated with abnormal vaginal flora morphology and bacterial vaginosis. In _Lancet_ 350: 545 - 550.  
-   Tierno, P. M., and Hanna, B. A. (1994). Propensity of Tampons and Barrier Contraceptives Amplify _Staphylococcus aureus_ Toxic Shock Syndrome Toxin-I. In _Infectious Diseases in Obstetric and Gynecology._ 2: 140 - 145.
-   TPH (Toronto Public Health). (2014). _Bacterial Vaginosis (BV)._
-   Turovskiy, Y., Sutyak Noll, K., & Chikindas, M. L. (2011). The etiology of bacterial vaginosis. In _J Appl Microbiol 110_(5): 1105 - 1128. Doi:10.1111/j.1365-2672.2011.04977.x.
-   Wiesenfeld, H. C., Hillier, S. L, Krohn, M. A, Landers, D. V, & Sweet, R. L. (2003). Bacterial Vaginosis is a Strong Predictor of _Neisseria gonorrhoeae_ and _Chlamydia trachomatis_ Infection. In _Clinical Infectious Diseases 36_(1): 663 - 668. Doi:1058-4838/2003/3605-0018