# 4: Artificial CEDs {.unnumbered}

## 4.1 - Introduction to Artificial CEDs {.unnumbered}

This section includes the most popular and widely accepted methods in conventional sexual health today. Artificial Contraceptive Endocrine Disruptors (ACEDs) are the methods most often discussed in conventional birth control counselling. Globally about sixty million women use hormonal contraception, and about twenty-one million in North America.

We call the methods explored in this section Artificial Contraceptive Endocrine Disruptors (CED) because they use synthetic compounds to disrupt the user's normal endocrine system to cause temporary and reversible infertility.

### Contents {.unnumbered}

#### Section 4.2 Combined Artificial CEDs

-   Oral Contraceptive Pill
-   Contraceptive Patch
-   Combined Intravaginal Ring
-   Combined Injectable

#### Section 4.3 Non-steroidal SERM

#### Section 4.4 Progestin Only Artificial CEDs

-   Progestin-Only Pill
-   Progesterone Intravaginal Ring
-   Long Acting Reversible Contraceptives
    -   Progestin-Only Injectable  
    -   Contraceptive Implant
    -   Intrauterine System

#### Section 4.5 Menstrual Suppression through Artificial CEDs

-   Extended Cycle Oral Contraceptive Pill  
    

#### Section 4.6 'Therapeutic' Use of Artificial CEDs

#### Section 4.7 Side Effects and Risks of Artificial CEDs

#### Section 4.8 Controlling Fertility: A Matter of Choice?

### Journals

-   Section 4.2 Journal 3: Being on the Pill is Like Being Pregnant
-   Section 4.6 Journal 23: Contraceptive Endocrine Disruptors
-   Section 4.7 Journal 27: Literature on “Hormonal” Contraceptives

### Required Readings {.unnumbered}

1.  Grigg-Spall, H. (2013). **_Sweetening the Pill or How We Got Hooked on Hormonal Birth Control_**. Alresford, UK: Zero Books.
2.  Marks, L. V. (2001). **_A history of the contraceptive pill._** New Haven, CT: Yale University Press.
3.  Rako, S. (2003). **_No More Periods? The Blessings of the Curse._** Lincoln, NE: iUniverse, Inc.
4.  Depo-Provera® Contraceptive Injection
5.  The Society of Obstetricians and Gynaecologists of Canada Website, **“Hormonal Contraception”** section [https://www.sexandu.ca/contraception/hormonal-contraception/](https://www.sexandu.ca/contraception/hormonal-contraception/)
6.  Planned Parenthood Federation of America Website. Explore the following sections: **Implant, Patch, Pill, Shot**. [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control)
7.  The Family Planning Association (UK) Website. Explore the following sections: C**ombined Pill, Implant, Injection, Patch, vaginal ring, IUS, Long acting reversible contraception (LARC), and protestogen-only pill (POP)**. [https://www.fpa.org.uk/help-and-advice/contraception-help](https://www.fpa.org.uk/help-and-advice/contraception-help)
8.  The Boston Women's Health Collective. (2011). **“Hormonal Methods: Pill, Minipill, Ring, Patch, Shot” and “Implanon”** In _Our Bodies, Ourselves,_ pp. 223 - 237. NY: Touchtone - Simon & Schuster.

  

___

  

## Unit D HRHP 4.2 - Combined Artificial CEDs {.unnumbered}

Combined Artificial Endocrine Disruptors are among the most popular methods of contraception worldwide. In many countries, the most common method is the oral contraceptive pill—too often used as a synonym for “birth control”. All CEDs include a combination of a synthetic estrin (most often ethinyl estradiol) and a synthetic progestin. These are estrogen-like and progesterone-like compounds that suppress the body's natural gonadotropins (FSH and LH). Specifically, they work in 3 ways: by inhibiting ovulation, by changing cervical mucus to be less estrogenic, and by thinning the endometrium to make implantation less likely.

Synthetic estrins may raise the serum concentrations of thyroxine-binding globulin, sex hormone-binding globulin, and cortisol-binding globulin. The dose of synthetic thyroid hormone or cortisol therapy may need to be increased while using CEDs. Synthetic progestins combine high progestational activity with low intrinsic androgenicity. The clinical relevance of this finding in humans is unknown.

This section includes an overview of the combined pill, patch, intravaginal ring, and injectable. All combined CEDs are required to go through Health Canada, FDA (US Food & Drug Administration), EMA (European Medicines Agency), or other local government approval processes for pharmaceuticals. They have been tested on animals (mice, rats, rabbits, dogs, and monkeys) to be deemed fit for human consumption.

<table><tbody><tr><td colspan="2"><h2><strong>Oral Contraceptive Pill (OCP)</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small round tablet containing ethinyl estradiol (a synthetic estrin) and a variety of synthetic progestins</span></li><li><span>Non-medicinal ingredients include magnesium stearate, povidone, maize starch, and/or lactose</span></li><li><span>Comes in blister packs of 21 or 28 pills</span></li><li><span>Pills can either be monophasic or triphasic (consistent dose, or varying doses)</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must ingest the pill orally every day, at the same time of day, producing a daily peak of synthetic hormone</span></li><li><span>The 21-day regimen consists of 21 pills with active synthetic hormones. After 21 days the user takes a 7-day break when they will experience withdrawal bleeding</span></li><li><span>The 28-day regimen consists of 21 pills with active synthetic hormones, and 7 days of placebos. The user will experience withdrawal bleeding within the 7 days they are taking the placebos</span><ul><li><span>The 28-day pack is commonly prescribed for new users, or people who have trouble remembering when to start the next pack and following the daily routine</span></li></ul></li><li><span>Some brands of OCP include either 24 combined pills, 2 estrogen-only pills, and 2 placebo pills, or 24 combined pills, and 4 placebos. User is advised to take all the pills in the pack. They may experience withdrawal bleeding in the last week, or little bleeding within the days they are taking the placebos</span></li><li><span>If a dose is late, contraceptive effect is maintained if taken within 12 hours</span></li><li><span>If a dose is late beyond 12 hours, user must take 2 pills and use a back-up barrier method for 7 days as they return to the regular dosage schedule</span></li></ul></td></tr><tr><td><h3><span>Possible side effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Effectiveness rate drops dramatically when doses are missed, vomited, or delayed</span></li><li><span>Effectiveness may be reduced in users weighing more than 70.5kg (160lbs) (some studies suggest failure rate in this group is 4.5 times greater when using lower dose formulations)</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies, and sexual health clinics worldwide &nbsp;</span></li><li><span>Available without prescriptions in some countries in the Global South</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><p><span>There are hundreds of combined oral contraceptive pills available worldwide. The following are some of the CED oral pill brands available in Canada. We are interested to hear about products locally available to you in your journal discussions.</span></p><p><strong>All combined CED pills include ethinyl estradiol (about 0.035mg) as the synthetic estrin. The synthetic progestin varies and will be listed below.</strong></p><ul><li><span>Desogestrel:</span><ul><li><span>April® by Barr</span></li><li><span>Freya® by Mylan Pharmaceutical</span></li><li><span>Linessa® and Marvelon® By Merck</span></li><li><span>Ortho Cept® by Janssen</span></li></ul></li><li><span>Drospirenone:</span><ul><li><span>Yasmin® and Yaz® by Bayer</span></li><li><span>Zamine® by Apotex</span></li></ul></li><li><span>Levonorgestrel:</span><ul><li><span>Aviane®, Portia®, and Triquilar® by Bayer</span></li><li><span>Alesse® and Min-Ovral® by Pfizer</span></li><li><span>Alsena® and Alysena® by Apotex</span></li><li><span>Lutera® by Cobalt Pharmaceuticals</span></li></ul></li><li><span>Norethindrone:</span><ul><li><span>Brevicon®, Select 1/35®, and Synphasic® by Pfizer</span></li><li><span>Loestrin®, Minestrin®, and LOLO® by Warner Chilcott:</span></li><li><span>Ortho® by Janssen</span></li></ul></li><li><span>Norgestimate: Cyclen®, Tri-Cyclen®, and Ortho Tri-Cyclen Lo® by Janssen</span></li><li><span>Ethynodiol diacetate: Demulen® by Pfizer</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not require inserting anything in the vagina. However, may lead to altered vaginal flora</span></li><li><span>May not require partner cooperation</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be taken every day at the same time of day, regardless of frequency of user sexual activity</span></li><li><span>Hormone is absorbed through the digestive system, which may cause nausea and vomiting. Digestion problems may interfere with absorption</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Dependent on length of use and prior reproductive health status</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $8 - $19 at sexual health clinics, depending on brand</span></li><li><span>CAD $20 - 40 at pharmacies, depending on brand</span></li><li><span>As of January 2018, birth control prescriptions are free for people without parental insurance coverage and under 25 in Canada</span></li><li><span>USD $0 - $50, depending on insurance coverage</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Contraceptive Patch</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Square (2” x 2”) with rounded edges containing 6.0mg norelgestromin and 0.60mg ethinyl estradiol</span></li><li><span>Norelgestromin is the active metabolite produced after oral ingestion of norgestimate (the same progestin in some oral contraceptive pills)</span></li><li><span>The patch consists of 3 layers:</span><ul><li><span>Backing layer of beige flexible film made of polyethylene outer layer and polyester inner layer</span></li><li><span>Middle layer contains polyisobutylene adhesive, crospovidone, and polyester and lauryl lactate, as well as hormones</span></li><li><span>Third layer is a release liner that protects the adhesive layer, removed prior to application</span></li></ul></li><li><span>Patch must be folded onto itself for disposal</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must adhere the patch to clean, dry skin (can be worn on the shoulder, upper arm, hips, abdomen, or buttocks, not on breasts)</span></li><li><span>User removes the patch and reapplies a new one once per week</span></li><li><span>Designed to provide a steady delivery of synthetic hormone over 7 days (35 mcg of ethinyl estradiol and 200mcg of norelgestromin every 24 hours)</span></li><li><span>After 3 weeks the user takes a 7-day break when they will experience withdrawal bleeding</span></li><li><span>Synthetic hormones are delivered transdermally (through the skin) directly into the bloodstream</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Effectiveness rate drops dramatically when the patch replacement schedule is not followed</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies, and sexual health clinics worldwide &nbsp;</span></li><li><span>Available without prescriptions in some countries in the Global South</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Evra® by Janssen Inc. (Available worldwide. Approved by the FDA in 2001)</span></li><li><span>Xulane® by Mylan (U.S.A)</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not require inserting anything in the vagina. However, may lead to altered vaginal flora</span></li><li><span>May be discrete</span></li><li><span>May be easier to use for people who cannot remember to take the OCP every day</span></li><li><span>Latex-free</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Manufactured in one beige tone, mimicking light skin. It will not be discrete on people with skin tones darker than the patch</span></li><li><span>Patch may come off without the user noticing (in about 4% of users)</span></li><li><span>May cause skin irritation (reason for discontinuation in about 2% of users)</span></li><li><span>May be less effective in users with body weight greater than 90kg (198 lbs)</span></li><li><span>Not suitable for folks who regularly use heating pads, electric blankets, heat lamps, saunas, hot tubs, or do significant sunbathing. Exposing the patch to heat increases transdermal absorption and can result in too much exposure to the synthetic hormone</span></li><li><span>Greater risk of developing gallbladder disease</span></li><li><span>Some studies suggest there is double the risk of blood clots in users of the patch than in those of the OCP</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Not available on the market long enough to gauge reversal. Assumed to be like the OCP</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>Patch is not sold individually - comes in a box of three patches (enough for one month's supply)</span></li><li><span>CAD $11 at sexual health clinics</span></li><li><span>CAD $25 - 60 at pharmacies without insurance</span></li><li><span>As of January 2018, birth control prescriptions are free for people without parental insurance coverage and under 25 in Canada</span></li><li><span>USD $55 - 100 at pharmacies without insurance</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Intravaginal Ring</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Thin (4mm) flexible ring, about 54mm in diameter</span></li><li><span>Made of ethylene vinylacetate copolymers and magnesium stearate (plastic)</span></li><li><span>Contains 11.7mg etonogestrel and 2.7mg ethinyl estradiol</span></li><li><span>Etonogestrel is the active metabolite produced after oral ingestion of desogestrel (the same progestin in some oral contraceptive pills)</span></li><li><span>Releases 0.120mg of etonogestrel and 0.015mg of ethinyl estradiol daily &nbsp;</span></li><li><span>Packaged in a resealable sachet made of aluminum foil, polyester, and low-density polyethylene. Ring is placed back in sachet for disposal.</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must insert the ring into vagina, with fingers or an applicator</span></li><li><span>Ring is held in place by the vaginal walls. It is left inside for 3 weeks, then removed for 1 week to allow for withdrawal bleeding</span></li><li><span>If ring is expelled, contraceptive efficacy is not reduced if it is rinsed and reinserted within 3 hours</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Effectiveness rate drops dramatically when the ring replacement schedule is not followed</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies, and sexual health clinics worldwide &nbsp;</span></li><li><span>Available without prescriptions in some countries in the Global South</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>NuvaRing® by Merck (in the market since 2002)</span></li><li><span>Patents on Nuvaring expired in April 2018, and several generic versions are in development</span></li><li><span>USAID is involved in the development of several “sustained-release combination intravaginal rings (IVRs)”, including a 60-day, and a 90-day formulation that include microbicides for HIV and HSV-2 prevention</span></li><li><span>A new 1-year combination ring containing ethinyl estradiol and Nestorone® (a new progestin) is in clinical trials in the U.S., Latin America, Europe, and Australia. Developed by the International Committee for Contraception Research of the Population Council</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use only once per month</span></li><li><span>Easy to insert (particularly for tampon users)</span></li><li><span>Latex-free</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>User must be comfortable touching their genitals</span></li><li><span>User must have access to clean water</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>May cause vaginal discharge, irritation, and / or discomfort (see Section 3.5 for effects of altered vaginal flora)</span></li><li><span>May cause cervical irritation</span></li><li><span>May slip out during intercourse or cause discomfort (some users remove it for sexual activity, although this is not recommended)</span></li><li><span>May require partner cooperation</span></li><li><span>May be expelled with straining during a bowel movement</span></li><li><span>May cause TSS in very rare cases</span></li><li><span>Ring is non-biodegradable</span></li><li><span>Ring may disconnect at the weld joint</span></li><li><span>Cannot be combined with a diaphragm as backup because it may interfere with its correct placement</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Not available on the market long enough to gauge reversal. Assumed to be like the OCP</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $15 at sexual health clinics</span></li><li><span>CAD $30 at pharmacies</span></li><li><span>As of January 2018, birth control prescriptions are free for people without parental insurance coverage and under 25 in Canada</span></li><li><span>USD $100 - 130 without insurance, $0 - 60 if covered by insurance</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Combined Injectable</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Intramuscular injection containing synthetic estrin and progestin-like compounds</span></li><li><span>Most injectable formulations contain either Medroxyprogesterone acetate (MPA) and estradiol cypionate, or Norethisterone enanthate (NET-EN) and estradiol valerate</span></li><li><span>Non-medicinal ingredients include: methylparaben, polyethylene glycol, polysorbate, propylparaben, sodium chloride and sterile water</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>Injection is given into the hip, upper arm, buttock, or outer thigh every 28 - 30 days</span></li><li><span>The user experiences withdrawal bleeding beginning day 21 - 25</span></li><li><span>Injection can be as much as 7 days early or late</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>May cause pain at the site of injection</span></li><li><span>May cause weight gain of up to 10 - 20 pounds (mean is 4 lbs gain after 13 injections, and 5 lbs after 15 injections).</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Effectiveness rate drops dramatically when the injection schedule is not followed</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>Available in some countries in Latin America, Asia, Europe, and Africa &nbsp;</span></li><li><span>Not available in North America. Not FDA or Health Canada approved.</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Mesigyna® by Bayer and Norigynon® by Schering Mexicana (NET-EN 50mg and estradiol valerate 5mg)</span></li><li><span>Chinese Injectable No. 1® (17?-hydroxyprogesterone caproate 250mg and estradiol valerate 5mg)</span></li><li><span>Gestin® By Walter-Bushnell</span></li><li><span>Harmonis® (Indonesia)</span></li><li><span>Dihydroxyprogesterone acetophenide 150mg and estradiol enanthate 10mg:</span><ul><li><span>Anafertin®</span></li><li><span>Deladroxate®</span></li><li><span>Deproxone®</span></li><li><span>Nomagest®</span></li><li><span>Perlutan®</span></li><li><span>Patectro®</span></li><li><span>Topasel®</span></li><li><span>Yectames®</span></li></ul></li><li><span>Medroxyprogesterone acetate (MPA) 25mg and estradiol cypionate 5mg:</span><ul><li><span>Ciclofem®</span></li><li><span>Ciclofeminina®</span></li><li><span>Cyclo-Provera®</span></li><li><span>Cyclofem®</span></li><li><span>Feminena®</span></li><li><span>Lunelle®</span></li><li><span>Lunella®</span></li><li><span>Novafem®</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use only once per month</span></li><li><span>May not require partner cooperation</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li>&nbsp;Possible weight gain</li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>50% may return to fertility within 6 months, 83% by 1 year. No data on long term users</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>MXN $35 - 85 (Mexican pesos)</span></li><li><span>CLP $1,300 - 6,000 (Chilean pesos)</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Combined CEDs</strong></h2></td></tr><tr><td><h3><span>How does it work?<br></span></h3></td><td><ul><li><span>Inhibits ovulation (95-98%) through the suppression of hypothalamic release of GnRH pulses, and may directly inhibit pituitary release of FSH and LH</span></li><li><span>Pituitary effect is greater with &gt;50 mg estrin and &gt;1 mg progestin.</span></li><li><span>Increases Type-G mucus production, inhibits of Type-E peak mucus</span></li><li><span>Fallopian tube secretions and peristalsis, and uterine contractility inhibit sperm and ovum transport</span></li><li><span>Premature degeneration of the corpus luteum (luteolysis) in cycles where ovulation does occur</span></li><li><span>Final contraceptive action depends on the amount of (endogenous) estrogen produced by the user's ovaries and fat tissue (biochemical individuality)</span></li></ul></td></tr><tr><td><h3><span>Possible Short -Term Side Effects</span></h3></td><td><ul><li><span>Headaches</span></li><li><span>Onset of migraine</span></li><li><span>Nausea and vomiting</span></li><li><span>Dizziness</span></li><li><span>Breast problems (tenderness, pain, enlargement, discomfort, discharge)</span></li><li><span>Stomach or abdominal pain</span></li><li><span>Painful withdrawal bleeding</span></li><li><span>Irregular bleeding (intermittent spotting)</span></li><li><span>Mood changes (Depression, low libido, anxiety, etc.)</span></li><li><span>Worsening or improving acne</span></li><li><span>Change in vaginal secretions</span></li><li><span>Vaginal infections (BV, yeast, altered flora)</span></li><li><span>Bloating (water retention)</span></li><li><span>Weight gain or loss</span></li><li><span>Fatigue</span></li><li><span>Cardiovascular problems (blood clot, stroke, heart attack, death)</span></li></ul></td></tr><tr><td><h3><span>Possible Long -Term Side Effects</span></h3></td><td><ul><li><span>Amenorrhea</span></li><li><span>Oligomenorrhea</span></li><li><span>Reduced serum HDL cholesterol levels</span></li><li><span>Persistent hypertriglyceridemia</span></li><li><span>Melasma</span></li><li><span>Migraine</span></li><li><span>Intolerance to contact lenses</span></li><li><span>Hirsutism</span></li><li><span>Hypertension</span></li><li><span>Hyperinsulinism</span></li><li><span>Possible embryotoxic effects</span></li><li><span>Possible liver toxicity</span></li><li><span>Chronic vaginitis / cervicitis</span></li><li><span>Accelerated development of gallbladder disease</span></li><li><span>May increase risk of HPV infection or other sexually transmitted infections (unclear to what extent this is due to difference in sexual behaviour or other factors)</span></li><li><span>Increased risk of breast cancer in users who start before age 20</span></li><li><span>Increased risk of breast cancer in all users of combined CEDs decrease over time after discontinuation, but does not disappear until 10 years later</span></li><li><span>Risk of developing myocardial infarction persists after discontinuing OCP for at least six to nine years for users 40-49 years old who used OCP for five or more years</span></li><li><span>Cardiovascular problems (blood clot, stroke, heart attack, death)</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 99.8 - 99.9%</span></li><li><span>Typical use: 92%</span></li><li><span>Continuance: 68% (NCCWCH, 2005, p. 31)</span><ul><li><span>OCP Continuance:</span><ul><li><span>89% after 1 month</span></li><li><span>72% after 6 months</span></li><li><span>67 - 50% after 1 year</span></li></ul></li><li><span>Lunelle®: 56%</span></li></ul></li><li><span>Effectiveness rates drop dramatically when methods are used incorrectly (pill or injection dose missed, patch or ring changed late, etc.)</span></li></ul></td></tr><tr><td><h3><span>Contraindications</span></h3></td><td><p><span>There are many conditions contraindicated in the use of CEDs. In most jurisdictions, people with a history of or current risk factors below cannot be prescribed artificial CEDs. Some medical providers do prescribe subjects with these medications when the following factors are present, only with careful and regular monitoring. This list is not organized in order of priority.</span></p><ul><li><span>Combined CEDs CANNOT be taken if the user has a history of or current:</span><ul><li><span>Thrombophlebitis or thromboembolic disorders</span></li><li><span>Inherited or acquired hypercoagulopathies</span></li><li><span>Rhythm diseases of the heart</span></li><li><span>Cerebral vascular or coronary artery disease</span></li><li><span>Myocardial infarction</span></li><li><span>Hypertension (uncontrolled by medication)</span></li><li><span>Diabetes with blood vessel damage</span></li><li><span>Migraine headaches with aura, numbness, weakness, or changes in vision</span></li><li><span>Breast cancer or any cancer that is estrogen-dependent</span></li><li><span>Carcinoma of the endometrium</span></li><li><span>Unexplained vaginal or uterine bleeding</span></li><li><span>Impaired gallbladder or liver function</span></li><li><span>Hepatic tumors</span></li><li><span>Cholestasis</span></li><li><span>Depression (although this risk is less discussed not most often not treated as an absolute contraindication)</span></li></ul></li><li><span>Combined CEDs CANNOT be taken if the user:</span><ul><li><span>Is over 35 years of age and a heavy smoker (&gt;10 - 15/day)</span></li><li><span>Is over 40 - 45 years of age (depending on jurisdiction) &nbsp;</span></li><li><span>Is lactating</span></li><li><span>Is or suspected to be pregnant</span></li><li><span>Has had a second-trimester abortion, miscarriage, or given birth within 4 weeks</span></li><li><span>Is using Hepatitis C drug combinations containing ombitasvir, paritaprevir, or ritonavir</span></li><li><span>Will require major surgery with prolonged immobilization</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not interfere with spontaneity in sexual activity</span></li><li><span>Gives user control over pregnancy avoidance</span></li><li><span>Can be used therapeutically to “treat” acne, menstrual pain, and menstrual irregularity (See Section 4.6)</span></li><li><span>May be combined with barrier methods</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Disposable, creates waste</span></li><li><span>Metabolized by the liver (eliminated in urine, bile, and feces)</span></li><li><span>Synthetic hormone is processed by the body, secreted, and contaminates water systems</span></li><li><span>Synthetic hormones in water bodies have been shown to feminize some species of fish</span></li><li><span>Must be used on a routine basis as directed for maximum effectiveness (daily, weekly, or monthly), regardless of frequency of user sexual activity</span></li><li><span>Do not protect against STIs</span></li><li><span>Require prescriptions in most jurisdictions</span></li></ul></td></tr></tbody></table>

### Required Readings {.unnumbered}

-   Grigg-Spall, H. (2013). _Sweetening the Pill or How We Got Hooked on Hormonal Birth Control_. Alresford, UK: Zero Books.
-   Marks, L. V. (2001). _A history of the contraceptive pill._ New Haven, CT: Yale University Press.

###  Bibliography {.unnumbered}

-   INFO Reports. (2006). _Injectable Contraceptives: Tools for Providers._ Issue No. 8.
-   NCCWCH - National Collaborating Centre for Women's and Children's Health. (2005). _Long-acting reversible contraception: the effective and appropriate use of long-acting reversible contraception._  London, UK: RCOG Press at the Royal College of Obstetricians and Gynacologists.
-   Shoupe, D., & Mishell, D. R. (2006). Oral Contraceptives: History, Pharmacology, Metabolic Effects, Side Effects, and Health Benefits. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 13 - 43). Totowa, NJ: Humana Press.  
-   UN Development Programme, UN Population Fund, WHO, World Bank Special Programme of Research Development and Research training in Human Reproduction, Task Force on Long-acting Systemic Agents for Fertility Regulation. (2003). Comparative study of the effects of two one-a-month in injectable contraceptives (Cyclofem® and Mesigyna®) and one oral contraceptive (Ortho-Novum 1/35®) on coagulation and fibrinolysis. In _Contraception_ 68: 159 - 176.

  

___

  

## Unit D HRHP 4.3 - Non-Steroidal SERM {.unnumbered}

The world's first non-steroidal selective estrogen receptor modulator (SERM) was designed for use as a contraceptive by Dr. Nitya Anand and his team of chemists in the 1960s and 70s at the Central Drug Research Institute (CDRI) in India. After clinical trials the drug was approved by Indian authorities in 1990 and sold with the name Saheli (girl friend). This contraceptive option is now part of the National Family Planning Programme in India. 

<table><tbody><tr><td colspan="2"><h2><strong>Non-Steroidal Oral Contraceptive Pill</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small round tablet containing centchroman (ormelixofene 30mg), a selective estrogen receptor modulator (SERM)</span></li><li><span>Comes in blister packs of 8 pills</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must ingest the pill orally twice a week for the first 12 weeks of use</span></li><li><span>From the 13</span><span>th</span><span> week on, it is taken once per week</span></li><li><span>Unlike combined and progestin-only CEDs, the non-steroidal pill:</span><ul><li><span>Can be ingested any time of day (doses do not have to be at the same time of day)</span></li><li><span>User must use a backup method for the first 2 - 3 months</span></li><li><span>User must start with the first day of menstruation, and cannot start in the middle of a cycle</span></li><li><span>If a dose is missed by 1 - 6 days, user must use a back-up method until the next bleeding as they return to the regular dosage schedule</span></li></ul></li></ul></td></tr><tr><td><h3><span>How does it work?<br></span></h3></td><td><ul><li><span>Centchroman has a weak estrogenic and potent anti-estrogenic action</span></li><li><span>In bones the action is estrogenic</span></li><li><span>In the uterus and breasts the action is antiestrogenic</span></li><li><span>It works by causing asynchrony in the normal menstrual cycle. Particularly:</span><ul><li><span>Accelerated tubal transport of blastocyst/morula</span></li><li><span>Accelerated blastocyst formation</span></li><li><span>Delayed zona shedding</span></li><li><span>Suppression of uterine decidualization</span></li></ul></li><li><span>Centchroman may cause delayed ovulation, but does not prevent it &nbsp;</span></li></ul></td></tr><tr><td><h3><span>Possible side effects</span></h3></td><td><ul><li><span>Delay in bleeding (8% of cases, should be no more than 15 days)</span></li><li><span>Decreased bleeding</span></li><li><span>Menstrual suppression</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 95 - 99%</span></li><li><span>Typical use: No data available</span></li><li><span>Continuance: No data available</span></li></ul></td></tr><tr><td><h3><span>Contraindications</span></h3></td><td><ul><li><span>Centchroman CANNOT be taken if the user has:</span><ul><li><span>Polycystic ovarian syndrome (PCOS)</span></li><li><span>Cervical hyperplasia</span></li><li><span>Recent history of jaundice or liver disease</span></li><li><span>Chronic illness such as tuberculosis, renal diseases, or severe allergic states</span></li></ul></li><li><span>Centchroman effectiveness is reduced with cannabis. User is advised to use a back up method.</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies in India only since 1991 (approved by the Indian Central Drug Research Institute (CDRI)</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>By HLL Lifecare Ltd</span><ul><li><span>Saheli® &nbsp;</span></li><li><span>Choice-7®</span></li><li><span>Novex®</span></li><li><span>Novex-DS®</span></li></ul></li><li><span>By Torrent Pharmaceuticals</span><ul><li><span>Centron® (discontinued)</span></li><li><span>Sevista®</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not interfere with spontaneity in sexual activity</span></li><li><span>Does not require inserting anything in the vagina</span></li><li><span>No side effects associated with combined and progestin-only CEDs</span></li><li><span>Gives user control over pregnancy avoidance</span></li><li><span>May not require partner cooperation</span></li><li><span>May be combined with barrier methods</span></li><li><span>No effect on platelet aggregation, lipid profile, and HDL cholesterol</span></li><li><span>Can be used by breast / chest feeding user</span></li><li><span>Used in the 'treatment' of dysfunctional uterine bleeding</span></li><li><span>Because of the antiestrogenic action on breast tissue, it is being researched as potential treatment and prophylactic against breast cancer, mastalgia, and fibrocystic breast disease</span></li><li><span>Being researched as a treatment against ovarian, head, and neck cancers</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Disposable, creates waste</span></li><li><span>Metabolized by the liver (eliminated primarily in feces)</span></li><li><span>Must be used on a routine weekly basis regardless of frequency of user sexual activity</span></li><li><span>Do not protect against STIs</span></li><li><span>Requires prescription</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Fertility returns within 6 months</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>Rs.16 for 8 pills (Indian Rupees)</span></li><li><span>About USD ¢0.25 or CAD ¢0.31</span></li></ul></td></tr></tbody></table>

###  Bibliography {.unnumbered}

-   Balasubramanian, D. (2017, June 24). Science: On conception and contraception: The story of Saheli. _The Hindu._ Retrieved from: [http://www.thehindu.com/sci-tech/science/on-conception-and-contraception-the-story-of-saheli/article19140909.ece](http://www.thehindu.com/sci-tech/science/on-conception-and-contraception-the-story-of-saheli/article19140909.ece)
-   Bansal, V., Bansal, A., Bansal, A. K. (2015). Efficacy of SEVISTA (Ormeloxifene) in treatment of mastalgia and fibrocystic breast disease. In _International Journal of Reproduction, Contraception, Obstetrics and Gynecology Aug 4_(4): 1057 - 1060. Doi: [http://dx.doi.org/10.18203/2320-1770.ijrcog20150426](http://dx.doi.org/10.18203/2320-1770.ijrcog20150426)
-   Gara, R. K., Sundram, V., Chauhan, S. C., & Jaggi, M. (2013). Anti-Cancer Potential of a Novel SERM Ormeloxifene. In _Current medicinal chemistry, 20_(33): 4177 - 4184.
-   Jain, K. (1997, November 5). 'Contraceptive Saheli has high failure rate'. _The Times of India News Service,_ p. 7.
-   'Saheli' touted as a breakthrough contraceptive pill for women. (1996, October 22). _The Times of India, Mumbai,_ p. 8.
-   Singh, M. H. (2001). Centchroman, a selective estrogen receptor modulator, as a contraceptive and for the management of hormone-related clinical di

  

___

  

## Unit D HRHP 4.4 - Progestin Only Artificial CEDs {.unnumbered}

Progestin only Contraceptive Endocrine Disruptors use only synthetic progestin-like compounds (no estrogen-like artificial hormones). They work in a similar way as combined CEDs but have different risks and contraindications. These methods are usually offered to people who have contraindications to combined CEDs, are lactating, or want to achieve menstrual suppression.

Long Acting Reversible Contraceptives (LARCs) are considered the most effective contraceptives because they are independent of the need for user adherence. These progestin-only methods are usually recommended for users who are non-compliant with other methods, or who have social or health factors that are considered high risk. For example, younger or older (40+) women, those with many partners, inconsistent condom users, folks in the sex trade, people who are HIV+, or those with learning disabilities. LARCs are also some of the most cost-effective methods. Several companies offer compassionate care programs through which the method can be obtained by low income people free of charge with a doctor's application (for example, Mirena®). However, these opportunities are few and far between and getting a LARC such as an implant or IUS still represents an investment for the average person. 

This section includes a brief overview of the progestin-only pill, intravaginal ring, injectable, implant, and Intra-Uterine Systems. All progestin-only CEDs are required to go through Health Canada, FDA (US Food & Drug Administration), EMA (European Medicines Agency), or other local government approval processes for pharmaceuticals. They have been tested on animals (mice, rats, rabbits, dogs, and monkeys) to be deemed fit for human use or consumption.

<table><tbody><tr><td colspan="2"><h2><strong>Progestin-only Pill (POP) or “Mini-pill”</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small round tablet containing a variety of synthetic progestins</span></li><li><span>Non-medicinal ingredients include magnesium stearate, povidone, maize starch, and/or lactose</span></li><li><span>Comes in blister packs of 28 monophasic pills (delivering a consistent dose)</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must ingest the pill orally every day, at the same time of day, producing a daily peak of synthetic hormone</span></li><li><span>Unlike combined CEDs, progestin-only CED regimens do not include a 7-day break or placebo pills. This means the user ingests the active pill every day, whether they are bleeding. They may bleed within the last 7 days of the pill pack, or may experience irregular bleeding</span></li><li><span>Pills contain only one hormone, and there is less room for error in timing of dosage</span></li><li><span>If a dose is late, contraceptive effect is maintained if taken within 3 hours</span></li><li><span>If a dose is late beyond 3 hours, user must use condoms or another back up method until the next episode of bleeding</span></li><li><span>For POP with desogestrel: if a dose is late, contraceptive effect is maintained if taken within 12 hours. If a dose is late beyond 12 hours, user must use condoms or another back up method for 7 days as they return to the regular dose schedule (similar to combined CED)</span></li><li><span>Users who are fully breast / chest feeding may start POP 6 weeks after delivery. Those partially breast / chest feeding may start 3 weeks after delivery</span></li></ul></td></tr><tr><td><h3><span>Possible side effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 95 - 99%</span></li><li><span>Typical use: 92 - 95%</span></li><li><span>Continuance: 68% (NCCWCH, 2005, p. 31)</span></li><li><span>Effectiveness rate drops dramatically when doses are missed, vomited, or delayed</span></li><li><span>Effectiveness may be reduced in users weighing more than 57.8kg (127.4lbs) (some studies suggest failure rate in this group is 4.5 times greater when using lower dose formulations)</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies, and sexual health clinics worldwide &nbsp;</span></li><li><span>Available without prescriptions in the Global South</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><p><span>There are hundreds of progestin-only oral contraceptive pills available worldwide. The following are some of the brands available in North America, Australia, and Europe. We are interested to hear about products locally available to you in your journal discussions.</span></p><ul><li><span>Desogestrel 0.75mg:</span><ul><li><span>Aizea® by Cyndea Pharma, S.L.</span></li><li><span>Cerazette® by Merck Sharp &amp; Dohme Ltd</span></li><li><span>Cerelle® by Consilient Health Ltd</span></li><li><span>Desomono® by MedRx Healthcare Ltd</span></li><li><span>Desorex® by Helm Pharmaceuticals</span></li><li><span>Feanolla® by Lupin Ltd</span></li><li><span>Nacrez® by Teka UK</span></li><li><span>Zelleta® by Morningside Healthcare Ltd</span></li></ul></li><li><span>Exluton® by Organon Ltd (lynestrenol)</span></li><li><span>Levonorgestrel 0.30mg:</span><ul><li><span>Ovrette® by Organon</span></li><li><span>Microlut® and Norgeston® by Bayer</span></li><li><span>Microval® by Akromed Products Ltd.</span></li><li><span>Minicon® by SMC</span></li><li><span>Neogest® by Schering AG</span></li></ul></li><li><span>Norethindrone 0.35mg:</span><ul><li><span>Aygestin® by Duramed</span></li><li><span>Camilla® and Errin® by Teva Pharmaceuticals</span></li><li><span>Jolivette® and Nor-QD® by Actavis Pharma, Inc.</span></li><li><span>Jencycla® by Lupin Ltd</span></li><li><span>Lyza® by Mylan Laboratories Ltd.</span></li><li><span>Micronor® by Janssen Inc</span></li><li><span>Norlyda® by Amneal</span></li><li><span>Nora-BE® by Barr</span></li><li><span>Sharobel® by Novast Laboratories, Ltd.</span></li></ul></li><li><span>Norethisterone 0.35mg:</span><ul><li><span>Locilan® 28 and Noriday® 28 by Pfizer Australia</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not require inserting anything in the vagina. However, may lead to altered vaginal flora</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be taken every day at the same time of day, regardless of frequency of user sexual activity</span></li><li><span>Hormone is absorbed through the digestive system, which may cause nausea and vomiting. Digestion problems may interfere with absorption</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Limited data available suggests rapid return of normal ovulation with no delay</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $19 at sexual health clinics</span></li><li><span>CAD $20 - 40 at pharmacies, depending on brand</span></li><li><span>As of January 2018, birth control prescriptions are free for people under 25 in Canada</span></li><li><span>USD $0 - $50, depending on insurance coverage</span></li><li><span>£46.70 - 75</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Progesterone Intravaginal Ring (PVR)</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Thin (8.4 - 9mm) flexible ring, about 58mm in diameter (slightly larger than the combined intravaginal ring)</span></li><li><span>Made of silicone elastomer</span></li><li><span>Contains 2,074 of progesterone</span></li><li><span>Releases 10mg of progesterone daily</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must insert the ring into the vagina with fingers</span></li><li><span>User must start between day 30 and 90 postpartum, if breast chest feeding&nbsp;</span></li><li><span>Ring is held in place by the vaginal walls, and must be replaced every 3 months (90 days)</span></li><li><span>Can be used for up to 1 year (4 rings used consecutively)</span></li><li><span>Designed for breast / chest feeding users to extend lactational amenorrhea, and must be discontinued upon weaning of infant</span></li><li><span>If ring is expelled, contraceptive efficacy is not reduced if it is rinsed and reinserted within 2 hours</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 98.5% with continued lactation</span></li><li><span>Typical use: No data available</span></li><li><span>Continuance:</span><ul><li><span>6-month: 52.5%</span></li><li><span>12-month: 23.5% - 41.3%</span></li></ul></li><li><span>Effectiveness rate drops dramatically when the ring replacement schedule is not followed</span></li></ul></td></tr><tr><td><h3><span>How available</span></h3></td><td><ul><li><span>By gynecologist prescription at pharmacies in Bolivia, Chile, Ecuador, Guatemala, Honduras, Dominican Republic, El Salvador, Panama, and Peru</span></li><li><span>May soon be available in India, once approved by Drug Controller</span></li><li><span>Currently being assessed for introduction to Kenya, Nigeria, and Senegal</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Progering® by Laboratorios Andromaco (Chile)</span></li><li><span>USAID is involved in the development of several “sustained-release combination intravaginal rings (IVRs)”, including a 60-day, and a 90-day formulation that include microbicides for HIV and HSV-2 prevention</span></li><li><span>A new 1-year ring containing Nestorone® (a new progestin) is currently undergoing clinical trials. Developed by the International Committee for Contraception Research of the Population Council</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Use only once every 3 months</span></li><li><span>Easy to insert (particularly for tampon users)</span></li><li><span>Latex-free</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>User must be comfortable touching their genitals</span></li><li><span>User must have access to clean water</span></li><li><span>User may have trouble inserting it correctly</span></li><li><span>May cause vaginal discharge, irritation, and / or discomfort (see Section 3.5 for effects of altered vaginal flora)</span></li><li><span>May slip out during intercourse or cause discomfort (some users remove it for sexual activity, although this is not recommended)</span></li><li><span>May require partner cooperation</span></li><li><span>May be expelled with straining during a bowel movement</span></li><li><span>Ring is non-biodegradable</span></li><li><span>Cannot be combined with a diaphragm as backup because it may interfere with its correct placement</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Not available on the market long enough to gauge reversal. Assumed to be like the POP</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CLP $16,000 (Chilean Pesos - about USD $26 or CAN $33)</span></li></ul></td></tr></tbody></table>

## Long Acting Reversible Contraceptives (LARCs) {.unnumbered}

<table><tbody><tr><td colspan="2"><h2><strong>Progestin-Only Injectable (“The Shot”)</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Injection containing a synthetic progestin (either depot-medroxyprogesterone acetate (DMPA) or Norethisterone enanthate (NET-EN)</span></li><li><span>Non-medicinal ingredients include: polyethylene glycol, polysorbate, sodium chloride, methylparaben, propylparaben, water (DMPA), and benzyl benzoate (NET-EN)</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>Injection is given into the anterior thigh or abdomen, or subcutaneously</span></li><li><span>Designed to act over a 2-month (NET-EN) or 3-month period (DMPA) using a timed release from the injection site</span></li><li><span>Contraceptive effectiveness achieved within 24 hours</span></li><li><span>After the first 3-week period, hormone levels decrease exponentially until they become virtually undetectable between 120 to 200 days post-injection</span></li><li><span>May be started by breast / chest feeding user 6 weeks postpartum</span></li><li><span>DMPA should be repeated every 12 weeks, and NET-EN every 8 weeks. Dose can be up to 2 weeks late without the need for a back-up method</span></li><li><span>May be started any time in the menstrual cycle, including immediately post partum or abortion</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>Most common reason for discontinuation is altered bleeding pattern, including persistent bleeding</span></li><li><span>Amenorrhea: 50% after 1 year of use, 70% after 2 years</span></li><li><span>Bone Mineral Density (BMD) loss, which is not completely reversible and worsens with increasing duration of use. There have been cases of osteoporosis including osteoporotic fractures reported in patients taking Depo-Provera age 16 - 48 years</span></li><li><span>DMPA is associated with an increase up to 2 - 3 kg in weight over 1 year</span></li><li><span>In some users DMPA serum levels remain effective as long as 7 - 9 months after discontinuation<br></span></li><li><span>May cause skin irritation and / or scarring at the site of injection</span></li><li><span>See below and Section 4.7 Side Effects and Risks of Artificial CEDs</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 99.7%&nbsp;</span></li><li><span>Typical use: 97%</span></li><li><span>Continuance: 56%</span><ul><li><span>DMPA 1-year continuance: 50%</span></li></ul></li><li><span>Effectiveness rate drops dramatically when the injection schedule is not followed</span></li></ul></td></tr><tr><td><h3><span>How available</span></h3></td><td><ul><li><span>By prescription worldwide</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Depo-Provera® by Pfizer (150mg DMPA)</span><ul><li><span>MPA was introduced in the market in the 1960s as a treatment for endometriosis and abnormal menstrual bleeding. Its use as a contraceptive was “off-label” until the FDA approved it for this purpose in 1992</span></li></ul></li><li><span>Depo-subQ Provera 104TM (104mg MPA)</span><ul><li><span>Approved by the FDA in 2004</span></li></ul></li><li><span>Petogen® by Intokem Pharmaceuticals Ltd (150mg MPA)</span></li><li><span>Noristerat® by Bayer (200mg NET-EN)</span><ul><li><span>Norethisterone enantate is partly converted in the body into ethinyl estradiol. The expected concentration of It in the body is lower than with combined artificial CEDs</span></li></ul></li><li><span>Syngestal®</span></li><li><span>Megestron®</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Can be discrete</span></li><li><span>May be used by breast / chest feeding user</span></li><li><span>DMPA may be associated with a reduction in the frequency of seizures in people with epilepsy</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Should not be used for more than 2 consecutive years</span></li><li><span>Should not be used by adolescents due to lack of evidence regarding the long-term impact of BMD loss</span></li><li><span>Considered a risk factor for osteoporosis</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Return of normal fertility takes longer than with other artificial CEDs. User can expect to wait between 6 and 18 months for return to ovulation and fertility</span></li></ul></td></tr><tr><td><h3><span>Contraindications</span></h3></td><td><p><span>Progestin-only injectables CANNOT be taken if the user has a history of, or current:</span></p><ul><li><span>Undiagnosed breast pathology</span></li><li><span>Known or suspected progestin-dependent neoplasia</span></li><li><span>Thrombophlebitis or thromboembolic disorders</span></li><li><span>Cerebrovascular disorders</span></li><li><span>Myocardial infarction or coronary artery disease</span></li><li><span>Presence of severe or multiple risk factors for arterial or venous thrombosis</span></li><li><span>Ophthalmic vascular disease</span></li><li><span>Migraine with focal aura</span></li><li><span>See below for more contraindications applicable to all progestin-only methods</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>About CAD $35 - $45 per injection</span></li><li><span>About USD $40 - $100 per injection + cost of doctor visit</span></li><li><span>£95 per dose</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Contraceptive Implant</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small, flexible, and cylindrical rod, rods, or capsules (34 - 43mm x 2 - 2.5mm each)</span></li><li><span>Contains a variety of synthetic progestins</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>Implant is inserted beneath the skin of the non-dominant upper arm, about 8 - 10cm above the elbow crease</span></li><li><span>Implant releases daily doses of progestin, delivered directly into interstitial fluids</span></li><li><span>Can be left in place for 1, 3, 4, or 5 years</span></li><li><span>May be inserted immediately after 1</span><span>st</span><span> trimester post abortion or miscarriage</span></li><li><span>Should not be inserted until after 4 weeks postpartum</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>Amenorrhea in 20% of users</span></li><li><span>Infrequent, frequent, or prolonged bleeding (45% of users)</span><ul><li><span>33% of users discontinue because of irregular bleeding</span></li></ul></li><li><span>Mood changes (&lt; 10% report it as a reason for discontinuance)</span></li><li><span>Low libido (&lt;2% report it as a reason for discontinuance)</span></li><li><span>Weight gain</span><ul><li><span>Implanon®: average 2.8 lbs after 1 year, and 3.7 lbs after 2 years</span></li><li><span>Jadelle®: average 9 lbs after 5 years. 20% gained at least 10 lbs in the first year, and 50% gained at least 10 lbs by the end of the 5</span><span>th</span><span> year</span></li><li><span>2.3% of users discontinue because of weight gain</span></li></ul></li><li><span>Should pregnancy occur, it may be more likely to be ectopic than a pregnancy occurring in a person not using contraception</span></li><li><span>Neural or vascular injury if inserted too deeply &nbsp;</span></li><li><span>Events of migration to the pulmonary vasculature have been reported with rod implants, in which case surgical procedures may be needed for removal</span></li><li><span>Infection, abscess formation, blistering, ulcerations, sloughing, excessive scarring, phlebitis, and hyperpigmentation can occur at insertion site (capsules)</span></li><li><span>If insertion too shallow, capsules can be expulsed</span></li><li><span>Broken or non-palpable implants complicating removal occur in 4.8% of users (Norplant), and 0.2% of users (Implanon)</span></li><li><span>If not palpable, user may need ultrasound or MRI to locate implant (cannot be seen via x-ray or CT scan)</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 99%</span></li><li><span>Typical use: Effectiveness drops below 99% over 5-year period</span></li><li><span>Continuance: 84%</span><ul><li><span>Implanon®: 43% within 3 years &nbsp;</span></li></ul></li><li><span>People who weigh more than 130% of their ideal body weight were not included in clinical trials of Implanon®. Serum concentrations of etonogestrel are inversely related to body weight and decrease with time after implant insertion. It is likely that Implanon® may be less effective in overweight users.</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription worldwide</span></li><li><span>Not approved in Canada</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>Norplant®:</span><ul><li><span>Set of six closed silicon capsules (each 34mm x 2.4mm)</span></li><li><span>Each capsule contains 36mg of levonorgestrel</span></li><li><span>Can be used up to 5 years</span></li><li><span>Inserted into the upper arm in a fan-like pattern, about 15 degrees apart</span></li><li><span>Withdrawn from the United Kingdom market in 1999, and United States distribution ended in 2002</span></li></ul></li><li><span>Jadelle® (Norplant® II):</span><ul><li><span>Set of two rods (each 43mm x 2.5mm)</span></li><li><span>Each rod consists of a dimethylsiloxane / methylvinylsiloxane copolymer core enclosed in thin-walled silicone tubing</span></li><li><span>Each rod contains 75 mg of&nbsp;levonorgestrel</span></li><li><span>Inserted into the upper arm in a V shape about 30 degrees apart</span></li><li><span>Can be used up to 5 years</span></li></ul></li><li><span>Sino-implant II® by Shanghai Dahua Pharmaceutical Co. Ltd:</span><ul><li><span>Sold under names: Femplant®, Levoplant®, Trust®, and Zarin®</span></li><li><span>Set of 2 rods (each 4cm x 2.4mm) made of medical-grade silicone elastomer</span></li><li><span>Each rod contains 75mg of levonorgestrel</span></li><li><span>Labelled for either 3 or 4 years of use, depending on the country registration status</span></li><li><span>On the market since 1991</span></li></ul></li><li><span>Implanon® and Nexplanon® by Merck:</span><ul><li><span>Single, off-white ethylene vinylacetate (EVA) implant (4cm x 2mm)</span></li><li><span>Contains 68 mg of etonogestrel (active metabolite of desogestrel)</span></li><li><span>Approved by the FDA in 2001</span></li><li><span>Can be used for up to 3 years</span></li></ul></li><li><span>Nestorone® Implant</span><ul><li><span>Single rod (45mm)</span></li><li><span>Made of polydimethylsiloxane eslastomer with Nestorone (new synthetic progestin) &nbsp;</span></li><li><span>Can be used up to 2 years</span></li><li><span>Currently in clinical trials in Latin America by The Population Council</span></li></ul></li><li><span>Uniplant® by Theramex (France):</span><ul><li><span>Single capsule (35mm x 2.4mm)</span></li><li><span>Made with medical grade dimethyl-polysiloxane (silastic) tubing</span></li><li><span>Contains 55mg of nomegestrol acetate</span></li><li><span>Can be used up to 1 year</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>May be discrete</span></li><li><span>Long-acting</span></li></ul></td></tr><tr><td><h3><span>Disadvantages&nbsp;</span></h3></td><td><ul><li><span>Requires access to healthcare provider for prescription and insertion / removal (must be removed by a healthcare professional)<br></span></li><li><span>Implants can be felt in arm and are sometimes visible</span></li><li><span>Insertion and / or removal can be painful and / or difficult</span></li><li><span>33% of users stop because of irregular bleeding</span></li><li><span>2.3% of users stop because of weight gain</span></li><li><span>Broken or non-palpable implants complicating removal occur in 4.8% of users (Norplant), and 0.2% of users (Implanon)</span></li><li><span>Must be inserted and removed by a trained healthcare professional</span></li><li><span>If not palpable, user may need ultrasound or MRI to locate implant (cannot be seen via x-ray or CT scan)</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Once device is removed fertility should return to normal</span></li><li><span>Removal may be difficult or impossible if the implant is not inserted correctly, too deeply, is not palpable, if it is encased in fibrous tissue, or has migrated</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>£90.00 for Implanon®</span></li><li><span>£125 for Nexplanon® + cost of insertion</span></li><li><span>About USD $8.50 for Jadelle® and $8 for Femplant® in the Global South</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>Intra-Uterine System (IUS)</strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small, white, polyethylene frame consisting of a vertical stem (30 - 32 mm) and a loop and threads</span></li><li><span>Frame may be T-shaped, with two flexible horizontal arms (28 - 32 mm), or frameless, consisting only of the vertical stem (35mm x 1.6mm) and loop and threads</span></li><li><span>White frame is pigmented with barium sulphate which makes it visible by x-ray</span></li><li><span>3-year IUS include a silver ring close to the horizontal arms to aid in detection by sonography</span></li><li><span>Has a cylindrical reservoir in the vertical stem made of polydimethylsiloxane, which contains a synthetic progestin</span></li><li><span>Has two long, thin threads hanging from the small loop on the bottom end of the vertical stem, which may be black, brown, or blue</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>Device is inserted into the uterus through the cervix</span></li><li><span>The arms of the t-shaped device open after insertion</span></li><li><span>The frameless device is anchored 1cm into the myometrium of the uterine fundus</span></li><li><span>The threads are cut by the healthcare provider,so they hang outside of the cervix about 2 - 3cm. They are left so the user can ensure the device is in place by touching them periodically, and they are used for removal of the device</span></li><li><span>Can be left in place for 3 - 5 years</span></li><li><span>Can be started 6 weeks postpartum, or until uterine involution is complete</span></li><li><span>User should have medical follow up 3 - 6 weeks after insertion to exclude the possibility of infection, perforation, or expulsion</span></li><li><span>Users are advised to use condoms in the first cycle to reduce risk of infection, and ensure continued protection should expulsion occur</span></li><li><span>Users are advised to abstain from penetrative sexual activity or inserting anything in the vagina for one week post-insertion to reduce risk of infection</span></li><li><span>Can be inserted at any time immediately following 1</span><span>st</span><span> trimester abortion or miscarriage</span></li><li><span>Can be inserted 6 weeks following 2</span><span>nd</span><span> trimester abortion of miscarriage, or postpartum</span></li></ul></td></tr><tr><td><h3><span>Possible Side Effects</span></h3></td><td><ul><li><span>Most common reasons for discontinuation are unacceptable vaginal bleeding and pain, less common are hormonal problems (non-bleeding)</span></li><li><span>Embedment in the myometrium</span></li><li><span>Severe infection or sepsis following insertion (rare)</span></li><li><span>Device may break during a difficult removal. All pieces must be found and removed, which may require surgery</span></li><li><span>Threads may retract into the uterus or break</span></li><li><span>Substances which may increase the clearance of levonorgestrel include phenytoin, barbiturates, primidone, carbamazepine, and rifampicin</span></li><li><span>See below</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect use: 99.8%</span></li><li><span>Typical use: N/A</span></li><li><span>Continuance: 81% (NCCWCH, 2005, p. 31)</span><ul><li><span>60% within 5 years</span></li></ul></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>T-shaped devices are available worldwide by prescription</span></li><li><span>Frameless devices available by prescription in Belgium</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><p><span>There are many progestin-only intrauterine devices available worldwide. The following are some of the brands available in North America and Europe. We are interested to hear about products locally available to you in your journal discussions.</span></p><ul><li><span>Mirena® by Bayer and Eloira® by Pregna International Ltd. (India):</span><ul><li><span>Contains 52mg of levonorgestrel</span></li><li><span>Releases 20mcg of levonorgestrel per day</span></li><li><span>Use for up to 5 years</span></li><li><span>Some studies suggest it can be left in place up to 7 years</span></li></ul></li><li><span>Kyleena® by Bayer:</span><ul><li><span>Contains 19.5mg of levonorgestrel</span></li><li><span>Releases an average of 9mcg of levonorgestrel per day</span></li><li><span>Use for up to 5 years</span></li></ul></li><li><span>Fibroplant®:</span><ul><li><span>Releases 20mg of levonorgestrel per day</span></li><li><span>Use for up to 5 years</span></li></ul></li><li><span>Jaydess® and Skyla® by Bayer:</span><ul><li><span>Contains 13.5mg of levonorgestrel</span></li><li><span>Releases an average of 6mcg of levonorgestrel per day</span></li><li><span>Use for up to 3 years</span></li></ul></li><li><span>Liletta® by Actavis Pharma, Inc.:</span><ul><li><span>Contains 52mg of levonorgestrel</span></li><li><span>Releases an average of 15.6mcg of levonorgestrel per day</span></li><li><span>Use for up to 3 years</span></li><li><span>May be extended for use up to 5 years, depending on the healthcare provider</span></li></ul></li><li><span>Progestasert® by ALZA Corporation (discontinued)</span></li></ul></td></tr><tr><td><h3><span>Contraindications</span></h3></td><td><ul><li><span>Current or recurrent Pelvic Inflammatory Disease (PID)</span></li><li><span>Uterine anomalies if they distort the uterine cavity</span></li><li><span>Uterine or cervical malignancy</span></li><li><span>Cervicitis</span></li><li><span>Cervical dysplasia</span></li><li><span>Septic abortion within the previous 3 months</span></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>May be used by breast / chest user</span></li><li><span>No documented side effect of weight gain</span></li><li><span>Users who are 40 years of age or older may retain device until menopause &nbsp;</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Requires access to healthcare provider for prescription and insertion</span></li><li><span>May require infections testing before insertion</span></li><li><span>Risk of perforation of the uterus during insertion / removal which may result in pain and bleeding (low, related to skill of healthcare professional inserting the device. &lt; 1 in 1000)</span></li><li><span>Risk of expulsion (low, &lt;1 in 20 in 5 years)</span></li><li><span>Increased r</span><span>isk of ectopic pregnancy (1 in 1000 in 5 years)</span></li><li><span>If method fails and pregnancy occurs, 1 in 20 pregnancies will be ectopic<br></span></li><li><span>Tampon users should be careful of inadvertently pulling on the threads</span></li><li><span>Should not be used by people with current or recurrent PID</span></li><li><span>Not suitable as a post-coital emergency contraceptive</span></li><li><span>Can only be safely scanned by MRI under very specific conditions</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Once device is removed fertility should return to normal</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CA</span><span>D $450 at pharmacies for Mirena®</span></li><li><span>CAD $270 at pharmacies for Jaydess®</span></li><li><span>As of January 2018, IUS prescriptions are free for people without parental insurance coverage and under 25 in Canada</span></li><li><span>USD $800 - $1,100 for Mirena® (with insurance)</span></li><li><span>USD $781 for Skyla® (with insurance)</span></li><li><span>£83.16 - £140 for Mirena® + insertion cost</span></li><li><span>Rs. 4,5000 (Indian Rupees) for Eloira®</span></li></ul></td></tr></tbody></table>

<table><tbody><tr><td colspan="2"><h2><strong>All Progestin-only CEDs</strong></h2></td></tr><tr><td><h3><span>Mechanism of Action</span></h3></td><td><ul><li><span>Inhibit ovulation in &lt; 60% of cycles with low doses</span></li><li><span>Inhibit ovulation in 97 - 100% of cycles w</span><span>ith intermediate or high doses</span><span><br></span></li><li><span>Increase Type-G (dry) mucus production, and inhibit Type-E (fertile quality) mucus</span></li><li><span>Suppress FSH levels and LH surge</span></li><li><span>Fallopian tube secretions, peristalsis, and uterine contractility inhibit sperm and ovum transport</span></li><li><span>Cause premature degeneration of the corpus luteum (luteolysis) in cycles where ovulation does occur</span></li><li><span>Produce strong antiproliferative effect on the endometrium, causing it to remain thin and unvascularized</span></li></ul></td></tr><tr><td><h3><span>Possible Short -Term Side Effects</span></h3></td><td><ul><li><span>Headache</span></li><li><span>Onset or exacerbation of migraine</span></li><li><span>Nausea and vomiting</span></li><li><span>Dizziness</span></li><li><span>Breast problems (tenderness, pain, enlargement, discomfort, discharge)</span></li><li><span>Abdominal pain (due to enlarged follicular development)</span></li><li><span>Irregular bleeding (absence of bleeding, or frequent bleeding or spotting, or long duration of bleeding episodes)</span></li><li><span>Mood changes (Depression, low libido, anxiety, etc.)</span></li><li><span>Worsening or improving acne</span></li><li><span>Change in vaginal secretions</span></li><li><span>Vaginal infections (BV, yeast, altered flora)</span></li><li><span>Bloating (water retention)</span></li><li><span>Weight gain or loss</span></li></ul></td></tr><tr><td><h3><span>Possible Long -Term Side Effects</span></h3></td><td><ul><li><span>Amenorrhea</span></li><li><span>Ovarian cysts</span></li><li><span>Oligomenorrhea</span></li><li><span>Hyperinsulinism</span></li><li><span>Androgenic side effects (acne, hirsutism, and weight gain)</span></li><li><span>Migraine</span></li><li><span>Hirsutism</span></li><li><span>Decreased lactation (rarely)</span></li><li><span>Increased risk of carcinoma of the breast and reproductive organs</span></li><li><span>May increase risk of HPV infection or other sexually transmitted infections (unclear to what extent this is due to difference in sexual behaviour or other factors)</span></li><li><span>Up to half of pregnancies that occur with an IUS in place are ectopic</span></li></ul></td></tr><tr><td><h3><span>Contraindications</span></h3></td><td><p><span>There are some conditions contraindicated in the use of progestin-only CEDs. In most jurisdictions, people with a history of or current risk factors below cannot be prescribed progestin-only CEDs. Some medical providers do prescribe subjects with these medications when the following factors are present, only with careful and regular monitoring. This list is not organized in order of priority.</span></p><ul><li><span>Progestin-Only CEDs CANNOT be taken if the user has a history of or current:</span><ul><li><span>Hypertension (uncontrolled by medication)</span></li><li><span>Known or suspected carcinoma of the breast or other sex organs</span></li><li><span>Known or suspected progestin-dependent neoplasia</span></li><li><span>Unexplained vaginal or uterine bleeding</span></li><li><span>Impaired gallbladder or liver function</span></li><li><span>Active liver disease or benign or malignant liver tumours</span></li><li><span>Lipid metabolism disorders</span></li><li><span>Post-partum endometritis</span></li><li><span>Bacterial endocarditis</span></li><li><span>Immunodeficiency</span></li><li><span>Acute malignancies affecting blood or leukemias</span></li></ul></li><li><span>Progestin-Only CEDs CANNOT be taken if the user:</span><ul><li><span>Is or suspected to be pregnant</span></li></ul></li><li><span>Use of progestin-Only CEDS should be carefully monitored if the user:</span><ul><li><span>Has migraines, or migraines with aura</span></li><li><span>Has a history of stroke or myocardial infarction</span></li><li><span>Smokes</span></li><li><span>Has diabetes. Should be observed closely to detect alterations in carbohydrate metabolism</span></li><li><span>Has a history of ectopic pregnancy, tubal surgery, or pelvic infection</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not interfere with spontaneity in sexual activity</span></li><li><span>Gives user control over pregnancy avoidance</span></li><li><span>Can be used therapeutically to “treat” acne, menstrual pain, and menstrual irregularity (See Section 4.6)</span></li><li><span>May be combined with barrier methods</span></li><li><span>Can be used by breast / chest feeding user (does not change the quantity and quality of milk production)</span></li><li><span>More cost-effective than combined artificial CEDs</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Disposable, creates waste</span></li><li><span>Metabolized by the liver (eliminated in urine, bile, and feces)</span></li><li><span>Synthetic hormone is processed by the body, secreted, and contaminates water systems</span></li><li><span>Must be used on a routine basis as directed for maximum effectiveness regardless of frequency of user sexual activity</span></li><li><span>Do not protect against STIs</span></li><li><span>Require prescriptions in most jurisdictions</span></li></ul></td></tr></tbody></table>

### Suggested Readings {.unnumbered}

-   [https://www.nexplanon.com/](https://www.nexplanon.com/)
-   [https://www.mirena-us.com/](https://www.mirena-us.com/)
-   [http://www.eloira.in/](http://www.eloira.in/)

###  Bibliography {.unnumbered}

-   Azmat, S. K., Hameed, W, Lendway, A., Shaikh, B. T., Mustafa, G., Siddiqui, M. A. … Feldblum, P. J. (2014). Rationale, design, and cohort enrolment of a prospective observational study of the clinical performance of the new contraceptive implant (Femplant) in Pakistan. In _International Journal of Women's Health (6)_: 573 - 583. [http://dx.doig.org/10.2147/IJWH.S58438](http://dx.doig.org/10.2147/IJWH.S58438)
-   Barbosa, I. C., Maia, H., Coutinho, E. Lopes, R., Lopes, A. C. V., Noronha, C., & Botto, A. 92006). Effects of a single Silastic® contraceptive implant containing nomegestrol acetate (Uniplant) on endometrial morphology and ovarian function for 1 year. In _Contraception 74_: 492 - 497. Doi:10.1016/j.contraception.2006.07.013  
-   BJOG. British Journal of Obstetrics and Gynaecology. (1997). Gynaecological aspects of the levonorgestrel-releasing intrauterine system. In _British Journal of Obstetrics and Gynaecology 104_: 285 - 289.  
-   Brache, V. (2012, April 20). Contraceptive Vaginal Rings. _Vision for Contraceptive Research and Development: 100__th_ _meeting ICCR._ New York, International Committee for Contraception Research (ICCR).
-   Carr, S. L., Gaffield, M. E., Dragoman, M. V, & Phillips, S. (2016). Safety of the progesterone-releasing vaginal ring (PVR) among lactating women: A systematic review. In _Contraception 94_: 253 - 261. [http://dx.doi.org/10/1016/j.contraception.2015.04.001](http://dx.doi.org/10/1016/j.contraception.2015.04.001)  
-   Friend, D. R. (2016). Development of controlled release systems over the past 50 years in the area of contraception. In _Journal of Controlled Release 240_: 235 - 241. http:dx.doi.org/10.1016/j.jconrel.2015.12.043
-   Jurow, R., & Shoupe, D. (2006). Long-Acting Progestin Injectables. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception_ (pp. 101 - 115). Totowa, NJ: Humana Press.  
-   Massai, R. Diaz, S., Jackanicz, T., & Croxatto, H. B. (2000). Vaginal rings for contraception in lactating women. In _Steroids 65_: 703 - 707.
-   Meckstroth, K., & Darney, P. (2008). Implantable Contraception. In _Global Library of Women's Medicine._ Doi:10.3843/GLOWM.10399
-   NCCWCH - National Collaborating Centre for Women's and Children's Health. (2005). _Long-acting reversible contraception: the effective and appropriate use of long-acting reversible contraception._  London, UK: RCOG Press at the Royal College of Obstetricians and Gynacologists.
-   Ojule, J.D., Oranu, E. O, & Enyindah, C. E. (2012). Experience with Implanon in Southern Nigeria. In _Journal of Medicine and Medical Sciences 3_(11): 710 - 714. Retrieved from: [http://www.interesjournals.org/full-articles/experience-with-implanon-in-southern-nigeria.pdf?view=inline](http://www.interesjournals.org/full-articles/experience-with-implanon-in-southern-nigeria.pdf?view=inline)
-   Ramarao, S., Clark, H., Merkatz, R., Sussman, H., & Sitruk-Ware, R. (2013). Progesterone vaginal ring: Introducing a contraceptive to meet the needs of breastfeeding women. In _Contraception 88_: 591 - 598. [http://dx.doi.org/10.1016/j.contraception.2013.05.004](http://dx.doi.org/10.1016/j.contraception.2013.05.004)
-   RHSC (Reproductive Health Supplies Coalition). (2012). Product Brief, Caucus on New and Underused RH Technologies: Progesterone Vaginal Ring. Retrieved from: [https://www.path.org/publications/files/RHSC\_progesterone\_br.pdf](https://www.path.org/publications/files/RHSC_progesterone_br.pdf)
-   Shaamsh, A. H, Salem, H. T., Shaaban, M. M., Ghaneima, S. A., & Helat, S. R. (2005). Effect of Uniplant on Liver Function in Egyptian Women with Asymptomatic Hepatitis B Virus Infection. In _African Journal of Reproductive Health / La Revue Africaine de Reproductive (9)_1: 24 - 31. [http://www.jstor.org/stable/3583157](http://www.jstor.org/stable/3583157)
-   Shoupe, D., & Mishell, D. R. (2006). Oral Contraceptives: History, Pharmacology, Metabolic Effects, Side Effects, and Health Benefits. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 13 - 43). Totowa, NJ: Humana Press.  
-   Sivin, I., Croxatto, H., Bahamondes, L., Brache, V., Alvarez, F., Massai, R. … Moo-Young, A. (2004). Two-year performance of a Nestorone®-releasing contraceptive implant: a three-centre study of 300 women. In _Contraception 69_: 137 -144. Doi:10.1016/j.contraception.2003.10.003
-   Smith, J. M, Moss, J.A, Srinivasan, P. Butkyavichene, I., Gunawardana, M., Fanter, R. … Baum, M. M. (2017). Novel multipurpose pod-intravaginal ring for the prevention of HIV, HSV, and unintended pregnancy: Pharmacokinetic evaluation in a macaque model. _PLoS One 12_(1): e0185946. Doi: 10.1371/journal.pone.0185946. eCollection 2017.  
-   Srivastava, R. K., Tanwar, H., Singh, P., & Patro, B. C. (2012). _Injectable Contraceptives to Epxland the Basket of Choice under India's Family Planning Programme: An Update._ Retrieved from: [http://www.nihfw.org/Doc/Policy\_unit/Injectable%20Contraceptives%20Programme%20An%20Update.%20September%202012.pdf](http://www.nihfw.org/Doc/Policy_unit/Injectable%20Contraceptives%20Programme%20An%20Update.%20September%202012.pdf)
-   Wildemeersch, D., Andrade, A., Goldstuck, N. D., Hasskamp, T., & Jackers, G. (2017). Intrauterine levonorgestrel delivery with frameless fibrous delivery system: review of clinical experience. _International Journal of Women's Health 9_, p. 49 - 58. [http://dx.doi.org/10.2147/IJWH.S122579](http://dx.doi.org/10.2147/IJWH.S122579)

  

___

  

## Unit D HRHP 4.5 - Menstrual Suppression by Artificial CEDs {.unnumbered}

Over the better part of the last two decades menstrual suppression has been a hotly debated topic. Technically, users of combined artificial CEDs can skip the hormonal “break” allotted, continuing to take active hormones and suppressing withdrawal bleeding. Users have been known to manipulate contraceptive pills this way for their convenience, with the approval and encouragement of their doctors, such as for postponing bleeding until after weddings, travel, athletic events, military deployment, etc. Such practices have been documented since the 1970s (Jacobson, Likis, & Aikins Murphy, 2012, p. 585).

However, suppressing menstruation entirely, as it occurs with the use of long acting progestin-only contraceptives, has been one of the disincentives to uptake of these methods. There was until recently no consensus in the conventional medical community that suppressing menstruation with combined contraceptives is either medically safe or unsafe for a person with previously healthy cycles. As of October 2014, the clinical practice guidelines of the Society of Obstetricians and Gynaecologists of Canada states that menstrual suppression or “therapeutic amenorrhea” is a safe and viable option for women who need or want fewer menses (SOGC, 2014, p. 915).

With the advent of Long Acting Reversible Contraceptive methods, and the appeal of freedom from user adherence, it has become increasingly acceptable for the medical community to strongly encourage menstrual suppression as a positive side effect.  In the late 1990s, Dr. Elsimar Coutinho, a Brazilian gynecologist, professor, and a pioneer in the use of Depo-Provera®, sparked controversy by claiming that the cultural value of menstruation is not related to its physiological value. For Coutinho menstruation is not only not medically necessary, but not a “'natural' state of women” (Coutinho & Segal, 1999, p. x). Dr. Coutinho claims that suppressing menstruation should be done to improve women's medical health, because regular menstruation is not necessary, and carries a risk of menstrual disorders.

The argument for menstrual suppression is based on the biological truth that modern folks who menstruate do so much more than in the past, because of cultural changes such as a reduction in the fertility rate, later childbearing, shortening durations of breast / chest feeding, later menopause, and greater involvement of women in the workforce. While the desirability of these changes is not up for debate, feminist critics argue that suppressing menstruation with the use of potent birth control pills is not by far a healthful solution to menstrual health concerns. In her book _No More Periods: The Blessings of the Curse_ (2003), Dr. Susan Rako responds to the question of whether menstrual suppression is harmful by discussing the risks of artificial CEDs, such as less bioavailability of natural testosterone, excess iron, greater risk of HPV, and irregular bleeding, to name a few.

Health professionals who advocate for therapeutic amenorrhea often have financial ties to the pharmaceutical industry as consultants and speakers (Hitchcock, 2008, p. 712). Sometimes they cite not medical concerns, but “women's preferences” for less bleeding (Nappi, Kaunitz, & Bitzer, 2016, p. 109). Further, and perhaps rightfully so, they see bleeding as unnecessary in the context of normative OCP use (p. 705). The argument goes that placebo pills were included in contraceptive regimens to mimic a person's natural cycle because it was thought this regimen could gain approval of the Catholic Church, reassure women they were not pregnant, and alleviate concerns about long-term adverse effects (Jacobson, Likis, & Aikins Murphy, 2012, p. 585). Now that hormonal methods are widespread, there is no reason to endure bleeding at all, as it is not a true menstruation with combined CEDs anyway. Hormone withdrawal increases the risk of a return of ovulation and can induce symptoms such as headaches, bloating, pelvic pain, etc. (Nappi, Kaunitz, & Bitzer, 2016, p. 106).

By contrast, critics of suppression see menstruation as part of a normal endocrine reproductive cycle, and a spontaneous menstrual cycle as normative. They argue that the safety of extended regimens of artificial hormone use requires evidence that should be presented along with discussions of side effects and risks of CEDs as one of many choices for pregnancy avoidance. Not only are there significant risks with the use of synthetic hormones (see Section 4.7), but their 'therapeutic' use for menstrual disorders points to the tendency of conventional scientific communities to medicate menstrual problems and suppress symptoms instead of developing therapies that heal the source of disease (see Section 4.6).

Many health experts and women's health advocates are calling for the menstrual cycle to be considered a vital sign—a critical and unique indicator of women's health and well-being (Lippe Taylor, Inc, 2004). Experts of the Society for Menstrual Cycle Research emphasize that the long-term effects of menstrual suppression are unknown. While it can be helpful for people with severe menstrual cycle problems, the Society warns against prescription for “all menstruating women out of a rejection of a normal, healthy menstrual cycle” (Hoffman, 2003).  

While the HRHP is well advised to see the menstrual cycle as a normal part of some of our bodies' experiences, many arguments about the 'natural' quality of menstruation discuss it as part of something integral to “women's” experience. This idea is problematic in its erasure of all the folks who identify as women who for many reasons do not menstruate, and the many men who do. Indeed, part of feminist criticisms of those who argue for menstrual suppression is their tendency to see menstruation within a heterosexist framework solely as failed reproduction (Hitchcock, 2008, p. 704), costly in lost work productivity, or at odds with women's ability to function normally (Granzow, 2014, p. 622).

Our relationships to our bleeding are as complex as they are diverse, and our conceptualization of menstruation has consequences not only for our work on body literacy, but for the revolutionary ways in which our generation is redefining what it means to have a cyclical body. Suffice it to say that for the HRHP and our uterus bearing clients a healthy menstrual cycle is an integral part of a person's overall health and wellbeing.

<table><tbody><tr><td colspan="2"><h2><strong>Extended Cycle Oral Contraceptive Pill<br></strong></h2></td></tr><tr><td><h3><span>What is it?</span></h3></td><td><ul><li><span>Small round tablet containing ethinyl estradiol and levonorgestrel</span></li><li><span>Non-medicinal ingredients: anhydrous lactose, hydroxypropyl methylcellulose, magnesium stearate, microcrystalline cellulose, polyethylene glycol, polysorbate 80, and titanium dioxide</span></li><li><span>Comes in 3 blister packs: pack 1 and 2 each hold 28 active monophasic pills, and pack 3 holds 35 active pills, or either 28 active pills and 7 placebos or 28 active pills and 7 low dose ethinyl estradiol pills</span></li></ul></td></tr><tr><td><h3><span>How do you use it?</span></h3></td><td><ul><li><span>User must ingest the pill orally every day, at the same time of day, producing a daily peak of synthetic hormone</span></li><li><span>Active pills are taken for 84 - 91 days, followed by 7 days of placebos, low dose ethinyl estradiol pills, or a break to allow for withdrawal bleeding</span></li><li><span>Schedule reduces withdrawal bleeding to 4 times per year</span></li><li><span>If a dose is late, contraceptive effect is maintained if taken within 12 hours</span></li><li><span>If a dose is late beyond 12 hours, user must take 2 pills and use condoms for 7 days as they return to the regular dosage schedule</span></li></ul></td></tr><tr><td><h3><span>Possible side effects</span></h3></td><td><ul><li><span>Breakthrough bleeding, especially in the first 3 months</span></li><li><span>See Section 4.7 Side Effects and Risks of Artificial CEDs</span></li></ul></td></tr><tr><td><h3><span>Effectiveness Rate</span></h3></td><td><ul><li><span>Perfect Use: 98%</span></li><li><span>Typical Use: No data available &nbsp;</span></li><li><span>Continuance: No data available</span></li></ul></td></tr><tr><td><h3><span>How available?</span></h3></td><td><ul><li><span>By prescription at pharmacies worldwide &nbsp;</span></li></ul></td></tr><tr><td><h3><span>Brand Names &amp; Manufacturers</span></h3></td><td><ul><li><span>84 active pills (levonorgestrel 0.15mg; ethinyl estradiol 0.03mg), plus 7 placebos:</span><ul><li><span>Seasonale® and Jolessa® by Barr (approved by FDA in 2003)</span></li><li><span>Introvale® by Laboratorios Leon Farma (Spain)</span></li><li><span>Quasense® by Teva Pharmaceuticals</span></li></ul></li><li><span>84 active pills (levonorgestrel 0.15mg; ethinyl estradiol 0.03mg), plus 7 low dosage (0.01mg) ethinyl estradiol pills:</span><ul><li><span>Seasonique® and LoSeasonique® by Paladin Labs Inc</span></li><li><span>Amethia®</span></li><li><span>Camrese®</span></li></ul></li><li><span>91 active pills (levonorgestrel 0.09mg; ethinyl estradiol 0.02mg). No hormone free interval:</span><ul><li><span>Lybrel® by Wyeth Pharmaceuticals (approved by FDA in 2007)</span></li></ul></li></ul></td></tr><tr><td><h3><span>Advantages</span></h3></td><td><ul><li><span>Does not require inserting anything in the vagina. However, may lead to altered vaginal flora</span></li></ul></td></tr><tr><td><h3><span>Disadvantages</span></h3></td><td><ul><li><span>Must be taken every day at the same time of day, regardless of frequency of user sexual activity</span></li><li><span>Hormone is absorbed through the digestive system, which may cause nausea and vomiting. Digestion problems may interfere with absorption</span></li><li><span>Most subjects in clinical trials were continuous users of combined artificial CEDs. There is little data on the effects on first time users. Further, most studies of extended regimens have followed users for only up to 2 - 4 years (there is no data on longer term extended regimen use) &nbsp;</span></li><li><span>Contraindications are the same as combined CEDs</span></li><li><span>May require partner cooperation</span></li></ul></td></tr><tr><td><h3><span>Reversal</span></h3></td><td><ul><li><span>Dependent on length of use and prior reproductive health status</span></li><li><span>There is no data on whether menstrual suppression lengthens the return of fertility</span></li></ul></td></tr><tr><td><h3><span>Cost</span></h3></td><td><ul><li><span>CAD $40 - 140 at pharmacies, depending on insurance and brand</span></li><li><span>As of January 2018, most birth control prescriptions are free for people without parental insurance coverage and&nbsp; under 25 in Canada</span></li><li><span>USD $50 - 150, depending on insurance coverage and brand</span></li></ul></td></tr></tbody></table>

### Suggested Readings {.unnumbered}

-   [www.susanrako.com/index.html](http://www.susanrako.com/index.html)     
-   [www.menstruationresearch.org](http://www.menstruationresearch.org/)
-   [www.mum.org](http://www.mum.org/)
-   [ww.noperiod.com](http://www.noperiod.com/)

### Required Readings {.unnumbered}

-   Rako, S. (2003). _No More Periods? The Blessings of the Curse._ Lincoln, NE: iUniverse, Inc.  
    

### References {.unnumbered}

-   Coutinho, E. M. & Segal, S. S. (1999). _Is Menstruation Obsolete? How suppressing menstruation can help women who suffer from anemia, endometriosis, or PMS._ NY: Oxford University Press.
-   Granzow, K. (2014). The 'nonmenstrual woman' in the new millennium? Discourses on menstrual suppression in the first decade of Extended Cycle Oral Contraception use in Canada. In _Culture, Health, & Sexuality 16_(6): 620 - 633. http://dx.doi.org.10.1080/13691058.214.896475  
-   Hitchcock, C. L. (2008). Elements of the Menstrual Suppression Debate. _Health Care for Women International 29_: 702 - 719. Doi: 10.1010/07399330802179155
-   Hoffman, K. (2003, June 24). Foes raise red flag against suppression of menstruation. In _post-gazette.com._ Retrieved from: [http://old.post-gazette.com/healthscience/20030624hcycle2.asp](http://old.post-gazette.com/healthscience/20030624hcycle2.asp)
-   Jacobson, J. C., Likis, F. E., & Aikins Murphy, P. (2012). Extended and Continuous Combined Contraceptive Regimens for Menstrual Suppression. In _Journal of Midwifery & Women's Health 57:_ 585 - 592. doi:10.1111/j.1542-2011.2012.00250x
-   Lippe Taylor, Inc. (2004, Sept 21). Scientific forum addresses menstrual cycle as vital sign. In _EurekAlert! The Global Source for Science News._ Retrieved from:  [https://www.eurekalert.org/pub\_releases/2004-09/lti-sfa092004.php](https://www.eurekalert.org/pub_releases/2004-09/lti-sfa092004.php)
-   Nappi, R. E., Kaunitz, A. M., & Bitzer, J. (2016). Extended regimen combined oral contraception: A review of evolving concepts and acceptance by women and clinicians. In _The European Journal of Contraception and Reproductive Health 21_(2), 106 - 115. [http://dx.doi.org/10.3109/13625187.2015.1107894](http://dx.doi.org/10.3109/13625187.2015.1107894).
-   Rako, S. (2003). _No More Periods? The Blessings of the Curse._ Lincoln, NE: iUniverse, Inc.
-   SOGC (Society of Obstetricians and Gynaecologists of Canada). (2014). SOGC Clinical Practice Guideline: Menstrual Suppression in Special Circumstances. _J Obstet Cynaecol Can 36_(10): 915 - 924. 

  

___

  

Unit D HRHP 4.6 - "Therapeutic Use" of Artificial CEDs {.unnumbered}

Contraceptive Endocrine Disruptors are sometimes used for non-contraceptive reasons to medically treat a variety of gynaecological health problems, or to suppress menstruation in people for whom it would be detrimental because of other health conditions. Artificial CEDs of choice for therapeutic use are the monophasic oral contraceptive pill, or LARCs. Many studies demonstrate several health benefits to artificial hormone use (outlined below), however, as we will discuss in Section 4.7, these methods cause significant side effects and carry a cardiovascular risk that may outweigh the commonly perceived benefits.

Note that much information about benefits directly contradicts information regarding risks. Research studies often arrive at contradictory findings, and the quality of findings depends on the quality of the data, rigour of academic ethics, strength of statistical analysis, etc. As you might imagine, findings are selectively reported on based on the context of conversations and audiences - if you are speaking to people who oppose birth control at all you may taylor your information differently than if you are speaking to an audience of liberally minded doctors. Further, many of the conditions noted below can also be effectively treated through complementary or alternative medicine, nutritional, and / or lifestyle changes.

### Medical Conditions treated with Artificial CEDs {.unnumbered}

-   Adrogenisation (acne, alopecia, hirsutism, and seborrhea)
-   Anemia
-   Adenomyosis / Endometriosis
-   Chronic pelvic pain
-   Dysfunctional uterine bleeding
-   Dysmenorrhea
-   Endometrial cancer
-   Endometrial hyperplasia
-   Fibrocystic breast disease
-   Inability to manage menstrual bleeding (due to mobility constraints or developmental disability)  
    
-   Menorrhagia
-   Migraines (menstrual)
-   Multiple sclerosis
-   Myoma (fibroids)
-   Perimenopausal symptoms
-   Polycystic Ovarian Syndrome (PCOS)
-   Premenstrual Syndrome (PMS)
-   Premenstrual Dysphoric Disorder (PMDD)
-   Rheumatoid arthritis
-   Ovarian cysts
-   Bothersome symptoms of perimenopause (hormone replacement therapy)
-   Renal cancer

### Non-contraceptive Benefits of Artificial CEDs {.unnumbered}

-   Reduced risk of:
    -   Anemia
    -   Benign breast disease
        -   Fibrocystic breast disease reduced by 30%
        -   Fibroadenoma reduced by 60%
        -   Clinically found breast lumps reduced by 40%
        -   Breast ductal hyperplasia risk reduced with more than 8 years of use
        -   Risk of benign breast disease is reduced with longer duration of use. Constant users demonstrate the lowest risk.
        -   Risk reduction lasts up to one year after discontinuation
    -   Colorectal cancer
    -   Ectopic pregnancy
    -   Endometrial cancer
        -   Reduced by 40% after 1 year of use, and by 80% after 10 years of use, with protection lasting up to 20 years
    -   Ovarian cancer
        -   Reduced by 40% after use, and by 80% after 10 years of use, with protection lasting up to 20 years
        -   Significant risk reduction in carriers of BRCA1 and BRCA2
    -   Breast cancer
        -   Protection may include those with BRCA mutations or strong family history, but some studies suggest it is limited to those not genetically at risk
    -   Pelvic Inflammatory Disease (especially gonorrhea PID)
        -   Reduced by 50 - 60%
        -   Due to thickened and impenetrable cervical mucus
        -   PID occurring during CED use is associated with less severe inflammation
        -   However, changes in vaginal flora may lead to increased risk
    -   Rheumatoid Arthritis
        -   Reduced by 30 - 51%
-   Less functional ovarian cysts  
-   Less frequent curettage or hysterectomy
-   Less mittelschmerz
-   Less cyclic mood changes or other premenstrual symptoms
-   Lowered incidence of symptomatic endometriosis
-   Peri and postmenopausal women (40+) tend to gain or preserve Bone Mineral Density (BMD)
-   Reduction of asthmatic symptoms
-   Reduction in hot flashes and other perimenopausal symptoms
-   Reduction in maternal deaths in women over 40 (by reducing the number of pregnancies)

### Bibliography {.unnumbered}

-   Bahamondes, L., Bahamondes, M. V., & Shulman, L. P. (2015). Non-contraceptive benefits of hormonal and intrauterine reversible contraceptive methods. In _Human Reproduction Update 21_(5), p. 640 - 651. Doi:10.1093/humupd/dmw023
-   Dragoman, M. V. (2014). The combined oral contraceptive pill-recent developments, risks and benefits. In _Best Practice & Research Clinical Obstetrics and Gynaecology 28_, p. 825 - 834. [http://dx.doi.org/10.1016/j.bpobgyn.2014.06.003](http://dx.doi.org/10.1016/j.bpobgyn.2014.06.003)
-   Hillard, P. A. (2014). Menstrual suppression: current perspectives. _International Journal of Women's Health 6,_ 631 - 637. [http://dx.doi.org/10.2147/IJWH.S46680](http://dx.doi.org/10.2147/IJWH.S46680)
-   Jurow, R., & Shoupe, D. (2006). Long Acting Progestin Injectables. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 101 - 114). Totowa, NJ: Humana Press.  
-   Mendoza, N., & Sanchez-Borrego, R. (2014). Classical and newly recognised non-contraceptive benefits of combined hormonal contraceptive use in women over 40. In _Maturitas 78_, p. 45 - 50. http:////dx.doi.org/10.1016/j.maturitas.2014.02.017
-   Schindler, A. E. (2013). Non-Contraceptive Benefits of Oral Hormonal Contraceptives. _International Journal of Endocrinology & Metabolism 11_(1), 41 - 47. Doi:10.5812/ijem.4158
-   Shoupe, D. (2006). Progestin-Only Oral Contraceptives. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 67 - 73). Totowa, NJ: Humana Press.  
-   Shoupe, D., & Mishell, D. R. (2006). Oral Contraceptives: History, Pharmacology, Metabolic Effects, Side Effects, and Health Benefits. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 13 - 43). Totowa, NJ: Humana Press.  

  

___

  

## Journal Activity - Unit D 4.6 Contraceptive Endocrine Disruptors {.unnumbered}

There are many diagnosable clinical diseases and disorders that claim an abnormal hormone situation as the primary cause, such as clinical depression, Parkinson's disease, insulin dependent diabetes, and amenorrhea, to name a few. All claim a faulty endocrine system and are treated by correcting this fault with hormones of various forms.

Consider the contradiction in the conventional medical community's ideas regarding synthetic hormones. Hormone imbalances such as those causing the conditions above are considered diseases to be treated, yet at the same time the community claims that it is okay for a healthy person to disrupt their own reproductive endocrine system? In other words, the use of contraceptive endocrine disruptors to make a healthy system sick is considered to carry little risk, be medically safe, and even desirable. Missing from the discussion are the potential side effects of this long-term hormone imbalance, and the myriad of medical conditions we know are caused by such endocrine disruption.

What are your thoughts regarding the therapeutic use of artificial CEDs? Reflect on the contradictions in the discourse of medical literature regarding endocrine disruptors.

  

___

  

## Unit D HRHP 4.7 - Side Effects and Risks of Artificial CEDs {.unnumbered}

Artificial Contraceptive Endocrine Disruptors are not safe for everyone to use. There are many side effects and risks involved. In most countries, the use of these medications requires doctor counselling and prescription; in some, they are easily available through pharmacies without prescriptions. Risks and potential side effects are always measured in relation to the same in pregnancy. This section includes discussions of the most common reasons users report hesitancy to use CEDs: side effects and risks.

<table><tbody><tr><td colspan="2"><h2><strong>Documented Side Effects of All Steroidal Artificial CEDs</strong></h2></td></tr><tr><td colspan="2"><ul><li><span>Acne / oily skin</span></li><li><span>Anovulation after discontinuation for 6 -18 months</span></li><li><span>Breakthrough bleeding / spotting</span></li><li><span>Benign breast disease (pain, tenderness, fibroadenomas, etc.)</span></li><li><span>Bloating</span></li><li><span>Cholestatic jaundice</span></li><li><span>Decreased carbohydrate metabolism</span></li><li><span>Decreased lipid metabolism</span></li><li><span>Decreased libido</span></li><li><span>Dizziness</span></li><li><span>Headaches</span></li><li><span>Increased breast size</span></li><li><span>Increased risk of:</span><ul><li><span>Breast cancer</span></li><li><span>Cervical cancer</span></li><li><span>Hypertension</span></li><li><span>STI transmission</span></li></ul></li><li><span>Infertility</span></li><li><span>Nausea</span></li><li><span>Nervousness</span></li><li><span>Pronounced mood changes (anxiety, irritability, violence, depression)</span></li><li><span>Vaginal Candidiasis</span></li><li><span>Vomiting</span></li><li><span>Weight changes (increase or decrease)</span></li></ul></td></tr><tr><td><h3><strong>Estrin &amp; Progestin only</strong></h3></td><td><h3><strong>Progestin Only</strong></h3></td></tr><tr><td><ul><li><span>Benign and malignant hepatic tumors</span></li><li><span>Chloasma or melasma (often not reversible)</span></li><li><span>Contact lens intolerance</span></li><li><span>Fluid retention</span></li><li><span>Gallbladder disease</span></li><li><span>Gastrointestinal symptoms</span></li><li><span>Hepatocellular carcinoma</span></li><li><span>Hypercoagulability</span></li><li><span>Increased insulin resistance</span></li><li><span>Increased risk of:</span><ul><li><span>Arterial thromboembolism</span></li><li><span>Cardiovascular disease (CVD</span></li><li><span>Cerebral hemorrhage</span></li><li><span>Cerebral thrombosis</span></li><li><span>Cervical neoplasia</span></li><li><span>Congenital anomalies</span></li><li><span>Hepatocellular adenoma</span></li><li><span>Ischemic or hemorrhagic stroke</span></li><li><span>Mesenteric thrombosis</span></li><li><span>Myocardial infarction</span></li><li><span>Pelvic Inflammatory Disease</span></li><li><span>Permanent sterility</span></li><li><span>Pulmonary embolism</span></li><li><span>Retinal thrombosis</span></li><li><span>Venus thromboembolism</span></li></ul></li><li><span>Lowered circulating free testosterone</span></li><li><span>Lowered free thyroid hormones</span></li></ul></td><td><ul><li><span>Amenorrhea</span><ul><li><span>50% after 1 year of use</span></li><li><span>70% after 2 years of use</span></li></ul></li><li><span>Decreased HDL cholesterol levels</span></li><li><span>Fatigue</span></li><li><span>Hypertension</span></li><li><span>Increased appetite</span></li><li><span>Increased risk of:</span><ul><li><span>Ectopic pregnancy</span></li><li><span>Venus thromboembolism in users of implants or injectables</span></li></ul></li><li><span>Ovarian cysts</span></li><li><span>Unpredictable, irregular, or frequent bleeding</span></li><li><span>Weight gain (Injectables &amp; IUS)</span><ul><li><span>5 - 10lbs in first year</span></li></ul></li></ul></td></tr></tbody></table>

### Cardiovascular Risk of Combined Artificial CEDs {.unnumbered}

Combined contraceptive endocrine disruptors increase the risk of venous thromboembolism two to four-fold. Cigarette smoking increases the risk of serious cardiovascular events, and this risk increases after age 35, and with the number of cigarettes smoked.

The risk of cardiovascular events while taking CEDs is half of the risk associated with pregnancy (Shoupe & Mischell, 2006, p. 20)

Users should stop taking artificial CEDs immediately, and go to the nearest emergency room, if they experience any of the following symptoms:

**A =** Abdominal pain (severe)

**C =** Chest pain (severe), shortness of breath

**H =** Headache (severe)

**E =** Eye problems (vision loss/blurring), speech problems

**S =** Severe leg pain (calf or thigh) 

### Method-Specific Risks and Side Effects {.unnumbered}

#### Evra® (Contraceptive Patch) {.unnumbered}

-   Greater risk of developing gallbladder disease
-   The risk of venous thromboembolism in users of the Evra® patch has been found to be 2.5 times higher than in users of the oral contraceptive pill (Evra monograph, p. 5).
-   May be less effective in users with body weight > 90kg (198lbs) (Evra monograph, p. 10)
-   Safety and efficacy of Evra have not been established in users younger than 18 years of age.
-   Due to risk of increased exposure to ethinyl estradiol users are advised to avoid Evra is regularly exposed to direct external heat sources (heating pads, electric blankets, saunas, whirlpools, intensive sunbathing, etc).
-   Skin irritation
-   Patch may come off 

#### Nuvaring® (Combined Intravaginal Ring)

-   Ulcers or lacerations in vagina or cervix
-   Ring may be expelled during sexual activity or with bowel movements 

#### Depo-Provera® (depot-medroxyprogesterone acetate - DMPA)

-   Amenorrhea: 50% after 1 year of use, 70% after 2 years 
-   Weight gain of up to 2 - 3kg per year 
-   Return of fertility may be delayed by as much as 7 - 9 months 
-   Skin irritation and / or scarring at the site of injection
-   Users of Depo-Provera may lose significant bone mineral density (BMD). Bone density loss is greater with increasing duration of use (2 years or more) and may not be completely reversible. Not recommended for use for more than two years unless no other suitable method of contraception is available.
-   As of November 2004, Depo-Provera comes with a “black box” warning from the U. S. Food and Drug Administration alerting users to significant bone mineral density loss.

#### Contraceptive Implants

-   Amenorrhea in 20% of users 
-   Infrequent, frequent, or prolonged bleeding (45% of users; reason for discontinuation in 33% of users)
-   Mood changes (< 10% report it as a reason for discontinuance)
-   Low libido (<2% report it as a reason for discontinuance)
-   Weight gain (reason for discontinuation in 2.3% of users) 
    -   Implanon®: average 2.8 lbs after 1 year, and 3.7 lbs after 2 years 
    -   Jadelle®: average 9 lbs after 5 years. 20% gained at least 10 lbs in the first year, and 50% gained at least 10 lbs by the end of the 5th year 
-   Should pregnancy occur, it may be more likely to be ectopic than a pregnancy occurring in a person not using contraception 
-   Neural or vascular injury if inserted too deeply  
-   Events of migration to the pulmonary vasculature have been reported with rod implants, in which case surgical procedures may be needed for removal
-   Infection, abscess formation, blistering, ulcerations, sloughing, excessive scarring, phlebitis, and hyperpigmentation can occur at insertion site (capsules)
-   If insertion too shallow, capsules can be expulsed 
-   Insertion and removal complications include:
    -   Pain, edema, bruising, blistering, ulcerations, excessive scarring, or hyperpigmentation at the insertion site 
    -   Broken or non-palpable implants complicating removal occur in 4.8% of users (Norplant), and 0.2% of users (Implanon)
    -   If not palpable, user may need ultrasound or MRI to locate implant (cannot be seen via x-ray or CT scan)
-   Implant expulsion and displacement 

#### Intra-Uterine Systems

-   Risk of expulsion (< 20 in 5 years)
-   Risk of uterine perforation (<1 in 1000)
-   Risk of uterine embedment
-   Risk of malposition 
-   If method fails and pregnancy occurs, 1 in 20 pregnancies will be ectopic 
-   Severe infection or sepsis following insertion (rare)

### Post-marketing Experience {.unnumbered}

Manufacturers of CEDs also disclose adverse drug reactions that have been reported voluntarily worldwide by users of their products. The list of these reactions is extensive, and it is not always possible to reliably estimate frequency or establish a causal relationship between the reaction and the  drug exposure. These lists are long, and usually include infections, cysts, polyps, immune system, psychiatric, nervous system, metabolism, eye and cardiac disorders, vascular or arterial events, respiratory, renal, or urinary disorders, as well as reproductive system and breast disorders.

### Drug Interactions {.unnumbered}

It is recommended that users of artificial CEDs have detailed conversations with pharmacists (not only family doctors) regarding interactions with other drug regimens.

#### Combined CEDs are less efficacious when combined with the following:

-   Antacids
-   Anticonvulsants
-   Antibiotics
-   Antifungals
-   Cholesterol-lowering agents
-   HIV protease inhibitors
-   Sedatives (including benzos)
-   Other drugs (ask doctor)
-   St. John's Wort

#### CEDs can interact and change the effect of other medications, including:

-   Anticoagulants
-   Antidiabetic drugs
-   Antihypertensive agents
-   Antipyretics (including ASAs, acetaminophen)
-   Corticosteroids
-   Folic Acid (impaired metabolism)
-   Sedatives and Hypnotics (increased effect) 

### Required Readings {.unnumbered}

1.  Pharmacia & Upjohn company. (2004). Depo-Provera® Contraceptive Injection. Physician Information. NY, NY: Pfizer Inc. 
2.  The Society of Obstetricians and Gynaecologists of Canada Website, “Hormonal Contraception” section [https://www.sexandu.ca/contraception/hormonal-contraception/](https://www.sexandu.ca/contraception/hormonal-contraception/)
3.  Planned Parenthood Federation of America Website. Explore the following sections: Implant, Patch, Pill, Shot. [https://www.plannedparenthood.org/learn/birth-control](https://www.plannedparenthood.org/learn/birth-control)
4.  The Family Planning Association (UK) Website. Explore the following sections: Combined Pill, Implant, Injection, Patch, vaginal ring, IUS, Long acting reversible contraception (LARC), and progestogen-only pill (POP).
5.  **The Boston Women's Health Collective. (2011). “Hormonal Methods: Pill, Minipill, Ring, Patch, Shot” and “Implanon” In _Our Bodies, Ourselves,_ pp. 223 - 237. NY: Touchtone - Simon & Schuster.**

### Bibliography {.unnumbered}

-   De Leo, V. Musaccio, M. M., Cappelli, V., Piomboni, P., & Morgante, G. (2016). Hormonal contraceptives: pharmacology tailored to women's health. In _Human Reproduction Update 22_(5), p. 634 - 646. Doi:10.1093/humupd/dmw016  
-   Hillard, P. A. (2014). Menstrual suppression: current perspectives. _International Journal of Women's Health 6,_ 631 - 637. [http://dx.doi.org/10.2147/IJWH.S46680](http://dx.doi.org/10.2147/IJWH.S46680)
-   Jurow, R., & Shoupe, D. (2006). Long Acting Progestin Injectables. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 101 - 114). Totowa, NJ: Humana Press.  
-   Schindler, A. E. (2013). Non-Contraceptive Benefits of Oral Hormonal Contraceptives. _International Journal of Endocrinology & Metabolism 11_(1), 41 - 47. Doi:10.5812/ijem.4158
-   Shoupe, D. (2006). Progestin-Only Oral Contraceptives. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 67 - 73). Totowa, NJ: Humana Press.  
-   Shoupe, D., & Mishell, D. R. (2006). Oral Contraceptives: History, Pharmacology, Metabolic Effects, Side Effects, and Health Benefits. In Shoupe, D_.,_ & Kjos, S. (Eds.), _The Handbook of Contraception: A Guide for Practical Management_ (pp. 13 - 43). Totowa, NJ: Humana Press.  
-   Sitruk-Ware, R. (2006). New progestogens for contraceptive use. In _Human Reproduction Update 12_(2), p. 169 - 178. Doi:10.1093/humupd/dmi046
-   Tepper, N. K., Whiteman, M. K., Marchbanks, P. A., James, A. H., & Curtis, K. M. (2016). Progestin-only contraception and thromboembolism: A systematic review. In _Contraception 94_, p. 678 - 700. [http://dx.doi.org/10.1016/j.contraception.2016.04.014](http://dx.doi.org/10.1016/j.contraception.2016.04.014)

  

___

  

## Journal Activity - Unit D 4.7 Literature on "Hormonal" Contraceptives {.unnumbered}

As you review Unit D Section 4, compare the information regarding all artificial contraceptive endocrine disruptors (combined and progestin-only), with that presented on websites or other communications of conventional authorities in the world of sexual heath.

Consider your local public health unit, Planned Parenthood clinic, the World Health Organization, Guttmacher Institute, the Society of Obstetricians and Gynecologists of Canada (some links below), or another organization that is known to provide accurate and up to date information for your country or region.

How is the information presented? Are these methods encouraged or discouraged? Is the information complete? Pick a few of your observations for discussion.

-   [www.ppt.on.ca](http://www.ppt.on.ca/)
-   [www.plannedparenthood.org](http://www.plannedparenthood.org/)
-   [http://who.int/reproductivehealth/topics/family\_planning/en/](http://who.int/reproductivehealth/topics/family_planning/en/)
-   [https://www.sexandu.ca/](http://www.sexandu.ca/)
-   [https://www.guttmacher.org/](https://www.guttmacher.org/)
-   [https://www.sexualhealthontario.ca/en/home](https://www.sexualhealthontario.ca/en/home)
-   [http://www.ashasexualhealth.org/](http://www.ashasexualhealth.org/)

  

___

  

## Unit D HRHP 4.8 - Controlling Fertility {.unnumbered}

### Unit D Section 4.8: Controlling Fertility: A Matter of Choice? {.unnumbered}

Excerpt from: 

**Salamanca, L. (2017). Reproductive Justice in Canada: Exploring Immigrant Women's Experiences. In Stettner, S., Burnett, K., & Hay, T. (Eds.). _Abortion: History, Politics, and Reproductive Justice after Morgentaler._ Vancouver, BC: UBC Press.** 

Since the so-called sexual revolution of the 1960s, widespread acceptance of hormonal birth control has created a pernicious climate in which women's decisions _not_ to “just take the pill” are perceived as irresponsible, silly, or uneducated. Most popular in industrialized countries such as New Zealand, Australia, Britain, and the United States, within five years of its launch in the 1960s, nearly eleven million women across the world were taking the pill every year**1**. The new technology was lauded as a dream come true. In the words of an American journalist: “Modern woman is at last free, as a man is free, to dispose of her own body, to earn her living, to pursue the improvement of her mind, to try a successful career**2**.”

Although the theoretical need to control conception in the name of women's freedom was part of the rhetoric of birth control advocates such as Margaret Sanger and Simone de Beauvoir since the 1920s, historian Lara Marks asserts that the pill significantly altered people's expectations about contraception and what it should be able to achieve, both in terms of efficacy and in terms of user responsibility**3**. Contraceptive appliances already popularized at the time of the pill's inception, such as the external condom and the diaphragm, are very effective with perfect use, but their typical effectiveness hovers around 84 to 85 percent. Couples in the earlier part of the twentieth century accepted an element of risk in contraceptive techniques and, believing they could not entirely control fertility, did not expect to be able to plan family size with absolute certainty**4**. The introduction of the pill dramatically altered this view for individuals, and for the international population control movement that enthusiastically popularized the idea that fertility is amenable to careful planning and control. From its launch, pharmaceutical companies have promoted the pill as at least 99 percent effective - often without explanations that this maximum efficacy is only made possible by individual women's abilities to take the medication every day at the same time, use backup contraception when mistakes are made, withstand the pill's potential side effects, and accept elevated risks of cardiovascular complications.

Notwithstanding its drawbacks, efficacy of the pill made the _perceived level of risk_ regarding pregnancy an important question when it came to contraceptive choice5. By raising expectations about the effectiveness of contraceptive techniques in general by providing seemingly near-perfect coverage, the pill also influenced reproductive behaviour; planning the size of families enabled couples to pursue other priorities - such as education, women's careers, and financial stability - and delay having children until it was convenient6. The importance of these other goals, and the fact that they can most often be achieved by women in capitalist economies only through careful control of their fertility, raises questions about the degree to which taking the pill is a matter of choice. Sociologist Kara Granzow explains, “if control of her reproductive capacity is what grants her 'freedom' then the question of 'choice' is brought immediately to bear: with freedom at stake, the 'choice' is one between being free and not being free - a dubious 'choice.'”**7** Given the necessity of women's participation in the workforce, and the perceived dearth of options for birth control, the social imperative to take what is lauded as the world's most effective (temporary) contraceptive feels for many like an obligation**8**.

Since the 1990s, feminist theorists have started to problematize this conceptualization of women's freedom as stemming directly from their disassociation from the body and its banal capacities of reproduction. Causal links between the advent of the pill and women's so-called liberation are persuasive only if we accept the premise that various forms and histories of gender oppression are universally due to women's essential biological inferiority**9**. Eco-feminist critiques have highlighted the ubiquity of what Lealle Ruhl calls the “paradigm of the willed pregnancy” and illustrated some of the punitive consequences for women who decline (or worse, fail) to prove their possession of personal responsibility by planning and controlling their fertility**10**. Neoliberal paradigms have made acting responsibly when it comes to reproduction synonymous with being in control of biological functions (as if this were entirely possible). Planned reproduction is idealized as the manifestation of women's ultimate freedom (from the body), and unplanned pregnancy conceptualized as individual moral failure to control the body - lack of choice in pregnancy is consequently a lack of freedom**11**.

The inescapability of this discourse of personal responsibility stems from the historical reality that women's reproductive capacities have been the bases of their exclusion from public life. Western feminism has historically accepted that the theoretical foundations of the rational actor are severed from natural and physical domains; women's escape from the binds of birthing and child rearing would lead to their status as autonomous and rational actors in the elusive public sphere**12**. For the liberal subject, the need to control the body is not a choice, but a condition of being accepted as human: autonomous, of rational intellect, and possessing free will.

Present-day ideology around reproduction positions pregnancy as a matter of choice within a general “fetishization of the will,” as well as the mind/body split characteristic of modern liberalism**13**. The willed pregnancy rehabilitates pregnancy - and therefore women - for liberalist autonomy; (self) control is imposed on a biological process widely held to be beyond human control and the scope of liberal theory**14**. In efforts to control their fertility, women's practical engagement with contraceptive technologies (including the pill) can be challenging and dissatisfying because of the latter's inability to reconcile rational planning with the lived experience of sexuality and the body. While women's trajectories in arriving at a suitable method of birth control and difficulties in doing so merit academic study on their own, I broach this subject here briefly in order to destabilize the common assumption I have encountered clinically in sexual health counselling that the sexual revolution and availability of the pill have made women's sexual lives straightforward, an assumption that Marks documents historically**15**.

### Works Cited {.unnumbered}

1.  Lara V. Marks, _Sexual Chemistry: A History of the Contraceptive Pill_ (New Haven, CT: Yale University Press, 2001), 183.
2.  As quoted in Marks, _Sexual Chemistry,_ 183.
3.  Lealle Ruhl, “Dilemmas of the Will: Uncertainty, Reproduction, and the Rhetoric of Control,” _Signs_ 27, 3 (2002): 641-63; Marks, _Sexual Chemistry._
4.  _Marks, _Sexual Chemistry_, 192._
5.  Ibid.
6.  Ibid.
7.  Kara Granzow, “The Imperative to Choose: A Qualitative Study of Women's Decision-Making and Use of the Birth Control Pill,” _Social Theory and Health_ 6 (2008): 5.
8.  I say “perceived” because there are actually many birth control options available in the Canadian market. However, doctors tend to push the pill as the most convenient choice, and not to provide comprehensive birth control counselling.
9.  Granzow, “The Imperative to Choose,” 6
10.  Ruhl, “Dilemmas of the Will,” 643.
11.  Kara Granzow, “De-constructing 'Choice': The Social Imperative and Women's Use of the Birth Control Pill,” _Culture, Health & Sexuality_ 9, 1 (2007): 50.
12.  Ibid., 46.
13.  Ruhl, “Dilemmas of the Will.”
14.  Ibid., 660.
15.  Marks, _Sexual Chemistry,_ 183-215.

___

We deepen into the above discussion in [Unit D HRHP Section 13.5 Contraceptive Ethics: Is Contraception Contra Naturam?](https://justisse.ca/index.php/college/courseware/page/1727). Skip ahead if you want or wait for it.