# 5: Herbal Contraceptives {.unnumbered}

## 5.1 - Introduction Herbal Contraceptives {.unnumbered}

 **Editor/authors for Unit D Section 5 Geraldine Matus and Jenny Koos (2017)**

### Required Readings {.unnumbered}

1.  Hoffman, David. **[Medical Herbalism: The Science and Practice of Herbal Medicine](https://drive.google.com/file/d/1dqe9hj5t7Ej_4FYYKPHK9OgSBbyF92lp/view?usp=sharing)** Chapters 18 Reproductive System, Chapter 20 Immune System, and Chapter 21 Endocrine System.
2.  Weed, Susun. **[_Wise woman herbal for the childbearing year_ (1996)](https://www.amazon.com/Wise-Woman-Herbal-Childbearing-Year/dp/0961462000)** Ash Tree Publishing

----

##  5.1 Introduction to Herbal Birth Control {.unnumbered}

### Considerations for Herbal Birth Control {.unnumbered}

Women throughout history have used herbal preparations to prevent or terminate pregnancy. These methods were developed specifically for birth control or as alternatives when other birth control methods were unavailable or failed. Some schools of thought consider herbal methods to be less harmful to the body than hormonal contraceptives developed by modern pharmacology. For this reason, and because women can administer these to themselves, herbal methods are still used today. The physiological safety of these methods is unproven, and there is not enough recorded clinical experience with these methods to make any conclusion as to their efficacy or safety. Bear in mind that much of the wise-woman knowledge underlying herbal birth control preparations was lost during the witch killings, and no serious attempt has been made since to restore this knowledge. Unfortunately, it remains at best sketchy and anecdotal.

It should be noted that some herbal preparations might be as damaging to a woman's long-term reproductive health as are some hormonal methods of birth control. The various contraceptive herbs achieve a number of different effects, and their culture and preparation considerably affect their efficacy. It is recommended that anyone interested in herbal methods of fertility control research the subject thoroughly and consult with a certified herbalist who is well trained in this area before using such formulations.

The information provided in this section is not intended for use in practice. Its purpose is to complete for the HRHP the picture of all that is available to women for the practice of birth control. Justisse does not recommend their use, unless by a certified herbalist or someone specifically trained in their safe use.  If you think you might want to recommend these in your HRHP practice, please take the caution of seeking a thorough training in their medicinal use. **Herbs used to for birth control are contraceptive endocrine disruptors (CEDs). Herbs may have as much or more of a bio-chemical effect on the body as do pharmaceutical contraceptive drugs.** In other words, common herbs act like drugs when used in particular preparations and situations - so just because they are 'natural' this does not mean that they are not potentially harmful if used unwisely. Remember, emmenagogues can profoundly affect the endocrine system, the second most important system in the human body, and thus need be used with extreme prudence because of the “hormonal shake-up” they induce. 

Remember that the 5th vital sign of a woman's health is the health of her menstrual cycle -- ANYTHING-- that interferes with fertility interferes with a woman's overall health.

  

___

##  5.2 Herbal Birth Control Mechanisms {.unnumbered}

### How Does It Work? {.unnumbered}

In discussing herbs that support or disrupt the endocrine system, we refer to a mixture of traditional, lost and partly revived knowledge as well as scientifically known biochemical qualities (alkaloids, tannins amongst a myriad others). That said, even though we know that a certain component is present in an herb, its use and effect in the human body may differ according to the practitioner's intention, experience and relationship with said herb as well as the individual “patient's” response and reaction to it. The scientifically proven biochemical effects of a certain herb may be in theory impossible to affect the uterus from oral intake, yet traditional, empirical results show otherwise.

Women who use and work with herbs often develop a personal relationship with different herbs, using taste, smell and communication with said herb to determine if, when and how to use it. With respect to strong abortifacients these are often bitter, pungent herbs that are less than pleasurable to consume, especially to a newly pregnant woman who is often consciously or subconsciously sensitive, even repelled, by everything that may endanger the pregnancy. This reaction may occur even before she is aware of the pregnancy, or despite being adamant about ending it. If we are aware of our own instincts, and relate to our chosen medicine on a level beyond reason or science, we can also use herbs more wisely.

### Why induce bleeding? {.unnumbered}

As an HRHP who may or may not recommend herbs to your clients to "regulate" menstrual cycles, it is first and foremost important to use the woman's chart and history to determine what is causing her irregular cycles, amennorrhea or other symptoms of hormonal imbalance/unhealth. If an herb is then recommended, be sure to know its specific actions (tonic, stimulant, anti-spasmodic, astringent e.g.), and do not rely on the very general description of "emmenagogue". There is no health benefit in simply causing a bleed, without understanding of the client's full situation and the reason she may be experiencing a longer than usual cycle.

If a woman truly is pregnant, it is important to understand that an intentional herbal abortion includes upsetting the endocrine system and, depending on the herbs and the individual, a certain degree of poisoning - in a fashion difficult to dose. The possible teratogenic effects mean that if the herbal abortion is not successful, it must be followed up by a medicinal/surgical abortion. Hence, the reason we inform on abortifacient herbs in this unit is not to endorse their use for this purpose, but to increase awareness.

### What is an emmenagogue? {.unnumbered}

Since ancient times, women alone or with the help of wise women (though there were male abortionists) have attempted to abort unwanted pregnancies.  A standard method of inducing abortion (ancient and modern) is the herbal emmenagogue. The preparation of and recipes for emmenagogues are part of herbal medicine folk culture and handed down among wise-women healers for thousands of years.

Emmenagogues are medicinal herbs that stimulate or encourage menstrual flow. Their use may be intended to stimulate menstrual flow whether or not a woman is pregnant. Traditional herbalists would use them for treating “menstrual congestion”. As an HRHP you will know that an induced bleeding does not equal true and healthy menstruation. Therefore it is important to distinguish between the specific herbal actions, when in the cycle they are consumed, and how they may affect the menstrual cycle and whole body health. Although there is some scientific knowledge on herbal bleeding promoters, the exact function of various emmenagogues is not always fully known. The term is used quite loosely, and doesn't always refer to the _true_ emmenagogue effect, which is that of a **circulatory stimulant that promotes the flow of blood**.

In most modern sources, the term “emmenagogue” is used for any herb that stimulate the menstrual flow, even though it may actually be an adaptogen that normalizes hormonal status and promotes healthy ovulation, like _Chasteberry/Vitex_ (Agnus Castus). In its strict meaning this is not an emmenagogue, but rather a hormonal tonic/regulator that promote healthy menstrual cycles, rather than induces bleeding. Herbs that are called emmenagogues may in fact be anti-spasmodic, cause increased peristalsis or carry any other action which may influence hormonal levels (gonadotropins, thyroid hormones, gonadal steroids, corticosteroids), micronutrient uptake and response, ovulation, endometrial stability, or uterine contractions.

  

___

  

## 5.3 - Tradition and Folklore {.unnumbered}

### Historical anecdotes {.unnumbered}

Many variations of herbal emergency contraceptives have been tried throughout history, and are now in the realm of folklore. Though many of these methods were once based on sound medicinal practices, recipes in earlier times were shared only orally between practitioners, and most of this information was lost as herbal methods of birth control became less socially acceptable. Therefore, treatments once based on centuries of tradition are currently unattainable, and we are left with forms of herbal birth control that have untested reliability.

In German folk medicine marjoram, thyme, parsley and lavender in tea form were used. The root of worm fern was used by German and French women and was also prescribed by a Greek physician in the time of Nero; in French it was called the “prostitute root”. In Sweden an old midsummer folk song, ”Uti vår hage” counts lilies, Granny's nightcap, roses, sage, spearmint, and lemon balm, in what could be considered an emmenagogue recipe to follow the romantic meeting in the summer meadows which the song (in a woman's voice) calls for. Other ancient recipes called for a paste of mashed ants, foam from camels' mouths, or tail hairs of blacktail deer dissolved in bear fat.

In modern times, women have been reported to use a variety of agents to induce abortion. The list of possible emmenagogues includes turpentine, castor oil, tansy tea, quinine water in which a rusty nail has been soaked, horseradish, ginger, epsom salts, ammonia, mustard, gin with iron filings, rosemary, lavender, and opium (Gordon, p.36; Norman Himes, _Medical History_ _of Contraception;_ George Devereux, “A Typological Study of Abortion in 350 Primitive, Ancient, and Pre-Industrial Societies”). Tellings of female sex workers douching with lemon water after having a client also abound.

Aside from internal emmenagogues, women have attempted external methods such as severe exercise, heavy lifting, climbing trees, hot baths, jumping and shaking to induce abortion. As late as the 20th Century, Jewish women of the Manhattan Lower East Side attempted to abort by sitting over a pot of steam (or hot stewed onions), a technique described in an 8th Century Sanskrit source.

Folk remedies for unwanted pregnancies were common and stories from all periods of American history abound. In Maryland in 1652, Susanna Warren, a single woman made pregnant by “prominent citizen”, Captain Mitchell, said that he prepared for her a 'potion of Phisick', put it in an egg and forced her to take it. It didn't work and she brought charges against him. 

Other activities that are generally considered to increase the possibility of miscarriage, which have traditionally been used to fortify the effect of herbs include: acupuncture/acupressure, nipple stimulation, sex, semen and orgasms, strenuous exercise, hot baths, saunas and steams, meditation/visualization/affirmation, and massage (especially on the abdomen). Disrupting melatonin production by sleeping with the lights on, or in other ways disturbing the sleep cycle is also considered unhelpful in maintaining pregnancy. 

  

___

  
## 5.4 Herbal Properties {.unnumbered}

### Herbal use to avoid pregnancy may mean: {.unnumbered}

-   **Hindering ovulation through hormonal disruption**
-   **Induce bleeding before implantation occurs, by disrupting the luteal phase/progesterone production and reception**
-   **Induce bleeding after implantation has occurred, by breaking down the endometrium, disrupting progesterone function, or general poisoning**

**Possible complications:**

If the woman, following herbal treatment or otherwise, is experiencing profuse bleeding, fever or sharp, stabbing pains, she must seek medical attention immediately. Self-poisoning may result in damage on organs and may even lead to death. Haemorrhage may also occur, and in this respect remember that soaking a pad in less than an hour is considered too much bleeding. Another risk is a missed or incomplete abortion, where either the foetus dies but isn't expelled, or parts of the placenta are not expelled. This may lead to infection and haemorrhage. If the woman is experiencing sharp pains on one side of the abdomen this may be a sign of an ectopic pregnancy, which doesn't necessarily have to do with herbal effects, but is a serious condition. In all cases emergency medical care is urgent.

Some women choose to use these forms of birth control as they feel it may be less destructive to their bodies. However, herbal preparations can result in significant damage to a woman's reproductive system if they are used incorrectly - therefore these remedies should be viewed with caution. A woman should consult with a certified herbalist to review any recipe in detail before use and the properties of each ingredient thoroughly before proceeding with this form of treatment. Herbal preparations should also not be used by a woman when she is alone in case of medical complications. Be mindful that essential oils of herbs are even more potent and should never be taken orally.

**Different properties of herbs**

Emmenagogues may have secondary actions, and herbs suggested for help or relief in other areas can also be emmenagogues. If you are considering to suggest _any_ herb to your clients for therapeutic reasons, do research on all its qualities as it may have more than one (all examples in the below list are considered emmenagogues of different strengths) **Is it?**

> **anticatarrhal** (reduces mucus and swelling) like _Chamomile_ (matricaria rescucitata),
> 
> **anti-inflammatory** like _Feverfew_ (tanacetum parthenium),
> 
> **antimicrobial** like _Thyme_ (thymus vulgaris),
> 
> **antispasmodic** (relaxes smooth muscle) like _Motherwort_ (leonorus cardiaca)
> 
> **alterative** (purifies blood) like _Black Cohosh_ (cimicifuga racemosa),
> 
> **astringent** like _Sage_ (salvia officinalis),
> 
> **carminative** (relieves flatulence) like _Lavender_ (lavandula spica),
> 
> **bitter** like _Mugwort_ (artemisia vulgaris),
> 
> **demulcent** (supports healthy mucus membranes) like _Fenugreek_ (trigonella foenum-graecum),
> 
> **diaphoretic** (induces sweating) like _Peppermint_ (mentha piperita),
> 
> **diuretic** (increases passing of urine) like _Yarrow_ (achillea millefolium),
> 
> **expectorant** (helps expel mucus from the lungs) _Hyssop_ (hyssopus officinalis),
> 
> **hepatic** (liver stimulating) like _Wormwood_ (artemisia absinthum),
> 
> **hypotensive** (lowers blood pressure) like _Valerian_ (valeriana officinalis),
> 
> **laxative** like _Goldenseal_ (hydrastis canadensis),
> 
> **nervine** (calms the nerves) like _Vervain_ (verbena officinalis),
> 
> **tonic** like _Red Raspberry Leaf_ (rubus idaeus),
> 
> or **vulnerary** (wound healing) like _Marigold_ (calendula officinalis)?

In general, herbs that are both strong/pungent, bitter, laxative, stimulatory, hallucinogen and/or detoxing in any fashion (like _Aloe_) carry abortifacient properties, although their specific action vary.

Below follows a descriptive example of a known emmenagogue, to explain how much information there is to be obtained about a single herb.

### **_Example:_** **Rue** **(**_Ruta graveolens_**)**

Rue (ruta graveolens) is a perennial that grows to 2 feet. It is a symbol of sorrow and repentance, sometimes called the "Herb of Grace”. Rue has been used for centuries as a medical preparation and has a variety of roles, probably because of its varied chemical composition. It has been used to improve eyesight and nerves and to treat insect bite, gout, worms, rheumatism, and hysteria. In the Middle Ages, it was used to ward off plague and as a defense against witches.

The native peoples of North America made extensive use of rue, as did the Aztecs and Mayas (Vogel 1970, pp. 78, 413). One of its prime uses in Greek and Roman medicine was as an abortifacient and emmenagogue. In _Contraception and Abortion from the Ancient World to the Renaissance_, John Riddle gives over twenty separate citations for rue in this role. The ancient gynaecologist Sopranos describes a preparation of "3 drachmas of rue leaves, 2 drachmas of myrtle, 2 drachmas of laurel, mix with wine" as an effective emmenagogue potion. Dioscorides, Pliny the Elder and Oribasius all advocate the use of rue, and Quintus Serenus indicates that a preparation of "egg, rue and dill" will serve to induce an abortion (Riddle 1992, pp. 47, 91).

In addition to its abortifacient and emmenagogue activity it has antispasmodic activity with large doses resulting in GI pains, confusion, twitching and vomiting. Some of the compounds contained in rue have been found to be mutagenic in large doses (Paulini and Schimmer 1987, p. 271).

The chemical composition is large and varied.  Over 110 chemicals have been found in all parts of the plant, including fats, oils, flavonoids, alkaloids, essential oils and a host of others. Of these chemical compounds, 36 are said to have some chemical activity with four of these listed with either emmenagogue or antifertility activity.

Aborinine, graveolinine and skimmianine are listed as abortion-producing while chalepensin is listed with antifertility activity (Duke 1992). Those with abortion producing activity belong to the class of compounds known as alkaloids with the antifertility of chalepesin established by research (Kong et al. 1989, p. 176).

The whole herb is emmenagogue, anthelmintic, antidote, antispasmodic, carminative, emetic, emmenagogue, expectorant, haemostatic, ophthalmic, rubefacient, strongly stimulant, mildly stomachic and uterotonic."

___

 \[1\] W. Jeffrey Hurst, Ph.D., FAIC Clinical Associate Professor of Comparative Medicine Penn State-Geisinger Medical Center, PO Box 805, Hershey, PA 17033 email: wjh5200024@aol.com; with the assistance of Deborah J. Hurst, MG, PO Box 378 Mt. Gretna, PA 17064

  

___

  

## 5.5 - Specific Herbs and Timing {.unnumbered}

If you were to administer these herbs, please seek herbalist training or work with a knowledgeable herbalist regarding recipes and distribution. Always attend to the individual woman's situation, health and intuition, and be humble to the plant's power.

### Herbs that may act before conception: {.unnumbered}

Three herbs are known to cause either permanent or temporary sterilization in women:

-   **Stoneseed Root (**Lithospermum ruderale)**:** This root acts on the pituitary gland and causes infertility.
-   **Jack-in-the-Pulpit (Calla Lily/Zantedeschia aethiopica) Root:** This root can cause either temporary or permanent sterilization.
-   **Thistles:** Many types of thistle including Cardus benedictus, Cnicus ochroncentrus and some of the Cirsiums are useful in preventing pregnancy. This preparation works for a limited amount of time.

### Male Temporary Sterilization {.unnumbered}

Herbs to be used as a male contraceptive have been a topic for many years, primarily _Neem_ (Azadirachta indica). It is said to be able to cause temporary infertility in men, both as pills and by injection into the vas deferens. More on the development of this herb into a future contraceptive standardized drug: [http://www.sisterzeus.com/neem\_men.html](http://www.sisterzeus.com/neem_men.html)

### Herbs and other substances that may prevent conception and/or implantation during or after intercourse: {.unnumbered}

These are examples of herbs that can be used to prevent conception and/or implantation. Preparations can be taken either before or shortly after intercourse occurs. When used after intercourse they would fall under the category of herbal emergency contraception. As you will understand, it is the compounds in the herbs that cause the physical reaction, but a woman's attitude towards the remedy (call it placebo if you will) also matters in the effects seen.

-   **_Queen Anne's Lace_** (_daucus carota_) to inhibit implantation (exact effect debated)
-   Herbs that affect immune system and stress response, blood pressure or the nervous system, such as **_Pennyroyal_** (menthe pulegium) usually make a woman ill in the process
-   **_Cannabis_** (cannabis sativa/indica) that may block LH, and have an oxytocic effect (causes contractions)
-   _**Neem**_ (Azadirachta indica)_, Lemon_ (citrus limon) or other sperm killing agents intravaginally, either by acidity or poison
-   Emmenagogues such as **_Rue_ or _Ginger_** can also be implantation inhibitors due to a disruptive effect on the endometrium
-   Herbs containing thujone (e.g. **_Wormwood or Juniper_**) and other uterine stimulants
-   _**Cotton root bark**_ (gossypium hirsutum) which disrupts progesterone and increases oxytocin (which may lead to uterine contractions)
-   _**Vitamin C:**_ Vitamin C is presented in various sources as a menstrual inducer. It is sometimes said to be able to induce abortion by blocking out progesterone, yet several studies instead show an increase in progesterone from vitamin C usage at normal doses. The amounts which would be necessary to produce an abortifacient effect (3g/hour for at least 24h is suggested) could potentially work by affecting the formation and function of the corpus luteum, wherein a delicate balance of enzymatic antioxidant and oxidant action is essential to its development. It will however also result in severe diarrhea, which might be a disturbing factor enough in itself.
-   _**Rutin**_: Rutin is a flavonoid found in many plant leaves, including the herb _Rue_ (ruta graveolens), buckwheat (fagopyrum esculentum), _black tea_ (camellia sinensis), apple peels (malus pumila), and _Elder_ (sambucus nigra). It is not an herb, but a flavonol glycoside comprised of the flavonol quercetin and the disaccharide rutinose. and can be found in tablet form in many health food stores. Rutin is used to "break down the endometrium", however with an unclear mechanism of action.

###  Herbal abortifacients to act after implantation {.unnumbered}

It is recommended that recipes such as these be taken within 4 weeks after implantation or about 3 to 3 ½ weeks after the “missed period”. One can clearly see the advantage of charting the menstrual cycle in determining the most advantageous use of these herbs, and clearly the sooner the herbal abortion is done the greater the chance of success. One disadvantage of these preparations is that they may make a woman very ill for the duration of treatment. Examples of such herbs used are _Pennyroyal_ (Mentha pulegium), _Blue and Black Cohosh_ (Caulophyllum thalictroides and Cimicifuga racemosa) and _Osha_ (Ligusticum porteri).

### Natural Emmenagogue or Emergency Contraceptive Recipes {.unnumbered}

1.  [Pennyroyal](http://www.sisterzeus.com/Pennyroyal.htm) 
2.  [Blue Cohosh](http://www.sisterzeus.com/BlueCoh.htm)
3.  [Osha](http://www.susunweed.com/Article_Herbal_Birth_Control.htm) 

For more considerations and lists of herbs, please see [http://www.sisterzeus.com/Emmeno.htm](http://www.sisterzeus.com/Emmeno.htm) 

___

 \[1\] W. Jeffrey Hurst, Ph.D., FAIC Clinical Associate Professor of Comparative Medicine Penn State-Geisinger Medical Center, PO Box 805, Hershey, PA 17033 email: wjh5200024@aol.com ; with the assistance of Deborah J. Hurst, MG, PO Box 378 Mt. Gretna, PA 17064

  

___

  

## 5.6 - Herbs and Pregnancy {.unnumbered}

If a woman is pregnant and wishes to maintain the pregnancy, the safest recommendation from you as an HRHP is for her to not consume any specific herb in large quantities, as most of them are not tested and their relative strength differs. It is not dangerous to take any of these more or less common herbs and spices in food or the occasional teacup, as its disruptive effect will only be present in higher concentrations and doses.

### Considerations for early pregnancy {.unnumbered}

-   **_Ginger_ and _Red raspberry_** may help with morning sickness, yet there is some controversy as they may also affect uterine muscle/cramping and are both considered emmenagogues. The distinction between medicine and poison is all in the dose - and the patient.
-   Be careful with herbs affecting hormonal status, even if it is “supportive” or adaptogen (like _Maca_). Herbs that affect your adrenals, thyroid or liver may also influence your general hormonal status. 

### Any of these herbal preparations are inadvisable during pregnancy: {.unnumbered}

-   Anything that affects **smooth muscle**, e.g. antispasmodic _Camphor_, _Valerian_
-   **laxatives** which irritate peristalsis and thus uterus: _Senna, Aloe, Rhubarb_
-   **blood pressure** affectors such as C_hili, Ginseng, Sage_, _Wormwood or Garlic_
-   **emmenagogues** g. _Southernwood, Parsley, Yarrow, Rue, Rosemary, Mint_ and many other aromatic herbs. 

### Contraindicated Herbs During Pregnancy {.unnumbered}

The Traditional Chinese Medical Medica Materia list of herbs contraindicated during pregnancy includes the herbs listed above for birth control.\[1\],\[2\],\[3\] The list has been supplemented with other herbs as well, based on the required readings for this section, and these additional sources \[4\]. Many herbs in this list will be considered emmenagogues, but some may have different disruptive effects, as discussed previously.

The herbs in the following category should **not be used** at any time during pregnancy or when pregnancy is even a possibility.

-   American false pennyroyal **(hedeoma puegioides)**
-   Angelica root/Dong Quai **(archangelica, atropurpurea, sinensis, sylvestris)**
-   Ba Dou **(croton tiglium semen)**
-   Bai Fu Zi **(Typhonii rhizome)**
-   Bai Mao Gen **(imperatae cylindricae)**
-   Ban Mao **(mylabris)**
-   Black Cohosh **(cimicifuga racemosa)**
-   Blue Cohosh **(caulophyllum thalictroides)**
-   Chan Su **(bufonis secretion)**
-   Chasteberry/Vitex **(agnus castus)**
-   Che Qian Zi **(plantago asiatica)**
-   Chong Lou **(Paridis rhizome)**
-   Chuan Niu Xi **(cyathulae officinalis)**
-   Condurango **(**Marsdenia cundurango)****
-   Cotton root bark **(gossypium hirsutum)**
-   Da Ji **(cirsii japonica, euphorbiae)**                    
-   Di Bie Chong **(eupolyphaga)**
-   E Wei
-   E Zhu **(curcumae root)**
-   Fan Xie Ye (**Senna alexandrina**)
-   Feverfew **(tanacetum parthenium)**
-   Fu Zi **(aconite carmichaeli radix)**
-   Gan Sui **(euphorbiae kansui)**
-   Gentian **(gentiana lutea)**
-   Goldenseal **(hydrastis canadensis)**
-   Guan Zhong **(dryopteris crassirhizomae)**
-   Hai Long
-   Hai Ma **(hippocampus)**
-   Hong Hua **(carthami tinctorii)**
-   Huai Hua **(sophorae japonicae immaturus)**
-   Jack-in-the-pulpit root **(arisaema)**
-   Juniper **(juniperus officinalis)**
-   Life root **(senecio aureus)**
-   Liu Huang **(sulphur)**
-   Ma Chi Xian **(portulacae)**
-   Ma Qian Zi **(strychni semen)**
-   Mang Xiao **(mirabilitum)**
-   Meng Chong
-   Monk's cress **(tropaeolum majus)**
-   Mu Dan Pi **(moutan)**
-   Niu Huang **(bovis calculus)**
-   Pennyroyal **(mentha pulegium)**
-   Qian Niu Zi **(pharbitidis semen)**
-   Qing Fen **(calomelas)**
-   Qu Mai (**dianthi folium)**
-   Rue **(ruta graveolens)**
-   Rutin (a bioflavonoid)
-   Saffron stigmas **(crocus sativus)**
-   San Leng **(sparganii rhizome)**
-   Shang Lu **(phytolaccae root)**
-   She Gan **(belamcandae rhizome)**
-   She Xiang **(moschus secretion)**
-   Shui Zhi **(hirudo)**
-   Smartweed **(polygonum hydopiper)**
-   Southernwood **(artemisia abrotanum)**
-   Stoneseed root **(lithospermum)**
-   Tansy Ragwort **(tanacetum vulgare)**
-   Tao Ren **(persicae seed peach)**
-   Thistles **(cardus, cnicus, cirsium genus')**
-   Tian Hua Fen **(trichosanthis)**
-   Vitamin C (**ascorbic acid**, high dose)
-   Wei Ling Xian **(clematidis radix)**
-   Wild Carrot seed/Queen Anne's lace **(daucus carota semen)**
-   White horehound **(marrubium vulgare)**
-   Wormwood **(artemisia absinthum)**
-   Wu gong **(scolopendra)**
-   Wu Tou **(aconite root)**
-   Xi Xin **(asari herb)**
-   Xiong Huang **(realgar)**
-   Xuan Ming Fen **(mirabilitum)**
-   Yan Hu Suo **(corydalis rhizome)**
-   Yi Mu Cao **(leonurus cardiaca)**
-   Yu Li Hua **(pruni flower)**
-   Yuan Hua **(daphnes genkwa)**
-   Zao Jiao **(gleditsiae)**
-   Zhang Nao/Camphor **(camphora)** 

### Cautionary Herbs During Pregnancy {.unnumbered}

The herbs listed below should be used with **caution** during pregnancy. If in doubt do not use/prescribe these herbs.

 Common name (**Latin botanical name**)

-   Bai Fu Zi **(typhoni gigantei)**
-   Ban Xia **(Pinelliae ternatae)**
-   Bethroot **(trillium pendulum)**
-   Birthwort root **(trillium pendulum)**
-   Bing Pian **(borneol)**
-   Blackhaw **(viburnum prunifolium)**
-   Chamomille **(matricaria rescucitata)**
-   Chan Tui **(cicadae)**
-   Chang Shan **(dichorae febrifugae)**
-   Chuan Jiao **(zanthoxyli bungeani)**
-   Chuan Sha Jia **(squama manitis)**
-   Da Huang **(rhizome rhei)**
-   Dai Zhe Shi **(haematitum)**
-   Dong Kui Zi **(abutiloni semen)**
-   Ergot fungus **(claviceps purpurea)**
-   Fenugreek **(**Trigonella foenum-graecum)****
-   Frankincense **(gummi olibanum)**
-   Gan Jiang **(zingiberis officinalis)**
-   Ginger root **(zingiberis officinalis)**
-   Guelder-rose ****(viburnum opulus)****
-   Hou Po **(magnoliae officinalis cortex)**
-   Huai Nui Xi **(achyranthis bidentatae root)**
-   Hua Shi **(talcum)**
-   Hyssop **(hyssopus officinalis)**
-   Lavender ****(lavandula officinalis)****
-   Lemon balm **(melissa officinalis)**
-   Linden **(tilia platophyllos)**
-   Lou Lu **(rhapontici echinops root)**
-   Lovage root **(levisticum officinale radix)**
-   Lu Hui **(herba aloes**)
-   Lu Lu Tong **(liquidambaris)**
-   Marigold ****(calendula officinalis)****
-   Marijuana **(cannabis sativa, indica)**
-   Mistletoe leaf **(phoradendron)**
-   Mo Yao **(Myrrha)**
-   Motherwort **(leonurus cardiaca)**
-   Mu Tong **(caulis mutong)**
-   Mugwort **(artemisia vulgaris)**
-   Myrrh
-   Osha root **(ligusticum porteri)**
-   Parsley **(petroselinum crispum)**
-   Peppermint **(mentha piperitum)**
-   Peruvian bark **(chinchona)**
-   Pu  Huang **(pollen typhae)**
-   Quan Xie **(buthus martensi)**
-   Red raspberry **(rubus idaeus folium)**
-   Rosemary **(tosmarinus officinalis)**
-   Rou Gui **(cortex cinnamomi cassiae)**
-   Ru Xiang **(gummi olibanum)**
-   Sage **(salvia officinalis)**
-   San Qi **(pseudoginseng root)**
-   Su He Xiang **(styrax liquidis)**
-   Su Mu **(lignum sappan)**
-   Sumac berries **(rhus glabra)**
-   Sweetflag root **(acorus calamus)**
-   Tian Nan Xing **(arisaematis rhizome)**
-   Thyme **(thymus vulgaris)**
-   Tong Cao **(medulla tetrapanacis papyriferi)**
-   Valerian **(valeriana officinalis)**
-   Vervain **(verbena officinalis)**
-   Wang Bu Liu Xing **(baccariae segetalis seed)**
-   Wood sorel, fresh **(oxalis acetosella)**
-   Xue Jie **(sanguis draconis)**
-   Yarrow **(achillea millefolium)**
-   Yi Yi Ren **(coicis lachrymal-jobi, barley seed)**
-   Yu Jin **(curcumae turmeric root)**
-   Yu Li Ren **(prunus japonica seed)**
-   Ze Lan **(herba lycopi lucidi)**
-   Zhi Ke (Qiao) **(citri ponciri fruit)**
-   Zhi Shi **(citri ponciri immaturis)**

Chinese herbs list used with permission by  [**http://tcm.health-info.org/index.htm**](http://tcm.health-info.org/index.htm) 

Traditional Chinese Medicine Health-info recommends consulting qualified practitioners of Eastern & Western herbology before administering any herbal treatment during pregnancy.  For more information see the TCM website [http://tcm.health-info.org/index.htm](http://tcm.health-info.org/index.htm) .

\[1\] _Natural Medicines Comprehensive Database_ (2003) Stockton California; Therapeutic Research Faculty.

\[2\] Benskey & Gamble. _Chinese Herbal Medicine Materia Medica_. revised edition (1993) Seattle, WA, Eastland Press.

\[3\] Chung, Michael. Cautions Using TCM Herbs. (2002) Vancouver Canada. Canadian Traditional Chinese Medicine Association 

\[4\] Nissim, Rina. _Natural Healing in Gynaecology - a manual for women_ (1996) San Fransisco, California, Pandora Press/Harper Collins Publishers

\[5\] Parvati, Jeannine. _Hygieia - a woman's herbal_ (1978) Freestone collective

\[6\] Annwen. _Herbal abortion_ (2002) Leeds, Godhaven Ink